### ISSUE TITLE
不好描述，看图

### ISSUE THREAD

**Issue by bdfish** [libpinyin/ibus-libpinyin#101]
![screenshot from 2017-12-21 10-51-00](https://user-images.githubusercontent.com/15389690/34238628-9c11d394-e63d-11e7-9b19-46797adc9f56.png)
最右那俩个上下页切换有办法去掉吗？觉得有点多余，应该没多少人用鼠标切换上下页吧

**Comment by epico** [comment]
以后可能支持触摸屏。目前，没有选项去掉。
