### ISSUE TITLE
用户词库如何添加简拼及中英文混合词条

### ISSUE THREAD

**Issue by suokunlong** [libpinyin/ibus-libpinyin#103]
我想建立一个自己日常频繁使用的词库，然后导入，以简化输入。
添加完整的拼音没有问题，比如：
'''
简拼 jian'pin
全拼 quan'pin
试了一下 shi'le'yi'xia
'''

但是，以下设置无效：
'''
简拼 j'p
全拼 q'p
试了一下 s'l'y'x
'''

以下中英文混输的设置也无效：
'''
AA制 a'a'zhi
A4纸 a'4'zhi
'''

怎么实现？如何添加？自定义词库文本文件格式有没有文档可以参考？谢谢。

**Comment by epico** [comment]
libpinyin 的导入功能不支持不完全拼音或者英文。

可以考虑编写 lua 脚本添加，输入 i 激活 lua 扩展功能。

**Comment by suokunlong** [comment]
> libpinyin 的导入功能不支持不完全拼音或者英文。
如何让它实现？有没有计划？导入功能的代码在哪里。
我看到/usr/share/ibus-libpinyin/phrases.txt 里有这样的词。这个文件在libpinyin里无用？

> 可以考虑编写 lua 脚本添加，输入 i 激活 lua 扩展功能。
对lua一无所知，之会一些python编程。

**Comment by ping-wu** [comment]
不知道你的意思？

我试了一下，好像没有问题？ （Fedora 26, ibus-libpinyin）

[
![screenshot from 2018-01-14 22-28-09](https://user-images.githubusercontent.com/21325422/34933684-de0a31be-f97b-11e7-84da-4fbb0ec3b104.png)
](url)

http://forum.ubuntu.com.cn/viewtopic.php?f=8&t=486270&p=3200398#p3200398

**Comment by suokunlong** [comment]
我在Fedora 27下，ibus-libpinyin输入/usr/share/ibus-libpinyin/phrases.txt 里定义的所有短语都不起作用，包括AA制等那些。但是，ibus-pinyin是能输入phrase.txt里的短语的。
我应该如何调试，才能定位问题。

**Comment by epico** [comment]
不好意思，ibus-libpinyin 不支持 phrase.txt， 请使用 lua 扩展。

**Comment by suokunlong** [comment]
那么我建议在下个版本中将phrase.txt文件删除，以免造成误解。

**Comment by epico** [comment]
好的，已经移除了。
