### ISSUE TITLE
ibus-libpinyin makes some shortcuts of Lyx invalid

### ISSUE THREAD

**Issue by starrose** [libpinyin/ibus-libpinyin#104]
lyx中有些快捷键在 ibus-libpinyin 处于英文状态时是失效得。而在切换到纯英文状态时，lyx快捷键是正常的。例如
lyx 中 Alt-m d (按住Alt 时同时按住 m，之后放开，按d) 是加入行间公式的快捷键。在ibus-libpinyin 的英文状态时，这个快捷键就失效了。许多以 Alt-m 开始的快捷键都有这个问题。
我在 Debian 上也报告了这个bug。https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887059

**Comment by epico** [comment]
Maybe for the 'd' character, input method should use ibus_engine_forward_key_event function instead of ibus_engine_commit_text function.

**Comment by starrose** [comment]
'd' is just an example. Lots of shortcuts consisting of Alt+m and a character (such as 'd;, '(', and 'g' ...) have the same bug.

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/28fa26af3d5680253e7a47953801add0e44118bf .

Please try it, thanks.

**Comment by starrose** [comment]
Dear Wu

I have tried the fixed codes. I think the modifications work. Thank you.


Best Regards

Wang Lu


________________________________

**Comment by epico** [comment]
As ibus-libpinyin 1.10.0 is released, close issue.
