### ISSUE TITLE
双拼模式的一些建议

### ISSUE THREAD

**Issue by tlannaax** [libpinyin/ibus-libpinyin#105]
双拼模式下v英文，i lua扩展无法使用，是否能使用大写V,I或者其他字符(如 ; ')来进行引导？
目前双拼模式下显示的是转换后的全拼编码，比较适合双拼的初学者。如果能增加显示原始输入码的选项的话，将极大提高双拼模式下的中英文混输体验。

**Comment by epico** [comment]
在双拼模式下，可以用 I 激活 lua 扩展。

猜测显示原始输入码，是为了输入英文？

**Comment by tlannaax** [comment]
对，显示原始输入方便临时输入英文。
双拼模式用不到拼音分隔符 ‘ ，另外 ；虽然有些双拼方案会当作韵母使用但都不会作为声母使用，这两个符号拿来引导英文和笔划比大写VU可能更方便

**Comment by epico** [comment]
个人觉得还是 U/V 好记忆，实现起来也简单。

Enable English and Stroke Editor for Double Pinyin in https://github.com/epico/ibus-libpinyin/commit/f80b1fbf06ffe89a15ad74d7c0c4e8b4aa4ec1c2 .

**Comment by epico** [comment]
觉得双拼模式还是显示全拼比较方便。

As ibus-libpinyin 1.10.0 is released, close issue.
