### ISSUE TITLE
Auto-commit English when pressing Shift-L

### ISSUE THREAD

**Issue by tlannaax** [libpinyin/ibus-libpinyin#106]
With the ibus property bar never showing (it cannot remember position upon restart when always show, while auto hide is rather distracting), it is hard to know the current Chinese/English status. Often I find it is in Chinese status after inputting a whole English word. The correct way here is Enter then Shift-L, but for example when I'm writing an English email, I feel that I will be using English for a while thus I directly press Shift-L which makes me lose what I have input. I think auto-commit English upon Shift-L is more intuitive because Enter is just for temporary English while Shift-L is for a while.

**Comment by epico** [comment]
Guess the expected behavior is commit the user input when press Shift key when switch English/Chinese mode.

**Comment by tlannaax** [comment]
Yes. This behavior is an option available on almost all other pinyin input methods.

**Comment by alx696** [comment]
请考虑实现此功能! 为了快速切换中文/英文, 会将切换快捷键设置成`shift`.
当前状态为中文时, 如果有输入字符, 按`shift`时将输入的字符生效(目前会丢失输入字符).
现在的拼音模式>输入中的"[shift]键选词"和"自动上词"功能感觉不合理, 单独设置自动上词没有任何作用, 同时选择shfit键选词及自动上词时上的是中文?! 如果我需要输入中文的话, 我应该按数字或空格键选择.

我是个码农, 中文/英文切换非常频繁. 之前一直使用sogou pinyin, 但18.04上一直没有更新匹配. 现在除了联想功能不是很理想外, 最不适应的就是英文切换为中文时, 无法将已经输入的英文应用的问题.

**Comment by alx696** [comment]
> Guess the expected behavior is commit the user input when press Shift key when switch English/Chinese mode.

请考虑实现此功能! 为了快速切换中文/英文, 会将切换快捷键设置成shift.
希望实现: 当前状态为中文时, 如果有输入字符, 按shift时将输入的字符生效(目前会丢失输入字符).
                 Please keep the inputted characters when switch from English to Chinese.

现在的拼音模式>输入中的"[shift]键选词"和"自动上词"功能感觉不合理, 单独设置自动上词没有任何作用, 同时选择shfit键选词及自动上词时上的是中文?! 如果我需要输入中文的话, 我应该按数字或空格键选择.

我是个码农, 中文/英文切换非常频繁. 之前一直使用sogou pinyin, 但18.04上一直没有更新匹配. 现在除了联想功能不是很理想外, 最不适应的就是英文切换为中文时, 无法将已经输入的英文应用的问题.

**Comment by epico** [comment]
在 ibus-libpinyin 1.10.91 中，已经支持了。

**Comment by alx696** [comment]
> 在 ibus-libpinyin 1.10.91 中，已经支持了。

非常感谢! Ubuntu 18.04中集成的版本为1.9.2, 用源码安装时遇到无法编译的问题了:

https://github.com/libpinyin/ibus-libpinyin/issues/132#issuecomment-434550712

**Comment by MaiLunJiye** [comment]
中文状态下 输入 vim 回车， 结果输是 im ， 希望可以把空格和回车两个逻辑分开 ，比如空格是选择第一个候选，回车是把输入的字符输出（ 其他情况已经很好了，就是输入 v 开头的英文还能优化一下 。 ）

**Comment by epico** [comment]
v 开头是英文输入模式，有人报 issue, 才改成现在这个行为。

**Comment by alx696** [comment]
@MaiLunJiye 1.9.2中文状态输入**vim**回车后结果是正确的**vim**.

@epico 现在还有一个问题是输入符号**`**,在编辑Markdown中输入代码块时经常需要用这个.但是输入法中文状态下好像触发了符号快捷键? 出现的是点号,逗号句号的候选,连按两次**`**就变得奇怪了.

**Comment by epico** [comment]
@alx696 在 gedit 中，**** 是正常的。
方便的话，请给这个问题开一个新的 issue.

**Comment by alx696** [comment]
@epico 见 #179

**Comment by littlewu2508** [comment]
我目前用的1.11.1，Shift-L切换中英文可以直接上坪屏，但中/英切换使用其他快捷键（例如ctrl）就无法直接上屏

**Comment by epico** [comment]
@littlewu2508 Fixed in https://github.com/epico/ibus-libpinyin/commit/318aea3862c6dbc382ccca6c7ea75c198e28b75e .
