### ISSUE TITLE
Can't import a symbol dictionary 

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#107]
I created a text file with the following content:

Δ san’jiao’xing

After going thru the import steps, including restarting, I was unable to type out the Δ symbol.  Exporting my user dictionary also does not show the Δ symbol.

In comparison, when I imported the following file:

ꖴ yu

I was able to type out the ꖴ symbol.

**Comment by epico** [comment]
libpinyin supports one character for each pinyin.

Δ san’jiao’xing

In the above example, the symbol has only one character, but have three pinyin.
This is not supported by libpinyin.

Please try lua extension instead.
