### ISSUE TITLE
ibus智能拼音的问题

### ISSUE THREAD

**Issue by grassvalley** [libpinyin/ibus-libpinyin#110]
1、从反应速度上，会有突然的卡顿；
2、当我输入i并跟随其他字母时（当然这应该是智能拼音没有定义的一个字母），回出现异常，导致无法继续输入汉字，需要切换到其他输入法，然后再切换回来才能继续使用，估计内部崩溃了。
3、在geany编辑器中，候选字浮动框无法正常跟随光标
4、预置词语里竟然没有“智能拼音”这个词，虽然无关紧要，但是感觉～～
5、仍然继续建议，预置特殊符号，虽然根据接受，用户可以自定义，但……还是预置更方便。

**Comment by epico** [comment]
Fedora 27 的 ibus-libpinyin 版本比较高，请测试一下有哪些问题？

**Comment by ping-wu** [comment]
Ubuntu 18.04 里 ibus-libpinyin 已升级到 1.9.2 了：

https://forum.ubuntu.com.cn/viewtopic.php?f=1&t=486434

我已使用了一阵子，相当好用，就是字/词库还不成熟（习惯），常常要翻好几页才能找到想打的字或词。（词还好，打单字则总是一个挑战。）

**Comment by epico** [comment]
请针对每个问题，分开提交 issue.
