### ISSUE TITLE
Respect system icon theme

### ISSUE THREAD

**Issue by jambonmcyeah** [libpinyin/ibus-libpinyin#111]
Right now ibus-libpinyin is unthemable thr icons are stored /usr/share/ibus-libpinyin/icons/ 

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1202

**Comment by ahyangyi** [comment]
A potential workaround is that you can implement a customized panel, then ask ibus to launch with your custom UI via
```
ibus-daemon -drx --panel=/path/to/your/panel
```

The `kimpanel-ibus-panel` that ships with KDE Plasma 5 is usable, and you might be able to use it as an example.

I do find such a setup more unstable than vanilla ibus though.
