### ISSUE TITLE
把特殊符号自定义为用户词组无效

### ISSUE THREAD

**Issue by grassvalley** [libpinyin/ibus-libpinyin#112]
我设定几个特殊字符，作为用户自定义词组，格式如下：

> ★	w'j'x
> ☆	w'j'x
> ▲	san'jiao'xing
> △	san'jiao'xing
> 

保存为utf8编码的txt文件，使用ibus智能拼音选项中导入用户词典功能导入，导入时没有任何错误提示。重启后发现无论是输入wjx还是输入san jiao xing，都不起作用。

**Comment by epico** [comment]
目前，ibus-libpinyin 要求一个字符对应一个拼音。

也许，可以改进 lua extension 来支持，但是需要开发者和时间... ;)

**Comment by ghostry** [comment]
https://github.com/Nuclides/pinyin-emoji-input

这个感觉是类似的实现

**Comment by epico** [comment]
请使用 Lua extension.
