### ISSUE TITLE
拼音自动分割不够智能，推荐逻辑不合理

### ISSUE THREAD

**Issue by grassvalley** [libpinyin/ibus-libpinyin#113]
在我输入【liao】（料）并没有手工分隔为【li'ao】，系统同时给我提供了【liao】和【li ‘ ao】的候选词，但是这种智能化推测适得其反。在我往后翻了两页后发现，在没有把【liao】音的字推荐完的情况下，居然开始推荐 【 li 】的字。因为用户并没有主动分隔【liao】为【li'ao】，按照一般的逻辑，应该是这样的：
首先推荐 【liao】音的常用字
然后推荐【li ' ao】音的常用词
然后推荐【liao】音的非常用字，直至提供全部【liao】音的字。
自始至终都不应该出现【li】音的字。

**Comment by ping-wu** [comment]
这个问题以前也有人提出来过，不过好像没有下文。

以下的截图是用 ibus-libpinyin 打入 【liao】的结果：

![ibus-libpinyin](https://user-images.githubusercontent.com/21325422/38129504-0c4c148a-339b-11e8-8d9e-917ff14757e0.jpg)

的确非常不合逻辑。

我把输入法换成 ibus-pinyin，则好用多了：

![ibus-pinyin](https://user-images.githubusercontent.com/21325422/38129555-3dda2df2-339b-11e8-9634-0f8e648f9020.jpg)

（这个 ibus-pinyin 乃是刚刚加入，并没有使用到个人的习惯用字/词。）

**Comment by epico** [comment]
在 ibus-libpinyin 的设置对话框内，请将 “候选词排列顺序” 改为 “拼音长度” 即可。

**Comment by grassvalley** [comment]
对于把按词频排序改为按拼音长度排序的解决方案，我认为非常不妥。因为词频调整几乎是输入法的必备功能。为了解决拼音中的分词功能，而取消词频调整功能，实在是舍大取小。
如果暂时无法解决这个问题，我建议不要启用拼音中的智能分词功能。也就是当用户输入【liao】时，只认为是【liao】音，不要自作主张分成【li】和【ao】两个音。当用户使用分词符输入成【li'ao】时，不要识别为【liao】音，只识别为【li】和【ao】两个音。现在这个智能分词自作主张帮了倒忙，还是交给用户自己确定是否分词吧。

**Comment by epico** [comment]
"拼音长度" 的候选词排序是会考虑词频的。

其实 iOS 的输入法是支持这种智能分词功能的。

整句输入的时候会选择 “liao”。

**Comment by ShelpAm** [comment]
请问一般来说哪个候选词排序会更常用/常见一些呢？

**Comment by epico** [comment]
> 请问一般来说哪个候选词排序会更常用/常见一些呢？

其实这个要看个人习惯，这些候选词排序选项是根据用户需求逐渐添加的。

**Comment by ShelpAm** [comment]
> > 请问一般来说哪个候选词排序会更常用/常见一些呢？
> 
> 其实这个要看个人习惯，这些候选词排序选项是根据用户需求逐渐添加的。

谢谢。
