### ISSUE TITLE
这两天在使用用户组词时崩溃

### ISSUE THREAD

**Issue by grassvalley** [libpinyin/ibus-libpinyin#116]
在输入过程中，输入一个本来没有的词，这时候需要一个字一个字的选，在选的时候，会出现输入法无法运作，无法输入汉字，只能重新启动操作系统的情况。

这种情况在组三字词的时候更容易出现。

系统环境ubuntu 18.04 64位，2018年04月08日更新系统后问题依然存在。

**Comment by epico** [comment]
Could you re-produce it on Fedora 27?

**Comment by grassvalley** [comment]
你的意思是不是问有没有在Fedora27中使用过？没有，电脑上没有安装Fedora。
我倒是同时安装有xubuntu 18.04，我今天再次试用，发现问题是这样的：
并不是在组词的过程中导致崩溃，而是中按下数字键选字的时候崩溃了。因为经常直接按空格选择首选字，所以没有观察到真正的问题。
使用空格直接选择第一个候选字没有问题，但是如果按数字键选择其他候选字就崩溃，其实我尝试用鼠标来选择其他候选字也会出现崩溃的。

**Comment by ping-wu** [comment]
rm -rf ~/.cache/ibus/libpinyin 再启动 ibus-libpinyin 就可以解决这个问题。

请先把个人的习惯字/词（user_bigram.db）储存起来，再 copy 回去。

2018-04-08 15:25 GMT-10:00 百草谷居士 <notifications@github.com>:

**Comment by epico** [comment]
用户数据不仅仅在 user_bigram.db 中，仅仅备份 user_bigram.db 可能会出问题。

可以要求 Ubuntu 同步到 Fedora 27 的 libpinyin 和 ibus-libpinyin 版本，
有可能在 Fedora 27 中已经修复了...

如果还有问题，我可以帮忙看一下。

**Comment by grassvalley** [comment]
删除这个文件夹后，问题消除。
因为libpinyin总除问题，使用的断断续续，并没有积累多少用户数据，所以对是否丢失用户数据无察觉。

**Comment by ping-wu** [comment]
我的系统（Ubuntu 18.04）没有问题。Fedora 27/28 也都没问题。

印象中 xubuntu 17.10/18.04 预设输入引擎是 fcitx，换成 ibus 时可能出了问题。

**Comment by epico** [comment]
可以比较下 Ubuntu 和 Xubuntu 的 ibus, libpinyin, ibus-libpinyin 的版本号是否一样...

**Comment by ping-wu** [comment]
我们试过 Rime 有一些问题，只能放弃。Rime 也差不多两年没有维护了。

ibus-libpinyin 在 Fedora 下还没有碰到什么问题，只是预设的字词库太差了，尤其是输入单字时常常要翻好几页，使用过搜狗的人可能不会习惯无法接受。

当然啦，搜狗有它的严重的缺点，我们是不可能使用的。不过一般大众可不会这么想。

**Comment by epico** [comment]
在设计的时候，单字输入确实没有考虑。

在词库版权的问题上还是谨慎点好。

**Comment by grassvalley** [comment]
ubuntu和xubuntu都是18.04，使用的同一个软件源，版本号是一致的。
今天切换到ubuntu下试用，关于候选字框跟随光标的问题：
1、不是固定在屏幕左下角，而是固定到文本输入区的左下角，因为在编辑文字的时候大部分时候，文本编辑区域都最大化了，所以造成一个错觉，好像是跑到屏幕左下角了。仔细观察后，发现是在文本编辑区的左下角。
2、在ubuntu环境下，大部分时候候选字框都能跟随光标。目前只有geany编辑器不能实现跟随光标。而在xubuntu下几乎所有软件环境下，都不能实现跟随光标

另：就用户感受来说，目前的智能拼音在稳定性和候选字顺序优化上还不如rime，其他方面也没有比rime突出的优点。如果有优点，就是可以反馈问题，不断改进。网上搜到的rime定制指南看起来井井有条，实际操作根本不起作用，反馈后也没人回复。对我来说rime最大的问题是不能录入标点符号。
再另：特殊符号录入功能，还是希望智能拼音能考虑加入这个功能。

**Comment by epico** [comment]
关于稳定性和光标跟随，建议报 bug 到 Ubuntu Launchpad，可能是 geany 和 ibus 的问题。
特殊符号录入功能，请考虑 lua extension.

其实，在设计的时候，主要考虑的是用户输入完词组或句子后，
智能猜测用户的输入，大部分情况下，不需要选择候选词。

如果您觉得 ibus-rime 适合您，请用 ibus-rime，用户可以选择自己喜欢的输入法。
