### ISSUE TITLE
ibus-libpinyin 1.9.2输入法不能输入文字

### ISSUE THREAD

**Issue by LYLSL** [libpinyin/ibus-libpinyin#117]
ubuntu 18.04 
输入法版本： ibus-libpinyin 1.9.2
   现象描述：当键入中文时，‘’候选词/字框‘’能出来，拼音候选词或字也能显示，但是当选择某一个词语或者字的时候，选择不了，再输入就，“候选词/字输入框”就不在显示，直接输入的是英文字母。
     举例说明：当我在文本里输入 py,‘’候选词/字框‘’能显示出来：1.培养，2拼音，3朋友4，便宜。。。。。等等。当我按数字2 时（我选择拼音这个词语）这个时候输入法感觉会卡一下，然后在文本上显示2，当我在继续输入py时，文本上显示的也是py，并且不会出现‘’候选词/字框‘’（感觉和英文输入法一样了）
       我点击右上角工具栏“中”再点击“汉语（intelligentpinyin）拼音”，在文本里又能输入中文，也能选词（恢复正常）。但是过一会儿，有出现上述情况。
我不知道怎么查看相关log。
如果需要更多信息，请告诉我怎么做。
只能描述现象给你。

感谢！

**Comment by epico** [comment]
猜测是 libpinyin 的 bug 造成的，可能是 Ubuntu 的 libpinyin 版本不够高。

或者清除用户目录 ~/.cache/ibus/libpinyin/, 看问题是否消失。

请给 Ubuntu Launchpad 报 bug, 并 CC me.

**Comment by ping-wu** [comment]
https://bugs.launchpad.net/ubuntu/+source/ibus-libpinyin/+bug/1768166

**Comment by epico** [comment]
上边的 bug, 有人提供了最新的 libpinyin 和 ibus-libpinyin 的 Ubuntu PPA.
URL:
https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-libpinyin

请试试看，看问题是否消失？

**Comment by ping-wu** [comment]
我使用了 ibus-libpinyin 2.10 一阵了，这个问题好像没有再出现。不过想知道其他人的经验如何。

**Comment by russell-li** [comment]
@ping-wu 您好，看了你发的ubuntu论坛帖子，请问下面这个是什么意思，初学，见谅。

Changed in ibus-libpinyin (Ubuntu):
--
status: | New → Incomplete

是要改这个么？要在哪里改

**Comment by XunGong99** [comment]
I have the Same question recently, seems `rm -rf /.cache/ibus/*pinyin` does work. 
THX.

**Comment by YaoLingyun** [comment]
我被这个问题也困扰liao2 好久

**Comment by epico** [comment]
Fixed in ibus-libpinyin 1.11.1.
