### ISSUE TITLE
激活ibus libpinyin且shift在英文模式下无法使用Tab键补全

### ISSUE THREAD

**Issue by ganloo** [libpinyin/ibus-libpinyin#118]
Shift键下的英文模式，（Nautilus，Terminal）无法用Tab键补全功能，然而Sunpinyin，rime却都是可以的。只有用Windows+Space切换回纯英文模式后才可以。

**Comment by epico** [comment]
It works with gnome-terminal on Fedora 27 with libpinyin 2.2.0 and ibus-libpinyin 1.10.0.

Could you test it with Fedora 27 with latest packages?

**Comment by ganloo** [comment]
Sorry I tested again, Gnome Terminal works eventually but Nautilus doesn't. I am using Archlinux with libpinyin 1.9.3, thanks.

**Comment by epico** [comment]
Sorry, how do you use or test Nautilus?

**Comment by ganloo** [comment]
打开文件（Nautilus），Ctrl+L 激活地址栏，正常情况下我可以使用Tab去自动补全如/usr/libs……，但是在libpinyin的英文模式下失效。纯英文模式或者Sunpinyin/rime的英文模式下都是可以的。谢谢。

**Comment by epico** [comment]
我试了试纯英文模式，Nautilus 在英文键盘下也是不支持 Tab 的。

可以给 Nautilus 也报个问题，请把相关问题的链接粘贴过来，谢谢。

**Comment by ganloo** [comment]
我指的是Nautilus自动补全地址，如/usr/share，我只需要输入/u，然后按Tab键，Nautilus会自动补全为/usr。这在英文模式下是可以的，在Sunpinyin, rime的英文模式下也是可以的。应该是我前面说的不清楚。

**Comment by epico** [comment]
能否测试一下 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0 上能否复现？

**Comment by ganloo** [comment]
我编译并升级到了最新的1.10.0，已经没有这个问题，呵呵，谢谢。

**Comment by ping-wu** [comment]
是否可以告知一下编译的步骤？我想在Ubuntu 18.04 里试试。谢谢！

**Comment by epico** [comment]
不客气。你们可以继续讨论。
