### ISSUE TITLE
ibus-pinyin不使用默认键盘布局

### ISSUE THREAD

**Issue by peter-jerry-ye** [libpinyin/ibus-libpinyin#119]
你好，
我目前的问题是，我有多个语言，英语法语键盘布局。而当我切换到中文时，键盘布局是根据我之前使用的那个语言的布局，而非我电脑的默认键盘布局。
另外一个问题在于，我设置了在不同窗口可以使用不同的语言，但是我在这个窗口使用中文（英文键盘布局），然后我切到另一个正在用法文的窗口，再回到这个窗口时，键盘布局变成了法文布局，受到了严重干扰。
不知道你们能否解决这个问题？我是否应该去ibus或者libpinyin里提交这个issue？
日语mozc输入法也存在这个问题。

**Comment by epico** [comment]
请自行修改 /usr/share/ibus/component 对应输入法的 xml 文件的 "<layout>default</layout>" 部分。

**Comment by peter-jerry-ye** [comment]
问题已解决。谢谢。
