### ISSUE TITLE
输入中文“与”时，“与”字下面的一横，笔画不对，穿出来了，“写”也是，请完善，谢谢

### ISSUE THREAD

**Issue by huastone2018** [libpinyin/ibus-libpinyin#120]
与字下面的一横，还是一横，但这一横的右侧，超出了附近组合笔画 横和弯钩的边界，太长了。

**Comment by epico** [comment]
这个是字体的问题，请汇报到所使用的 Linux 发行版。

**Comment by huastone2018** [comment]
发行版是ubuntu 18.04 LTS, amd-64bit。我是开放人员，也觉得是字体问题，但我有看到libpinyin有自带字体：  libpinyin-data:amd64，版本2.1.91-1（使用dpkg -l查询）。 说明是“Data for PinYin / zhuyin input method library”，请教如何解决呢？

**Comment by epico** [comment]
libpinyin-data 是输入法数据文件，不是字体。

该问题在简体中文界面下会消失。

或者在 .bash_profile 中加入:
export FC_LANG=en-US:zh-CN
