### ISSUE TITLE
在gnome自带程序中无法输入右引号等问题

### ISSUE THREAD

**Issue by akrisrn** [libpinyin/ibus-libpinyin#121]
fedora 28，gnome 3.28.1，libpinyin 1.10.0

在gnome-terminal、nautilus、gedit等gnome自带程序中输入时发现了两个问题。

- 无法输入中文右引号，一直都是左引号
- 带下划线的预输入字符无法彻底删除，最后一个字会一直留在屏幕上，失去焦点后才会消失

在chrome、gimp、vscode等后来安装的程序中没发现以上问题。

**Comment by epico** [comment]
如果是 wayland 特有的话，问题有可能出在 ibus 中。

请用英文汇报 issue 到 ibus, 并把问题链接粘贴过来，我会一起调查这个问题的。

**Comment by epico** [comment]
Already fixed in GNOME upstream.
