### ISSUE TITLE
ibus输入法的问题

### ISSUE THREAD

**Issue by brucekane22** [libpinyin/ibus-libpinyin#122]
debian9.4 stable，GNOME Shell 3.22.3，ibus智能拼音1.7.3 
在使用ibus过程中有如下问题：
1. 切换成中文输入法后，输入的第一个字母仍旧以字母形式输出到文本框，从第二个字母开始，才有中文输入显示框 （偶尔出现，但经常出现，重现几率高）
2. 使用中文输入法后，从某一刻开始，所有的输入不再显示，当ctrl+space切换成英文输入法后，之前输入的所有中文一次性输出到文本框中。（偶尔出现）
3. 某些输入文本的地方，完全无法输入中文，比如amule的搜索框。切换成英文输入法后，一切都没问题。（必现）

以上问题在debian8中没有遇到，请检查，谢谢。

**Comment by punkmonday** [comment]
fedora28 gnome shell 3.28 也出现这个问题，但是只是在gnome-terminal和Activities里的输入框切换会有buffer残留，光标会消失，网页上没有问题。

**Comment by epico** [comment]
Fedora 和 Debian 的版本号相差很多，可能是不同的问题。

请问能否在 Debian 测试下 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0.
在 github.com 上有 tar ball 下载。

Fedora 的问题，我回来看一下。

**Comment by epico** [comment]
在 Fedora 28 中，在 Xorg 模式下没有这个问题，是 wayland 特有的。

**Comment by nicholascw** [comment]
Telegram Desktop, GNOME 3.28.2, 3.26, 3.24, Arch Linux 4.9~16,稳定复现.
以前Ubuntu GNOME 16.04 上也有这问题.

**Comment by epico** [comment]
Already fixed in GNOME upstream.

**Comment by epico** [comment]
Fedora 28 的问题应该已经在 GNOME 上游修复。

**Comment by wffger** [comment]
Fedora 32上Telegram输入不了中文呀

**Comment by punkmonday** [comment]
> Fedora 32上Telegram输入不了中文呀

试试[ibus-rime](https://rime.im/)吧

**Comment by wffger** [comment]
> > Fedora 32上Telegram输入不了中文呀
> 
> 试试[ibus-rime](https://rime.im/)吧

试了，一样没法输入中文。

**Comment by epico** [comment]
请问 Telegram 是如何安装的？ rpm 还是 flatpak?

**Comment by wffger** [comment]
官网下载压缩包，解压后直接运行可执行文件Telegram。

**Comment by epico** [comment]
flatpak 版本的 Telegram 也有问题吗？

**Comment by wffger** [comment]
flatpak版本可以输入中文。此前因为网速问题，一直不安装flathub的软件。现在参考《[试用为中国大陆用户打造的 Flathub 镜像](https://zh.fedoracommunity.org/2020/05/13/try-on-flatpak-mainland-china-mirror.html)》，下载网速可以接受。
