### ISSUE TITLE
输入中文“与”或者“与”字时，下面的一横，笔画不对，见图，请教如何解决，谢谢

### ISSUE THREAD

**Issue by huastone2018** [libpinyin/ibus-libpinyin#123]
系统是ubuntu 18.04 LTS, amd-64bit。我是开发人员，也觉得是字体问题，但我有看到libpinyin有自带字体： libpinyin-data:amd64，版本2.1.91-1（使用dpkg -l查询）。 说明是“Data for PinYin / zhuyin input method library”，请教如何解决呢？   现象请见下面贴图：
![libpinyin bug](https://user-images.githubusercontent.com/39025953/39858910-97a4fe08-546a-11e8-9854-b3b212b825ec.jpg)

**Comment by huastone2018** [comment]
![libpinyin bug2](https://user-images.githubusercontent.com/39025953/39859059-23269b26-546b-11e8-826d-2b5120ff5c36.jpg)

**Comment by huastone2018** [comment]
![libpinyin bug3](https://user-images.githubusercontent.com/39025953/39903939-32e783c0-5508-11e8-931b-a16a2e1ba6b9.jpg)

![libpinyin bug4](https://user-images.githubusercontent.com/39025953/39903949-41ef8b7e-5508-11e8-9d4b-7c5968b96f27.jpg)

同样在fiefox浏览器下，在github下输入与时，包括与在输入法的候选框和网页的显示框，与显示都是不对的，但在bing.com的输入框下，输入与时，仅在输入法的候选界面与的笔画不对，但输入到网页之后，显示是正常的。  现象见上面2个图片，很是困惑，请教如何解决这个问题？

**Comment by epico** [comment]
libpinyin-data 是输入法数据文件，不是字体。

该问题在简体中文界面下会消失。

或者在 .bash_profile 中加入:
export FC_LANG=en-US:zh-CN

**Comment by huastone2018** [comment]
ref :
https://www.zhihu.com/question/47141667/answer/112253917
https://wiki.archlinux.org/index.php/Arch_Linux_Localization_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#.E4.BF.AE.E6.AD.A3.E7.AE.80.E4.BD.93.E4.B8.AD.E6.96.87.E6.98.BE.E7.A4.BA.E4.B8.BA.E5.BC.82.E4.BD.93.EF.BC.88.E6.97.A5.E6.96.87.EF.BC.89.E5.AD.97.E5.BD.A2
