### ISSUE TITLE
使用libpinyin导致Libreoffice崩溃

### ISSUE THREAD

**Issue by ganloo** [libpinyin/ibus-libpinyin#125]
我在终端中只有这个没什么用的信息。如果使用ibue-rime，没有碰到问题，ibus-libpinyin在其他程序中也没有这个问题。只有Libreoffice（只在输入时，能正常打开libreoffice程序）会崩溃。系统环境为archlinux， gnome 3.28.2
终端出错信息：
[gl@archlinux ~]$ libreoffice 
javaldx: Could not find a Java Runtime Environment!
Warning: failed to read path from javaldx

我的ibus-libpinyin，libreoffice等版本如下：(均为最新版)
[gl@archlinux ~]$ pacman -Qs libreoffice
local/libcdr 0.1.4-3
    CorelDraw file format importer library for LibreOffice
local/libreoffice-fresh 6.0.4-1
    LibreOffice branch which contains new features and program enhancements
local/libreoffice-fresh-zh-cn 6.0.4-1
    Chinese (simplified) language pack for LibreOffice Fresh
[gl@archlinux ~]$ pacman -Qs libpinyin
local/ibus-libpinyin 1.10.0-1
    Intelligent Pinyin engine based on libpinyin for IBus
local/libpinyin 2.2.0-1
    Library to deal with pinyin

**Comment by epico** [comment]
这个问题请汇报到 ArchLinux 的 LibreOffice 组件。

**Comment by ganloo** [comment]
Ok，不过我不清楚为什么使用ibus-rime则没有问题。

**Comment by epico** [comment]
我现在也不太清楚，等等 LibreOffice 开发者的回复吧。

**Comment by ping-wu** [comment]
我在 Ubuntu 18.04 下没有问题。

是否试一试 LibreOffice 的 AppImage?

**Comment by epico** [comment]
请问此问题是否仍然在 Arch Linux 中存在？

**Comment by epico** [comment]
No response, just close this issue now.
