### ISSUE TITLE
无法选择除第一个外的候选词

### ISSUE THREAD

**Issue by gbk** [libpinyin/ibus-libpinyin#127]
描述详见： https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891954

- Ubuntu 18.04 LTS 64 位
- GNOME 3.28.1
- IBus 版本 1.5.17
- IBus 智能拼音 1.9.2

最近频繁发生无法选择除第一个外候选词的情况，
例如：
- 想要输入`实时`，
- 拼音输入`shishi`后发现候选词在第 5 个，
- 此时按下键盘 5，候选框消失
- 期望`实时`进入到输入区域，实际 `5` 进入到了输入区域
- 然后系统会生成一份崩溃报告

一旦发生该情况后续可一直重现，除非将 ~/.cache/ibus/libpinyin/* 删除

**Comment by zhangyz189** [comment]
我也遇见这样的情况
- Ubuntu 18.04 LTS 64bit
- GNOME 3.28.1
- IBus 1.5.17
- IBus 智能拼音 1.9.2
使用super+space 切换英文后在切中文后可用

**Comment by epico** [comment]
请把详细的 backtrace 上传到此 issue, 我看看能能不能发现问题。

同时，请汇报给 Ubuntu 的 Launchpad.

要是还不能解决问题的话，等我有空，安装个 Ubuntu 18.04 试试。

**Comment by Deali-Axy** [comment]
我也遇到过这种情况，无奈之下只好换成ibus-pinyin了。

**Comment by dingqing** [comment]
我也是Ubuntu 18.04 LTS 64bit，一开始shi hao的，用zhe用zhe就出现同样问题了，真是无奈。

**Comment by BiggerChina** [comment]
我遇到过这种情况,产生的原因是 因为 升级了 gnome的版本,  
查看系统日志,可以看到 ibus发生错误了.
解决办法是 新建一个用户,在新用户下就好了.
应该是 配置文件有问题.把 ibus 相关的配置文件 删除,让程序自己再生成一版就好了.

**Comment by gbk** [comment]
@BiggerChina 删除全部配置文件重新生成后过一段时间仍可能出现……

**Comment by epico** [comment]
请给 Ubuntu 报 bug, 升级到 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0, 谢谢。

**Comment by peter-jerry-ye** [comment]
@epico 你好，我使用
https://launchpad.net/%7Egunnarhj/+archive/ubuntu/ibus-libpinyin
这个PPA，ibus-libpinyin 1.10.0，也有这个问题。

**Comment by epico** [comment]
@peter-jerry-ye 请在命令行下，将 ~/.cache/ibus/libpinyin/* 删除，试试。

**Comment by peter-jerry-ye** [comment]
@epico 可以了，谢谢。

**Comment by ping-wu** [comment]
试试只删除 opengram.dbin 跟 gb_char.dbin ， 不必删除整个档案夹。

**Comment by ping-wu** [comment]
看起来目前最好的方案乃是把 .cache/ibus/libpinyin 做成一个备份，出问题时马上还原回去。

**Comment by ping-wu** [comment]
好久没有出问题，已经解决了？

可能跟 gnome 的 update 有关？

**Comment by epico** [comment]
可能是 libpinyin 的版本不够高，libpinyin 2.2.0  应该已经修复了。

**Comment by ping-wu** [comment]
从 Ubuntu 中文论坛上，我感觉到有问题的总是那些系统里也装了搜狗的人。

可能是他们在装 fcitx 时（required by 搜狗），影响了系统的稳定性。

我不知道把 fcitx 拆卸掉是否系统就可以恢复正常。But my recommendation is: Don't install fcitx in Ubuntu。

**Comment by ping-wu** [comment]
另外，根据 Ubuntu 中文论坛一位使用者的报导：

Re: 18.04 你们的ibus 拼音输入法 没有出什么问题么？
#8 帖子  由 slave » 2018-06-27 8:42
输入法首选项 外观 候选词排列方向 改垂直 再改回水平

搞定！

**Comment by outshow** [comment]
根据@ping-wu的方法 ，删除 opengram.dbin和user_bigram.db后问题解决。谢谢。

**Comment by gbk** [comment]
@ping-wu 目前还是没有解决，
我没有安装 fcitx 也能重现，基本上每半个月一次，
候选词排列方向改垂直再改回水平不能解决问题，
目前唯一有效的办法是删除 `~/.cache/ibus/libpinyin/opengram.dbin` 和 `~/.cache/ibus/libpinyin/user_bigram.db` 文件。

**Comment by russell-li** [comment]
装了1.10.0，20天左右没出现问题了，今天又出现问题了，在CSDN写东西的时候出现的，用删除 opengram.dbin和user_bigram.db的方法解决了。 @ping-wu 我一直用的原装18.04自带的输入法，应该不是fcitx的问题。

**Comment by yangzhichina** [comment]
把.cache/ibus这个目录删除，然后再使用拼音就可以正常选字了。不能选字的时候，真是着急。上班的时候不能和别人正常沟通了。

**Comment by epico** [comment]
有可能是发行版打包了libpinyin 的不稳定版本，请用 libpinyin 的 tar ball 版本。
推荐用 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0 的 tar ball 版本，在 github.com 上已经有 tar ball 可以下载了。

**Comment by ICHx** [comment]
Ubuntu 18.10. 我發現我只要一導入這個詞庫，就會出現這個問題
https://github.com/broly8/libpinyin-dict

**Comment by ICHx** [comment]
clear dictionary就沒事，不過這樣就無法享受詞庫的便利了

**Comment by ICHx** [comment]
Intelligent Pinyin 1.10.0

**Comment by epico** [comment]
可以试试 Fedora 29 Live Workstation 吗？

我导入了词库，没发现问题。建议给 Ubuntu Launchpad 报个 issue.

**Comment by russell-li** [comment]
更新后仍然每隔一段时间出现这个问题，不过目前替换文件夹的方法可以解决。

**Comment by epico** [comment]
libpinyin 2.2.x 和 ibus-libpinyin 1.10.0 才是稳定版本。

**Comment by shalk** [comment]
@epico  了解

顺便想问一下， 本项目的稳定版本会在什么时候进入到ubuntu的官方仓库？

虽然这个仓库可能和本项目无关，如果您了解的话。

```
sudo apt show  ibus-libpinyin
Package: ibus-libpinyin
Version: 1.9.2-2
Priority: optional
Section: utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: IME Packaging Team <debian-input-method@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2,761 kB
Depends: ibus, python3:any (>= 3.3.2-2~), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libglib2.0-0 (>= 2.37.3), libibus-1.0-5 (>= 1.5.14), libpinyin13 (>= 2.1.0), libsqlite3-0 (>= 3.6.11), libstdc++6 (>= 5.2), python3-gi
Homepage: https://github.com/libpinyin/ibus-libpinyin
Task: ubuntu-live
Supported: 5y
Download-Size: 671 kB
APT-Manual-Installed: yes
APT-Sources: http://mirrors.ustc.edu.cn/ubuntu bionic/main amd64 Packages

```

**Comment by luneice** [comment]
> 请给 Ubuntu 报 bug, 升级到 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0, 谢谢。

您好，这个要怎么才能更新到 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0?需要增加额外的源还是什么？

**Comment by gbk** [comment]
> > > 请给 Ubuntu 报 bug, 升级到 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0, 谢谢。
> > 
> > 
> > 您好，这个要怎么才能更新到 libpinyin 2.2.0 和 ibus-libpinyin 1.10.0?需要增加额外的源还是什么？
> 
> 我知道怎么解决了，谢谢！问题现在已经解决了！
> 具体操作是需要添加额外的PPA，问题在这个页面（[点击进入](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-libpinyin)），具体的操作步骤如下：
> 
> ```
> sudo add-apt-repository ppa:gunnarhj/ibus-libpinyin
> sudo apt-get update
> sudo apt-get upgrade
> ```
> 然后重启系统即可，问题就可以解决了，希望可以帮到遇到同样问题的同学。
> Hey, guys! This problems was solved. [There are details about this bug, and give a solution](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-libpinyin). You can flow these steps to solve it:
> 
> ```
> sudo add-apt-repository ppa:gunnarhj/ibus-libpinyin
> sudo apt-get update
> sudo apt-get upgrade
> ```
> After that, execute this shell `reboot`, enjoy typing!

半年前已更新，但至今仍不定期重现，该问题并未解决。

**Comment by epico** [comment]
推荐删除 ~/.cache/ibus/libpinyin/user.conf 文件，不然数据是不完整的。

不知道是不是 Kyoto Cabinet 的问题，也许应该考虑继续使用 Berkeley DB 5.3 版本...

**Comment by epico** [comment]
或者继续将用户文件加载到内存，而不是直接打开？

为了改善输入法加载，之前我将加载到内存，改为了直接打开。

**Comment by epico** [comment]
Reverted in https://github.com/epico/libpinyin/commits/master .

**Comment by zhang8473** [comment]
同问，刚刚遇到此类错误

**Comment by epico** [comment]
刚刚发布 libpinyin 2.2.2, 文件损坏的问题应该会减轻。

**Comment by luneice** [comment]
问题又出现了，怎么更新到 ``` libpinyin 2.2.2 ```，具体的命令? thanks.

**Comment by luneice** [comment]
刚刚又出现这个问题，几经周折安装到 ``` libpinyin 2.2.2 ```结果发现还是无法输入候选字，于是卸载了 ``` fcitx ```问题目前没有了。

**Comment by winfredkqin** [comment]
> 从 Ubuntu 中文论坛上，我感觉到有问题的总是那些系统里也装了搜狗的人。
> 
> 可能是他们在装 fcitx 时（required by 搜狗），影响了系统的稳定性。
> 
> 我不知道把 fcitx 拆卸掉是否系统就可以恢复正常。But my recommendation is: Don't install fcitx in Ubuntu。

我没有安装搜狗，还是出问题。希望可以尽快修复。 Ubuntu 18.04

**Comment by epico** [comment]
Ubuntu 18.04 中 libpinyin 版本为 2.1.91, 这是一个不稳定版本，请至少更新到 2.2.0 .

**Comment by gbk** [comment]
![image](https://user-images.githubusercontent.com/865717/54068142-1c559d80-4284-11e9-922b-65cb71664b05.png)
libpinyin 2.2.2 稳定运行一个月没有再重现了该问题了

**Comment by YaoLiMuMu** [comment]
As to me

**Comment by zhang8473** [comment]
使用slack，pycharm之类软件输入中文的时候拼音候选框出现在了屏幕边缘或者外面，导致无法选词。
1.1.10版本

**Comment by gbk** [comment]
> 使用slack，pycharm之类软件输入中文的时候拼音候选框出现在了屏幕边缘或者外面，导致无法选词。
> 1.1.10版本

是 qt 软件么？我记得用 qtconfig-qt4 设置一下光标跟随就行的。

**Comment by gbk** [comment]
libpinyin 2.2.2 稳定运行三个月没有再重现了该问题了。
close :+1:

**Comment by ichobits** [comment]
在新立德软件包管理里显示1.9.x版本的ibus是灰色，应该是有问题。
然后更新软件到新1.11.X版本后，可以正常选择词。
