### ISSUE TITLE
ibus版本

### ISSUE THREAD

**Issue by colorsakura** [libpinyin/ibus-libpinyin#130]
configure: error: Package requirements (
    ibus-1.0 >= 1.5.11
) were not met:

No package 'ibus-1.0' found
但是我的ibus是
ibus version
IBus 1.5.17

**Comment by colorsakura** [comment]
电脑是centos7.5

**Comment by epico** [comment]
请检查 ibus-devel 是否安装。

**Comment by colorsakura** [comment]
感谢，确实没有装

**Comment by colorsakura** [comment]
@epico 请问,我通过编译安装了libpinyin2.2.0 ,为什么安装ibus-libpinyin 的时候提示没有 libpinyin 呢, 关于linux,我还是个新手,希望您多指导一下.

**Comment by epico** [comment]
请用 ./configure --prefix=/usr .
