### ISSUE TITLE
在VScode里面无法输入中文

### ISSUE THREAD

**Issue by frogPeng** [libpinyin/ibus-libpinyin#131]

**Comment by frogPeng** [comment]
求大神指导，在其它地方都可以输入中文，但是在VScode当切换到这个中文输入法时，无法输入中文，英文也没用！！

**Comment by epico** [comment]
请用英文汇报到 ibus:
https://github.com/ibus/ibus/issues

**Comment by levinit** [comment]
@frogPeng  尝试将以下三行添加到/etc/enviroment
  export GTK_IM_MODULE=ibus
  export XMODIFIERS=@im=ibus
  export QT_IM_MODULE=ibus

注销后再试试看

**Comment by Ydcool** [comment]
> @frogPeng 尝试将以下三行添加到/etc/enviroment
> export GTK_IM_MODULE=ibus
> export XMODIFIERS=@im=ibus
> export QT_IM_MODULE=ibus
> 
> 注销后再试试看

ubuntu 19.04 无效

**Comment by fengyunhe** [comment]
在ubuntu仓库里安装的vscode版本是有问题的，从官网下载vscode安装就可以输入了，有一个问题是输入法的候选字的选择框的位置在这种基于web打包的程序总是飘忽不定。

**Comment by epico** [comment]
请问此问题是否仍然在 Ubuntu Linux 中存在？

**Comment by fengyunhe** [comment]
> 请问此问题是否仍然在 Ubuntu Linux 中存在？

官网下载deb安装没有问题

**Comment by hurae** [comment]
snap打包存在此问题，可以采用原生安装解决

**Comment by alreadytakenn** [comment]
在ubuntu20.04, Pycharm 也遇到了这个问题.

**Comment by epico** [comment]
请用英文在 ibus upstream 讨论。

**Comment by alx696** [comment]
@epico 这个问题可以关闭,我是最近几个月才用vscode. 但中文输入一直都没问题,相比idea太正常了.

操作系统: Ubuntu 20.04.1 LTS

Visual Studio Code:
```
版本: 1.52.1
提交: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
日期: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-58-generic
```
> 连续升级了好几个版本,一直都是从官网下载deb安装, 搜狗,百度输入法也都一直正常.

**Comment by fatalc** [comment]
如果是使用snap安装的建议换成apt安装

**Comment by cnfatal** [comment]
对于 vscode ，如果以 snap 方式安装的，有一定概率触发无法输入；可以考虑切换为 apt 安装的。chrome 同理

**Comment by zouming74** [comment]
add these to `.bashrc ` or  `.zshrc`
```
 export GTK_IM_MODULE=ibus
 export XMODIFIERS=@im=ibus
 export QT_IM_MODULE=ibus
```
