### ISSUE TITLE
鹋 should not be offered as a candidate character in traditional Chinese mode

### ISSUE THREAD

**Issue by patrickdark** [libpinyin/ibus-libpinyin#136]
(This is a near‐duplicate refile of https://github.com/ibus/ibus/issues/2022 as requested in the comment at https://github.com/ibus/ibus/issues/2022#issuecomment-403350319.)

Which distribution and version?: Ubuntu 18.04
Which desktop environment and version?: ubuntu:GNOME (I don't know how to determine the version)
Which session type?: x11
IBus version?: 1.5.17
Issue description: "鹋" is offered as a candidate character when using the traditional mode of the "Chinese (Intelligent Pinyin)" input method with the input "miao" and "ermiao" ("鴯鶓"). Furthermore, in a default installation, it's suggested with higher priority than the traditional variant, "鶓".

**Comment by epico** [comment]
For Traditional Chinese, please try ibus-libzhuyin instead.

**Comment by patrickdark** [comment]
@epico 不幸的，這不解決拼音輸入法錯誤。因為拼音比注音好，所以不想取代。

（很抱歉我的漢語不太好了。）

**Comment by epico** [comment]
ibus-libzhuyin 支持拼音方案，只是需要音调。
