### ISSUE TITLE
shift 从中文切换到英文时，将已输入的字母直接上屏

### ISSUE THREAD

**Issue by zhuleilei** [libpinyin/ibus-libpinyin#139]
工作中经常中英文切换输入，使用shift可以切换中英文，但是在windows下的输入法中，直接在中文状态下输入字母后 按 shift切换到英文时，会自动将已经输入的字母上屏， sunpinyin中也有这个功能，libpinyin 我我看了配置中目前没有这个功能，而且libpinyin中 按v输入英文，似乎只能输入字典中存在的单词，如果不能匹配单词，空格键 将也无法将已输入的字母上屏，必须按 回车键，而且，会把首个模式字母 v 也加在了单词前面。

**Comment by zhuleilei** [comment]
额，和 #106  重复了。关闭了。

**Comment by levinit** [comment]
貌似没发现可以 你可以按下回车键输入的就是字母了 然后再按shift切换模式吧

**Comment by epico** [comment]
Fixed English Editor in https://github.com/epico/ibus-libpinyin/commit/f4d792986e5d52e6104d0e9ab159a8197608667d .
