### ISSUE TITLE
Centos 7 重启之后无法使用libpinyin

### ISSUE THREAD

**Issue by XiaofanLii** [libpinyin/ibus-libpinyin#141]
RT,每次重启机器后都无法输入中文,后来发现如下设置一下就可以,但是每次重启机器都这样好麻烦...
Setting->Region & Language -> Input Source这里随便添加一个源,之后,就可以切换到中文,不知道什么原因

**Comment by epico** [comment]
试试 yum reinstall "ibus*" 能否解决问题？

**Comment by XiaofanLii** [comment]
还是不行，ibus-1.5.17-2.el7.x86_64 Intelligent Pinyin 1.6.91

**Comment by baronv5** [comment]
我按照一篇[帖子](https://blog.csdn.net/buildcourage/article/details/80649194)中的办法解决了这个问题
`yum install im-chooser`
`imsettings-switch ibus`

**Comment by XiaofanLii** [comment]
@baronv5 确实可以了感谢
