### ISSUE TITLE
atom里输入中文会吃字符

### ISSUE THREAD

**Issue by PatrickHuang888** [libpinyin/ibus-libpinyin#143]
在atom里编辑markdown文件，比如输入“问题，”接着输入就会把“，”吃掉，很麻烦。
是ibus的问题还是输入法的问题？

系统ubuntu18.04, gnome

**Comment by epico** [comment]
建议用英文问问 ibus 的维护者。

**Comment by PatrickHuang888** [comment]
我的IDE GoLand里试了一下，工作正常，so assume maybe the problem is Atom

**Comment by PatrickHuang888** [comment]
今天试了一下vscode正常，目前用vscode代替了atom
