### ISSUE TITLE
多屏幕下在第二屏幕里输入候选框无法正常更新

### ISSUE THREAD

**Issue by ph3rin** [libpinyin/ibus-libpinyin#144]

**Comment by ph3rin** [comment]
系统：Ubuntu 18.04.1 LTS x64 on Gnome, Wayland

**Comment by epico** [comment]
可以用英文问问 ibus 的维护者。

另外，可以试试 Fedora 28 Workstation Live，是否有问题；如果没有问题的话，请要求 Ubuntu 升级 ibus 到 Fedora 的版本。

**Comment by neewbee** [comment]
fedora 29 have this issue too.

**Comment by neewbee** [comment]
https://github.com/ibus/ibus/issues/2048

**Comment by waynezwf** [comment]
fedora29 也有这个问题。

另外问一个问题：选字窗口中的大图标，怎么去掉，每次输入的时候，总有个图标文字特别大，显示在选择窗格中

**Comment by epico** [comment]
选字窗口中的大图标?

**Comment by waynezwf** [comment]
输入汉字的时候，在候选字窗格中，常常会出现一个很大的表情符号，一般都是在第4个字符位置上，如果小一点是可以接受的，主要就是太大了，大约有：128px X 128px 那么大，导致候选字窗格变得很大。

![2018-11-12 13-34-12](https://user-images.githubusercontent.com/22018207/48328638-e1e64600-e67f-11e8-8739-441f6a0b7626.png)

**Comment by epico** [comment]
在 Fedora 29 上无法复现大图标。

**Comment by waynezwf** [comment]
我现在用的就是Fedora 29，能否告诉我，正常情况显示的是否是一样的图标？我检查一下是不是系统字体设置有问题？

**Comment by epico** [comment]
这里显示的图标和文字一样大。

请问是否安装了 gnome-shell 的扩展？

**Comment by epico** [comment]
请问此问题是否仍然在 Fedora Linux 中存在？

**Comment by epico** [comment]
No response, just close this issue now.
