### ISSUE TITLE
无法选择第一个候选词语之后的其他词语

### ISSUE THREAD

**Issue by wulidongdong** [libpinyin/ibus-libpinyin#145]
没办法选择除了第一个候选词语以外的其他词语，无论是用数字还是空格，并且之后输入法就崩坏了，只能通过切换语言才能重新输入。

**Comment by OURCKTheCoder** [comment]
和#127重复了。
也许你可以试试删除缓存~/.cache/ibus/libpinyin/*，不过之前的输入记录（比如词频等信息）会消失。慎用。
