### ISSUE TITLE
在没有任何键盘操作的情况会自动产生不能选择的候选词

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/ibus-libpinyin#146]
如图所示，确认不是云集成带来的 bug ，我在编译时去掉了云功能的代码。代码为最新的 git 版本。
![2018-10-10 15-28-11](https://user-images.githubusercontent.com/1880237/46719870-98ca5d00-cca1-11e8-91b1-88a32b52cc2c.png)

**Comment by epico** [comment]
请更新 libpinyin 到 2.2.1.
