### ISSUE TITLE
Arch下无法在特定app中使用

### ISSUE THREAD

**Issue by KaiserKkaiser** [libpinyin/ibus-libpinyin#148]
安装完成后发现可以在terminal和chrome上使用，但不能在telegram上使用。初步怀疑是GTK的问题，但是按照arch wiki添加了 
(gtk2) export GTK_IM_MODULE_FILE=/etc/gtk-2.0/gtk.immodules
 (gtk3) export GTK_IM_MODULE_FILE=/usr/lib/gtk-3.0/3.0.0/immodules.cache
到～/.bashrc中还是无法解决问题。

**Comment by epico** [comment]
建议用英文给 ibus 报个 issue.

**Comment by KaiserKkaiser** [comment]
> 建议用英文给 ibus 报个 issue.

好的 辛苦了。
