### ISSUE TITLE
切换到另一个窗口后丢失中英文状态信息

### ISSUE THREAD

**Issue by archstrange** [libpinyin/ibus-libpinyin#151]
系统：Ubuntu 18.10， ibus-libpinyin 版本 1.10
在一个窗口切换为中文后，focus 到另一个窗口，再回到原来的窗口，发现输入状态就变成了英文。

**Comment by ghostry** [comment]
ubuntu系统设置里有一个选择,所有窗口使用相同输入源,和,每个窗口使用单独输入源.

如果选的是单独,就会是你说的这种表现.

**Comment by archstrange** [comment]
如果是单独，为什么不保存中英文状态呢？

**Comment by ghostry** [comment]
> 如果是单独，为什么不保存中英文状态呢？

不清楚,我用了很多版ubuntu都是这样.

**Comment by archstrange** [comment]
现在一直都是用 fcitx 了，好用一点

**Comment by ghostry** [comment]
> 现在一直都是用 fcitx 了，好用一点

是的,fcitx有个按程序,比ibus这个按窗口好多了.
