### ISSUE TITLE
fedora 29 输入词组：运行，选择词组后，输入框中没有结果

### ISSUE THREAD

**Issue by linshengjian** [libpinyin/ibus-libpinyin#153]
fedora 29 输入词组：运行，选择词组后，输入框中没有结果

**Comment by linshengjian** [comment]
> 请详细描述现象。

就是输入：yunxing，然后候选词选择“运行”，输入光标的地方会多了一个空格（用空格选择第一个候选词，如果用的是数字，这里会多一个数字），然后输入法就变成只能输入字母，需要切换到其他输入再切换回来，才能继续使用

**Comment by epico** [comment]
我这里无法复现，试试创建一个新用户试试。

过一阵儿，我会更新 Fedora 29 的 libpinyin 和 ibus-libpinyin.

**Comment by linshengjian** [comment]
> 我这里无法复现，试试创建一个新用户试试。
> 
> 过一阵儿，我会更新 Fedora 29 的 libpinyin 和 ibus-libpinyin.
新创建用户，没有这个问题

**Comment by linshengjian** [comment]
> 我这里无法复现，试试创建一个新用户试试。
> 
> 过一阵儿，我会更新 Fedora 29 的 libpinyin 和 ibus-libpinyin.

新创建的用户，没有这个问题

**Comment by epico** [comment]
请清理 ~/.cache/ibus/libpinyin/ 目录，看看能否解决问题。

**Comment by linshengjian** [comment]
这样可以解决了

**Comment by szdailei** [comment]
OS: Solus 3.9999
2018年12月20日系统升级以后，我遇到了同样的问题。
现象：只有第一个候选词可以使用SPACE或者1正确选择，其他候选词包括翻页后的第一个候选词，选择后直接显示原始的输入值(SPACE或者数字键)。
删除 ~/.cache/ibus/libpinyin/ 目录里面的下列文件，问题解决：
user_bigram.db
user_phrase_index.bin
user_pinyin_index.bin

**Comment by valiantkui** [comment]
我也出现了同样的问题，输入拼音时，出现词组，用数字选择时数字会替代词组而不会选择汉语词组，删除缓存内容后已经解决了，谢谢大神

**Comment by zhao-kun** [comment]
The same issue occurs on my ubuntu 18.10 laptop

**Comment by zhao-kun** [comment]
I've manually upgraded *libpinyin* to v2.2.2, will give feedback to you when the issues reproduced.

> 请将 libpinyin 升级到 2.2.2，清除数据后，看看问题会不会再出现。

**Comment by zhao-kun** [comment]
The issue hadn't been reproduced since I updated the latest libpinyin.
