### ISSUE TITLE
Configurable OpenCC mode

### ISSUE THREAD

**Issue by marmistrz** [libpinyin/ibus-libpinyin#154]
https://github.com/libpinyin/ibus-libpinyin/blob/master/src/PYSimpTradConverter.cc#L46
currently uses the default engine, which uses 爲了 for `weile`, while the `s2tw` engine.

If you help me I can add it myself, I don't know how to expose the configuration value so that it's accessible via the ibus interface.

**Comment by epico** [comment]
Currently ibus-libpinyins use GSettings.

How to add config key/value in ibus-libpinyin:

1. add the config key/value to com.github.libpinyin.ibus-libpinyin.gschema.xml
2. add the config key/value to src/PYConfig.* and src/PYPConfig.*
