### ISSUE TITLE
How to migrate "user-1.0.db" to ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by stevenGu** [libpinyin/ibus-libpinyin#156]
i installed UBT18.04 and used ibus-libpinyin 1.9.2. How to migrate "user-1.0.db"(built in UBT16.04) to ubuntu 18.04 continue used?

**Comment by epico** [comment]
The "user-1.0.db" file is from ibus-pinyin.

First you need to convert it to text format, then import it in setup dialog.

**Comment by stevenGu** [comment]
thank you for reply!
How to ¨convert it to text format¨?  need software?  I´m beginner Sorry!

**Comment by epico** [comment]
The "user-1.0.db" file is sqlite file format.

You need to SQL to convert it, and write some scripts I think.

Maybe also need to check some code of ibus-pinyin.
