### ISSUE TITLE
在中文模式下可否让小键盘区的小数点键依然保持半角状态

### ISSUE THREAD

**Issue by m0wong** [libpinyin/ibus-libpinyin#157]
目前是全角句号，个人认为大多数人使用数字键盘时还是想输入数字吧

**Comment by epico** [comment]
ibus-libpinyin 有半角/全角切换啊。

请问哪个拼音输入法是这样设计的？

**Comment by m0wong** [comment]
是可以切换，但是中文和小数混合输入要来回切换就不是很方便。
fcitx-sunpinyin，Windows 上的 Google 拼音、搜狗输入法，ibus-mozc （虽然不是中文，但日文的句号也是“。”），都是这样设计的。

**Comment by epico** [comment]
目前的问题是需不需要在 "首选项" 对话框加入新的选项以支持这个功能...

**Comment by m0wong** [comment]
仔细观察了一下，
结论：约等于没有。

fcitx-sunpinyin：
没有配置项，即小数点输出始终为小数点。
Google拼音和搜狗拼音：
关于小键盘，有配置项“小键盘功能”，可以选择“数字输入”或者“选字”，但是经测试，不影响小键盘小数点键，即输出始终为小数点。
ibus-mozc：
关于小键盘，有“input from numpad key”配置项，可以选择“direct input”或者“follow input mode”，选择“follow input mode”意味着如果处于日文模式会像按下主键盘句号一样出现选词框，但默认候选词依然是小数点。

【小声说，我个人投不需要配置项一票。😁

**Comment by epico** [comment]
Draft fixes in https://github.com/epico/ibus-libpinyin/commit/9a1474c0e4972fa4d7c53e19ac939f6d3faacc69 , but without tests.

**Comment by epico** [comment]
不客气，周五太忙了，谢谢提醒！

**Comment by epico** [comment]
As libpinyin 2.2.2 and ibus-libpinyin 1.11.0 are released, close issue.
