### ISSUE TITLE
No way to disable emoji candidates

### ISSUE THREAD

**Issue by jadahl** [libpinyin/ibus-libpinyin#158]
Since some version, ibus-libpinyin started to often show emoji candidates as the first candidate when typing something. In general, this means that for me very often the first alternative in the alternative window is incorrect, and I have to, compared to before, very often select the correct phrase manually.

Looking at ibus-setup and in the code, there seems to be no way to disable the emoji selection. I have no interest in using emoji, I just want to type words, but it's currently fairly frustrating.

**Comment by epico** [comment]
I think ibus-libpinyin will show word candidates with pinyin input, show the emoji candidates as the first candidate happens with English input.

**Comment by jadahl** [comment]
That is not the case. For example if I type "yier", the first result is "🕐", the second is "一二", and so one.

**Comment by jadahl** [comment]
This is Fedora 29. "Clear All Data" had no effect.

**Comment by epico** [comment]
Please provide ibus-libpinyin, libpinyin and ibus version.

Could you check if new user still have this issue?

**Comment by jadahl** [comment]
ibus-1.5.19-9.fc29.x86_64
libpinyin-2.2.1-1.fc29.x86_64
ibus-libpinyin-1.10.92-1.fc29.x86_64

I tried adding another user, logged in, added ibus-libpinyin, and I still got emojis.

Note that I use traditional characters, not simplified.

**Comment by epico** [comment]
Okay, I can reproduce this issue with Traditional Chinese now.

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/a0a9fd6b1deb4384ac7ca8ce0bc35c98d1193339 .

Scratch Build: https://koji.fedoraproject.org/koji/taskinfo?taskID=31947147

**Comment by jadahl** [comment]
I can confirm that the scratch build changes the behavior from showing the emoji first, to showing it in the 4th position, if any. Is that intended?

**Comment by epico** [comment]
Yes, it is designed like that. :smile:

**Comment by epico** [comment]
As libpinyin 2.2.2 and ibus-libpinyin 1.11.0 are released, close issue.
