### ISSUE TITLE
Error: near line 20005: database is locked

### ISSUE THREAD

**Issue by zxhaxdr** [libpinyin/ibus-libpinyin#160]
yinzheng@yinzheng-MS-7A33:~/Downloads/ibus-libpinyin-1.11.0$ make
make  all-recursive
make[1]: Entering directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0'
Making all in data
make[2]: Entering directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0/data'
Making all in icons
make[3]: Entering directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0/data/icons'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0/data/icons'
make[3]: Entering directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0/data'
  GEN      english.db
Error: near line 20005: database is locked
Makefile:902: recipe for target 'english.db' failed
make[3]: *** [english.db] Error 1
make[3]: Leaving directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0/data'
Makefile:581: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0/data'
Makefile:518: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/yinzheng/Downloads/ibus-libpinyin-1.11.0'
Makefile:448: recipe for target 'all' failed
make: *** [all] Error 2

====================================================================
yinzheng@yinzheng-MS-7A33:~/Downloads/ibus-libpinyin-1.11.0$ /usr/bin/sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1

**Comment by zxhaxdr** [comment]
Ubuntu 18.04 kernel 4.20.3 amd64

Tried make distclean then redo everything but still not working. Thank you.

**Comment by epico** [comment]
Please try to create a new account, and git clone again.

**Comment by epico** [comment]
Feel free to comment, if still have this issue.
