### ISSUE TITLE
1.11.0 coredump when bootup

### ISSUE THREAD

**Issue by lljgithub** [libpinyin/ibus-libpinyin#161]
evn: clear linux 
version :ibus-engine-libpinyin - Version 1.11.0

coredump like below: 
gdb) info proc 
exe = '/usr/libexec/ibus-engine-libpinyin --ibus'
gdb) bt
0x00007f43da1af931 in pinyin::ForwardPhoneticConstraints::ForwardPhoneticConstraints(pinyin::FacadePhraseIndex*)Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x30: 
 (phrase_index=#1  0x00007f43da1af931 in pinyin_alloc_instance(pinyin_context_t*)
....

log like below:
1月 27 14:37:49 clear kernel: ibus-engine-lib[1337]: segfault at 30 ip 00007fa10c13f931 sp 00007ffd4edada70 error 4 in libpinyin.so.13.0.0[7fa10c11e000+6c000]
1月 27 14:37:49 clear kernel: Code: fd ff 48 c7 43 20 00 00 00 00 bf 10 00 00 00 48 89 43 08 e8 71 e9 fd ff ba 0c 00 00 00 be 01 00 00 00 bf 01 00 00 00 49 89 c4 <49> 8b 45 30 49 89 44 24 08 e8 31 e9 fd ff 4c 8>
1月 27 14:37:49 clear systemd[1]: Started Process Core Dump (PID 1342/UID 0).
1月 27 14:37:49 clear systemd-coredump[1343]: Failed to compress (unnamed temporary file): Protocol not supported
1月 27 14:37:49 clear systemd-coredump[1343]: Process 1337 (ibus-engine-lib) of user 1000 dumped core.
                                               
                                               Stack trace of thread 1337:
                                               #0  0x00007fa10c13f931 _ZN6pinyin26ForwardPhoneticConstraintsC4EPNS_17FacadePhraseIndexE (libpinyin.so.13)
                                               #1  0x0000000000414ebc _ZN2PY16FullPinyinEditorC2ERNS_16PinyinPropertiesERNS_6ConfigE (ibus-engine-libpinyin)
                                               #2  0x000000000041863b _ZN2PY12PinyinEngineC2EP11_IBusEngine (ibus-engine-libpinyin)
                                               #3  0x000000000040a367 ibus_pinyin_engine_constructor (ibus-engine-libpinyin)
                                               #4  0x00007fa10c35417f g_object_new_with_custom_constructor (libgobject-2.0.so.0)
                                               #5  0x00007fa10c354f21 g_object_new_valist (libgobject-2.0.so.0)
                                               #6  0x00007fa10c355269 g_object_new (libgobject-2.0.so.0)
                                               #7  0x00007fa10c5662a4 ibus_engine_new_with_type (libibus-1.0.so.5)
                                               #8  0x00007fa10c56ac2c ibus_factory_real_create_engine (libibus-1.0.so.5)
                                               #9  0x00007fa10c578190 _ibus_marshal_OBJECT__STRING (libibus-1.0.so.5)
                                               #10 0x00007fa10c358bf5 g_closure_invoke (libgobject-2.0.so.0)
                                               #11 0x00007fa10c33ecc7 signal_emit_unlocked_R (libgobject-2.0.so.0)
                                               #12 0x00007fa10c34043a g_signal_emit_valist (libgobject-2.0.so.0)
                                               #13 0x00007fa10c340fdd g_signal_emit (libgobject-2.0.so.0)
                                               #14 0x00007fa10c56aa04 ibus_factory_service_method_call (libibus-1.0.so.5)
                                               #15 0x00007fa10c41bb0d call_in_idle_cb (libgio-2.0.so.0)
                                               #16 0x00007fa10c03fc39 g_main_dispatch (libglib-2.0.so.0)
                                               #17 0x00007fa10c040098 g_main_context_iterate (libglib-2.0.so.0)
                                               #18 0x00007fa10c040342 g_main_loop_run (libglib-2.0.so.0)
                                               #19 0x00007fa10c55c1c3 ibus_main (libibus-1.0.so.5)
                                               #20 0x0000000000408dbc start_component (ibus-engine-libpinyin)
                                               #21 0x00007fa10bc3a153 __libc_start_main (libc.so.6)
                                               #22 0x0000000000408f9e _start (ibus-engine-libpinyin)
                                               
                                               Stack trace of thread 1338:
                                               #0  0x00007fa10bd27fa4 __GI___poll (libc.so.6)
                                               #1  0x00007fa10c03fffe g_main_context_poll (libglib-2.0.so.0)
                                               #2  0x00007fa10c0401db g_main_context_iteration (libglib-2.0.so.0)
                                               #3  0x00007fa10c00dce6 g_thread_proxy (libglib-2.0.so.0)
                                               #4  0x00007fa10bb72160 start_thread (libpthread.so.0)
                                               #5  0x00007fa10bd34a53 __clone (libc.so.6)
                                               
                                               Stack trace of thread 1339:
                                               #0  0x00007fa10bd27fa4 __GI___poll (libc.so.6)
                                               #1  0x00007fa10c03fffe g_main_context_poll (libglib-2.0.so.0)
                                               #2  0x00007fa10c040342 g_main_loop_run (libglib-2.0.so.0)
                                               #3  0x00007fa10c40521e gdbus_shared_thread_func (libgio-2.0.so.0)
                                               #4  0x00007fa10c00dce6 g_thread_proxy (libglib-2.0.so.0)
                                               #5  0x00007fa10bb72160 start_thread (libpthread.so.0)
                                               #6  0x00007fa10bd34a53 __clone (libc.so.6)
                                               
                                               Stack trace of thread 1340:
                                               #0  0x00007fa10bd27fa4 __GI___poll (libc.so.6)

**Comment by epico** [comment]
请问您用的 Linux 发行版是？

**Comment by epico** [comment]
请提供更多的 gdb backtrace 的信息，谢谢。

**Comment by lljgithub** [comment]
backtrace 只看到第一个frame的符号，贴的log中有其他的堆栈信息，如果还需要其他信息，我可以尽量提供，谢谢

**Comment by epico** [comment]
请问您用的 Linux 发行版是？

**Comment by lljgithub** [comment]
是clear linux https://clearlinux.org/documentation/clear-linux/get-started 滚动发行版本

**Comment by lljgithub** [comment]
The clear linux version like below:
lilj@clear ~ $ swupd info
Installed version: 27410
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/

**Comment by epico** [comment]
libpinyin supports both Berkeley DB and Kyoto Cabinet.

Could you check whether this issue re-produce on Berkeley DB or Kyoto Cabinet?

**Comment by lljgithub** [comment]
ok, but can you tell me how to try them ? by configuration ?

**Comment by epico** [comment]
When compile, please try the below command:
./configure --with-dbm=BerkeleyDB
or
./configure --with-dbm=KyotoCabinet

**Comment by lljgithub** [comment]
@epico Ok, i will try today. but i need install the gnome-dev bundle, need same patient
I am try to use double-pinyin, the coredump like below:
```

#0  0x00007f78e73b76f1 pinyin_alloc_instance (libpinyin.so.13)
#1  0x00000000004152bc _ZN2PY18DoublePinyinEditorC2ERNS_16PinyinPropertiesERNS_6ConfigE (ibus-engine-libpinyin)
#2  0x0000000000417fff _ZN2PY12PinyinEngineC2EP11_IBusEngine (ibus-engine-libpinyin)
#3  0x000000000040a367 ibus_pinyin_engine_constructor (ibus-engine-libpinyin)
#4  0x00007f78e760317f g_object_new_with_custom_constructor (libgobject-2.0.so.0)
#5  0x00007f78e7603f21 g_object_new_valist (libgobject-2.0.so.0)
#6  0x00007f78e7604269 g_object_new (libgobject-2.0.so.0)
#7  0x00007f78e78152a4 ibus_engine_new_with_type (libibus-1.0.so.5)
#8  0x00007f78e7819c2c ibus_factory_real_create_engine (libibus-1.0.so.5)
#9  0x00007f78e7827190 _ibus_marshal_OBJECT__STRING (libibus-1.0.so.5)
#10 0x00007f78e7607bf5 g_closure_invoke (libgobject-2.0.so.0)
#11 0x00007f78e75edcc7 signal_emit_unlocked_R (libgobject-2.0.so.0)
#12 0x00007f78e75ef43a g_signal_emit_valist (libgobject-2.0.so.0)
#13 0x00007f78e75effdd g_signal_emit (libgobject-2.0.so.0)
#14 0x00007f78e7819a04 ibus_factory_service_method_call (libibus-1.0.so.5)
#15 0x00007f78e76cab0d call_in_idle_cb (libgio-2.0.so.0)
#16 0x00007f78e72b0c39 g_main_dispatch (libglib-2.0.so.0)
#17 0x00007f78e72b1098 g_main_context_iterate (libglib-2.0.so.0)
#18 0x00007f78e72b1342 g_main_loop_run (libglib-2.0.so.0)
#19 0x00007f78e780b1c3 ibus_main (libibus-1.0.so.5)
#20 0x0000000000408dbc start_component (ibus-engine-libpinyin)
#21 0x00007f78e6eafc03 __libc_start_main (libc.so.6)
#22 0x0000000000408f9e _start (ibus-engine-libpinyin)

Stack trace of thread 1388:
#0  0x00007f78e6f9dc34 __poll (libc.so.6)
#1  0x00007f78e72b0ffe g_main_context_poll (libglib-2.0.so.0)
#2  0x00007f78e72b11db g_main_context_iteration (libglib-2.0.so.0)'

#3  0x00007f78e727ece6 g_thread_proxy (libglib-2.0.so.0)
#4  0x00007f78e6de517e start_thread (libpthread.so.0)
#5  0x00007f78e6faa253 __clone (libc.so.6)

Stack trace of thread 1389:
#0  0x00007f78e6f9dc34 __poll (libc.so.6)
#1  0x00007f78e72b0ffe g_main_context_poll (libglib-2.0.so.0)
#2  0x00007f78e72b1342 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f78e76b421e gdbus_shared_thread_func (libgio-2.0.so.0)
#4  0x00007f78e727ece6 g_thread_proxy (libglib-2.0.so.0)
#5  0x00007f78e6de517e start_thread (libpthread.so.0)
#6  0x00007f78e6faa253 __clone (libc.so.6)

```

**Comment by lljgithub** [comment]
I try to recompiled the libpinyin use the newest soucecode:
last commit: 9b15d6b86ad84cee5c86c9e27fd24107c6eab89f
# ./autogen.sh
# make
# make install
then reboot the issue disappeared.

**Comment by lljgithub** [comment]
I think it should be my software env issue, because i use 1.11.0 version before, and the newest code is 1.11.0 also. 
Thank @epico  @yongsun  very much.
