### ISSUE TITLE
按shift会将字上屏，但是无法切换英文

### ISSUE THREAD

**Issue by colorsakura** [libpinyin/ibus-libpinyin#162]
关闭 select candidate，解决此问题。
但是希望按shift的功能是切换中英文，当前的字上屏作为附加功能

**Comment by epico** [comment]
这个选项默认关闭啊！

**Comment by alx696** [comment]
@colorsakura **1.11.0**中的**Shift键选词**和**自动上词**都是默认没有勾选的, 默认就是按Shift键切换中英文.
