### ISSUE TITLE
License question for Debian packaging

### ISSUE THREAD

**Issue by czchen** [libpinyin/ibus-libpinyin#163]
Hi,

When updating Debian package, we found that license in `data/libpinyin.appdata.xml`, which is `CC0-1.0` is inconsistent with `COPYING`, which is `GPL-2.0`. Please help to clarify this situation so that we can update copyright information according.

**Comment by epico** [comment]
I think that file is used by gnome-software, and many xml files for gnome-software will use CC0-1.0 license.

The CC0-1.0 license is only for the data/libpinyin.appdata.xml file.
