### ISSUE TITLE
How to disable the emoji suggestions?

### ISSUE THREAD

**Issue by marmistrz** [libpinyin/ibus-libpinyin#164]
In 1.11.0 I have noticed some emoji candidates, which I completely don't want - I don't use emoji and they just distract me from the actual candidates. How do I turn it off? I can see no option in the settings.

For example, typing `de` suggests 🉐 and this behavior wasn't present in 1.10

**Comment by epico** [comment]
Right, currently there is no option to disable emoji candidates.

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/730847008beb5af220c0a9b1b5c713ba23560984 .

**Comment by Haozun** [comment]
I have installed the latest version(1.11.1) so where I can disable the hellish emoji candidate?

**Comment by epico** [comment]
It can be disabled by dconf.

**Comment by epico** [comment]
Please use dconf to disable emoji candidates.

$ dconf write /com/github/libpinyin/ibus-libpinyin/libpinyin/emoji-candidate false
