### ISSUE TITLE
无法看到候选词

### ISSUE THREAD

**Issue by zhaochaobo** [libpinyin/ibus-libpinyin#165]
当输入框在屏幕下方时，无法看到候选词框，
* Fedora 29 64 位
* GNOME 3.30.2
* IBus 版本 1.5.19
* IBus 智能拼音 1.11.0

不知道会不会是4k屏的原因

**Comment by epico** [comment]
请用英文报到 ibus 项目。

**Comment by pengln** [comment]
我也遇到了同样的问题，不过我的是ubuntu 18.04 64位，ibus-pinying升级到2.2.0没有效果，ibus升级到1.5.17没有效果

**Comment by epico** [comment]
这个应该是 ibus 的问题。
