### ISSUE TITLE
Migrate from Intltool to Gettext

### ISSUE THREAD

**Issue by t-chaik** [libpinyin/ibus-libpinyin#166]
Recent gettext versions can extract and merge back strings from and to various file formats, not need for deprecated intltool any more. Migrating modules to gettext is a [GNOME Goal](https://wiki.gnome.org/Initiatives/GnomeGoals/GettextMigration).

ibus itself has [already been ported](https://github.com/ibus/ibus/commit/a6710817b3d29d6a522f108f96ffe64d2f5367fe).

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .

Could you review the patch?

**Comment by t-chaik** [comment]
Thanks I'll test this and will keep you posted with the outcome.

Which repo. is the official one for `ibus-libpinyin` by the way?

**Comment by epico** [comment]
The repo https://github.com/epico/ibus-libpinyin  is my personal repo,
I will sync to the the official repo https://github.com/libpinyin/ibus-libpinyin periodically.

**Comment by t-chaik** [comment]
Ok thanks for the clarification. It may be worse adding a note about that in the project descriptions, it's a bit confusing to be honest, especially considering that `libpinyin/ibus-libpinyin` is a fork of `epico/ibus-libpinyin`...

**Comment by epico** [comment]
Actually I want to avoid that, but github.com added that information about fork...

**Comment by t-chaik** [comment]
@epico: Any idea when you'll release the next version of `ibus-libpinyin`? Would be nice to have a stable version free of the `intltool` dependency.

**Comment by epico** [comment]
Okay, I think next release is about 1-2 months later.

**Comment by t-chaik** [comment]
Perfect, thanks again.

**Comment by epico** [comment]
FYI, ibus-libpinyin 1.11.1 is released.

**Comment by t-chaik** [comment]
It's been integrated in upstream GNOME build recipes: [gnome-build-meta !303](https://gitlab.gnome.org/GNOME/gnome-build-meta/merge_requests/303). Thanks a lot!

**Comment by epico** [comment]
Welcome! :)
