### ISSUE TITLE
1.9.2在Ubuntu18.04上突然无法选次了，只能用空格打出第一个被选次

### ISSUE THREAD

**Issue by MukuroSama** [libpinyin/ibus-libpinyin#169]
按任何数字见选次，都会打出那个数字，然后中文输入法失效，只能打出字母，需要重新切换输入法才能恢复，然后依然不能选次……我现在大了这么多错别字就是这个原因。要炸了，重启系统也无效。

**Comment by epico** [comment]
我没有记错的话，Ubuntu 18.04 默认安装的是非稳定版本，不知道有没有更新。

如果可能的话，个人推荐 libpinyin 2.2.0 或 2.3.0 版本。

这是第三方提供的 Ubuntu PPA, 不过我没有测试过...
https://launchpad.net/%7Egunnarhj/+archive/ubuntu/ibus-libpinyin

请在更新后，清除用户数据:
删除 ~/.cache/ibus/libpinyin/user.conf 文件。

**Comment by pengln** [comment]
升级到2.2.0一样会有这个情况，并不是不显示，而是因为位置发生了巨大偏移，选词框在屏幕外了，把应用界面向左上角拖动，可以在右下角看到选词框。不是所有应用tyroa这个应用会有这个情况，vscode、控制台和chrome没有这个情况

**Comment by epico** [comment]
> 升级到2.2.0一样会有这个情况，并不是不显示，而是因为位置发生了巨大偏移，选词框在屏幕外了，把应用界面向左上角拖动，可以在右下角看到选词框。不是所有应用tyroa这个应用会有这个情况，vscode、控制台和chrome没有这个情况

这好像是两个不同的问题...

**Comment by pengln** [comment]
我感觉应该是同一个问题，选词框跟随问题，感觉可能跟屏幕分辨率和屏幕放大比例这两个系统参数有关，影响到了一些应用的跟随效果。

**Comment by epico** [comment]
与其他报告的问题重复, 关闭此问题。
