### ISSUE TITLE
shift 无法区分双击和单击,导致快捷键冲突

### ISSUE THREAD

**Issue by git784589** [libpinyin/ibus-libpinyin#172]
系统: Linux ubuntu 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

单击切换输入法的中英文状态,  其他软件中的双击事件会被拦截掉,导致其他快捷键失效

**Comment by epico** [comment]
请详细描述问题。

**Comment by git784589** [comment]
正常习惯是单击shift就可以切换中英文状态,如果开启libpinyin的shift快捷键,不会区分是双击还是单击,
其他应用中注册的双击shift就被阻断了,无法触发.

**Comment by epico** [comment]
其实，ibus-libpinyin 的快捷键是可以定制的。

**Comment by git784589** [comment]
需要如何实现?

**Comment by epico** [comment]
请问是什么应用啊？

**Comment by git784589** [comment]
intellij idea , shift 双击快捷键

**Comment by epico** [comment]
经测试，在 Fedora 上，Intellij Idea , Shift 双击快捷键工作正常。

**Comment by epico** [comment]
Feel free to comment, if still have this issue.

**Comment by i-love-tadpole** [comment]
@git784589 你是不是安装了ibus-pinyin,我安装了ibus-pinyin有同样的问题,安装ibus-libpinyin是没有问题的

**Comment by mxy19980428** [comment]
我也遇到这个问题了。我想使用idea的双击 shfit，却不能打开全局搜索，请问，怎么解决的？ @git784589
