### ISSUE TITLE
無法用繁體中文輸入「划」

### ISSUE THREAD

**Issue by patrickdark** [libpinyin/ibus-libpinyin#173]
無法用繁體字輸入「划」。繁體字例子是[http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=W00000005022](http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=W00000005022)。

軟體版本：Intelligent Pinyin 1.11.0
作業系統：Fedora 29 (Wayland)

**Comment by epico** [comment]
Please try ibus-libzhuyin instead, thanks!

**Comment by patrickdark** [comment]
@epico 這不是ibus-libzhuyin的錯誤。謝謝！

**Comment by epico** [comment]
请问如何重现该问题，我对繁体中文不太熟悉。谢谢！

**Comment by yanjisheng** [comment]
“划”的繁体字应该是“劃”吧
