### ISSUE TITLE
无法用相同的快捷键切换全角/半角字母和符号

### ISSUE THREAD

**Issue by Geekinus** [libpinyin/ibus-libpinyin#174]
我想保留Win的习惯，用`<Shift>space`切换全角/半角字母和符号，但是*ibus-libpinyin*只支持把其中一个设置这样的快捷键，我不能同时切换字母和符号。

**Comment by epico** [comment]
请问使用的是 Windows 上的哪一个输入法?

**Comment by Geekinus** [comment]
Win10 自带

On 4月 28 2019, at 10:45 上午, Peng Wu <notifications@github.com> wrote:
请问使用的是 Windows 上的哪一个输入法?

**Comment by epico** [comment]
也许可以考虑为同时切换字母和符号半角/全角设置一个新的快捷键。

其他快捷键应该没有设置成一致的需求...

**Comment by Geekinus** [comment]
en，是可以，只不过要是能设置相同的快捷键同时切换这更符合我的习惯。

On 5月 6 2019, at 2:46 下午, Peng Wu <notifications@github.com> wrote:
也许可以考虑为同时切换字母和符号半角/全角设置一个新的快捷键。

其他快捷键应该没有设置成一致的需求...

**Comment by epico** [comment]
个人觉得，对于快捷键设置，还是做一些检查比较好，防止输入法出现比较奇怪的行为。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .
