### ISSUE TITLE
-=翻页键，输入标点符号卡顿

### ISSUE THREAD

**Issue by netroby** [libpinyin/ibus-libpinyin#175]
输入中文的时候，我如果马上用-=来翻页了，接下来，如果我要输入-=标点符号，ibus死活不让我输入。

不知道为什么不让我输入

**Comment by netroby** [comment]
你们有没有这样的问题。

**Comment by netroby** [comment]
@epico

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/2328a50d678a6fd737057b57f593f67ea10744df .

**Comment by netroby** [comment]
Thank you . god like
