### ISSUE TITLE
全拼模式下输入jie时有问题

### ISSUE THREAD

**Issue by yanjisheng** [libpinyin/ibus-libpinyin#177]
在输入jie时，候选词中第一个是“节”，第二个是“届”，第三个是“饥饿”，第四个是“其”，第五个是“及”，在往后翻页时候选词中出现很多拼音为ji的字，只有少数字拼音为jie，导致输入“借”字要翻七页。希望尽快修复该bug。

**Comment by yanjisheng** [comment]
系统ubuntu18.04 LTS，ibus版本1.9.2

**Comment by yanjisheng** [comment]
输入jian、qian、xian、qie、jue时也有类似问题

**Comment by yanjisheng** [comment]
tuan、zuan、luan、tian、dian、lian、yuan也有类似问题，他们的共同特点是第三个候选词都是两个字的词语而不是一个字

**Comment by epico** [comment]
在最近版本的 libpinyin 和 ibus-libpinyin 中，在“首选项”对话框的“常规”页面中，将“候选词排列顺序”，修改为“拼音长度”即可。

**Comment by yanjisheng** [comment]
谢谢，问题已解决

**Comment by sixg0000d** [comment]
> 在最近版本的 libpinyin 和 ibus-libpinyin 中，在“首选项”对话框的“常规”页面中，将“候选词排列顺序”，修改为“拼音长度”即可。

在没有开启拼音纠错和模糊音的情况下，这应该属于非预期行为吧？

**Comment by epico** [comment]
好像是预期行为。
