### ISSUE TITLE
中文模式：无法输入Markdown的代码标记“`”

### ISSUE THREAD

**Issue by alx696** [libpinyin/ibus-libpinyin#179]
### 问题描述
中文状态下在Github和GitLab中输入Markdown的代码标记(右斜点), 出现的是标点符号候选栏"1. 2, ...". 作为一个专门的符号键, 这个表现很奇怪. 按两次右斜点键后, 候选栏变为"1 ‵ 2'". 英文状态时则表现正常.

### 期望行为
中文状态下输入Markdown的代码标记(右斜点), 右斜点直接输出到文本框. 因为符号都有专门的按键, 无需出现标点符号候选栏.

**Comment by epico** [comment]
这个可能是为了方便输入中文符号，而专门设计的。

**Comment by epico** [comment]
这个问题我回来看一下。

**Comment by epico** [comment]
查看了下代码，输入 `, 会激活标点输入模式。

**Comment by alx696** [comment]
@epico 标点输入模式感觉可以去掉, 普通标点都有专门的按键. 特殊标点在这个候选里面又没有.

**Comment by epico** [comment]
我试了试其他的输入法，按键 "`" 对应的标点符号是 "·" , 也就是说按 "`" 会输入 "·" .

**Comment by ghostry** [comment]
这个确实有些影响,

我输入法设置的是半角英文符号,这种情况下,

理论上`应该是一个英文符号输入,实际上并不是.

**Comment by epico** [comment]
在标点输入模式中，可以用来输入「」...

**Comment by ghostry** [comment]
> 在标点输入模式中，可以用来输入「」...

这个对于文字工作者确实有用.

我觉得有两个方案

1, 标点模式是否打开可以根据用户选择的标点 中/英 来判定.

标点选中文的就给 标点模式,标点选英文的不进入标点模式

2, 提供快速输入`符号的方式,比如双击 ` 是输入符号,或者双击 ` 是进入标点模式.

**Comment by epico** [comment]
在标点英文模式中，标点模式禁用。

Fixed in https://github.com/epico/ibus-libpinyin/commit/7be9b52ba5ef951d48de960d36d0c015d7d50cd8 .
