### ISSUE TITLE
 “候选词排列顺序”设置找不到

### ISSUE THREAD

**Issue by hanx-phy** [libpinyin/ibus-libpinyin#180]
输“入嗯嗯”，“干嘛呢”等常用语必须使用[']键来分词，否则则是 鄂嫩(e'nen)和 干满额(gan'man'e)
之前有人提到更改“候选词排列顺序”为 “拼音长度”即可解决问题[#113](https://github.com/libpinyin/ibus-libpinyin/issues/113)
但是我没有在首选项中找到这一项设置

ibus-libpinyin 1.6.91
Scientific Linux 7.6

**Comment by epico** [comment]
可能是 ibus-libpinyin 版本比较低的过。

**Comment by hanx-phy** [comment]
> 可能是 ibus-libpinyin 版本比较低的过。

请问RHEL系列没有更新的包吗？

**Comment by epico** [comment]
可以考虑开个 bug.
