### ISSUE TITLE
用久了之后切换到中文输入法会很卡

### ISSUE THREAD

**Issue by gbk** [libpinyin/ibus-libpinyin#181]
- Ubuntu 18.04 LTS 64 位
- GNOME 3.28.2
- IBus 版本 1.5.17
- IBus 智能拼音 1.10.0
- libpinyin 2.2.2-1

高频使用 4 个月左右，最近频繁发生切换输入法时输入卡顿的情况，
具体表现为：

- 在英文输入状态下按 shift 切换到中文
- 输入法指示 "中" 字图标已正常展示（但点击首选项无响应）
- 此时在任何软件中输入内容无响应
- 卡顿 5～10 秒之后，可恢复正常输入，卡顿过程中输入的文本会一下子插入进来
- 如卡顿过程中切换到英文输入，可正常输入

删除 `~/.cache/ibus/libpinyin/user_bigram.db` 并重启 ibus 不能解决该问题。

删除 `~/.cache/ibus/libpinyin` 并重启 ibus 可以解决该问题。

烦请看下可能是什么原因导致的问题？

**Comment by epico** [comment]
试试删除 ~/.cache/ibus/libpinyin/user.conf .

用 gnome-system-monitor 或者 top, 看看是哪个进程在占用 CPU.

**Comment by gbk** [comment]
> 试试删除 ~/.cache/ibus/libpinyin/user.conf .
> 
> 用 gnome-system-monitor 或者 top, 看看是哪个进程在占用 CPU.

下次重现的时候我看看～
