### ISSUE TITLE
Failure to switch English/Chinese

### ISSUE THREAD

**Issue by Geekinus** [libpinyin/ibus-libpinyin#182]
This input method works well, yet since yesterday it cannot switch English/Chinese.

If I click `汉语 (Intelligent Pinyin)` in <center>![ET2H8e.png](https://s2.ax1x.com/2019/05/15/ET2H8e.png)</center>, I can type in Chinese transiently.<br /><center>![ETRcIf.png](https://s2.ax1x.com/2019/05/15/ETRcIf.png)</center>

However I can only input the 1st candidate word by pressing `SPACE` or `1`. If I try to input others by pressing other number or by pressing ↑↓ and then pressing `SPACE`, the input method will switch itself to English and the word I want will not be input.

**Comment by epico** [comment]
看情况，好像用的是 libpinyin 2.2.0 以前的版本，比如 2.1.91.

请考虑升级到 libpinyin 2.2.2 或者 2.3.0 .

**Comment by Killea** [comment]
建议用Gnome 设置键盘快捷键。 ibus自带切换键盘太慢了。 ibus设置为默认中文，然后 跟us键盘来回切换即可。我设置的是ctrl+space.
