### ISSUE TITLE
 'intelligent PinYin'(version=1.9.2) to input '类图‘ t

### ISSUE THREAD

**Issue by Rlyslata** [libpinyin/ibus-libpinyin#183]
problem i got:
when i wanna use the 'intelligent PinYin'(version=1.9.2) to input '类图‘ today，then i pressed 4and 1 to select that，but it didn't work, just   give me '1' instead  '类图', i also found that i couldn't switch input method to Enlish after this.

ps:i find a similar problem at another issue,but i closed by that problem has been solved, so
i don't no how i get this problem again in version 1.9.2

hope this could be solved soon,thanks!

**Comment by epico** [comment]
Please ask the Linux distribution to update ibus-libpinyin to 1.11.0 or 1.11.1.

**Comment by Rlyslata** [comment]
okay, thank you
