### ISSUE TITLE
Can not input Chinese

### ISSUE THREAD

**Issue by BenSYZ** [libpinyin/ibus-libpinyin#184]
When I shift the inputting method from English to Chinese by 'super'+'space' I still cannot input Chinese, even if I press the 'shift' button. It still input English word directly. How can I solve it and what files should I submit?

**Comment by epico** [comment]
Please switch to "Chinese (Intelligent Pinyin)".

**Comment by bingtimren** [comment]
I have the same issue. Ubuntu 19.04. If I only install "Chinese (Intelligent Pinyin)", after pressing 'super+space' input is switched to Pinyin (can be seen from the icon on system bar). However it still input English directly. Even if I tried 'shift' button it's still the same. 

If I install "Chinese (Pinyin)" it works all perfect. If I install both "Chinese (Pinyin)" and "Chinese (Intelligent Pinyin)", both works. 

So, seems something is missing? Something required by Intelligent Pinyin but only installed with Pinyin?

**Comment by epico** [comment]
@bingtimren Please consider to file an issue on Ubuntu Launchpad.

**Comment by bingtimren** [comment]
@epico done, as Bug #1847021

**Comment by epico** [comment]
Thanks!

**Comment by gunnarhj** [comment]
Couldn't reproduce. Please see comment 2 at [LP bug #1847021](https://launchpad.net/bugs/1847021).

**Comment by bingtimren** [comment]
Problem solved. Thanks gunnarhj for help. See https://launchpad.net/bugs/1847021

==================================================
Gunnar Hjalmarsson (gunnarhj) wrote 23 minutes ago: | #15

Try to clear the cache:

rm ~/.cache/ibus/pinyin/* ~/.cache/ibus/libpinyin/*

and then relogin.
