### ISSUE TITLE
显示BUG

### ISSUE THREAD

**Issue by yexua** [libpinyin/ibus-libpinyin#185]
https://i.loli.net/2019/07/06/5d2027a7cc3fb79436.png
就像这样，切换到中文一直在这里显示

**Comment by epico** [comment]
请更新 libpinyin 到 2.2.0 以上版本，推荐 2.2.2 或者 2.3.0.

**Comment by TimeTricker** [comment]
我也出现了这个问题，想要一下安装教程，libpinyin我有点更新不明白

**Comment by epico** [comment]
https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

**Comment by ping-wu** [comment]
there is no autogen.sh in the tarball

**Comment by epico** [comment]
Sorry, my mistake, updated the document.

Please use ./configure instead.

**Comment by ping-wu** [comment]
running in Ubuntu 18.04.2, compilation failed, error messages:

configure: error: in `/home/ryzenv/Downloads/libpinyin-2.3.0':
configure: error: The pkg-config script could not be found or is too old.
Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

**Comment by epico** [comment]
I think it needs to install build-essential or some other packages...

**Comment by ping-wu** [comment]
already have it, the whole package

**Comment by epico** [comment]
Fixed in libpinyin 2.3.0.
