### ISSUE TITLE
"Show suggestions" trigger wrong Chinese Character full pinyin  matching 

### ISSUE THREAD

**Issue by larryw3i** [libpinyin/ibus-libpinyin#187]
**"Show suggestions" trigger wrong Chinese Character full pinyin  matching** ,but the input is correct again when you press space after typing

**Comment by epico** [comment]
Please describe more about this issue, and provide screenshot if possible.

**Comment by larryw3i** [comment]
You can try to set **References > Show Suggestions**  to trigger this issue, and it doesn't affect normal use when I don't use **Show Suggestions**

**Comment by epico** [comment]
Please upgrade libpinyin to 2.2.0 or above.
