### ISSUE TITLE
How to use English symbol at Chinese mode

### ISSUE THREAD

**Issue by MarcoGao123** [libpinyin/ibus-libpinyin#188]
When we write code, we always need English symbol, it's trouble a lot to switch to English mode every time when I want to input a English symbol. When I forget to do that, the code will return error and it is hard to find out. For these reason I suggest to add this mode.

**Comment by epico** [comment]
Does any Pinyin input method support this?

**Comment by MarcoGao123** [comment]
Absolutely, most Pinyin input method in China support this, Microsoft Pinyin input in Windows also support this.

**Comment by MarcoGao123** [comment]
I suggest you to look at Microsoft one if you have Windows operating system, because it is English and most Pinyin input in China are Chinese, if you can't read Chinese, it will be really hard work for you.

**Comment by epico** [comment]
请描述下，微软拼音如何在拼音模式下，输入英文。

我不记得微软拼音支持这个选项。

**Comment by MarcoGao123** [comment]
sorry, maybe i describe it wrong, I mean English symbol.
对不起，我可能描述错误， 我指输入英文符号。

**Comment by MarcoGao123** [comment]
I use the word wrong, really sorry about that.
我用错词了，我对此很抱歉。

**Comment by epico** [comment]
这个选项在输入法菜单中有开关啊。

另外，在设置对话框中，可以设置默认为半角符号。

**Comment by MarcoGao123** [comment]
I get it, I was trying to do that before but I don't switch to English input and switch back, I just try to switch to English method of Chinese input method and this is not work, thank you.
好的,我曾经这么做过但是我没有切换到英文的输入再切换回来,我只尝试切换到中文输入法中的英文模式,而那样没有用,谢谢
