### ISSUE TITLE
简体中文模式支持直角引号

### ISSUE THREAD

**Issue by iridiumcao** [libpinyin/ibus-libpinyin#190]
问题：
目前 ibus-libpinyin 简体模式下不支持也不能配置引号类型，因此不能使用直角引号。

期望的解决方案：
支持自定义引号类型： “” ‘’ 「」 『』。

参：https://github.com/phuang/ibus-pinyin/issues/4

**Comment by epico** [comment]
请考虑使用 ibus-libpinyin 的 Lua 脚本扩展功能。

**Comment by ping-wu** [comment]
请参阅：
https://forum.ubuntu.com.cn/viewtopic.php?f=8&t=490400&start=7

**Comment by ghostry** [comment]
「」在`键的符号模式里有.

**Comment by FranklinYu** [comment]
請問這個「符號模式」在什麼地方有介紹呢？感覺 libpinyin 沒啥文檔，在首選項裏也沒看到，我是直到看到本 issue 才獲悉此功能。希望能讓這個實用的功能可以更 discoverable。

**Comment by epico** [comment]
@FranklinYu 谢谢您的建议，刚刚更新了下 wiki page.

https://github.com/libpinyin/ibus-libpinyin/wiki
