### ISSUE TITLE
关于CapsLock键盘切换中英文的问题。

### ISSUE THREAD

**Issue by inanalaopo** [libpinyin/ibus-libpinyin#191]
通常键盘上的Caps Lock 键使用频率非常非常的低，只有极少数情况下需要全句大写英文，为何不把中英文切换默认就是Caps Lock来解放Shift Control Alt 这三个按键呢？？
目前自定义按键无论是设置成 "Caps Lock" " caps lock" "CapsLock" "capslock" 都无法使用Caps Lock 切换中英文。

**Comment by epico** [comment]
其实，ibus-libpinyin 使用的是 Gtk+ 的控件来设置快捷键。

如果，Gtk+ 无法捕获 "Caps Lock" 快捷键，ibus-libpinyin 实现起来很费力的。
