### ISSUE TITLE
Porting User Dictionary

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#192]
When I copied my ~/.cache/ibus/libpinyin folder to a new installation (or a new user), a new libpinyin folder will be regenerated and my user dictionary will be wiped out.

How to I port my user vocabulary to a new system?

**Comment by epico** [comment]
I guess the new system has a newer version of libpinyin?

**Comment by ping-wu** [comment]
from 1.11 to 1.11.1

**Comment by epico** [comment]
I mean the version of libpinyin instead of ibus-libpinyin.

**Comment by ping-wu** [comment]
libpinyin from 2.2 to 2.3.

**Comment by epico** [comment]
Sorry, use libpinyin with old user data may cause undefined behavior.
