### ISSUE TITLE
Maximum size of user dictionary that can be imported

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#193]
What's the maximum size of user dictionary that can be imported?  I am trying to import a 4.8 MB file and failed.

**Comment by epico** [comment]
I think it is because the file format is not correct.

I test to import some dictionary larger than that, and it works.

**Comment by ping-wu** [comment]
Thanks.  After adjusting the input text file data format, I am able to
import an 8+MB file into libpinyin, the resultant user_pinyin_index.bin is
about 10+M.

This should drastically improve the performance of ibus-libpinyin.

**Comment by epico** [comment]
Welcome!
