### ISSUE TITLE
输入法 会 自动按住某个键不放，2台电脑都有这个情况不可能是键盘坏了

### ISSUE THREAD

**Issue by onhao** [libpinyin/ibus-libpinyin#195]
![Peek 2019-08-30 17-08](https://user-images.githubusercontent.com/28284702/64008603-01842780-cb49-11e9-9a2b-bb827aee55dc.gif)
请看我的图，
系统环境   ubuntu  19.04  / 19.10   
都有这种情况，
尤其是 在写代码的时候，发生这种情况，真是要命阿。

**Comment by epico** [comment]
请问后台是否在运行任务，CPU 的占用率是多高？

**Comment by onhao** [comment]
> 请问后台是否在运行任务，CPU 的占用率是多高？

后台运行任务 ，你指得是 shell  后台 么  ？

**Comment by onhao** [comment]
答： 没有 运行  nohup  或者  & 的 任务，cpu 占用  没有注意看，等下次再现的时候 再观察下。真的 我一度以为是我的键盘按键那里坏了，直到第二台电脑也出现这个情况，第二台电脑 之前一直用fcitx,最近ubuntu升级后坏掉了，就换回ubuntu默认的输入法。

**Comment by onhao** [comment]
终于找到 bug  复现的 法门了
1.切换到中文输入

**Comment by onhao** [comment]
2.输入字母后，再按shift 切换回英文
3.按下致命的回车，恶魔即将开始。

**Comment by onhao** [comment]
图解：
![Peek 2019-09-02 14-42](https://user-images.githubusercontent.com/28284702/64094947-f7079f00-cd8f-11e9-8786-65fc83573b59.gif)

**Comment by onhao** [comment]
不只是 終端 有這個問題
sublime 
![Peek 2019-09-02 14-50](https://user-images.githubusercontent.com/28284702/64095434-5a460100-cd91-11e9-8a6a-c81a60b45c40.gif)

**Comment by epico** [comment]
请报告给 Ubuntu。

方便的话，请测试下 Fedora 30 是否有问题？

**Comment by onhao** [comment]
这是 ubuntu的锅 阿，只测试了   u19。04  和  u19。10
Fedora 30 没有安装，无法测试。

**Comment by onhao** [comment]
不知你的电脑能复现这个问题么

**Comment by onhao** [comment]
哥们，我又来了，可以判断 这个跟输入法是相关的
理由如下：
1.用fcitx无此问题
2.同样的 用ibus框架 sunpinyin也无此问题
有图有真相
![Peek 2019-09-03 10-59](https://user-images.githubusercontent.com/28284702/64141261-f0356680-ce39-11e9-95c8-dfa1ab20d093.gif)

**Comment by epico** [comment]
请问 libpinyin 和 ibus-libpinyin 的版本是？

我无法复现此问题...

**Comment by onhao** [comment]
应该是最新版 IBus 智能拼音 1.11.0

**Comment by epico** [comment]
请问 libpinyin 的版本是？

**Comment by onhao** [comment]
libpinyin13 已经是最新版 (2.3.0-1)。
libpinyin13 已设置为手动安装。

**Comment by epico** [comment]
建议给 Ubuntu 开一个 issue.

**Comment by epico** [comment]
创建个新用户是否输入正常？

**Comment by onhao** [comment]
@epico 果然创建一个新用户没有这种情况了，我该怎么操作消除这种问题？
清除主目录里的那个（些）配置文件，有建议么？
多谢！

**Comment by epico** [comment]
应该是用户数据出问题了，请在 Console 删除 ~/.cache/ibus/libpinyin/user.conf 文件。

**Comment by onhao** [comment]
@epico  我知道是那个配置的问题了，只要在 首选项
候选词
勾选了
show suggestions.
就会出现这个问题。
保证你会复现这个问题了，不勾不会有这个问题！

**Comment by onhao** [comment]
另外  Console 删除 ~/.cache/ibus/libpinyin/user.conf 文件。  这个解决方案是无效的

**Comment by epico** [comment]
请试试 ibus-libpinyin 1.11.1, 看看是否还有问题。

在 ibus-libpinyin 1.11.1, 无法复现此问题。

**Comment by onhao** [comment]
算啦，不纠结了，不启用show suggestions.   就好了
还有一个问题
就是中文收入状态下  按 v 后 操作很生硬，一点不便捷 ，虽然可能是为了输入英文方便，但是其实，按了v后 你就只能回车来取消这种状态， 按 空格 或者 shift 都无效
更有效的 中英切换，其实就是 之间按回车（中文输入状态下，按回车就好了）
v真的很鸡肋，可以取消或者做一个开关（是否按v后进入英文输入状态）

**Comment by epico** [comment]
其实 v 键并不和其他按键冲突。

英文模式目前是有编译开关的。

**Comment by epico** [comment]
刚刚改了改代码，Shift 或者 空格 都可以关闭英文模式。

**Comment by onhao** [comment]
@epico ^_^
谢谢，你的 这个智能拼音 还是 比sunpinyin功能全面很多，可设置项多，对中文更友好！
你代码更新  ubuntu的是不是不会自动升级？
要用最新版是否只有自己从新编译一份？

**Comment by epico** [comment]
谢谢夸奖！
刚刚发现英文模式需要输入大写字母，Shift 键不能用来关闭英文输入模式。
抱歉，Ubuntu 的包不是我维护的，可以开 issue 让他们更新。

**Comment by suokunlong** [comment]
根issue #99 一模一样。Fedora 30 1.11.1下仍然能重现。

**Comment by epico** [comment]
@suokunlong 这个可能和 GNOME wayland 相关。

**Comment by ping-wu** [comment]
W. Wayne Liauh <wp@hawaiilinux.org>
6:23 PM (0 minutes ago)
to libpinyin/ibus-libpinyin

完全不同意！！！

每次打小数点的时候就要启用半角符号，太不符合一般中国人的习惯了。

Ubuntu 论坛几乎没有人喜欢 libpinyin，这是很重要的一个原因，for example:
https://forum.ubuntu.org.cn/viewtopic.php?f=8&t=489689&p=3215328#p3215328

**Comment by epico** [comment]
@ping-wu 发错 issue 了吧？
