### ISSUE TITLE
[Feature Request] inline_preedit mod

### ISSUE THREAD

**Issue by fujiwarat** [libpinyin/ibus-libpinyin#196]
From https://github.com/ibus/ibus/issues/2122
Reported by @hosxy

```
distribution: Archlinux
DE: xfce4.14
Session: X11
IBus version: 1.5.21
```

Could you please add inline_preedict mod  like windows10 / OSX, eg:
![批注 2019-08-30 112609](https://user-images.githubusercontent.com/17108640/63992733-dcc78a00-cb1f-11e9-936d-447c554cf411.png)
![深度截图_选择区域_20190830114425](https://user-images.githubusercontent.com/17108640/63992737-e0f3a780-cb1f-11e9-8af2-dfa254b10792.png)

This would be simple and save space, and it look likes pretty good.

**Comment by fujiwarat** [comment]
@hosxy commented:

> I think preedit is already inline in ibus as you mean and I guess you mean the inline lookup window?
> I have Windows 10 but I'm not sure what you mean.
> Could you attach the full screenshot in Windows?

@fujiwarat  I will paste two screenshot,you can see
![Snipaste_2019-08-30_20-50-29](https://user-images.githubusercontent.com/17108640/64023734-9009a080-cb6b-11e9-8e9b-4ff3cf5ae7fa.png)

![深度截图_选择区域_20190830211204](https://user-images.githubusercontent.com/17108640/64023789-a9125180-cb6b-11e9-80b6-f75a1da67190.png)

On windows 10, you can see candidate box only have one line are candidate words，the chars you input are on inline_preedit.

On ibus, candidate box has two line, one is the chars you input, another is candidate words. and inline_preedit use to show first candidate words, but first candidate has been in obsious position on candidate box.  
why not move chars to inline_preedit,and  candidate box will only have one line are candidate words? (The default IM of windows10 and osx also do this)

**Comment by epico** [comment]
The preedit line is very important, and need to be displayed inline.

**Comment by hosxy** [comment]
这边应该是可以用中文交流吧，有些地方可能用英文无法表述的很清楚。
而且有些地方用词可能不是很准，因为我也不知道它原本该叫什么名字，所以才发了好多图，请谅解

候选框上面显示已输入字符的那一栏的确是很重要，我的意思不是说直接砍掉它或者不显示它，而是把它移到  我称之为 inline_preedit 那块，之前这地方是显示第一候选词，第一候选词在候选框一般都是有高亮显示，已经很醒目了，没必要把它再放到 inline_preedit 来重复显示
像Windows10和OSX默认输入法那样把 已输入的字符 放到 inline_preedit 区域，这样就可以利用 inline_preedit 这块区域，让整个候选框只有一行，这样看起来更简洁，我觉得像现在的方案 用 inline_preedit显示已经被高亮显示的内容，意义不是很大，有些浪费的这块地方了
而且可以在设置里加个开关来开启/禁用这个特性，这也不会对现有的方案有影响了

**Comment by epico** [comment]
其实这个模式的主要问题是，
如果你在文章中间输入的话，在提交的时候，后面的文本会突然向前移动一下。
个人觉得这个文本移动的用户体验并不太好。

**Comment by hosxy** [comment]
> 
> 
> 其实这个模式的主要问题是，
> 如果你在文章中间输入的话，在提交的时候，后面的文本会突然向前移动一下。
> 个人觉得这个文本移动的用户体验并不太好。

的确有这个问题，如果一次输入内容比较长的话的的确不怎么好(因人而异，有人介意有人不介意)，如果输入比较简短(单字，单词)的话，其实影响也不是很大

我还是觉得在设置里加个 这个功能的开关比较好，这样用户体验比较完整，应该有不少人和我一样喜欢这个模式的。

**Comment by Titubery** [comment]
这个确实可以有，双行候选框的有已经作古的谷歌输入法和国内的一众输入法（单行也不方便皮肤设计，宽点才镇得住），而微软拼音和mac自带的都是单行。在gnome中的话，两行高度所占一样，实际上拼音的高度往往比汉字低，这样光标和候选区视觉上就更远了些，在候选框横向时有不小的留白，单行值得考虑

**Comment by epico** [comment]
好的，这个问题我回来有空看一下。

**Comment by epico** [comment]
Okay, implemented in https://github.com/libpinyin/ibus-libpinyin .

**Comment by ping-wu** [comment]
That was the MOST STUPID idea that I have ever heard.  PLEASE DO NOT CHANGE.  OR If you already made the change according to this one person's stupid idea, please change it back.  Pleeeeeeeeeeeeeease!

When I type English words, I only look at the screen.  I never have to look at the keyboard.  One of the best advantages of the present setup in ibus-libpinyin is that, if I used it long enough and have built my own 词库, when I type Chinese characters, I  (most of the time anyway) only have to look at the screen.   Change the display of Chinese characters to pinyin symbols does not make any sense at all.

This is a VERY STUPID idea.

Please keep the original feature.  Or at least make this a user preference.  We want Linux desktops to be actually better than Windows.

**Comment by ping-wu** [comment]
一般人打中文时，屏幕上本来就应该显示中文。原来的 ibus-libpinyin 好好的，为什么打中文时要在屏幕上显示英文字母？ 根本就是不伦不类。

虽然中文字会在 dialog window 里显示，一般熟悉中文打字的人根本不会去注意这个 dialog window。一面要看屏幕，一面要看 dialog window？ 不但画蛇添足对 posture 也不好。习惯使用 ibus-libpinyin 的人，基本上只要把眼睛注意在屏幕上就可以。我想提出这个要求的人根本没有使用过 ibus-libpinyin （或 ibus-pinyin），就乱出主义要我们这些忠实的 ibus-libpinyin 使用者成为受害者。太过分了！

**Comment by ping-wu** [comment]
如附图所示，在输入日文时（ibus-anthy），主屏幕上显示就是日文，而不是狗爬英文拼音字母：

![日本語](https://user-images.githubusercontent.com/21325422/71071767-4a281680-2121-11ea-8cd9-dfb1b3a86f10.jpg)

**Comment by epico** [comment]
这个选项默认关闭。

另外，为什么不早点反对，还有注意你的措辞。

**Comment by ping-wu** [comment]
I have never received notice of this request from email.  There is no way for me to raise objection earlier.

Plus, a lot of the requests were ignored (especially those from Ubuntu users).  I have no idea that you will act on it.

If there is no way for users to choose the preference, as a long-time user and strong supporter of ibus-libpinyin, I would really appreciate it if you could change it back to the original format (i.e., showing Chinese characters in the "inline edit".)

**Comment by tuberry** [comment]
@ping-wu 很遗憾您不喜欢这个功能。虽然我使用`ibus-libpinyin`时间还不长，但并非头脑发热作为旁观者随口说单行好。如果每次打字首项是想要的那直接显示汉字更好（这种情况下连候选框都没必要）但拼音做不到这样，当前模式若不要首项往下看其他候选项是比较分神的（个人感觉首项和其余候选项被割裂开来了）。所以就单行候选框而言，我并不认为这两厂商设计的就一定是好的，但这无疑是一种折衷的方案。其实微软拼音随光标移动候选框也不是很好，我更希望每次提交时而非输入时更新，就像这样：
![input](https://user-images.githubusercontent.com/17917040/71078329-2073fb80-21c4-11ea-999d-76b6dd656692.png)
另作者大大也提到了默认关闭该选项，作为死忠粉的您大可不必急着换回[`ibus-rime`](https://github.com/rime/ibus-rime/issues/81)。

**Comment by epico** [comment]
是的，ibus-libpinyin 的默认行为没有改变。

之前 Ubuntu 上的不少问题，其实已经在这里修复了，更新到最新的 ibus-libpinyin 就可以解决大部分问题的。

**Comment by ping-wu** [comment]
On Wed, Dec 18, 2019 at 12:43 AM tubery <notifications@github.com> wrote:

> 如果每次打字首项是想要的那直接显示汉字更好，但拼音做不到这样
>
This is the biggest difference between a long-time ibus-libpinyin user like
myself and a novice user.  For me, I almost never have to look at the
dialog window (i.e., the candidate window).  I am really irked that the
maintainer(s) never solicited opinions from long-time ibus-libpinyin users
before unilaterally made such a major change.

> （这种情况下连候选框都没必要）—
>
However, there are times (for me, less than 10% of the time), I do have to
look at the candidate window (which I have referred to as the "dialog
window") to select the right candidate, be it a single word or a multi-word
phrase.

In typing Chinese characters, I don't compose the whole sentence
beforehand.  Rather, I "think" when I "type"--as if I were composing an
impromptu speech.  Thus, it is critically important for me (and many other
similarly-situated Chinese speakers) to have my intended candidate "inline"
(shown on the screen), to see how it fits with the words and phrases that I
already typed.  Showing English pinyin characters in-line with the
already-typed Chinese words does not make any sense at all.  As I mentioned
earlier, I have trained my ibus-libpinyin dictionary such that the first
candidate shown on the screen is usually my intended word or phrase.  This
new change totally messed up my system.

The screenshot that you attached in your previous post is actually not very
relevant.  Most Chinese Windows users use Sogou pinyin (搜狗拼音）, the
so-called "inline_preedit mode" is shown in Chinese, as it should.

**Comment by ping-wu** [comment]
![image](https://user-images.githubusercontent.com/21325422/71082296-ef001f00-2134-11ea-832d-2957d38fedc4.png)

把中文字跟英文混在一起，打中文时眼睛要移上移下，这是这个新功能最大的致命伤（Bye-bye 啦）。

**Comment by ping-wu** [comment]
在喏大的 Ubuntu 中文论坛里，我大概是唯一替 ibus-libpinyin 辩护的人（but no more,
sorry）。ibus-libpinyin 最大的缺点主要在于附带的词库太弱，一般人使用 Ubuntu iso
开机时常常要翻好几页才能找到想要的字，马上就转到搜狗去了。

**Comment by tuberry** [comment]
我觉得你是不是有所误解，这个功能是可选的且默认关闭并非强制也就是说你完全可以当它不存在。我完全理解了你不需要和喜欢这功能，也希望你理解有的人喜欢并且二者没有任何冲突。

**Comment by ping-wu** [comment]
> 我觉得你是不是有所误解，这个功能是可选的且默认关闭并非强制也就是说你完全可以当它不存在。我完全理解了你不需要和不喜欢这功能，也希望你理解有的人喜欢并且二者没有任何冲突。

前面 Epico 也提过默认是关闭的。但重点是： 绝大多数 Ubuntu 中文使用者一装机后就把中文输入法换成搜狗。以前这个做法一直没有问题，但搜狗所基于的 fcitx　已多年没有更新了，与　gnome 3.x 不相容的例子越来越多，也会越来越严重。目前 （Ubuntu 19.10 以及 future versions）基本上可使用的中文输入法只有 ibus-libpinyin。这一点我在 Ubuntu 中文论坛提了很多次，大家都同意，但还是没有人愿意使用 ibus-libpinyin。

主要原因是，以前有不少 Ubuntu 中文大牛经过我的恳求，直接到这里来提出对 ibus-libpinyin 的改良建议，但都被拒绝了。从 ibus-libpinyin 长期使用者的观点，我很支持他们的建议，不过也了解资源有限。把有限的资源放在一个几乎没有人会用到的功能，而忽略了一般使用者遇到的问题？ 我也是 Fedora 的使用者，Ubuntu 使用者提出的问题在 Fedora 也存在。

**Comment by epico** [comment]
开发者会根据 issue 内容决定开发优先级，和 Linux 发行版无关。

对于 Ubuntu 用户汇报的问题，可以复现的，基本上已经修复了。
