### ISSUE TITLE
繁体模式下 emoji 始终是第一候选

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/ibus-libpinyin#197]
简体模式下不是这样，只有繁体模式是这样。
https://bugzilla.opensuse.org/show_bug.cgi?id=1112998

**Comment by wnereiz** [comment]
It is annoying. 
The option "Dynamic adjust the candidates order" (with "Sort candidates by: Frequency") does not work at all.

**Comment by epico** [comment]
我记得这个问题已经修复了。

好像是在 a0a9fd6b1deb4384ac7ca8ce0bc35c98d1193339 中修复的。

请测试下 ibus-libpinyin 1.11.1 是否正常。

**Comment by hillwoodroc** [comment]
openSUSE Tumbleweed 20181015 里面的 ibus-libpinyin 就是 1.11.1

**Comment by epico** [comment]
2018.10.15 的时候， ibus-libpinyin 1.11.1 还没有发布啊。

此问题已经修正了，另外，可以在 dconf 中关闭 emoji.

**Comment by epico** [comment]
之前的 issue: https://github.com/libpinyin/ibus-libpinyin/issues/158

**Comment by hillwoodroc** [comment]
> 2018.10.15 的时候， ibus-libpinyin 1.11.1 还没有发布啊。
> 
> 此问题已经修正了，另外，可以在 dconf 中关闭 emoji.
眼误，我看成最近的版本的。我试试看。
