### ISSUE TITLE
输入法是透明的，怎么修复

### ISSUE THREAD

**Issue by ns-jin** [libpinyin/ibus-libpinyin#198]
![](https://github.com/NESPTechnology/AppDownloadCenter/blob/android/2019-09-10%2012-31-21%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png?raw=true)

**Comment by epico** [comment]
请提供更多信息，比如桌面环境，主题设置等

**Comment by ns-jin** [comment]
> 请提供更多信息，比如桌面环境，主题设置等

GNOME 3.32.1

主题：sierra-compact-light

能不能添加个 是否跟随系统主题的设置选项？

万分感谢！

**Comment by epico** [comment]
这个主题不由 ibus-libpinyin 控制。

参照下面的链接自己试着修改吧。
https://pwu.fedorapeople.org/ibus/gnome-ibus/

**Comment by ns-jin** [comment]
> 这个主题不由 ibus-libpinyin 控制。
> 
> 参照下面的链接自己试着修改吧。
> https://pwu.fedorapeople.org/ibus/gnome-ibus/

谢谢
