### ISSUE TITLE
建议翻页按钮在翻页的时候能固定在一个位置

### ISSUE THREAD

**Issue by wi24rd** [libpinyin/ibus-libpinyin#199]
建议居左上，这样翻页的时候不用总是移动鼠标。
（虽然点击的功能使用的频率并不大，但是既然有了，在使用方面还是最好能方便用户吧

**Comment by epico** [comment]
请问哪个拼音输入法是这样设计的，能否提供个截图?

**Comment by ghostry** [comment]
真的有人会点鼠标翻页而不是用键盘吗
