### ISSUE TITLE
词库导入的问题

### ISSUE THREAD

**Issue by ghost** [libpinyin/ibus-libpinyin#20]
刚用linux 几个星期, 对导入词库不懂, 网上的解决办法似乎没用. 请问一下词库的导入路径在哪? thanks!

**Comment by c4ys** [comment]
做了一个251万单词的词库,放在百度网盘可直接导入.
地址是: https://pan.baidu.com/s/19t1Jo8qY5JKsDboYbKRTTA

**Comment by ping-wu** [comment]
现在要从 Baidu 云下载必须要有国内的手机号码，我们没有。是否可以放到 GitHub 里？ Thanks a whole lot!
