### ISSUE TITLE
不知能否导入搜狗词库，libpinyin总感觉词库太少

### ISSUE THREAD

**Issue by yybbob** [libpinyin/ibus-libpinyin#201]
不知能否导入搜狗词库，libpinyin总感觉词库太少，用起来找词比较慢

**Comment by ping-wu** [comment]
https://forum.ubuntu.org.cn/viewtopic.php?f=8&t=490017&sid=0690631d921ed593b5d3a68d71992b3a

**Comment by ghostry** [comment]
https://github.com/ghostry/libpinyin_dict
