### ISSUE TITLE
Ctrl+Shift+D删除用户短语的功能失效了

### ISSUE THREAD

**Issue by yaminogame** [libpinyin/ibus-libpinyin#202]
ArchLinux
GNOME 3.34
ibus 1.5.21
ibus-libpinyin 1.11.1
linpinyin 2.3.0

**Comment by epico** [comment]
请问是哪个短语？

**Comment by yaminogame** [comment]
> 请问是哪个短语？

似乎对哪个短语都没效果, 在输入的时候对被记住的错误短语按Ctrl+Shift+D, 不会有任何反应, 而且对比这个操作前后, 导出的用户词典, 也没看到要删除的短语被删除了

**Comment by epico** [comment]
我需要短语内容来复现此问题。

**Comment by yaminogame** [comment]
> 我需要短语内容来复现此问题。

比如"这也太参了"

**Comment by epico** [comment]
第一个候选词无法删除。

**Comment by epico** [comment]
不好意思，我再看看代码，回来再回复您。

**Comment by epico** [comment]
可能是 PYPPhoneticEditor.cc 的相关代码忘记更新了。

**Comment by epico** [comment]
Okay, fixed in https://github.com/libpinyin/ibus-libpinyin .

**Comment by hurae** [comment]
最新版本（ibus-libpinyin-1.11.92-1.fc31.x86_64）没有这个功能吗？这个快捷键不能删除自造词，没有任何反应。

> Okay, fixed in https://github.com/libpinyin/ibus-libpinyin .

**Comment by epico** [comment]
刚刚测试了一下，Ctrl+Shift+D 可以使用啊，删除键对于第1-3个候选词可能无效。

**Comment by hurae** [comment]
> 刚刚测试了一下，Ctrl+Shift+D 可以使用啊，删除键对于第1-3个候选词可能无效。

确实如此，但是为什么要设计为对前三个无效呢？自造词就是会成为第一个候选词啊，如果不小心按错了就是会在首位出现错误的自造词。比如我这里，我想要输入“好嘞”，但是第一次造词时一不小心输入成了“好勒”，那该怎么办？

**Comment by epico** [comment]
可以多输入几次"好嘞", "好勒" 会自动消失的...

**Comment by epico** [comment]
或者出现在后边的候选词中，这时候就可以删除了

**Comment by hurae** [comment]
真是好办法，我就是这么干的

**Comment by hurae** [comment]
好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞好嘞

好累

好勒仍然坚持在第二位，没有退去。上次我用"hao‘l"删掉了，这次试了试"hao'lei"发现还在。能不能在设置里面提供一个开关，让我可以临时删除前三位的候选词呢？

**Comment by epico** [comment]
可能得使用清除用户数据功能了...

**Comment by hurae** [comment]
我知道这个功能可以解决的，但是是不是有点太过于兴师动众了？到底为啥不能删除前三个候选词啊？
