### ISSUE TITLE
拼音输入卡顿,希望能解决(Use pinyin input often suddenly stuck)

### ISSUE THREAD

**Issue by xixifeng** [libpinyin/ibus-libpinyin#203]
使用拼音输入经常突然卡顿,希望能解决.谢谢!
版本: ibus-libpinyin-1.6.91-4.el7.x86_64
系统环境: CentOS Linux release 7.7.1908 (Core)

Use pinyin input often suddenly stuck, I hope someone can fix that problem. Thanks!
version: ibus-libpinyin-1.6.91-4.el7.x86_64
System environment: CentOS Linux release 7.7.1908 (Core)

**Comment by epico** [comment]
Please remove ~/.cache/ibus/libpinyin/user.conf in the Console, then re-login.

**Comment by ping-wu** [comment]
make sure to export user dictionary to a text file before deleting the
cache, then import this text file to re-use user dictionary
