### ISSUE TITLE
Input bar floats away in scaled windows

### ISSUE THREAD

**Issue by xijiang** [libpinyin/ibus-libpinyin#205]
In Fedora 30/31, if the windows scaled to 200%, for example, the input bar is then scaled away from the input cursor. If the input point/cursor is near the bottom, or the right edge of the window, the input bar may disappear. This make it very difficult to select candidates.

**Comment by xijiang** [comment]
Just found that if I use fractional scaling with gnome-tweak, this problem disappeared. Using the integer scaling in display setting will result in the problem above.

**Comment by aidistan** [comment]
Same issue since I changed to a high-dpi screen. I've tried to google it but got no solution.

**Comment by epico** [comment]
Please report this issue to ibus upstream.

URL: https://github.com/ibus/ibus/
