### ISSUE TITLE
希望添加新功能

### ISSUE THREAD

**Issue by adongs** [libpinyin/ibus-libpinyin#206]
希望添加新功能，在中文下输入所有符号为英文符号

**Comment by epico** [comment]
这个功能好像已经有了，请切换全角/半角符号。

**Comment by ping-wu** [comment]
主要问题在于，中文输入时，小数点会变成句点，每次都要切换全角/半角符号，非常不方便。其他中文输入法，如 ibus-pinyin, rime,
搜狗，等，都没有这个问题。

以前提出这个问题得到的回复是，转到其他输入法就好了。我想这不是一个 responsible answer。

**Comment by epico** [comment]
请在设置对话框中，将启动后默认为启用半角符号即可。

@ping-wu 这个自动转换是 feature, 之前有用户要求的。

**Comment by ping-wu** [comment]
完全不同意！！！

每次打小数点的时候就要启用半角符号，太不符合一般中国人的习惯了。

Ubuntu 论坛几乎没有人喜欢 libpinyin，这是很重要的一个原因，for example:
https://forum.ubuntu.org.cn/viewtopic.php?f=8&t=489689&p=3215328#p3215328

当然啦，你可以认为这是 Ubuntu 使用者的问题，但我也是长期 Fedora 使用者之一阿。

如果说这是一个 feature 的话，真的是一个 very negative 的 feature。 自毙！！！
（打中文时会碰到小数点的机会很多，每次多要加两个动作，先启用半角符号，再转回全角符号，太白痴了！！！）

**Comment by epico** [comment]
如果关掉这个 feature, 怎么输入中文句号呢？

如果喜欢输入 . , 请设置一次默认启用半角符号即可，之后就会一直输入 . 的。

**Comment by ping-wu** [comment]
I‘m sorry to say this, but I think you are finally getting the point!

默认为半角符号以后，句点（“ 。”）就打不出来，输入逗点后也会把整个中文的 kern 弄得乱七八糟。This the worst Chinese
input method that many of us have ever experienced，根本不能算是中文输入法吗！

如果说默认为全角符号时，输入的小数点（“ . ”）变成中文句点（“ 。”）是一个 *feature*，很多人会说这其实是一个 "*nightmare*
"。

**Comment by ping-wu** [comment]
基本上这个问题很好解决：把 algorithm 稍微修改一下，数字后面的 “句点” 就使用 半角的
'.'；其他情况，则按照默认值。一般输入中文时，都是默认全角符号，句点就是 “ 。” 。如前所述，其他所有的中文输入法，都有这个
algorithm，都没有问题！

**Comment by epico** [comment]
Actually this is just one bug introduced when fixing some compatibility issue.

Fixed in https://github.com/epico/ibus-libpinyin/ .

**Comment by ping-wu** [comment]
目前无法从 master 里编码，等到 1.11.2 （或 1.12.0？）出来后再试试。

**Comment by ping-wu** [comment]
另外，数字后面的 “逗点” 也请改为 半角符号。

目前（预设值为全角符号），输入数字时如果有逗点或句点，打出来非常不合习惯。举例：

目前： 123，456。05

请改为： 123,456.05

这个问题是一位会计师提出的。

**Comment by epico** [comment]
Okay, fixed in https://github.com/epico/ibus-libpinyin/ .
