### ISSUE TITLE
建议一些操作上的习惯,能类似win!

### ISSUE THREAD

**Issue by 474420502** [libpinyin/ibus-libpinyin#208]
1.多个快捷键位, ctrl+shift ctrl+space. 
2.输入的过程无法切换中英文(切换输入法).

**Comment by epico** [comment]
请问 ibus-libpinyin 的版本号是？

**Comment by 474420502** [comment]
> 请问 ibus-libpinyin 的版本号是？

1.11.0.
ubuntu 19.04.
在存在输入框的时候, ctrl+space(切换). 是无法像搜狗一样.取消自身并且切换.

**Comment by epico** [comment]
ibus 的默认切换键是 Super + space .

在 ibus-setup 中可以修改多个切换键。

**Comment by 474420502** [comment]
> ibus 的默认切换键是 Super + space .
> 
> 在 ibus-setup 中可以修改多个切换键。

我知道的, 我修改了ctrl+space切换, 但是在存在输入框的时候, 是无法切换的. 搜狗是可以的. 
如下输入框存在:
![image](https://user-images.githubusercontent.com/9397764/70016064-41c8cb00-15ba-11ea-9bc9-92319a41309a.png)

**Comment by 474420502** [comment]
> > ibus 的默认切换键是 Super + space .
> > 在 ibus-setup 中可以修改多个切换键。
> 
> 我知道的, 我修改了ctrl+space切换, 但是在存在输入框的时候, 是无法切换的. 搜狗是可以的.
> 如下输入框存在:
> ![image](https://user-images.githubusercontent.com/9397764/70016064-41c8cb00-15ba-11ea-9bc9-92319a41309a.png)

@epico  如果这个改了, 就和搜狗操作习惯差不多了.

**Comment by epico** [comment]
GNOME 3.x  需要在控制面板中修改，其他桌面可以在 ibus-setup 中修改。

**Comment by epico** [comment]
在 GNOME 3.x 中测试，切换键可以正常工作。

**Comment by 474420502** [comment]
![image](https://user-images.githubusercontent.com/9397764/70256910-4f51a100-17c4-11ea-946f-b570834bbd5f.png)
ubuntu 19.04 实测无效

**Comment by epico** [comment]
请给 Ubuntu Launchpad 也开一个 issue.

**Comment by 474420502** [comment]
@epico 我试了下ubuntu 18也不能切换, 还有切换按键延迟. 总的和搜狗就差点操作体验， 其他都差别不大.

**Comment by epico** [comment]
最好问问 Ubuntu ，看样子好像 ibus 包好像有点问题，可以让他们对比下 Fedora 的包，可能缺少一两个 patch.

ibus 输入法切换是 ibus 包负责的，Shift 和其他切换才是 ibus-libpinyin 负责的。

**Comment by 474420502** [comment]
@epico  THANKS
