### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [libpinyin/ibus-libpinyin#210]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by epico** [comment]
- [mandatory] which branch is your development branch?
My development branch is "master".

- [mandatory] have you merged latest translation from Zanata and locked the project?
Yes, I made ibus-libpinyin in zanata readonly now.

- [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
Okay, I just include the ibus-libpinyin.pot in the git repo now.

**Comment by Jibec** [comment]
configuration is done: https://translate.fedoraproject.org/projects/ibus-libpinyin/
please connect to the platform and share with me your username so I make you admin

Weblate already opened a PR to update po files: https://github.com/libpinyin/ibus-libpinyin/pull/265/files
You can merge it to have smaller pull requests in the future, or keep it open, whatever you prefer. Weblate will reuse the PR if it still exists, or create a new one.

I also activated a component addon to update your LINGUAS file.
Would you like me to remove line numbers to reduce future diff sizes?

**Comment by epico** [comment]
My Fedora Account is pwu .

The translation PR is merged, thanks!

I am okay to keep the line numbers, guess line number is helpful when translation.

**Comment by Jibec** [comment]
translator will have it accessible in weblate (the pot contains it), but saved po files won't store it.

**Comment by epico** [comment]
I think I am okay to keep the line numbers. :-)

Thank you very much!

**Comment by Jibec** [comment]
ok

i also added you as admin, you may close this issue

all the best

**Comment by epico** [comment]
Thanks, again!

**Comment by Jibec** [comment]
you're welcome, you may send an email to  translator mailing list to inform a week before release. You'll get our help :)
--
Jean-Baptiste

**Comment by epico** [comment]
Sure, nice to know it!
