### ISSUE TITLE
i模式无效

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#212]
Version: `IBus 1.5.21` /  `libpinyin  2.3.0-1` /  `ibus-libpinyin 1.11.1-2`
DE: `Arch` / `Gnome  3.34.2`
![irq](https://user-images.githubusercontent.com/17917040/71552579-a13fbc80-2a3a-11ea-9592-9284ada7fbc8.png)
从[sourceforge](sourceforge.net/projects/libpinyin/files/ibus-libpinyin/)下载安装的`i`模式可用但仅限于[base.lua](https://github.com/libpinyin/ibus-libpinyin/blob/master/lua/base.lua)中几个功能，而[special_table](https://github.com/libpinyin/ibus-libpinyin/blob/master/src/special_table)中的符号均不可用
![imode](https://user-images.githubusercontent.com/17917040/71552460-b87daa80-2a38-11ea-83e5-08cec0b5a165.png)
而`arch`包信息里上游URL就是`github`地址，不确定是否是`github`和`sourceforge`文件差异造成的。

另外从`ibus`打开的`libpinyin`的配置面板和从系统设置打开的不一样。
系统设置（注音）
![sysibus](https://user-images.githubusercontent.com/17917040/71552589-e9f77580-2a3a-11ea-87aa-eeb369413cfa.png)
Ibus首选项（拼音）
![ibuslib](https://user-images.githubusercontent.com/17917040/71552590-ecf26600-2a3a-11ea-888b-f576af1eb4cb.png)

**Comment by epico** [comment]
可能 Arch 包编译的时候，没有安装 Lua 的开发包。
如果没有检测到 Lua 包，扩展模式自动关闭。

special_table 在 Lua 扩展模式完成后，已经不再使用了；请自行转化为 Lua 程序，并通过 libpinyin 的“首选项” 对话框打开并保存到 user.lua 文件中。

不好意思，“首选项” 对话框是一个 bug, 已经在 github.com 中修复。

**Comment by tuberry** [comment]
`Arch` 那边提了个[BUG](https://bugs.archlinux.org/task/65013?project=5&string=ibus-libpinyin)，不知什么时候有回应。我暂时SourceForge上的，关于`user.lua`有几个小问题：
1. `register_command` 第一个参数(命令名)必须是两个及以上字符，单字符好像没有效果(保留字?)；
```lua
ime.register_command("sj", "get_time", "输入时间", "alpha", "输入可选时间，例如12:34")
```
2. 特殊符号候选框宽度问题(照顾右上的提示?),其实看作单字就好
![ifhxl](https://user-images.githubusercontent.com/17917040/71672431-e05e6c80-2db0-11ea-9fe0-c99e9fba1bb8.png)
```lua
-- 没看代码看用例写的，可能没用对
user['xl'] = { 'α','β','γ','δ','ε','ζ','η','θ','ι','κ','λ','μ','ν','ξ','ο','π','ρ','σ','ς','τ','υ','φ','χ','ψ','ω' }
function symbols(input)
	return user[input]
end
ime.register_command("fh", "symbols", "特殊符号", "digit", "输入简拼")
```
3. 就2中的代码，如果list只有1项的时候没法用数字键选中。不怎么会Lua，这要怎么改才行？
```lua
-- 测试代码,  user['te'] = '℡' 也不行
user['te'] = {'℡'}
```

**Comment by epico** [comment]
是的，必须是两个字符。

我把 Lua 代码修改了一下:
```
function symbols(input)
        return { 'α','β','γ','δ','ε','ζ','η','θ','ι','κ','λ','μ','ν','ξ','ο','π','ρ','σ','ς','τ','υ','φ','χ','ψ','ω' }
end
ime.register_command("fh", "symbols", "特殊符号", "digit", "请选择特殊符号")
```

**Comment by tuberry** [comment]
用`user['xl']`是为了进一步过滤(xl代表希腊字母)，因为特殊符号很多，先分类来减少翻页。

问题2是图中绿色这块太突兀了。
![xllib](https://user-images.githubusercontent.com/17917040/71710863-3ecf2d80-2e39-11ea-8a2e-e8d7ead2ee51.png)
问题3是用table这种写法，当list只有一个元素时候没法用数字1选中但多个元素是可以选的...
![libts](https://user-images.githubusercontent.com/17917040/71711253-13e5d900-2e3b-11ea-9e79-2e86da25c089.png)
```lua
function test(input)
        return 'α'
end
ime.register_command("ts", "test", "test", "digit", "test")
```
所以我想是不是用错了，有更好的写法?

**Comment by epico** [comment]
修改后的 Lua 代码为:
```
_SYMBOLS = {
  ['xl'] = { 'α','β','γ','δ','ε','ζ','η','θ','ι','κ','λ','μ','ν','ξ','ο','π','ρ','σ','ς','τ','υ','φ','χ','ψ','ω' }
}

function symbols(input)
         if #input == 0 then
            return {'xl 希腊符号'}
         end
         return _SYMBOLS[input]
end
ime.register_command("fh", "symbols", "特殊符号", "digit", "请选择特殊符号")
```

**Comment by tuberry** [comment]
这个有点问题，按数字键提示文字就上屏了：
```lua
_SYMBOLS = {
  ['xl'] = { 'α','β','γ','δ','ε','ζ','η','θ','ι','κ','λ','μ','ν','ξ','ο','π','ρ','σ','ς','τ','υ','φ','χ','ψ','ω' }
  ['te'] = { 't','e','s','t' }
}

function symbols(input)
         if #input == 0 then
            return {'xl 希腊符号'i, 'te 测试'}
         end
         return _SYMBOLS[input]
end
ime.register_command("fh", "symbols", "特殊符号", "digit", "请选择特殊符号")
```
![sybtip](https://user-images.githubusercontent.com/17917040/71717502-43a0db00-2e53-11ea-8c69-969b82d9a73e.png)

**Comment by tuberry** [comment]
能否完善一下Lua扩展乃至整个项目的注释或开发文档? 恕我愚钝，不能很好的理解和使用这些功能。比如`register_trigger`目前还不知道除了在`lua-ext-console`外怎么去`trigger`，以及它的具体用途。
以及从上面的使用场景来看可能需要微调和扩展一些功能...

**Comment by epico** [comment]
可以考虑注册 "xl", "te" 两个命令...
