### ISSUE TITLE
V模式挺好用的,是否可以常驻

### ISSUE THREAD

**Issue by ghostry** [libpinyin/ibus-libpinyin#213]
就是做成像shift切换中英这样,

可以用一个快捷键切换到V模式,

不需要每个单词都先输入一个v.

效果类似这个 https://github.com/BlindingDark/rime-easy-en

**Comment by epico** [comment]
不是可以用 Shift 切换到 英文模式了吗？

输入单个单词，请按 v; 输入多个单词，请按 Shift 键。

如果想用 rime 风格的话，可以考虑让 rime 调用 libpinyin 的 API, 这样就可以高度定制了。

**Comment by ghostry** [comment]
> 不是可以用 Shift 切换到 英文模式了吗？
> 
> 输入单个单词，请按 v; 输入多个单词，请按 Shift 键。
> 
> 如果想用 rime 风格的话，可以考虑让 rime 调用 libpinyin 的 API, 这样就可以高度定制了。

按shift是没有单词提示的. V模式有单词候选,这不一样.

**Comment by ghostry** [comment]
先关掉了,虽然输入英文挺好的,但是好像不怎么常用.
