### ISSUE TITLE
ibus-engine-libpinyin进程内存占用过高

### ISSUE THREAD

**Issue by zhuli1230** [libpinyin/ibus-libpinyin#214]
[ibus-engine-libpinyin进程内存占用过高，达到了800M以上，清除用户数据后依旧。
注：桌面环境为gnome 3.34.2，libpinyin为1.11.1

**Comment by zhuli1230** [comment]
系统是Archlinux

**Comment by epico** [comment]
请在 Console 下删除以下文件:
~/.cache/ibus/libpinyin/user.conf

**Comment by zhuli1230** [comment]
> 请在 Console 下删除以下文件:
> ~/.cache/ibus/libpinyin/user.conf

已经解决了，谢谢

**Comment by epico** [comment]
不客气
