### ISSUE TITLE
建议快捷方式!

### ISSUE THREAD

**Issue by 474420502** [libpinyin/ibus-libpinyin#215]
我发现搜狗和libpinyin的快捷方式区别在于, keypressDown(搜狗)触发和keypressUp触发, 这个非常影响体验.  w

**Comment by epico** [comment]
请详细说明。

**Comment by 474420502** [comment]
@epico  就是搜狗的快捷键在按下Down时候就触发效果, 但是libpinyin是Up的时候触发. 有时候会有奇怪的现象发生.

**Comment by epico** [comment]
什么奇怪的现象？

**Comment by 474420502** [comment]
@epico 延迟或者不触发.
