### ISSUE TITLE
候选词是否可以显示比输入长度更长的词

### ISSUE THREAD

**Issue by ghostry** [libpinyin/ibus-libpinyin#216]
我发现现在,当词库中有词的时候,仍然需要打完所有的拼音,

比如`白日依山尽黄河入海流`

事实上,我比较期待在输入到`白日依`的拼音的时候,就能在候选词看到它.

而不是等待输入完整句拼音.

又比如 `中华人民共和国`,输入`中华`拼音后,我觉得比较好的候选词是

`中华`,`中华人民共和国`,`中华人民`

我看搜狗拼音在长词候选词方面的做法是

优先显示词库中存在的以输入内容开头的长词,并限制最大个数

长词后面显示的是输入拼音对应的组词.

**Comment by epico** [comment]
好的，这个问题我回来看一下。

**Comment by ping-wu** [comment]
Any progress?

**Comment by epico** [comment]
This is a big feature I think, didn't get time for this feature yet.

**Comment by blickers** [comment]
事实上，目前最新版的 libpinyin （2.6.2）和 ibus-libpinyin （1.12.1）在处理候选词上做法逻辑很有问题。

比如完整敲入 “白日依山尽” 的拼音，出来的候选词依次如下：

1、白日依山金
2、白日依山进
3、白日依山近
4、白日依山进
5、百日已
6、百日

很显然，前三个是 libpinyin 自己 “推测” 并胡乱组合出来的词库里面不存在的，第四个才是词库里面跟拼音对应的词条。
这明显的不符合逻辑，不符合习惯，甚至很反人类。

首先应该检查词库，如果里面发现有与输入拼音对应的词，按词频顺序在候选词 1、2、3... 位置列出，后面再展示 libpinyin 推测的组合，这才符合逻辑。

现在的做法是，无论词库里面有没有词条，候选词前三位置一律现展示 libpinyin 的推测组合。只有在用户打过一次，并选择第四条候选词 “白日依山尽”之后，后面再次敲入相同的拼音，“白日依山尽” 才会出现在候选词第一位置（动态调整记录在用户配置里了）。这做法是反人类的。

希望改进。

**Comment by blickers** [comment]
> 打开 cloud input，输入 bryshj ，即可出现 “白日依山尽” 候选词（第4顺位）：
> 
> file:///home/ryzen/Pictures/Screenshot%20from%202022-07-20%2022-44-14.jpg
> 
> 输入该云字汇后，下次再输入 bryshj，即变成第一顺位。

不是的，我没有打开云输入。
我在词库文件 culture.table 里面已经加入了所有的古诗语句。

我们说的问题是，词库里面符合拼音的词应该默认出现在候选词第一顺位，后面再出现 libpinyin 联想推测的词语组合，而不是反过来把前三个候选词位置让给 libpinyin 联想推测出来的乱七八糟的东西。

**Comment by epico** [comment]
libpinyin 2.8 已初步支持显示比拼音输入更长的候选词。
