### ISSUE TITLE
[Feature Requests] 几个功能上的建议

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#217]
这些是我以前使用`fcitx`时比较喜欢的功能，希望`ibus-libpinyin`也有...
1. 终端状态控制
`Fcitx`提供了一个叫[fcitx-remote](https://manpages.ubuntu.com/manpages/bionic/man1/fcitx-remote.1.html)的命令。它能够从终端改变`fcitx`的输入状态，这个功能在某些情况下很有用，例如[fcitx.vim](https://github.com/lilydjwg/fcitx.vim)
2. 剪切板历史
`Gnome`下虽然有些剪切板管理插件但都在顶栏，这个由输入法来实现更直接和方便。或许可以由`ibus`来实现...
3. 云拼音
这个功能将网络返回的结果放在第二候选项，能极大的改善词库问题。

另外有个问题，用户导入的词库用简拼检索不到...
谢谢!

**Comment by epico** [comment]
可以用 `ibus engine` 在终端切换输入法。

**Comment by tuberry** [comment]
恩，`ibus engine`可以切换输入法，但是这种方式有[bug](https://github.com/ibus/ibus/issues/1932)而且比较慢（尤其是用在vim里感觉更明显，用`dbus`更快些），更重要的是既然自带了中英文切换仍需切换输入法体验不是很好。
