### ISSUE TITLE
词库数据会丢失

### ISSUE THREAD

**Issue by ghostry** [libpinyin/ibus-libpinyin#218]
系统ubuntu1904,软件版本 1.11.0

最近在折腾词库,然后就发现前一天导入的词库,到第二天就没有了.

然后我找了.local和.config都没有找到词库文件.

后来在 .cache 里边找到了.词库丢失的原因也明白了,我的 .cache目录是用的tmpfs.重启就没有了.

我觉得这里有些不对,.cache应该是放置的缓存类的文件,可以随时丢弃的内容.

像chrome浏览网页缓存文件这种

而用户词库看起来不属于这种,是否应该放到 local 里边.他应该是属于用户数据.

**Comment by epico** [comment]
为什么要用 tmpfs ?

很多应用都会放数据到 .cache, 比如 evolution 等。

**Comment by ghostry** [comment]
> 为什么要用 tmpfs ?
> 
> 很多应用都会放数据到 .cache, 比如 evolution 等。

为了快,

目前就遇到libpinyin存在cache,别的还没遇到.

**Comment by ghostry** [comment]
这个我先关了,我用`mount -B`先解决了,

如果作者觉得我说的对可以改下路径.

**Comment by epico** [comment]
好的，目前还没有其他人报这个问题，暂时没有打算修改路径。

修改路径的话，需要进行数据迁移，否则会引起数据丢失。
