### ISSUE TITLE
Interpunct Problems

### ISSUE THREAD

**Issue by BootlegPhil** [libpinyin/ibus-libpinyin#220]
I'm using Pop_OS! as my distro.

**Issue/Bug Description:**
When pushing the "~" key, the Intelligent Pinyin selection menu pops up as normal. However, when attempting to input a number to select a symbol within the selection menu or use the bracket keys to move through it, the "·“ interpunct character is overwritten by the symbol on the key I push. For example, when I push 1 to select the interpunct character, the character becomes 1.

However, I can still use the interpunct character by clicking on it in the selection menu.

**Steps to reproduce (if you know):**
Switch to Intelligent Pinyin Chinese input.

Type an interpunct symbol by hitting the "~" key.

Then hit a number or attempt to use the bracket keys to move through the menu that comes up.

**Expected behavior:**
For the interpunct symbol to be selectable by hitting a number, and the selection menu that comes up when hitting the "~" key to be navigable with the bracket keys.

**Comment by epico** [comment]
I think that feature is designed to input Full Width numbers, like "１".

**Comment by BootlegPhil** [comment]
> I think that feature is designed to input Full Width numbers, like "１".

Well, since you are the creator of the original project and you seem to know what you're talking about, I'll just close this issue. 

Also, thank you for making libpinyin.
