### ISSUE TITLE
候选栏位置

### ISSUE THREAD

**Issue by fujiwarat** [libpinyin/ibus-libpinyin#222]
Reported https://github.com/ibus/ibus/issues/2180 by @yueduz

![2020-02-04 17-30-40 的屏幕截图](https://user-images.githubusercontent.com/1448159/73732050-743aa400-4774-11ea-9674-4960dcef7a96.png)
我认为在我没有按下空格键上屏前，候选条应该定位在图片红色标记位置。这样可以减少候选条过多的移动干扰输入。另外我还认为应该提供一个固定候选栏不跟随光标的选项，例如定位在屏幕顶部。

＃ 状态跟随建议
只要文本框被激活（即使还没开始输入）就让状态栏跟随在光标上，当有候选时，隐藏状态栏，跟随候选栏，当无候选时隐藏候选栏跟随状态栏。可以跟随显示部分状态，如中英状态，全／半角状态。

因为在开始输入法时我真的不知道我当前是中文状态还是英文状态啊。每次都输了四五个键又回头改。

**Comment by fujiwarat** [comment]
> 我认为在我没有按下空格键上屏前，候选条应该定位在图片红色标记位置。

I also wondered why the horizontal lookup window has been shown at the end of the string while vertical lookup window hasn't. I guess the original model exists in other platforms.

CC'ing @epico

BTW, I also proposed the similar fix in vte; https://bugzilla.gnome.org/show_bug.cgi?id=795319

> 这样可以减少候选条过多的移动干扰输入。另外我还认为应该提供一个固定候选栏不跟随光标的选项，例如定位在屏幕顶部。

Currently I don't think such an setting option.

> 只要文本框被激活（即使还没开始输入）就让状态栏跟随在光标上，当有候选时，...

You can show a property panel from ibus-setup -> "General" -> "Show property panel"

> 因为在开始输入法时我真的不知道我当前是中文状态还是英文状态啊。每次都输了四五个键又回头改。

ibus-anthy can show the input mode in the panel and ibus-libpinyin also could be. You can request the feature in https://github.com/libpinyin/ibus-libpinyin/issues .

**Comment by epico** [comment]
From the screenshot, it seems it is not Pinyin input method.

Please open the issue to correct input method, I will close this issue soon.

**Comment by fujiwarat** [comment]
I think this can be reproduced in ibus-pinyin and ibus-libpinyin so it's a common issue for engines to use horizontal lookup window?

**Comment by epico** [comment]
I think it is okay to keep the current behavior, it has been used for some years.

When typing, user will focus on preedit text, and some other pinyin input method
also show candidates window after preedit text when requested.

Maybe you could try compact display style in ibus-libpinyin (not released yet).
The compact display style will show candidates in the beginning of the preedit text.

**Comment by fujiwarat** [comment]
OK, I'm fine to close this issue.
@yueduz Any comments?

**Comment by yueduz** [comment]
>您可以从ibus-setup->“常规”->“显示属性面板”显示属性面板。

但是这个只是显示不能跟随

**Comment by yueduz** [comment]
> 我认为保留当前行为是可以的，它已经使用了几年。

当第一个候选词由四字词变为二字词时，候选条就会从右往左跳，再继续输入法又往右跳。特别在使用码表输入法时，经常左右来回跳，体验很不好。如果候选条再有一个固定的大小，而提供滚动条，就更好。不会随候选词长度变化而改变大小，减少晃眼次数。使用码表输入法时，使用者会更频繁的使用空格提交上屏，不像拼音整句输入法，候选条频繁隐现也很晃眼。所以我觉得，固定大小一直显示的候选条是最好的。固定位置不跟随也可作为一个选项。对于熟练使用码表输入法的用户，并不会过多的去看候选条，所以跟随对他们来说没有很大的用处。

**Comment by epico** [comment]
码表输入法的话，请用英文报到 ibus-table .

URL: https://github.com/mike-fabian/ibus-table

**Comment by epico** [comment]
@yueduz Which input method are you using?

**Comment by yueduz** [comment]
> @yueduz Which input method are you using?

ibus-table   自定义码表

**Comment by epico** [comment]
@yueduz 请问是哪个码表？

**Comment by yueduz** [comment]
https://blog.juying.co/content/%E8%B6%85%E5%BC%BA%E9%9F%B3%E5%BD%A2%E7%A0%81%E8%A1%A8

Peng Wu <notifications@github.com> 于 2020年3月2日周一 12:17写道：

**Comment by epico** [comment]
I think ibus-table doesn't move the candidates window with Wubi input method.

**Comment by tuberry** [comment]
Gnome下大部分软件中候选框是随预编辑区光标移动的，比如gedit:
![image](https://user-images.githubusercontent.com/17917040/76677656-e623ca00-660b-11ea-819c-c4b3d8642793.png)
小部分是停在键入位置的，目前只发现一个火狐浏览器是这样:
![image](https://user-images.githubusercontent.com/17917040/76677664-06538900-660c-11ea-81ee-835ae659b125.png)
别的比如搜狗输入法是没有预编辑区域，它的光标是不动的更像后一种。我觉着这样也不错

**Comment by epico** [comment]
在下一个 ibus-libpinyin 版本中，引入了新的显示风格，请耐心等待。:)

**Comment by tuberry** [comment]
等了好久了:)，先发个Pre-release呗

**Comment by hurae** [comment]
目前已经实现此需求，现在ibus的输入框位置正如你所描述的。

> Reported [ibus/ibus#2180](https://github.com/ibus/ibus/issues/2180) by @yueduz
> 
> ![2020-02-04 17-30-40 的屏幕截图](https://user-images.githubusercontent.com/1448159/73732050-743aa400-4774-11ea-9674-4960dcef7a96.png)
> 我认为在我没有按下空格键上屏前，候选条应该定位在图片红色标记位置。这样可以减少候选条过多的移动干扰输入。另外我还认为应该提供一个固定候选栏不跟随光标的选项，例如定位在屏幕顶部。
> 
> ＃ 状态跟随建议
> 只要文本框被激活（即使还没开始输入）就让状态栏跟随在光标上，当有候选时，隐藏状态栏，跟随候选栏，当无候选时隐藏候选栏跟随状态栏。可以跟随显示部分状态，如中英状态，全／半角状态。
> 
> 因为在开始输入法时我真的不知道我当前是中文状态还是英文状态啊。每次都输了四五个键又回头改。
