### ISSUE TITLE
How to use ibus in terminal emulator and code editor?

### ISSUE THREAD

**Issue by Photonico** [libpinyin/ibus-libpinyin#223]
我的系统是 Solus OS Plasma, 在libreOffice这类的富文本编辑器以及FireFox中, 我可以用Ibus-pinyin正常输入中文, 但是在VSCode这类的代码编辑器和终端中, 我不能呼出中文功能, 只能输入英文. (但是希腊语不受影响)

My OS is Solus OS Plasma, I can use ibus to put Chinese in text editor and Firefox, but I cannot use it in terminal emulator and code editor.

**Comment by epico** [comment]
Please report to ibus upstream.

URL: https://github.com/ibus/ibus/

**Comment by wffger** [comment]
我系统是Fedora31，VS Code正常使用libpinyin。
