### ISSUE TITLE
与ibus-pinyin的功能比较丢失的问题

### ISSUE THREAD

**Issue by guoqiyi** [libpinyin/ibus-libpinyin#23]
首先感谢大牛的辛苦开发，让俺们有了方便的中文输入法^_^
  据我所知ibus-libpinyin是在ibus-pinyin的基础上改进而来的，最让我喜欢的新功能就是是切换输入法时右上角可以显示是中文还是英文，免去先打一个字测试的麻烦^_^,但是用惯了ibus-pinyin的我切换到本输入法时发现ibus-pinyin的一些好用功能丢失了，希望能修复啊：
1.记忆输入过的词不及时
    在ibus-pinyin中，输入个人词库没有的新词后再接着后面输一遍就会立即显示出刚才新输的词，或者已有的词会调整排序，很及时，但是在libpinyin中第一次输入后接着输有时候会出现有时候则没有，挺不稳定的，而且必须再结束本次输入状态后才能记录，就是输入完之后切换到另一程序再切换回来才会记录，一直在本程序则不会，直到关闭才会记录，不能动态的随书随记了
2.记录同音词有丢失现象
    比如我先输入了一个词“奇异果”，再输入一个词“起义国”，第三次输入qiyiguo时提供的排序就是1起义国2奇异果，我选了第二个词“奇异果”，可是当我第四次输入qiyiguo时，提供的词只有1奇异果了，而那个本该排在2的“起义国”却消失了，这是一个bug
3.简拼对输入过的词无效
    如题所示，这是我最不能忍的一个功能丢失了，严重拖慢了输入速度啊，比如我输入过一次“奇异果”了记录在个人词库，在ibus-pinyin中下一次我就可以直接打qyg三个声母调出来，可是libpinyin不行，还得完整地打出qiyiguo才能调出，这应该是简拼功能部分丢失了吧，望作者大牛解决啊
不管怎么说，谢作者的辛勤工作先^_^

**Comment by epico** [comment]
ibus-libpinyin 1.6.99.20150203 已发布，
请打开设置对话框的 "将每个输入记录为新的词汇" 选项，
可修正此 issue.

如果还有问题，请报 issue，谢谢。

**Comment by epico** [comment]
Please try libpinyin 2.6.1 and ibus-libpinyin 1.12.1, thanks!
