### ISSUE TITLE
用户词典如何自定义短语？

### ISSUE THREAD

**Issue by wffger** [libpinyin/ibus-libpinyin#230]
我想输入两个字母直接显示一个特定短语，我编辑用户字典如下：

> 北京路20号 dz 1
> abc@163.com yx 1

导入字典后，输入字母却不显示对应的短语。
用户字典是不是不能这样用？怎么才能实现我的快捷输入？
谢谢。

**Comment by epico** [comment]
目前用户词典还不支持此功能，请考虑使用 Lua 脚本扩展。

**Comment by wffger** [comment]
有没有lua script extension的示例？我编辑了user.lua而且重启了ibus，但是i选项还是没有显示我自定义的函数。

**Comment by epico** [comment]
请参考 /usr/share/ibus-libpinyin/base.lua .

**Comment by wffger** [comment]
我编辑user.lua如下：
```
_CUST_PHRASE = {
  [xm] = "张三",
  [sj] ='18823459876',
}

function get_phrase(input)
  local ret
  ret = _CUST_PHRASE[input]
  return ret
end

------------
ime.register_command("cp", "get_phrase", "自定义短语", "none", "输入您的短语编码")
print("user lua script loaded.")
```

然后重启ibus，`ibus restart`。
然后敲击'i'，没有新功能出来。
请问我是哪一步出错了？

**Comment by epico** [comment]
```
_CUST_PHRASE = {
  ['xm'] = "张三",
  ['sj'] ='18823459876',
}
```

**Comment by wffger** [comment]
> ```
> _CUST_PHRASE = {
>   ['xm'] = "张三",
>   ['sj'] ='18823459876',
> }
> ```

修改了，还是没有新选项显示在'i'功能里面。我先找个REPL测试一下代码。

**Comment by wffger** [comment]
终于可以了，原来是有个字符识别不了。🙈
