### ISSUE TITLE
在disable fuzzy syllable且incomplete pinyin的时候，非翘舌音的简拼应该要能打出翘舌音的字。

### ISSUE THREAD

**Issue by hebo6** [libpinyin/ibus-libpinyin#235]
在disable fuzzy syllable且incomplete pinyin的时候，非翘舌音的简拼应该要能打出翘舌音的字。
比如现在的版本中用“s”打不出”是（shi）“。需要用“sh”才能打出。
同理还有后鼻音同样需要改进。比如“an”理应可以打出“昂（ang）”。

**Comment by epico** [comment]
fuzzy syllable 是模糊拼音，需要打开才能通过 "s" 输入 是（shi）等。

**Comment by i-love-tadpole** [comment]
开启简拼且关闭模糊拼音的情况下，“sm”打不出“什么（shenme）”是设计的本意吗？

**Comment by epico** [comment]
是的，请打开模糊拼音。

**Comment by i-love-tadpole** [comment]
这大大降低了简拼的实用性。我有类似搜狗超级简拼这样的需求：
s=s或sh，
sh=sh（不包含s），
应该怎么办？开启模糊音的话，sh会包含s结果。

**Comment by epico** [comment]
目前不支持此功能。
