### ISSUE TITLE
Warning: /usr/share/appdata is deprecated 

### ISSUE THREAD

**Issue by guoqiyi** [libpinyin/ibus-libpinyin#236]
* This package seems to install metainfo files into the following
 * location(s):
 * 
 *   /usr/share/appdata
 * 
 * This location is deprecated, it should not be used anymore by new software.
 * Appdata/Metainfo files should be installed into /usr/share/metainfo directory.
 * For more details, please see the freedesktop Upstream Metadata guidelines at
 * https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/1e9f1f343f4c098fc9619364233e905182eba9bb .
