### ISSUE TITLE
特殊符号输入问题

### ISSUE THREAD

**Issue by hurae** [libpinyin/ibus-libpinyin#237]
i特殊模式现在没有特殊符号，应该如何输入特殊符号呢？

**Comment by epico** [comment]
请考虑使用 Lua 脚本扩展。

参考: #234 .

**Comment by hurae** [comment]
目前我使用math-latex(m17n)输入源解决此问题，使用体验上很好。唯一的缺点就是需要记住特殊符号对应的英文，熟练了也不算缺点。
