### ISSUE TITLE
候选词显示为省略号

### ISSUE THREAD

**Issue by wffger** [libpinyin/ibus-libpinyin#238]
有时ibus无故挂了，用`ibus-daem -rdx`重启，这时候选词显示为省略号（两个或三个点号）。
同时，任务栏中的输入法菜单显示为中英文混合。首选项的内容则全部是英文。
我用的是Fedora 31，gnome桌面。推测是重启的选项缺少了语言，导致后面错乱。

**Comment by epico** [comment]
请问新建用户是否也有这个问题？

ibus-libpinyin 是自己编译的吗？

**Comment by wffger** [comment]
暂时不能新建用户。
软件是用dnf安装官方的。

**Comment by epico** [comment]
请新建用户试一试，我这里无法复现。

**Comment by wffger** [comment]
应该是gnome-shell主题导致的问题。我在“优化”工具中修改了“外观”-“应用程序”的主题，然后就可以正常显示了。
