### ISSUE TITLE
不能切换回智能拼音

### ISSUE THREAD

**Issue by 00000000NUL** [libpinyin/ibus-libpinyin#242]
当系统中设置好 英语-美国，智能拼音，俄语三个输入法，只要切换到俄语，就不能直接按 Windows + Space 切换回智能拼音，只能先切换到 ”英语-美国“ 再切换到智能拼音，目前没有发现跟操作系统有关，在 CentOS 8， Debian 10, Kali 2020.1b 中都如此，同样的操作环境，sunpinyin 不存在此问题。

**Comment by epico** [comment]
可能是俄语将键盘布局切换到了俄语键盘有关。

请自行修改 /usr/share/ibus/component/libpinyin.xml.

```
<layout>default</layout>
=>
<layout>us</layout>
```

**Comment by 00000000NUL** [comment]
果然是的，大佬一语中的，非常感谢！
