### ISSUE TITLE
gnome-shell-extension-ibus-font does not work in gnome tweaks

### ISSUE THREAD

**Issue by cw400** [libpinyin/ibus-libpinyin#244]
gnome-shell-extension-ibus-font does not work in gnome tweaks
The extension cannot be activated in gnome tweaks
Fedora 32
Gnome 3.36.2
gnome-shell-extension-ibus-font 0.20170217
![ibus](https://user-images.githubusercontent.com/65080812/81477843-283b4780-921a-11ea-9357-d9f68207e4d5.png)

**Comment by tuberry** [comment]
https://extensions.gnome.org/extension/2729/ibus-font-setting/

**Comment by epico** [comment]
Just updated the package in Fedora 32, thanks for the report!

URL: https://bodhi.fedoraproject.org/updates/FEDORA-2020-f3760b984f
