### ISSUE TITLE
开头为v，输入英文字母会少个v

### ISSUE THREAD

**Issue by wkt** [libpinyin/ibus-libpinyin#245]
正常情况下，想要输入英文字母，可以直接回车OK了。
但是只要是输入的开头是v，回车时就会少开头的那个v，输入体验很差...

**Comment by epico** [comment]
v 是英文输入模式，用户要求修改成这样的。

**Comment by wkt** [comment]
> v 是英文输入模式，用户要求修改成这样的。

那如何禁用这这种模式呢？比较喜欢回车输入英文。

**Comment by epico** [comment]
好像在编译时可以关闭这种模式...

**Comment by wkt** [comment]
> 好像在编译时可以关闭这种模式...

好吧，看来我只能忍了。自己编译还挺麻烦的。
