### ISSUE TITLE
候选框位置超出屏幕，乃至不可见

### ISSUE THREAD

**Issue by CliffHan** [libpinyin/ibus-libpinyin#247]
前置条件：
1. Ubuntu 20.04，屏幕放缩设置成125%（已确认设置成100%并重启后无此问题）
2. 使用Microsoft Teams Preview for Ubuntu（我怀疑所有electron应用都有此问题，但未经验证）

效果：
使用智能拼音输入法时，候选框出现在右下方偏移很远的地方。
如果是在屏幕底部的输入框输入，那么会根本看不到候选框

**Comment by CliffHan** [comment]
版本：ibus-libpinyin/focal,now 1.11.1-3 amd64 [installed]

**Comment by epico** [comment]
可能是 ibus 的问题，建议用英文到 ibus upstream 问一下。

**Comment by epico** [comment]
https://github.com/ibus/ibus/issues/

**Comment by CliffHan** [comment]
I added comment in https://github.com/ibus/ibus/issues/2221
