### ISSUE TITLE
请问如何设置某个字出现的顺序

### ISSUE THREAD

**Issue by Syize** [libpinyin/ibus-libpinyin#248]
使用输入法时经常遇到需要输入的字在非常靠后的位置，即使输入过了很多次也是如此。想知道如何将它出现的位置调前。

**Comment by epico** [comment]
也许可以将常用字和发音保存到文本文件中，然后从设置对话框导入，看看能否改变候选字的位置。

**Comment by Syize** [comment]
是按照设置里面那个用户词典的格式保存并导入吗？我试一试

**Comment by epico** [comment]
是的

**Comment by Syize** [comment]
这个输入法有根据用户习惯调整词序的功能吗？我模糊的记得它好像调整过某些字出现的顺序，但是现在看来它好像又不会调整词序。

**Comment by epico** [comment]
好像在设置对话框有个选项。

**Comment by Syize** [comment]
候选词的 动态调整候选词顺序 我一直是打开的，排列顺序也是改成了 词频，但是好像没有效果

**Comment by Syize** [comment]
我知道了，需要将候选词选项里面的“将每个输入记录为新的词汇”勾选，输入法才会动态调整词序
