### ISSUE TITLE
The libpinyin show candidates at bottom when I am typing in WPS

### ISSUE THREAD

**Issue by larryw3i** [libpinyin/ibus-libpinyin#250]
**The libpinyin show candidates at bottom when I am typing in WPS**  
![Screenshot from 2020-06-16 19-21-44](https://user-images.githubusercontent.com/24457116/84768329-a7385280-b006-11ea-8785-a8c365c4a30a.png)  
do hope it been fixed soon, Thanks!

**Comment by epico** [comment]
I think this issue should be fixed in ibus or WPS.

WPS seems to use QT5 for GUI, please check whether WPS use QT5 ibus input module.

And for customized widget, the widget should call QInputMethod::setInputItemRectangle, QInputMethod::setInputItemTransform, etc.

Please try to contact WPS, thanks!

**Comment by larryw3i** [comment]
@cyrpaut guy， we need your help

**Comment by ping-wu** [comment]
I don't have this problem.

**Comment by epico** [comment]
Does this issue happen with Snap only or with rpm and deb package?

**Comment by epico** [comment]
No response, close this issue.
