### ISSUE TITLE
Build failures with Lua 5.4

### ISSUE THREAD

**Issue by felixonmars** [libpinyin/ibus-libpinyin#252]
```
lmyoslib.c: In function ‘getfield’:
lmyoslib.c:60:36: error: expected ‘)’ before ‘LUA_QS’
   60 |       return luaL_error(L, "field " LUA_QS " missing in date table", key);
      |                                    ^~~~~~~
      |                                    )
make[2]: *** [Makefile:795: libpylua_la-lmyoslib.lo] Error 1
```

**Comment by epico** [comment]
I think I copied some code from loslib.c.

Maybe it is time to update the code now.

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/f3faeeff3fbe3bf9e30ed4461c2c8d0466966e56 .

Could you review this patch?

**Comment by ping-wu** [comment]
Can someone share the build procedure so we can try (especially regarding the dependencies)?  I'm having a lot of problem trying to build ibus-libpinyin in Ubuntu 20.04.  Thanks!

**Comment by epico** [comment]
Please check with the Ubuntu packages.

URL: https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

**Comment by ping-wu** [comment]
Please see:

https://forum.ubuntu.com.cn/viewtopic.php?f=8&t=491327

**Comment by felixonmars** [comment]
> Fixed in [epico@f3faeef](https://github.com/epico/ibus-libpinyin/commit/f3faeeff3fbe3bf9e30ed4461c2c8d0466966e56) .
> 
> Could you review this patch?

Thanks, it builds fine here on Arch with Lua 5.4.

**Comment by ping-wu** [comment]
Where can I find info about using Lua in ibus-libpinyin?  Current build default is to disable it, but the Ubuntu build seems to enable Lua.

**Comment by epico** [comment]
Please read base.lua .

**Comment by epico** [comment]
ibus-libpinyin 1.11.93 is released.
