### ISSUE TITLE
使用<shift>+双符键，输入上档字符时，半角/全角颠倒

### ISSUE THREAD

**Issue by Hugo342523** [libpinyin/ibus-libpinyin#255]
打个比方，中文模式下，按shift+双符6键，本应输出……，然而它输出了^；反过来，英文模式下，按shift+双符6键，本应输出^，然而它输出了……。 
这个半全角颠倒情况仅限于shift+双符键输入上档字符，对于单按下档字符，半全角正常。

另外，我测试了一下，按住shift不松开，同时多次点击双符6键，会输出^……^……^……^……^……，状态栏的输入法中英标志也会随之在中英之间跳动，希望对您判断问题有帮助。

Ubuntu20.04，IBus 智能拼音 1.11.1

谢谢！

**Comment by epico** [comment]
我试了一下，无法在 1.11.92 中复现，建议尝试 1.11.92。

另外，请给 Ubuntu 报一个 Bug.

**Comment by Hugo342523** [comment]
好的我试试，谢谢！


 
---原始邮件---
发件人: "Peng Wu"<notifications@github.com&gt;
发送时间: 2020年7月16日 09:25:58
收件人: "libpinyin/ibus-libpinyin"<ibus-libpinyin@noreply.github.com&gt;;
抄送: "Hugo342523"<hxh342523@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [libpinyin/ibus-libpinyin] 使用<shift&gt;+双符键，输入上档字符时，半角/全角颠倒 (#255)




 
我试了一下，无法在 1.11.92 中复现，建议尝试 1.11.92。
 
另外，请给 Ubuntu 报一个 Bug.

**Comment by ping-wu** [comment]
Ubuntu20.04 里，IBus 智能拼音的版本应该是 1.11.3（18.04 ibus-libpinyin 的版本才是 1.11.1）。我试了一下，没问题。中文模式下，按shift+双符6键，输出……，英文模式下，按shift+双符6键，输出了^。

**Comment by Hugo342523** [comment]
我也不知道什么情况，我是从1910升级到2004的，默认就是1.11.1，没动过。我试着升级一下，谢谢！


 
---原始邮件---
发件人: "ping-wu"<notifications@github.com&gt;
发送时间: 2020年7月16日 11:29:54
收件人: "libpinyin/ibus-libpinyin"<ibus-libpinyin@noreply.github.com&gt;;
抄送: "Hugo342523"<hxh342523@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [libpinyin/ibus-libpinyin] 使用<shift&gt;+双符键，输入上档字符时，半角/全角颠倒 (#255)




 
Ubuntu20.04 里，IBus 智能拼音的版本应该是 1.11.3（18.04 ibus-libpinyin 的版本才是 1.11.1）。我试了一下，没问题。中文模式下，按shift+双符6键，输出……，英文模式下，按shift+双符6键，输出了^。

**Comment by Hugo342523** [comment]
刚才确认了一下，ubuntu20.04里的智能拼音版本是1.11.1-3。请问如何升级呢，没找到升级按钮。请问能提供最新版的.deb包吗？Sent from my Huawei phone-------- Original message --------From: ping-wu <notifications@github.com>Date: Thu, 16 Jul 2020, 11:29To: libpinyin/ibus-libpinyin <ibus-libpinyin@noreply.github.com>Cc: Hugo342523 <hxh342523@foxmail.com>, Author <author@noreply.github.com>Subject: Re: [libpinyin/ibus-libpinyin] 使用+双符键，输入上档字符时，半角/全角颠倒 (#255)

Ubuntu20.04 里，IBus 智能拼音的版本应该是 1.11.3（18.04 ibus-libpinyin 的版本才是 1.11.1）。我试了一下，没问题。中文模式下，按shift+双符6键，输出……，英文模式下，按shift+双符6键，输出了^。

**Comment by Hugo342523** [comment]
参考你给的链接，折腾了一下午，终于成功打包ibus-libpinyin 1.11.93，并成功安装上了。但是，它　还是从前那个bug　没有一丝丝改变。。。。。。哇我要哭了

另外，你们让我去ubuntu反馈，可惜我英文不太行，难以描述。。。

决定弃坑了，不过还是要感谢，我学会了打包源码了！！！

**Comment by ping-wu** [comment]
使用 Ubuntu 或 Fedora 时我们是绝对不升级而是直接 install 新的版本。直接升级问题太多了。

**Comment by epico** [comment]
我个人用 Fedora, 是每个版本都升级的。

不推荐 Fedora 跨版本升级...

**Comment by epico** [comment]
ibus-libpinyin 1.11.93 is released.
