### ISSUE TITLE
Lua 脚本不支持 require 语法

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#257]
![image](https://user-images.githubusercontent.com/17917040/88137133-76f35d80-cc1d-11ea-93cd-c4b1d90325bd.png)
这样的话所有的东西都必须放到 user.lua 中，不太方便

**Comment by epico** [comment]
我对 Lua 语法不是很熟悉。

在输入法中，出于安全考虑，用了 sandbox 机制。

禁用了一些 Lua 的功能。

**Comment by tuberry** [comment]
这个类似 `import/include` 的作用，把脚本[模块化](https://github.com/jimmy54/rime-lua/blob/master/rime.lua)，直接用 `lua` 执行没有报错。这种基本库会引入什么隐患呢？

**Comment by epico** [comment]
ibus-libpinyin 内建的 Lua 支持并不完整，require 的模块不一定能够正常工作...

**Comment by tuberry** [comment]
看起来是对标准库做了一些裁减，我也没有想引入什么复杂的模块，就是想把每个功能写到一个单独的文件而已，效果和全写到 `user.lua` 是一样的。`require` 由 `luaopen_package` 提供，只增加这个库如何？

**Comment by epico** [comment]
看了下 loadlib.c 的代码，里边的功能不少...
好像还可以加载二进制库。

如果给 ime 模块，加一个 load 方法呢？

**Comment by tuberry** [comment]
我看了一下 lua [沙盒](http://lua-users.org/wiki/SandBoxes)的说明，`require` 是不安全的。但没有这些不安全的特性脚本就只有一些‘纯函数’用了，不能访问环境和文件系统就谈不上 `load` 。至于加载二进制库，我觉得开源软件用户应该为自己写的东西负责。 如果`require`不行的话，那目前已经加载的 `base` 库同样也有一个功能类似且同样不安全的 [`dofile`](https://stackoverflow.com/questions/31144564/what-are-the-differences-between-dofile-and-require-in-lua)，

**Comment by epico** [comment]
我觉得可以使用 dofile, 毕竟不会加载二进制文件......

**Comment by tuberry** [comment]
如果我没理解错这里面的重点的话：现在风险不在于是否加载文件而在于加载什么样的文件。后者是由用户决定，二进制就是恶意的吗？为什么要加载不明的二进制呢？而 `require` 还可以自己搜目录和缓存模块比`dofile`规范得多。我觉得'二进制'作为用`dofile`而非`require`的理由有些因噎废食。

**Comment by epico** [comment]
我觉得加载动态链接库会破坏 Lua sandbox 机制，关闭 issue.
