### ISSUE TITLE
能否增加一个类似手机上的笔画输入法的模式？

### ISSUE THREAD

**Issue by astrojhgu** [libpinyin/ibus-libpinyin#259]
现在通过`u`键可以开启笔画输入法，我是指，能否增加一个笔画输入法常开的模式，然后每一个笔画的按键可以重新绑定

**Comment by epico** [comment]
请参考 https://github.com/YQ-YSY/one-hand_Rime

**Comment by astrojhgu** [comment]
> 请参考 https://github.com/YQ-YSY/one-hand_Rime

谢谢，这正是我需要的。
