### ISSUE TITLE
繁簡體模式下的問題

### ISSUE THREAD

**Issue by ee23** [libpinyin/ibus-libpinyin#26]
1 ）簡體模式下候選字同時出現簡體字和繁體字

2）繁體模式下有些候選字會出現2次
輸入"li"，候選字有2個"裏" 3個"歷"，還有其他...

3）繁體模式下輸入"li"候選字沒有"里"，暫時的解決方法：需要輸入"gongli"，候選字出現"公里"，然後再刪除"公"字

建議增加的功能：能夠改候選字大小

fedora 20
libpinyin 1.6.92

**Comment by hizukiayaka** [comment]
1.6.92 4.fc21
当中正体模式不能工作，切换到正体模式，按下第二个音ibus-libpinyin就会退出。

**Comment by epico** [comment]
我刚刚做了个 f21 的更新，可以试试新版本，在 updates-testing 中。
也可以试试 ibus-libzhuyin.
还有问题的话，欢迎开 issue.

**Comment by hizukiayaka** [comment]
很遗憾的是，在testing安装上来会有问题，无法输入正体还是简体的汉字。也更新了ibus还是不行。
估计是安装在f21有问题。

**Comment by epico** [comment]
请移除 ~/.cache/ibus/libpinyin/ 试试。

**Comment by epico** [comment]
不好意思，最近我刚刚发现在 fedora 上 ibus-pinyin 的繁体模式使用的是自带的代码。
ibus-libpinyin 使用的是 opencc.
如果确实是 ibus-pinyin 的效果好的话，我可以下次把 ibus-libpinyin 的 opencc 关掉，试试。

**Comment by epico** [comment]
Hi hizukiayaka,
知道了，我看一下。

**Comment by epico** [comment]
Hi hizukiayaka,
Draft patch landed on https://github.com/epico/libpinyin/commit/42121a7a95a703db5af20bf799943bb460f7c281.
