### ISSUE TITLE
输入‘大’之后会有奇怪的bug出现

### ISSUE THREAD

**Issue by cliuyang** [libpinyin/ibus-libpinyin#261]
首先输入一个‘大’
![image](https://user-images.githubusercontent.com/39078310/88746504-4e201a80-d17f-11ea-8dee-7d86ddb33e14.png)
然后就自动弹出来了个‘词典’
![image](https://user-images.githubusercontent.com/39078310/88746674-a9eaa380-d17f-11ea-893c-3f6c35438c06.png)

我的系统是ubuntu 20.04 LTS
IBus的版本是IBus 1.5.22

可能有用的信息：我之前是有大量输入过大词典之类的信息。

就在刚刚，我发现输入‘是’之后也有类似的现象，我猜测可能的原因是我打开了‘将每个输入’记录为新的词汇。但即使是这样，在输入完‘大’或者‘是’之后继续给出新的字词，也是有些不符合使用习惯。

**Comment by epico** [comment]
请关闭"显示建议"选项试试。

**Comment by cliuyang** [comment]
关掉之后不会再次出现这样的现象了。
我之前还以为这个建议是放在候选词里的建议。

**Comment by epico** [comment]
这个是联想功能...
