### ISSUE TITLE
webstorm 2020.2 无法输入中文

### ISSUE THREAD

**Issue by wangming-0215** [libpinyin/ibus-libpinyin#262]
在webstorm中输入中文的时候，候选框消失，然后就无法输入中文，重启webstorm后，依旧是上述状态，一直循环。

操作系统: ubuntu 20.04

![2020-07-31_14-12](https://user-images.githubusercontent.com/21071580/89006103-8d459b80-d338-11ea-8ccc-75c4a0e41b7b.png)

**Comment by epico** [comment]
请用英文给 ibus upstream 开个 issue.

**Comment by openalmeida** [comment]
@wangming-0215 我解决了这个问题：添加启动参数 -Drecreate.x11.input.method=true 解决的，今天找半天。

具体是添加到 bin/idea64.vmoptions中还是别的地方根据你的平台看，我的是Linux x64所以加到这里。
既然是用这个输入法的，你会用ps命令查看上文的启动参数是否传给了java，就不啰嗦了啊。

但是特喵的jb的老问题又回来了：输入法选字框不跟随鼠标，一直在左下角不动。我是intellij idea 2020.2带jbr版本，jb官方的jbr有了个小更新，但是先是没找到release note所以不知是否有相关更新……后觉得反正代码中中文写得少……而且已经半夜2点多，打了自己两耳光决定去睡觉了，又不是不能用！

**Comment by wangming-0215** [comment]
> @wangming-0215 我解决了这个问题：添加启动参数 -Drecreate.x11.input.method=true 解决的，今天找半天。
> 
> 具体是添加到 bin/idea64.vmoptions中还是别的地方根据你的平台看，我的是Linux x64所以加到这里。
> 既然是用这个输入法，默认你会用ps命令查看上文的启动参数是否传给了java，这就不啰嗦了啊。
> 
> 但是特喵的jb的老问题又回来了：输入法选字框不跟随鼠标，一直在左下角不动。我是intellij idea 2020.2带jbr版本，jb官方的jbr有了个小更新，但是先是没找到release note所以不知是否有相关更新……后觉得反正代码中中文写得少……而且已经半夜3点多，打了自己两耳光决定去睡觉了，又不是不能用！
> 
> @epico 但我对java不了解，字面意思看这参数是对输入法做重建？重启？……正好在Intellij idea 2020.2也遇到这个问题，用上面的方法后除了输入框不随光标外(升级到1.11.92没解决)，没发现别的问题。

添加启动参数的方法我上周也试过，但是没成功，今天用有可以了！！！ - 。-

**Comment by benxiaohair** [comment]
phpstrom 也是不能输入中文

**Comment by CoderYellow** [comment]
解决问题最好给个来源[来源](https://youtrack.jetbrains.com/issue/IDEA-23472)
