### ISSUE TITLE
双拼模式下是否有办法将显示真实输入的字符？

### ISSUE THREAD

**Issue by JiapengLi** [libpinyin/ibus-libpinyin#264]
双拼模式可以正常工作，我使用的是自然码，输入后将键值直接给转为全拼显示的。个人习惯使用显示真实输入的字符。

**Comment by epico** [comment]
为什么要显示真实输入的字符?

个人觉得输入的字符，很难读懂的。

**Comment by JiapengLi** [comment]
我这边的体验是感觉按下去的字符和显示的不一样就感觉有点奇怪。
可能这个需求确实有些过于个性化了。再其他一些输入法上面，像是微软自带的、老早的谷歌拼音都可以通过配置实现，输入和显示的一致。

**Comment by cupsday** [comment]
请问现在这个可以配置了吗？我觉得这个不算特别个性化，以双拼的方式阅读并不会特别难懂。显示真实字符的需求是在混合输入英文的时候需要，输入对应英文字母然后按shift就可以输入英文，但自动显示为全拼时反而需要将全拼转换为英文字母才知道输入了什么，这样更难读懂，或者需要shift上屏之后才知道输入什么，这过程中如果输入错误不利于纠错

**Comment by T-Oner** [comment]
同需要这个功能。有时候在中文输入法下想要直接输入英文，不显示真实输入就很难受，而且不显示真实输入纠错的时候也很难受

**Comment by epico** [comment]
Fixed in https://github.com/libpinyin/ibus-libpinyin .
