### ISSUE TITLE
ubuntu 20.04 could not work with Pinyin(Chinese)

### ISSUE THREAD

**Issue by benxiaohair** [libpinyin/ibus-libpinyin#267]
ubuntu 20.04
Intelligent Pinyin 1.11.1
when i use phpstorm ,it could not work with Chinese

**Comment by epico** [comment]
Please report this issue to ibus upstream in English, thanks!

**Comment by epico** [comment]
Do you use phpstorm from Ubuntu Snap?

**Comment by benxiaohair** [comment]
> Do you use phpstorm from Ubuntu Snap?

yes

**Comment by benxiaohair** [comment]
> Please report this issue to ibus upstream in English, thanks!

where is  "ibus upstream", please give me the url

**Comment by epico** [comment]
https://github.com/ibus/ibus

**Comment by epico** [comment]
Please also report to Ubuntu Snap, thanks!

**Comment by epico** [comment]
https://forum.snapcraft.io/categories

**Comment by gamesover** [comment]
very strange, this input does not work in all ubuntu 20.04 app, such as chrome/vs code...

but when I click windows icon to search app in Ubuntu, it works

**Comment by epico** [comment]
This issue may be some Ubuntu bug...

**Comment by epico** [comment]
I think built-in Ubuntu 20.04 app should work, or it may be some bug there.

**Comment by dyc12ii** [comment]
same issue. also not work in idea

> very strange, this input does not work in all ubuntu 20.04 app, such as chrome/vs code...
> 
> but when I click windows icon to search app in Ubuntu, it works

**Comment by epico** [comment]
Please open bug for Ubuntu Launchpad.
