### ISSUE TITLE
导入了个 11M 用户词库 ibus-libpinyin 的内存占用增加了 200+M, 这是正常现象吗? 

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#268]
词库[libpinyin-dict](https://github.com/broly8/libpinyin-dict)
内存占用`gnome-system-monitor`:
![image](https://user-images.githubusercontent.com/17917040/90613095-7f01e580-e23b-11ea-9057-d4c47c1410d1.png)

**Comment by epico** [comment]
可能用户数据有问题。

请删除 ~/.cache/ibus/libpinyin/user.conf， 重新导入试试。

**Comment by tuberry** [comment]
无效,删除后重启输入法占用恢复正常,再导入内存又上去了.

**Comment by epico** [comment]
请将 ~/.cache/ibus/libpinyin/ 的内容用 `ls -lh` 显示出来，谢谢！

**Comment by epico** [comment]
可能需要删除 user.conf, 注销后，重新登陆，再导入数据，等待一会儿再使用输入法。

最好在导入后十分钟内，不要注销或者重启。

**Comment by tuberry** [comment]
> 请将 ~/.cache/ibus/libpinyin/ 的内容用 ls -lh 显示出来，谢谢

![image](https://user-images.githubusercontent.com/17917040/90714913-57faf080-e2db-11ea-9888-b6d55ecda7bd.png)

> 可能需要删除 user.conf, 注销后，重新登陆，再导入数据，等待一会儿再使用输入法。
> 
> 最好在导入后十分钟内，不要注销或者重启。

经尝试也没有效果。你无法复现吗？

**Comment by epico** [comment]
前几天见过这个情况。

最近做过系统升级，昨天清理了 user 数据，到目前没有再发生。

我再用几天看看，看看会不会再发生。

**Comment by epico** [comment]
libpinyin 2.4.91 已发布，可以试一试。

**Comment by tuberry** [comment]
安装 libpinyin 2.4.91 后导入词库内存占用下降了一些,但是对比而言还是不少
![image](https://user-images.githubusercontent.com/17917040/91424226-17c3e100-e88c-11ea-9c0c-bdd9591123be.png)

**Comment by epico** [comment]
要不试一试 Berkeley DB.

注意，Kyoto Cabinet 和 Berkeley DB 的数据格式不兼容；使用前，可以考虑备份下用户数据...

**Comment by tuberry** [comment]
Arch 上和 BerkeleyDB 相关的包是这个 https://www.archlinux.org/packages/core/x86_64/db/ 不确定是不是编译所需的。
改了参数编译安装后，输入拼音出不了候选项。

**Comment by epico** [comment]
请删除 ~/.cache/ibus/libpinyin/user.conf , 再重新登录...

**Comment by tuberry** [comment]
这也尝试了， 同样只会显示 emoji 候选项。不确定是否是 [db](https://www.archlinux.org/packages/core/x86_64/db/files/) 版本的问题。我的编译选项：`  ./autogen.sh --prefix=/usr --with-dbm=BerkeleyDB --enable-libzhuyin`
