### ISSUE TITLE
以u开头进入五笔模式后无法切换为英文

### ISSUE THREAD

**Issue by t4rf9** [libpinyin/ibus-libpinyin#271]
在拼音模式下，如果希望将输入的字母串直接输入，可以通过Enter（不切换输入语言）或是Shift（直接切换为英文）。
但以u开头进入五笔模式后，就仅支持Enter的方式，使用切换输入语言的快捷键将无效。
希望能够增加在五笔模式下直接切换输入语言的特性。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .

现在关于笔画输入模式，可以使用 Shift 切换。

**Comment by epico** [comment]
ibus-libpinyin 1.11.93 is released.
