### ISSUE TITLE
[Feature Request] 输入后有候选项时隐藏 Lua 插件的说明提示文字

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#272]
目前是这样的(Gnome Shell):
![xl](https://user-images.githubusercontent.com/17917040/90897879-5ffc8280-e3f8-11ea-8adf-ea3504361463.gif)
候选项的总体长度不足时会留下不少空白,体验不是很好.既然都有候选项了提示说明的文字不要也罢.
笔画模式:
![bh](https://user-images.githubusercontent.com/17917040/90898559-56bfe580-e3f9-11ea-8d8e-597945ac7518.gif)
这样就挺好的.不知能不能支持一下 :)

**Comment by epico** [comment]
我觉得这个还是保留的好，第一次使用 Lua 扩展的话，这是用来说明如何使用 Lua 脚本的。
