### ISSUE TITLE
加入更多自定义选项

### ISSUE THREAD

**Issue by zq1997** [libpinyin/ibus-libpinyin#273]
希望能为输入法加入更多自定义配置，譬如
- 字体和字号和颜色，现在默认的字体感觉有点小
- 按v进入单词输入模式，个人感觉还是很不习惯
- 另外，自定义用户词典好像不支持emoji，是被过滤了？

**Comment by epico** [comment]
- 字体的话，不是 ibus-libpinyin 控制的，和 gnome, ibus 有关;

- 自定义用户词典仅仅支持普通短语，请考虑 Lua 脚本扩展;
