### ISSUE TITLE
如何完全关闭字词顺序自动调整

### ISSUE THREAD

**Issue by Dee-Ng** [libpinyin/ibus-libpinyin#274]
Archlinux Intelligent Pinyin 1.11.1

我已经关闭了Dynamic adjust the candidates order和remember every input as a phrase，并将Sort candidates by设置为Pinyin Length，但是发现字词还是会自动调整顺序，可能我输入方式比较守旧，习惯像旧微软全拼般硬性记住每个字词的位置，虽然现在并不影响平常的输入，但是我依然想知道怎么完全关闭这个词频调整功能。

**Comment by epico** [comment]
抱歉，这个功能 ibus-libpinyin 不支持。

清除用户数据，可以临时还原候选词顺序。

**Comment by Dee-Ng** [comment]
好吧，非常感谢您的回复，我先恢复默认设置尝试习惯，但是我依然希望能支持这个功能：）
