### ISSUE TITLE
拼音模式无法输入小写V

### ISSUE THREAD

**Issue by WhymustIhaveaname** [libpinyin/ibus-libpinyin#279]
拼音模式, 无论简体繁体, 都不能输入一个单独的小写V. 
比如我打a时,我会按a然后回车. 打其他字母也没有问题, 唯独到了V, 输入法提示"Please input the English word", 此时按回车就是打不了V.
这是什么神仙bug啊.

**Comment by epico** [comment]
Please input "vv", then press enter key.

`v` is for English mode.

**Comment by WhymustIhaveaname** [comment]
Thanks. I think this is counter-intuitive.
