### ISSUE TITLE
快捷键的设置

### ISSUE THREAD

**Issue by jimmy-song** [libpinyin/ibus-libpinyin#28]
希望能有对快捷键的设置，比如简体和繁体切换功能键的设置等等，这些快捷键与很多其他软件冲突，例如：Eclipse的格式排版的功能就是`CTRL+SHIFT+F`，同时在一些软件中无法使用输入法，必须要关闭软件再打开才有可能有效

**Comment by epico** [comment]
ibus-libpinyin 1.6.99.20150203 已发布，关闭 issue.

如果还有问题，请报 issue，谢谢。
