### ISSUE TITLE
How to Compile ibus-linpinyin in Oracle Linux (or RHEL) 8.2?

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#281]
Recently I moved from Ubuntu 20.04 to Oracle Linux 8.2, and realized the version of ibus-libpinyin in the latest Oracle Linux remains at 1.10.1.   Since Oracle Linux is SRPM-cloned after Red Hat, I am sure users of Red Hat would have experienced similar problems.

I reported my experience of how to successfully compile ibus-libpinyin 1.11.93 in the Chinese Ubuntu Forum; however, I have not been able to access the forum for at least a couple of weeks now.

I was wondering if anyone has successfully compiled ibus-libpinyin in Red Hat 8.2?

**Comment by epico** [comment]
Please update the libpinyin package first.

**Comment by ping-wu** [comment]
I am more interested in how to satisfy the dependencies in compiling both libpinyin and ibus-libpinyin.

**Comment by hillwoodroc** [comment]
You should build kyotocabinet for libpinyin first.

**Comment by ping-wu** [comment]
Because the version of ibus-libpinyin in Oracle/RHEL 8.2 outputs a decimal point as a Chinese period (”。”), it is unusable.
