### ISSUE TITLE
关于云拼音的一些想法

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#285]
1. [Google](https://github.com/libpinyin/ibus-libpinyin/blob/b6a2247e92b7ccf503d1d691976b7777dbb47620/src/PYPCloudCandidates.cc#L61) 云拼音对于有的用户来说是不可用的，建议用 [google.cn](https://www.google.cn/inputtools/try/) 提供的服务代替:
```c
static const char *GOOGLE_URL_TEMPLATE = "https://www.google.cn/inputtools/request?ime=pinyin&text=%s&num=%d";
```
2. [gsetting](https://github.com/libpinyin/ibus-libpinyin/blob/b6a2247e92b7ccf503d1d691976b7777dbb47620/data/com.github.libpinyin.ibus-libpinyin.gschema.xml#L224) 建议加上范围限制，以免用户设置无效值:
```xml
<key name="cloud-request-delay-time" type="i">
  <range min="200" max="2000"/>
  <default>600</default>
  <summary>Sending Cloud request with delay</summary>
</key>
```
3. 延迟是个很棒的想法，可以减少很多请求。但是对于输入来说，我觉着[预期的行为](https://felixc.at/2017/08/lets-try-a-new-pinyin-input-method-that-might-be-slightly-better-than-sunpinyin/)是在每次按键时更新，x10 毫秒级的延迟都可能使用户有卡顿的感觉。目前的行为看起来是用户停止输入时出云候选项，感觉上是比直接用云输入法还要‘卡’；

4. 希望云候选项与本地的候选项相同时合并或者说隐藏。另[加载的占位符](https://github.com/libpinyin/ibus-libpinyin/blob/b6a2247e92b7ccf503d1d691976b7777dbb47620/src/PYPCloudCandidates.cc#L49)在网络正常的情况下往往是一闪而过的，只会让用户感觉‘有点卡’，建议还是不加为好；

5. 谢谢!

**Comment by epico** [comment]
Google 云拼音是为国外用户准备的，国内推荐用 Baidu 云拼音。

已添加 `<range min="200" max="2000"/>` .

个人觉得还是尽量减少服务器的请求比较好。

**Comment by epico** [comment]
关于 3-4 项，如果云输入触发后，ibus-libpinyin 不显示任何状态；
如果有结果返回并且候选词不重复，ibus-libpinyin 添加云输入符号，并且插入云候选词；
在其他情况下，ibus-libpinyin 忽略返回结果，不显示内容。

这样修改如何？

**Comment by tuberry** [comment]
> Google 云拼音是为国外用户准备的，国内推荐用 Baidu 云拼音。

Google CN 国外用户应该也是能使用的。如果有其他方面的考虑，我觉得可以增加一个`Google CN`的输入源。

> 个人觉得还是尽量减少服务器的请求比较好。

同意。但目前感觉是输入后停下来‘等’云拼音出现，体验不是很好。能有折衷的办法更好 :)

> 这样修改如何？

这样挺好的。

**Comment by hillwoodroc** [comment]
> Google CN 国外用户应该也是能使用的。如果有其他方面的考虑，我觉得可以增加一个`Google CN`的输入源。

当前的代码还需要进行一些稳定的优化，会考虑这个提议。

> 同意。但目前感觉是输入后停下来‘等’云拼音出现，体验不是很好。能有折衷的办法更好 :)

这个延时设置隐藏在 dconf 里面，可以通过 dconf 修改。

**Comment by epico** [comment]
代码已经基本完成，欢迎帮忙测试。 :)

**Comment by epico** [comment]
关于新的提议，请开新的 issue, 谢谢！
