### ISSUE TITLE
IntelliJ IDEA无法输入中文

### ISSUE THREAD

**Issue by FaithALL** [libpinyin/ibus-libpinyin#289]
ubuntu 20.04
Intelligent Pinyin 1.11.1
IntelliJ IDEA 2020.2.2(Ultimate Edition)
当全拼输入2~3个汉字时，会被强行打断，然后就无法继续输入(也无法切换中英文)，并且汉字下会有下划线。

**Comment by epico** [comment]
请参考:

https://github.com/libpinyin/libpinyin/wiki/libpinyin-FAQ#question-how-to-fix-ibus-libpinyin-crash-or-exit-randomly

**Comment by FaithALL** [comment]
很感谢你的解答，但是这不起作用。即使输入法在IDEA里短暂崩溃了，也不影响其它窗口使用，这个问题我目前只在IDEA中发现。

**Comment by epico** [comment]
这样的话，请用英文报到 ibus upstream.

**Comment by epico** [comment]
如果其他窗口中能够使用的话，应该不是 crash 了。

**Comment by FaithALL** [comment]
使用ibus-rime没有问题，我想这是否是因为输入法本身的问题？

**Comment by epico** [comment]
ibus-rime 好像沒有用到 inline preedit 这个 feature.

**Comment by MrLeopard** [comment]
+1
pycharm-community-2020.2.3
ubuntu18.04
和楼主现象一致
===========================分割线===========================
最近pycharm刚启动就卡死，试了好多偏方才知两天前fcitx和sogou拼音导致的，于是放弃了sogou，换回了自带的Intelligent Pinyin。然后又遇到了这个问题。
idea全家桶和输入法干上了。

**Comment by epico** [comment]
建议你们用英文到 ibus upstream 去问问，这部分功能是 ibus 项目负责的。

**Comment by fantasy0v0** [comment]
这是我在YouTrack上看到的临时解决方案，对我自己是有效的，你们可以试试。

1. 点击菜单 "Help | Edit Custom VM options..."
2. 添加 -Drecreate.x11.input.method=true 到最后一行
3. 重启IDEA

**Comment by MintYale** [comment]
Fedora 33 的 IDEA社区版 也有此问题 症状一模一样 估摸着应该不是 Linux 方面的问题 可能还是输入法方面 或者更有可能是 JetBrains 方面的 Linux 版软件对 iBus 系列输入法中文的兼容处理问题 

IDEA 社区版也是在GitHub维护么？想去用英文问一下...其实类似这种问题主要还得靠国内的大佬们给上PR处理 因为国外开发者会中文的凤毛麟角除非是华裔基本不太有 很难去调试处理中文方面的BUG.

**Comment by alx696** [comment]
@FaithALL 可以试试 @fantasy0v0 的方法,我的问题跟你描述的一样,设置之后就正常了. 感觉就是IDEA的问题,各个版本都会或多或少出现问题.

操作系统: Ubuntu 20.04.1 LTS

IntelliJ IDEA:
```
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1952M
Cores: 4

Current Desktop: ubuntu:GNOME
```

**Comment by FaithALL** [comment]
@alx696 我已经把输入法暂时换成了ibus-rime了，虽然配置麻烦，但是没有上面的问题。打算等JetBrains或者ibus-libpinyin更新几个版本，没问题了再换过来。

**Comment by beiluve** [comment]
> 这是我在YouTrack上看到的临时解决方案，对我自己是有效的，你们可以试试。
> 
>     1. 点击菜单 "Help | Edit Custom VM options..."
> 
>     2. 添加 -Drecreate.x11.input.method=true 到最后一行
> 
>     3. 重启IDEA

厉害，该方法实测有效！
Ubuntu系统环境：
```txt
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
Intellij IDEA版本：
```txt
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-41-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1964M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alibaba.p3c.smartfox, com.chrisrm.idea.MaterialThemeUI
Current Desktop: ubuntu:GNOME
```

**Comment by beiluve** [comment]
> > 这是我在YouTrack上看到的临时解决方案，对我自己是有效的，你们可以试试。
> > ```
> > 1. 点击菜单 "Help | Edit Custom VM options..."
> > 
> > 2. 添加 -Drecreate.x11.input.method=true 到最后一行
> > 
> > 3. 重启IDEA
> > ```
> 
> 厉害，该方法实测有效！
> Ubuntu系统环境：
> 
> ```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.1 LTS
> Release:	20.04
> Codename:	focal
> ```
> 
> Intellij IDEA版本：
> 
> ```
> IntelliJ IDEA 2020.3.1 (Community Edition)
> Build #IC-203.6682.168, built on December 29, 2020
> Runtime version: 11.0.9.1+11-b1145.63 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Linux 5.8.0-41-generic
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1964M
> Cores: 4
> Registry: ide.balloon.shadow.size=0
> Non-Bundled Plugins: com.alibaba.p3c.smartfox, com.chrisrm.idea.MaterialThemeUI
> Current Desktop: ubuntu:GNOME
> ```

还需要在idea.sh文件顶部添加如下配置才能生效：
```sh
# ---------------------------------------------------------------------
# IntelliJ IDEA startup script.
# ---------------------------------------------------------------------

export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
```

**Comment by FlyingMcDonald** [comment]
> ubuntu 20.04
> Intelligent Pinyin 1.11.1
> IntelliJ IDEA 2020.2.2(Ultimate Edition)
> 当全拼输入2~3个汉字时，会被强行打断，然后就无法继续输入(也无法切换中英文)，并且汉字下会有下划线。

一样的问题
我的是 Arch linux + i3
下面是我找到的解决方法，对本人有用
https://youtrack.jetbrains.com/issue/IDEA-246833
需要注意的是如果Runtime选择不对，idea将不能启动。这时需要到`~/.config/JetBrains/<your idea version>/`内删除`jdks`目录，再重新打开idea即可。

**Comment by GuoYu-Peng** [comment]
我发现 Rstudio 也有这样的问题，切换到中文然而输入的英文。

**Comment by tlw-ray** [comment]
环境: 
  操作系统: 
      No LSB modules are available.
      Distributor ID:	Ubuntu
      Description:	Ubuntu 18.04.5 LTS
      Release:	18.04
      Codename:	bionic

  IDEA: 
       社区版2020.3

方案: 
    失败方案1: 
         参考: https://blog.csdn.net/beguile/article/details/88950729
         概述: 修改idea.sh
        添加: 
           export XMODIFIERS="@im=fcitx"
           export GTK_IM_MODULE="fcitx"
           export QT_IM_MODULE="fcitx"
    
    失败方案2: 修改jdk为oracle的jdk
        参考: https://blog.csdn.net/xc516410823/article/details/103501189
        概述: 基于或不基於方案1, 修改~/.profile ， 设置IDEA_JDK=${JAVA_HOME}
    
    成功方案: 
        參考: 樓上beiluve
        概述: 不需要更換jdk， 需要修改idea.sh
        1.在安装目录下的bin/idea.sh文件顶部中添加如下配置：
    
          # ---------------------------------------------------------------------
          # IntelliJ IDEA startup script.
          # ---------------------------------------------------------------------
          export XMODIFIERS="@im=ibus"
          export GTK_IM_MODULE="ibus"
          export QT_IM_MODULE="ibus"

**Comment by chaunceym** [comment]
把 idea 退回到旧版本, 我的 webStrom 2020 不能输入, 但是到 2019 就可以

**Comment by yuzhou721** [comment]
@fantasy0v0 谢谢大神 按照你的设置 已恢复使用

**Comment by hapihacking** [comment]
osx 13.2
goland2022.3.2
mac原生输入法
有同样中文字符无法输入问题（但是我只有双引号无法输入，其他字符都正常）
以上方案都已尝试，但是无法解决

**Comment by lovelock** [comment]
> @alx696 我已经把输入法暂时换成了ibus-rime了，虽然配置麻烦，但是没有上面的问题。打算等JetBrains或者ibus-libpinyin更新几个版本，没问题了再换过来。

我最近刚装了个Fedora 41，JB家的IDE里根本就没有中文输入模式。。。

**Comment by the-new-com** [comment]
try the "**Use the same source for all windows**" option, more info [https://youtrack.jetbrains.com/issue/IJPL-54540/Ubuntu-X11-switching-language-in-IDE-does-not-work-with-Switch-input-sources-individually-for-each-window-OS-option-enabled](https://youtrack.jetbrains.com/issue/IJPL-54540/Ubuntu-X11-switching-language-in-IDE-does-not-work-with-Switch-input-sources-individually-for-each-window-OS-option-enabled)

**Comment by licretey** [comment]
# ibus-x11导致的无法切换中文输入法

本来输入法好好的，折腾了一下给整崩溃了，排查下来是ibus-x11的问题

+ 首先需要确认 ibus-daemon 进程在，然后需要保证 ibus-x11 在

+ 可以写一个下面类似的脚本启动x11，然后配置autostart或者systemctl服务开机自启动即可

```shell
cat > ~/.local/bin/start-ibus-x11.sh <<'EOF'
#!/bin/bash
# 等 X 显示 + ibus-daemon 就绪，最多等 30 秒，再启动 XIM 桥
for i in $(seq 1 30); do
  if [ -n "$DISPLAY" ] && pgrep -x ibus-daemon >/dev/null; then break; fi
  sleep 1
done
exec /usr/libexec/ibus-x11
EOF
```
+ systemctl

```shell
cat > ~/.config/systemd/user/ibus-x11.service <<'EOF'
[Unit]
Description=IBus XIM bridge (ibus-x11) for Java/XIM apps
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/home/de/.local/bin/start-ibus-x11.sh
Restart=on-failure
RestartSec=3

[Install]
WantedBy=graphical-session.target
EOF 
```
