### ISSUE TITLE
[Feature Request] 固定云输入候选项位置以及将其加入本地词库

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#291]
固定位置的候选项更容易选取。

**Comment by hillwoodroc** [comment]
加入本地词库是什么意思？

**Comment by tuberry** [comment]
> 加入本地词库是什么意思？

候选词 > 将每个输入记录为新的词汇。

**Comment by hillwoodroc** [comment]
你说的本地词库是不是用户词库啊？如果是用户词库本来就有这个功能。

**Comment by epico** [comment]
加入本地词库的功能可能会引起 ibus-libpinyin 不稳定，这个得仔细考虑后再决定。

**Comment by tuberry** [comment]
这也是出于改善词库的考虑。不过一直用云输入的话效果也差不多，只是用户会缺失一部分自己的数据。如果为此牺牲稳定性有些得不偿失，不要也罢。

**Comment by epico** [comment]
好的，知道了。

**Comment by nagae-memooff** [comment]
同样希望固定云输入候选项位置，以前用fcitx的时候，云输入一般是固定在一个位置，可配置，即使没有结果或是重复、不可用的情况也会有占位。
我个人的习惯是第二候选词，也许其他人有其他的习惯。
而目前ibus-libpinyin的云输入可能随机出现在好几个位置，而且有时会在选择本地候选词之前突然插队，反而导致输入错误。

此外目前选词的时候，好像并不影响云输入的结果，云输入的返回结果似乎是作为一个整体的，更改了一部分猜测词语时，云输入的结果并没有随之更新。印象里以前fcitx的云输入是会随着定字而更新的。

**Comment by wsxy162** [comment]
上面的插队问题可能是网络情况不好，也许可以使用百度输入源来改善。
理想的话是不要固定位置，没有空候选项，且所有的候选词都能竞争排序。

**Comment by zsimple** [comment]
首先云输入这个功能真的很棒！这一点毋庸置疑，可以说拯救了被其他输入法惯坏了的普罗大众。

但是还是觉得云输入联想出来的词语，一旦用户选中并输入了，就可以自动加入用户词库，否则每次都要重新发送网络请求有点卡卡的。
毕竟如果手动输入一串拼音然后一个一个字选择后，下次再输入就可以快捷地再次选择，而如果这个次可以被云联想出来，却没办法通过简单的方法加入本地候选词，并且位置也无法自动调整到首位，岂不是很不便嘛。

**Comment by epico** [comment]
好像记录云输入的功能初步支持了。
