### ISSUE TITLE
切换中英时,不能上屏已经输入的字符

### ISSUE THREAD

**Issue by m1517** [libpinyin/ibus-libpinyin#293]
你好, 经常切换中英, 中文状态输入的字符, 在按下中英文切换键无法上屏,而且必须按回车或者删掉已经输入的内容后才能切换中英,及其不便.   希望能按下中英切换键直接上屏英文,不知能不能实现.     : )

**Comment by epico** [comment]
请问你使用的 ibus-libpinyin 版本是？

**Comment by m1517** [comment]
我用的是centos8 自带的 ibus-libpinyin 1.10.0 ,输入方案是小鹤双拼. .

**Comment by epico** [comment]
考虑试试 ibus-libpinyin 1.11.1 或者 Fedora 32?

记得好像修复过这个问题了。

**Comment by epico** [comment]
我在 Fedora 33 上测试正常。

**Comment by m1517** [comment]
恩恩,我正在安装最新的1.11.94 , 执行./configure  报错  
configure: error: Package requirements (
    ibus-1.0 >= 1.5.11
) were not met:
我电脑上ibus版本是 1.5.19-11.el8.x86_64
请问要修改那里呢?

**Comment by epico** [comment]
安装 ibus-devel 开发包...

**Comment by m1517** [comment]
你好,我又来了.    我已经把系统换成 fedora 33 了,  系统自带的版本是 1.11.93,  现在的问题是 只有 使用  shift 键作为中英切换健时才可以直接上屏英文.  其他的都不行.  麻烦测试下,  看看是那里的问题.

**Comment by epico** [comment]
目前，中英切换健仅支持一个按键。

**Comment by epico** [comment]
这个问题刚刚修正了，测试了一下，Shift/Ctrl/Alt 应该都可以工作的。

**Comment by epico** [comment]
ibus-libpinyin 1.12.91 is released, close issue.
