### ISSUE TITLE
Typing 'enen' does not give an expected candidate

### ISSUE THREAD

**Issue by zhangyuannie** [libpinyin/ibus-libpinyin#294]
`enen` is recognized as `e'nen`, which gives `鄂嫩` instead of a more expected word such as `嗯嗯`(`en'en`) in ibus-libpinyin 1.11.92 (fedora 32).
ibus-pinyin however correctly lists `嗯嗯` as the first candidate.

Is this the expected behaviour? If so, is there any way to configure it?

Thanks a lot!

**Comment by epico** [comment]
Fixed in https://github.com/epico/libpinyin .

**Comment by zhangyuannie** [comment]
Thank you!
