### ISSUE TITLE
Where does my imported dictionary go?

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#297]
I imported a dictionary of more than 8M in size, but didn't see any of the files related to ibus-libpinyin changed.  Where did my imported dictionary go?

I am running ibus-libpinyin 1.11.1.3 in Ubuntu 20.04, fully updated.

**Comment by epico** [comment]
I think you import that file before.

Please try to import one empty file, then import the file again.

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .

**Comment by ping-wu** [comment]
I will test the new patch in a virtual machine in a few days.

**Comment by epico** [comment]
Please try libpinyin 2.6.1 and ibus-libpinyin 1.12.1, thanks!

**Comment by ping-wu** [comment]
I am awaiting both packages to move into the Debian sid repo.

Look forward to it!

**Comment by ping-wu** [comment]
我可以编译 ibus-libpinyin-1.12.1，但 libpinyin-2.6.1 碰到 “configure: error: Cannot find Berkeley DB library version 5” 的问题，无法编译。

今天 Debian 12 的套件库已有libpinyin-2.6.1包，但前面的问题希望能帮忙解决。

**Comment by ping-wu** [comment]
加装 libdb-dev 跟 libdb++-dev 两个套件 （系统里已有db5.3-util)，libpinyin-2.6.1 已可编译。

**Comment by epico** [comment]
Cool

**Comment by epico** [comment]
ibus-libpinyin 1.12.91 is released, close issue.
