### ISSUE TITLE
关于libpinyin 的键盘映射问题

### ISSUE THREAD

**Issue by TangdizhiH** [libpinyin/ibus-libpinyin#299]
您好，我现在在pop_os上面使用libpinyin。唯一的问题就是我发现libpinyin会依赖于前面一个使用的输入法所留下来的键盘映射。因为个人使用的是德语和英语，所以在前一个使用德语键盘的情况下，z和y键的映射会跟着德语键盘的映射被改变（对调，因为德语键盘两者是对换的），我想请问开发者是否有办法固定这种映射，将它固定在英语键盘呢？谢谢！

**Comment by epico** [comment]
请自行修改 /usr/share/ibus/component/libpinyin.xml 文件。

将 `<layout>default</layout>` 修改为 `<layout>us</layout>` .

**Comment by TangdizhiH** [comment]
> 请自行修改 /usr/share/ibus/component/libpinyin.xml 文件。
> 
> 将 `<layout>default</layout>` 修改为 `<layout>us</layout>` .

哇 非常感谢你！！
