### ISSUE TITLE
fedora 21编译报错

### ISSUE THREAD

**Issue by 1dot75cm** [libpinyin/ibus-libpinyin#30]
由于opencc更新到了 1.0.2(更新了库版本 libopencc.so.2)，所以尝试基于新版opencc重新编译 ibus-libpinyin。但编译失败，报错如下。

opencc使用 https://copr.fedoraproject.org/coprs/mosquito/myrepo 源提供的rpm包，目前还不知怎么更新官方update源的包，就先暂时使用copr编译rpm包。

编译 https://github.com/epico/ibus-libpinyin/commit/5d445470457a3bbf3684ef782410ce9cafac57e3 、 https://github.com/epico/ibus-libpinyin/commit/82b89ae4b01f353664a44e833829f1633ffdfdd2 、 1.6.92 均失败。

\############ spec file ############
%build
export ACLOCAL_FLAGS="$ACLOCAL_FLAGS -I m4"
gnome-autogen.sh
%configure --disable-static \
           --enable-opencc \
           --disable-boost
make %{?_smp_mflags}
\############ end spec file ############

\# make -j4
......
  CXX      ibus_engine_libpinyin-PYSimpTradConverter.o
PYSimpTradConverter.cc: In member function 'void PY::opencc::convert(const gchar*, PY::String&)':
PYSimpTradConverter.cc:61:9: error: 'ucs4_t' was not declared in this scope
         ucs4_t *pinbuf = (ucs4_t *)in_ucs4;
         ^
PYSimpTradConverter.cc:61:17: error: 'pinbuf' was not declared in this scope
         ucs4_t *pinbuf = (ucs4_t *)in_ucs4;
                 ^
PYSimpTradConverter.cc:61:35: error: expected primary-expression before ')' token
         ucs4_t *pinbuf = (ucs4_t *)in_ucs4;
                                   ^
PYSimpTradConverter.cc:64:21: error: 'poutbuf' was not declared in this scope
             ucs4_t *poutbuf = (ucs4_t *)m_buffer;
                     ^
PYSimpTradConverter.cc:64:40: error: expected primary-expression before ')' token
             ucs4_t *poutbuf = (ucs4_t *)m_buffer;
                                        ^
PYSimpTradConverter.cc:66:94: error: 'opencc_convert' was not declared in this scope
             size_t retval = opencc_convert(m_od, &pinbuf, &inbuf_left, &poutbuf, &outbuf_left);
                                                                                              ^
Makefile:841: recipe for target 'ibus_engine_libpinyin-PYSimpTradConverter.o' failed
make[3]: *** [ibus_engine_libpinyin-PYSimpTradConverter.o] Error 1
make[3]: *** Waiting for unfinished jobs....
PYMain.cc: In function 'int main(gint, gchar**)':
PYMain.cc:179:5: warning: 'void g_atexit(GVoidFunc)' is deprecated (declared at /usr/include/glib-2.0/glib/gutils.h:242) [-Wdeprecated-declarations]
     g_atexit (atexit_cb);
     ^
PYMain.cc:179:24: warning: 'void g_atexit(GVoidFunc)' is deprecated (declared at /usr/include/glib-2.0/glib/gutils.h:242) [-Wdeprecated-declarations]
     g_atexit (atexit_cb);
                        ^
make[3]: Leaving directory '/home/mosquito/rpmbuild/BUILD/ibus-libpinyin-1.7.0git20141105/src'
......

**Comment by epico** [comment]
libpinyin-1.0.99.20150203 和 ibus-libpinyin 1.6.99.20150203 已发布，关闭 issue.

如果还有问题，请报 issue，谢谢。
