### ISSUE TITLE
如何输入这两组括号「」『』？

### ISSUE THREAD

**Issue by zungmou** [libpinyin/ibus-libpinyin#300]
好像用户字典导入功能无效，不知道有什么方法能够输入这两组括号？

**Comment by epico** [comment]
对于 「」，请使用 ` 符号模式来选择输入。

对于 『』，请使用 Shift + [] 来输入。

**Comment by zungmou** [comment]
感谢，是否有帮助文件可供参考？

**Comment by epico** [comment]
好像目前还没有帮助文件...

**Comment by ping-wu** [comment]
我按了 ` 符号，选择第4个候选字时，出现4，而不是 「。

ibus-libpinyin 版本 1.12 （Debian 11)。

**Comment by epico** [comment]
移动光标到第四个候选词，按空格键即可。

**Comment by NekoApocalypse** [comment]
必须用鼠标去选符号吗？感叹不太正常
有没有只用键盘就能选到的办法

**Comment by epico** [comment]
可以用上下移动键，来移动光标，用空格键来选中符号。

**Comment by ping-wu** [comment]
> 对于 「」，请使用 ` 符号模式来选择输入。
> 
> 对于 『』，请使用 Shift + [] 来输入。

怎么启动符号模式？

**Comment by epico** [comment]
在中文模式下，输入 ` ...
