### ISSUE TITLE
预输入文本未获得 st-entry 的输入焦点 (例如 Gnome Shell overview 搜索框)

### ISSUE THREAD

**Issue by tuberry** [libpinyin/ibus-libpinyin#301]
[st-entry](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/st/st-entry.c#L1157) 的提示文本获得焦点后会自动隐藏。 但开启 `compact` 在 Gnome Shell 的搜索框输入时，预输入文本与占位的文本重叠：

![libpinyin-compact](https://user-images.githubusercontent.com/17917040/104076266-8fe5de80-5250-11eb-9d55-6a7563972edf.png)

默认情况下：
![libpinyin-default](https://user-images.githubusercontent.com/17917040/104076131-11893c80-5250-11eb-8d72-8653db88cd92.png)

另外，貌似云输入候选项(`*厕所`) 与本地候选项(`厕所`) 仍然重复了。

`ibus-rime` 的相应模式:
![rime-preedit](https://user-images.githubusercontent.com/17917040/104076167-35e51900-5250-11eb-89ee-d358a4a0a6b4.png)

**Comment by epico** [comment]
我在 Fedora 33 上无法复现此问题...

如果是 ibus-rime 的问题，请报告到 Rime Input Method Engine upstream.
