### ISSUE TITLE
双拼模式下重复输入问题

### ISSUE THREAD

**Issue by wsxy162** [libpinyin/ibus-libpinyin#302]
系统环境：
openSUSE Tumbleweed
GNOME Wayland 3.38.2
Ibus 1.5.23    ibus-ibpinyin 1.11.94    libpinyin 2.4.92（自编译的 1.12.0+2.6.0 也有同样问题）

复现步骤：
1. 输入法模式设置为双拼（任一方案）
2. 切换到libpinyin输入法
3. 开启大写（Caps Lock），输入U或I或V

问题现象：
按下以上三个键后，这个窗口的输入就变成自动重复了，包括Backspace。

相关：
U、I、V和Shift组合都有快捷功能。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .
