### ISSUE TITLE
添加--disable-english-input-mode编译后中文模式下输入一些首字母会进入奇怪模式

### ISSUE THREAD

**Issue by alx696** [libpinyin/ibus-libpinyin#303]
环境信息:
* 系统版本: Ubuntu 20.04.1 LTS 5.8.0-38-generic x86_64
* libpinyin:  2.3.0-1build1
* 源码版本: 1.12.0
* 编译参数: `./autogen.sh --prefix=/usr --disable-lua-extension --disable-english-input-mode --disable-stroke-input-mode`

出现问题:
1. 首字母输入`v`或`u`或`i`后, 候选词界面变成一个气泡, 这在输入v, u, i开头的英文时很奇怪;
2. 首字母输入`f`时候选候选词会在f后面出现`|`, 这个表现也感觉很奇怪. 

![20210117_234433](https://user-images.githubusercontent.com/2497908/104848026-0ef8a800-591e-11eb-81ef-ff18804535d6.jpg)

![20210117_234408](https://user-images.githubusercontent.com/2497908/104848040-191aa680-591e-11eb-8000-c1e9cdc75d38.jpg)

**Comment by epico** [comment]
在设置对话框中，将表情符号选项关闭，结果会好一点。

**Comment by alx696** [comment]
> 在设置对话框中，将表情符号选项关闭，结果会好一点。

已经关闭了"显示建议"和"显示表情符号"选项, 感觉这个输入法历史功能包袱有点重.

像我是写代码, 需求就3个要点:
1. 符号能够锁定为半角, 不随中英文状态切换变化;
2. 中英文一键切换;
3. 兼容vscode, idea(android studio)这些常用IDE.

我前后试了谷歌拼音, 搜狗拼音, 百度拼音, 只有ibus-libpinyin以上3点做的好. 之前好像有中英文一键切换上屏问题, 现在解决了. 剩下的就是一些奇怪的快捷模式了, 希望能够改进.

你们用的是C和Python, 不熟也帮不上忙. 如果有Java, Go, Web(html, javascript, css)这几块能帮助改进的地方, 可以联系我.

**Comment by epico** [comment]
好的，这个问题修复起来比较花时间，等我有时间了，会看一下。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .

**Comment by alx696** [comment]
@epico 非常感谢你的付出!

第一时间下载编译安装了, vui不会出现v空候选了. 问题2不构成实质影响, 应该是输入的拼音不存在, 所以就竖线分开了.
