### ISSUE TITLE
user dictionary import

### ISSUE THREAD

**Issue by chenshanhai-mc** [libpinyin/ibus-libpinyin#304]
想导入用户字典来挂载小鹤双拼的形码, 导入不生效.

版本 1.11.1

**Comment by epico** [comment]
目前，只支持导入拼音和词语。

**Comment by chenshanhai-mc** [comment]
> 目前，只支持导入拼音和词语。

```
接口 jpkg
借口 jpkg 2
```

这样不支持吗

**Comment by epico** [comment]
jpkg 不是拼音...

**Comment by chenshanhai-mc** [comment]
> jpkg 不是拼音...

后续会考虑支持吗, ibus-pinyin现在是可以的

**Comment by epico** [comment]
请问这个功能在 ibus-pinyin 哪里？

**Comment by chenshanhai-mc** [comment]
> 请问这个功能在 ibus-pinyin 哪里？

ibus-pinyin的用户字典可以直接编辑, 格式跟libpinyin不一样, 但是支持字母随便组合
![image](https://user-images.githubusercontent.com/25859421/105452849-fdb2f100-5cb9-11eb-8f08-179c7fb021ba.png)

**Comment by epico** [comment]
最近，我将 ibus-libpinyin Lua 脚本功能作了一点扩展，在下一个版本中，可以用如下的 Lua 脚本来支持这个功能。
URL: https://github.com/epico/ibus-libpinyin

```Lua
_XHE_TABLE = {
  ['ann'] = {"按钮"},
  ['jpkg'] = {"接口", "借口"},
}

function getTablePhrase(input)
  local ret
  ret = _XHE_TABLE[input]
  return ret
end

ime.register_trigger("getTablePhrase", "自定义短语", {'*'}, {})
```

**Comment by Xiya-Duan** [comment]
你好，我最近遇到同样无法导入用户辞典的问题。
版本：1.12
系统：manjaro 
内核：5.9.16-1-MANJARO

准备导入18k条数据，但是点击导入后没有反应

**Comment by epico** [comment]
请问你的 ibus-libpinyin 和 libpinyin 版本号是？

**Comment by Xiya-Duan** [comment]
> 请问你使用的 ibus-libpinyin 和 libpinyin 版本号是？

谢谢答复。
ibus-libpinyin 的版本是 1.12.0
libpinyin的版本是2.6.0

**Comment by ping-wu** [comment]
> 最近，我将 ibus-libpinyin Lua 脚本功能作了一点扩展，在下一个版本中，可以用如下的 Lua 脚本来支持这个功能。

请问如何在 ibus-libpinyin 里使用这个 Lua 脚本？

**Comment by epico** [comment]
在设置对话框里，有“用户Lua脚本的选项”，点击编辑按钮即可。

**Comment by ping-wu** [comment]
目前好像无法输出特殊符号？ 下列 lua 脚本无效：

. . .
#the following script was added on 2021.06.27
_XHE_TABLE = {
  ['bfb'] = {"‰", "‱"},
  ['sjx'] = {"∆", "∇"},
}
. . .

**Comment by ping-wu** [comment]
> > 请问你使用的 ibus-libpinyin 和 libpinyin 版本号是？
> 
> 谢谢答复。
> ibus-libpinyin 的版本是 1.12.0
> libpinyin的版本是2.6.0

我在 Debian 11 里没有问题。

**Comment by epico** [comment]
目前，只支持一个候选词，比如 `['ann'] = {"按钮"}` 。

请等待 ibus-libpinyin 1.12.1 版本发布...

**Comment by ping-wu** [comment]
> 
> ime.register_trigger("getTablePhrase", "自定义短语", {'*'}, {})
> ```

请问最后这一行需不需要？

**Comment by epico** [comment]
需要。

**Comment by ping-wu** [comment]
1.12.1 如果能利用 lua os.date/os.time 增加日期/时间的输出功能，更佳。希望能考虑。

**Comment by epico** [comment]
Lua os.date/os.time 这个功能好像有。

**Comment by ping-wu** [comment]
ibus-pinyin 有这个功能：

![Screenshot from 2021-06-28 20-13-38](https://user-images.githubusercontent.com/21325422/123746607-92afac80-d84d-11eb-9f5b-b5cf1d68dbd4.jpg)

**Comment by epico** [comment]
试试 `irq` 和 `isj` .

**Comment by ping-wu** [comment]
👍👍👍

**Comment by epico** [comment]
Please try libpinyin 2.6.1 and ibus-libpinyin 1.12.1, thanks!
