### ISSUE TITLE
build failed on ubuntu 16.04

### ISSUE THREAD

**Issue by nagae-memooff** [libpinyin/ibus-libpinyin#305]
Build failed since 1.11.93 on ubuntu 16.04. 
It seems cause by old version libgio without some function such as"g_settings_set_int64 ".
what can I do for it?

 $> make
...
make  all-recursive
make[1]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94' に入ります
Making all in data
make[2]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/data' に入ります
Making all in icons
make[3]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/data/icons' に入ります
make[3]: 'all' に対して行うべき事はありません.
make[3]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/data/icons' から出ます
make[3]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/data' に入ります
make[3]: 'all-am' に対して行うべき事はありません.
make[3]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/data' から出ます
make[2]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/data' から出ます
Making all in src
make[2]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/src' に入ります
make  all-am
make[3]: ディレクトリ '/software/source_code/ibus-libpinyin-1.11.94/src' に入ります
  CXX      ibus_engine_libpinyin-PYConfig.o
PYConfig.cc: In member function ‘gboolean PY::Config::write(const gchar*, gint64)’:
PYConfig.cc:165:55: error: ‘g_settings_set_int64’ was not declared in this scope
     return g_settings_set_int64 (m_settings, name, val);

**Comment by epico** [comment]
Please consider to upgrade glib2, or try lower version of ibus-libpinyin...

**Comment by nagae-memooff** [comment]
> Please consider to upgrade glib2, or try lower version of ibus-libpinyin...

这似乎是引入network dictionary 之后产生的问题，请问是否有可能忽略相关功能，单独把云输入相关的代码cherry pick回1.11.92？ 

或是将调用 g_settings_set_int64 的代码修改为调用其他可用的方法？（我尝试修改g_settings_set_int64 为 g_settings_set_int，编译成功，但运行期会崩溃，gnome-session提示 received a NET_CURRENT_DESKTOP message from a broken (outdated) client who sent a 0 timestamp.）

**Comment by nagae-memooff** [comment]
上面提到的，修改代码后的运行期崩溃，似乎与导入用户词库有关。清空用户词库后，产生新词也不会崩溃了，并能正确记住新词。

此外，我发现实际崩溃的原因并非上面的警告，而是另一个错误。而上面提到的警告并不会直接导致输入法崩溃。由于现在没有复制环境，示例如下：
kernel:  ibus-engine-lib[9200]: segfault at 0 ip 00007xxxxxxxx sp 00007xxxxxxx  error 4 in libc-2.23.so


看起来是发生在落库新词的时候。大致的现象为：
1、输入一些词库里本来不存在的词
2、输入法猜测的词语不符合预期，用户按数字键逐个组词
3、在确定最后一个词后，输入法崩溃，落到输入框里的是用户最后输入的数字

输入词库中原本存在的词语似乎不会产生段错误。

**Comment by epico** [comment]
感觉使用了 libpinyin 的非稳定版本...

**Comment by nagae-memooff** [comment]
> 感觉使用了 libpinyin 的非稳定版本...

抱歉，忘了说明，我现在使用的是最新的master分支，实际是1.12.0，而非标题里的1.11.93。

标题里说1.11.93，是因为昨天使用1.12.0编译失败，我往后回退版本测试编译的时候，退到1.11.94、1.11.93都失败，所以标题里只说了1.11.93。
1.11.92可以正常编译，我用了有几个月了，没有出现导入词库后崩溃的问题。

**Comment by epico** [comment]
推荐使用 libpinyin 的稳定版本。
