### ISSUE TITLE
[Feature Request] Option to disable embed preedit text

### ISSUE THREAD

**Issue by akiirui** [libpinyin/ibus-libpinyin#306]
A options to disable embed preedit text into application window.

Because embed preedit text is have lag when typing.

`ibus-setup - General - Embed preedit text in application window` option not work with libpinyin.

**Comment by epico** [comment]
Which desktop environment do you use?

**Comment by akiirui** [comment]
> Which desktop environment do you use?

GNOME 3.38

I have test between enable embed preedit text or not at another ibus ime, big different for feel.

**Comment by epico** [comment]
In GNOME desktop, the ibus panel UI is from gnome-shell.

Sorry, some option is not used in GNOME desktop...

**Comment by epico** [comment]
Which application is affected?

**Comment by akiirui** [comment]
> Which application is affected?

emm, `Embed preedit text in application window` mean:
![Screenshot from 2021-01-26 14-57-50](https://user-images.githubusercontent.com/3736910/105811237-48e54080-5fe7-11eb-8f09-b07cf64fbefb.png)

All applications have input lag when typing.

**Comment by epico** [comment]
Please consider to test with new user account, sometimes data corruption can also have input lag.

If all applications have input lag issue, then please open an issue for your Linux distrubtion, it may be some problem in the OS.

**Comment by akiirui** [comment]
Yep, new user is same for me.
I found

https://ibus.github.io/docs/ibus-1.5/IBusEngine.html#ibus-engine-update-preedit-text
https://ibus.github.io/docs/ibus-1.5/IBusEngine.html#ibus-engine-show-preedit-text
https://ibus.github.io/docs/ibus-1.5/IBusEngine.html#ibus-engine-hide-preedit-text

I will fork and try to add this option.
Thanks for reply.

**Comment by epico** [comment]
Implemented in https://github.com/epico/ibus-libpinyin .
