### ISSUE TITLE
Surgestions aren't shown

### ISSUE THREAD

**Issue by Meresmata** [libpinyin/ibus-libpinyin#307]
Hi I am using using ibus-libpinyin on a TuxedoOS which is derived from Ubuntu Budgie.

I added intelligent pinyin via the Region and Languages setting, but the surgestions  aren't shown, even though the box is checked.

Methoded I tried:
1. removed intelligent pinyin and also removed the settings files in the ibus intelligent pinyin subfolder. Than reinstalled the intelligent pinyin. Result: Same as before
2. in CLI: reset I bus. Result: same as before.

I tried it with other pinyin options for ibus, too. None of them show the surgestions.

**Comment by epico** [comment]
Please try the following command:

```bash
export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
```

Then run gedit to see if it works.

**Comment by Meresmata** [comment]
Thanks at @epico,

I did as you wrote, but nothing changed.
Even not after restarting. Are there some important files, or outputs of a command, I shall post?

**Comment by Meresmata** [comment]
Looks like, it was something to do with the budgie desktop, or how it is configured. I installed Xubuntu ontop. I have no problem there...

**Comment by epico** [comment]
Please report to Ubuntu Launchpad, too.
