### ISSUE TITLE
智能拼音卡顿

### ISSUE THREAD

**Issue by 13229896070** [libpinyin/ibus-libpinyin#308]
Ubuntu 20.04   ibus-libpinyin   (1.11.1-3)  apt最新版
配置:i7-6700k 索泰-1660s
问题:
1.卡顿，莫名其妙的卡，30分钟卡2次左右，视频倒是没停顿，就是打不出字，卡顿期间鼠标可以移动，但不能执行其它命令
2.换成英文键盘就不会这样了
3.因为卡顿不能看任务进程，不知怎么查具体原因

**Comment by ping-wu** [comment]
You can try this patch:

https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-libpinyin

**Comment by epico** [comment]
请尝试创建一个新用户，看看这个问题是否还存在。

**Comment by 13229896070** [comment]
> 请尝试创建一个新用户，看看这个问题是否还存在。

新建用户，重装系统也不能解决，包括换显卡驱动，问题依旧
win10用了几年没什么问题
所以怀疑是cpu或者gpu和系统 的兼容性？

**Comment by epico** [comment]
要是方便的话，可以试试 Fedora 33 Workstation Live CD 或者 USB，看看是否也存在问题。

**Comment by History-exe** [comment]
Have the same problem.

**Comment by 13229896070** [comment]
> 要是方便的话，可以试试 Fedora 33 Workstation Live CD 或者 USB，看看是否也存在问题。
@epico 
谢谢，有空我再试吧

> Have the same problem.
 @History-exe  
目前我的解决办法是：用智能拼音 的时候，将英语(美国)键盘删除
这是另一种办法(我还没尝试)：

**Comment by epico** [comment]
@History-exe Please describe more about how to reproduce it on Fedora, thanks.

**Comment by History-exe** [comment]
> @History-exe Please describe more about how to reproduce it on Fedora, thanks.

就是使用的时候，在快速切换时会莫名导致系统界面卡住，然后就会出现一些比较奇怪的情况：

1. 比如打完字之后，输入了2个字，光标不是停留在最后那个字的后面，而是**出现在了两个字的中间**。
2. 在某些应用中，打一个字，**莫名自动输入两个字**，这两个字都是重复的。
3. 在ubuntu20.04.2系统中，使用默认的快捷键（win + 空格）切换输入法时，屏幕右上角指示输入法状态的图标不是平时正常的“拼”，而是变成了“中”，这时候能正常输入中文，但是按shift后，屏幕右上角那个图标不会变为“英”，但英文字母此时还可以正常输入。

**Comment by epico** [comment]
@History-exe 请问您使用的 Linux 发行版是？

目前，我还无法在 Fedora 33 上复现......

**Comment by History-exe** [comment]
Ubuntu20.04.2

**Comment by SumenSeven** [comment]
Same problem. And I found this in `/var/log/syslog`.
`IBUS-WARNING **: Process Key Event failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code24: Timeout was reached`

**Comment by epico** [comment]
@SumenSeven It seems this issue is related with ibus.

Please consider to report this issue to Ubuntu Launchpad.

**Comment by gmemcc** [comment]
same problem on ubuntu 20.04 tls

**Comment by Jesse3692** [comment]
I hava the same problem on ubuntu 20.04 lts

**Comment by ecstayalive** [comment]
same problem, so i am trying to upgrade it to see whether the problem is still there

**Comment by lulinfeng** [comment]
我也曾被这个问题困扰了很久，现在临时规避办法是：
首先新建一个重启ibus的命令
`vim /usr/local/bin/restart_ibus`
```
#!/bin/sh
killall ibus-daemon
sleep 0.2
ibus-daemon -d
```
`chmod +x /usr/local/bin/restart_ibus`

然后在设置中新建一个restart_ibus的快捷键
![image](https://user-images.githubusercontent.com/5935887/120581310-2ebbe300-c45d-11eb-8174-e63cb9a7f73b.png)

再次出现无法输入的时候，通过快捷键重启ibus即可恢复。

**Comment by epico** [comment]
@lulinfeng 用 `ibus restart` 会不会安全点？

**Comment by ecstayalive** [comment]
ok, after i complied the source to install the newest one , and the problem was still there. I thought the previous cache may have some affection, so i used the command : rm -rf ~/.cache/ibus/libpinyin ,  and it worked surprisingly.

**Comment by ping-wu** [comment]
> 用 `ibus restart` 

Worked well for me.  

Learned something new today!

**Comment by lihexin88** [comment]
> ok, after i complied the source to install the newest one , and the problem was still there. I thought the previous cache may have some affection, so i used the command : rm -rf ~/.cache/ibus/libpinyin , and it worked surprisingly.

It worked for me !
