### ISSUE TITLE
An option to make the font bigger 

### ISSUE THREAD

**Issue by mittenchops** [libpinyin/ibus-libpinyin#309]
I have a small font as my default, but it would be nice to see a section in 
Preferences > General > UI 
to set/increase the font size of the candidates specifically

**Comment by wsxy162** [comment]
ibus-setup has this option, but it doesn't work in GNOME. You can use a specific gnome extension to config the font.

**Comment by epico** [comment]
For gnome-shell, please try the following extension.

URL: https://extensions.gnome.org/extension/1121/ibus-font-setting/
