### ISSUE TITLE
如何输入希腊字母？

### ISSUE THREAD

**Issue by Endle** [libpinyin/ibus-libpinyin#31]
希望能加入这一功能，谢谢

**Comment by epico** [comment]
ibus-libpinyin 1.6.99.20150203 已发布，关闭 issue.

如果还有问题，请报 issue，谢谢。

**Comment by epico** [comment]
lua script 扩展示例:

_MAPPING_TABLE = [[
a α
b β,γ
c δ,ε,ζ
]]

_MAPPING = ime.parse_mapping(_MAPPING_TABLE, "\n", " ", ",")

function Lookup(input)
  if _MAPPING[input] then
    return _MAPPING[input]
  else
    error("Invalid argument")
  end
end

ime.register_command("lp", "Lookup", "希腊字母")
