### ISSUE TITLE
请问怎么删除错误上词

### ISSUE THREAD

**Issue by ys543437872** [libpinyin/ibus-libpinyin#311]
如果错误添加了新词汇应该怎么清除

**Comment by epico** [comment]
如果是前 1-3 个候选词的话，可以考虑多输入几次，应该会消失或者成为后边的候选词。

对于后边的候选词，可以试试按 Ctrl-Shift-d 试试。

**Comment by epico** [comment]
还可以通过清除用户词典的方式来清除所有的历史输入记录。

**Comment by ys543437872** [comment]
好的,感谢
