### ISSUE TITLE
centos8 ibus-libpinyin 不能弹出首选项设置窗口

### ISSUE THREAD

**Issue by dogbaha** [libpinyin/ibus-libpinyin#313]
![2021-03-25 11-16-36 的屏幕截图](https://user-images.githubusercontent.com/43167127/112413824-d16c2d00-8d5b-11eb-8892-c0206c88774b.png)
点击以后没有反应

**Comment by epico** [comment]
方便的话，请看看 RHEL 8.3 有这个问题吗？

**Comment by dogbaha** [comment]
> 方便的话，请看看 RHEL 8.3 有这个问题吗？

我的版本是centos8，

**Comment by dogbaha** [comment]
问题被我解决了，过程如下：
我找到了ibus的安装程序，在 /usr/bin/下面，有一个 ibus-setup的程序，执行就会弹出安装界面，但是因为我在机器上安装了python3.8 而且设置了软链接python->python3.8 导致了setup程序不能运行，解决办法很简单，要么修改setup程序，要么把软链接删去，两种办法都行，实行起来难度差不多，随便哪个都行。

**Comment by epico** [comment]
推荐删除软连接，问题已解决，关闭 issue.
