### ISSUE TITLE
Ubuntu 20.04 Pycharm  11.0.10

### ISSUE THREAD

**Issue by anjiel** [libpinyin/ibus-libpinyin#314]
在pycharm使用中文会出现下划线, 切换过程中会莫名其妙删除一些之前输入的字符

**Comment by epico** [comment]
Please report this issue to ibus and PyCharm in English, too.

**Comment by epico** [comment]
请参考 #289 .

**Comment by anjiel** [comment]
感谢回复，已解决


 
---Original---
From: "Peng ***@***.***&gt;
Date: 2021/4/6 11:24:09
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [libpinyin/ibus-libpinyin] Ubuntu 20.04 Pycharm  11.0.10 (#314)




 
请参考 #289 .
