### ISSUE TITLE
fedora34内置版本没有云输入

### ISSUE THREAD

**Issue by yuw0360** [libpinyin/ibus-libpinyin#315]
fedora34内置版本设置里找不到云输入，ubuntu和manjaro版的都有

**Comment by ljhui** [comment]
看了下fedora 34 ibus-libpinyin包的[spec文件](https://src.fedoraproject.org/rpms/ibus-libpinyin/tree/f34), 里面编译时configure没有启用--enable-cloud-input-mode,你可以下载spec文件自己编译一个自用,注意处理依赖,我自己重新编译一个自己云输入版,感觉没什么提升,最多只出现一个云输入的词汇,有时本地和云两个相同的词汇都出现了.

**Comment by epico** [comment]
对于 Fedora 34, 可以试一试 Fedora copr 中的 ibus-libpinyin, 这个是打开了云输入的。

URL: https://copr.fedorainfracloud.org/coprs/pwu/cloud-input/

**Comment by ping-wu** [comment]
我从 1.12.1 master 编译出来的包也是没有运输入选择。

Debian 11 里的版本（1.12.0）有运输人。

**Comment by epico** [comment]
请启用 `--enable-cloud-input-mode` 选项。

**Comment by ping-wu** [comment]
从 GitHub 下载的 1.12.1-master 编译后没有这个选项。（Debian 11 里的 1.12 版本则有这个选项。）

**Comment by ping-wu** [comment]
If I added this option then the compilation would fail.

Oh Wait!  It looks like the cloud-input option is already built in
(Preference 里没有云词库选项，但输入法里已经有了）

**Comment by epico** [comment]
出于安全方面的考虑，Fedora 里的 ibus-libpinyin 在编译的时候，没有打开云输入。
