### ISSUE TITLE
Cannot Select Pinyin From List

### ISSUE THREAD

**Issue by crimsonpython24** [libpinyin/ibus-libpinyin#317]
I can't select "Pinyin" from the dropdown list as shown: there is the name of the dropdown, but there are no actual choices for me to click on.

![Screenshot_20210507_010417](https://user-images.githubusercontent.com/76871022/117337923-8a339900-aed0-11eb-8273-c0b39b855c09.png)

I am currently running the latest Arch build. If you need additional details, please comment.

Apologize for unable to type in Chinese at this moment

**Comment by crimsonpython24** [comment]
I executed using `./autogen.sh`, `make`, `sudo make install`, and `ibus-daemon -r -d -x` (the last one to restart the ibus service) and installed missing libraries along the way. Is there anything that I missed?

**Comment by epico** [comment]
Please choose "Chinese" language first, then choose the input method.

URL: https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

**Comment by crimsonpython24** [comment]
![image](https://user-images.githubusercontent.com/76871022/117389513-11a7f900-af1f-11eb-9b18-d9f00e58c0b4.png)


Somehow, there is only the Zhuyin method. I will try to re-clone and configure everything again and update this thread as soon as possible.

**Comment by crimsonpython24** [comment]
![image](https://user-images.githubusercontent.com/76871022/117390063-115c2d80-af20-11eb-80d9-c516150eb580.png)

What's weird is that the IBus system suddenly switched to Chinese while the rest of my system is in English... regardless, I cloned the repo and restarted iBus but I can't get Pinyin to show up, per the screenshot above.

My abbreviated konsole output (I'm on KDE/Arch Linux):
```bash
[crimsonpython24@thinkpadx1c ~]$ sudo pacman -Rcns ibus 
[sudo] password for crimsonpython24: 

[crimsonpython24@thinkpadx1c ~]$ git clone https://github.com/libpinyin/ibus-libpinyin.git
Cloning into 'ibus-libpinyin'...


[crimsonpython24@thinkpadx1c ~]$ sudo nano /etc/environment
[crimsonpython24@thinkpadx1c ~]$ sudo nano ~/.config/autostart/ibus-daemon.desktop
'
[crimsonpython24@thinkpadx1c ~]$ sudo pacman -S ibus      
resolving dependencies...
looking for conflicting packages...

Packages (4) dbus-python-1.2.16-4  gobject-introspection-runtime-1.68.0-1
             python-gobject-3.40.1-1  ibus-1.5.24-1

[crimsonpython24@thinkpadx1c ~]$ ibus-setup

(ibus-setup:2406): Gtk-WARNING **: 10:35:36.671: Locale not supported by C library.
        Using the fallback 'C' locale.
Using the fallback 'C' locale

(ibus-setup:2406): GLib-GIO-CRITICAL **: 10:35:42.264: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

**Comment by crimsonpython24** [comment]
Nevermind, the link above you sent solved everything. 多谢你的帮忙！
