### ISSUE TITLE
取消v进入英文模式的选项

### ISSUE THREAD

**Issue by WhymustIhaveaname** [libpinyin/ibus-libpinyin#318]
这个v非常misleading，已经有不止一位朋友向我吐槽这个问题了。而且这个v完全看不到有什么方便的地方，他竟然存在了这么就很难理解。如果开发者硬是觉得这个方便的话，也应该是把它改为默认关闭而不是开启。

这是我对本项目最后的一点建议，因为我已经忍无可忍要换别的输入法了（v只是压死骆驼的最后一根稻草，拼音联想太弱是另一个主要原因）。希望项目越来越好。

**Comment by epico** [comment]
这个功能可以在编译时关闭。

**Comment by PeterlitsZo** [comment]
> 这个功能可以在编译时关闭。

请问不可以在 GUI settings 中或者在配置文件中（如果有的话）提供选项吗？

**Comment by PeterlitsZo** [comment]
> 最近比较忙，等有了时间，我会看一下这个问题。

或者考虑一下 #334 怎么样～

**Comment by WhymustIhaveaname** [comment]
我认为，把其作为一个选项挺好，但是默认选项应当是大部分人的选择。我周围的四五位使用 Linux 的朋友都不喜欢这个功能，所以应当是可选开启“v进入英文模式”功能。或者可以在哪里搞一个更大规模的投票。

谢谢！开发者辛苦了！

**Comment by epico** [comment]
目前是打算在 dconf 中，先提供下隐藏设置。

等有了时间，再加入到 GUI 设置中。

**Comment by epico** [comment]
刚刚在 dconf 里边加入了这个选项。

URL: https://github.com/libpinyin/ibus-libpinyin

**Comment by WhymustIhaveaname** [comment]
谢谢！请问 dconf 在哪里？需要重新编译安装吗？

**Comment by epico** [comment]
是的，用 dconf-editor 编辑。

**Comment by epico** [comment]
需要重新编译安装。

**Comment by WhymustIhaveaname** [comment]
非常抱歉，我自行编译安装失败了，请问有教程吗？

我参考了#132，我装了一些依赖，之后`.autogen.sh`，一段输出之后报错
```
configure: error: Package requirements (
    ibus-1.0 >= 1.5.11
) were not met:

Package 'ibus-1.0', required by 'virtual:world', not found
```
但是我的`ibus`版本似乎是够高的
```
$ ibus version
IBus 1.5.23
```
我发现这和 #73 的问题一样，我的系统是 Fedora33。

**Comment by epico** [comment]
请参考 https://github.com/libpinyin/ibus-libpinyin/wiki/Installation#build--install-ibus-libpinyin .

Fedora 33 的话，可能不需要重新编译 libpinyin .

需要安装 ibus-devel 包。

dconf 修改后，不需要重新编译的。

**Comment by epico** [comment]
Fixed in https://github.com/libpinyin/ibus-libpinyin .

**Comment by WhymustIhaveaname** [comment]
感谢！我终于会自己编译安装了。照着这个安装说明装：https://github.com/libpinyin/ibus-libpinyin/wiki/Installation
一年前碰到的错误
```
configure: error: Package requirements (
    ibus-1.0 >= 1.5.11
) were not met:

Package 'ibus-1.0', required by 'virtual:world', not found
```
应该这么解决：首先它说少ibus，那就 `dnf search ibus`，然后找到带 devel 后缀的最像的安上，devel 是开发版带源码的之后编译需要。还将会少很多包都这么解决，就能 `./configure --prefix=/usr` 了。

然后 `make clean`、`make`、`sudo make install`就行了。心情好的话可以加上需要的功能，比如`./configure --prefix=/usr --enable-cloud-input-mode --disable-english-input-mode`

**Comment by WhymustIhaveaname** [comment]
另一种解决方案：[Fedora 中文输入法](https://github.com/WhymustIhaveaname/Notes/blob/main/README.md#fedora-%E4%B8%AD%E6%96%87%E8%BE%93%E5%85%A5%E6%B3%95)

**Comment by liinyun** [comment]
现在已经2024年快7月份了，这个问题居然还存在。不是已经有方法了吗，开发者自己改一下很快的。偏要这么折腾。我不是批评人家，人家做这个也不容易。只是很不能理解，这个问题大家都是几行代码就解决了。他直接加上这么几行就方便很多的。是信任大家的水平嘛😎

**Comment by epico** [comment]
这个选项在首选项对话框的用户数据页面已经有了。
