### ISSUE TITLE
希望改进上词规则

### ISSUE THREAD

**Issue by yuw0360** [libpinyin/ibus-libpinyin#319]
1. 超级简拼上词有点慢，
如输入我的名字：王昱wangyu,
第二次输入wy在第十一页才找到，
希望可以输入过一次后，超级简拼输入可以出现在第一个或第一页；

2. 云输入词汇不会被记录，（已开启将每个输入记录为新的词汇)
如输入kmns夸美纽斯,
第二次输入kmns仍是云输入显示，并未被加入字典

**Comment by epico** [comment]
1. 请用全拼输入几次，简拼是不会记录的。

**Comment by epico** [comment]
2. 对于云输入，可以试试 Fedora copr 中的测试包。
URL: https://copr.fedorainfracloud.org/coprs/pwu/cloud-input/
libpinyin 目前只会记录全拼的词语，简拼是不会记录的。

**Comment by epico** [comment]
Please try libpinyin 2.6.1 and ibus-libpinyin 1.12.1, thanks!

**Comment by epico** [comment]
这两个问题可能已经修复了，可以试试最新的版本！
