### ISSUE TITLE
【新功能建议】中英混输

### ISSUE THREAD

**Issue by WenqingZong** [libpinyin/ibus-libpinyin#321]
目前输入法在需要频繁转换中英文输入时的体验不是很好，比如无法完整输入“伦敦就是London”。使用v模式输入英文时很别扭，希望以后可以在中文模式下直接将London识别成候选词。

以及，希望可以去掉标点符号自动选词功能，在中文模式下输入“www.google.com”时，会变成“外文为。个哦噢过了。com”

以上，希望ibus-libpinyin越来越好！

**Comment by ping-wu** [comment]
我觉得没有这个必要。

不过想问另一个问题：如何在 ibus-libpinyin 里加入英文词库？

**Comment by epico** [comment]
英文词库在 english.db sqlite 文件中，请自行修改该文件。

**Comment by wsxy162** [comment]
比如不能直接输入 openSUSE 这个词。
候选框上面的输入自动转换成拼音，也跟直接输入英文相悖。
我想现在的输入模式就不是为直接（兼容）输入英文设计，补充英文词库不能解决问题。

**Comment by ping-wu** [comment]
在我的系统里，没有问题。第一次输入 openSUSE 后，第二次打 su 就自动出现了。请见附图。

**Comment by wsxy162** [comment]
@epico 我说的是原 issue 中的直接输入（中英混输），你展示的是V模式。

**Comment by ping-wu** [comment]
我觉得目前 ibus-libpinyin 最需要加强的乃是中文字词库问题。在中文 Ubuntu 论坛里，几乎只有我在使用 ibus-libpinyin，Epico 已做了很多改善，希望把有限的资源先放在这里。

**Comment by wsxy162** [comment]
Libpinyin 更像是把英文输入模式专门剥离了出来，跟传统和以往的拼音输入法都不相同。不过我也觉得中文词库优先级更高，现在基本依赖云输入候选词。

**Comment by ping-wu** [comment]
在 1.12 版里中文输入模式下，即使已经输入英文字母，按 shift 键就可以马上转入英文输入模式，已输入英文字母被保留。比起（例如）
ibus-rime 要方便多了。我中英混输的机会很多，这个功能是我选择 ibus-libpinyin 的主要原因。

**Comment by chengwang2077** [comment]
But if you enter V, pressing shift will not convert to English, which forces me to give up ibus

**Comment by chengwang2077** [comment]
The same is true for the u key. Characters like v and u are like traps. I don’t know how many other characters like this one. If you don’t press it, you can make big characters quickly, but once you press it, you have to get stuck. , Keep delete, shift, delete, shift

**Comment by epico** [comment]
在 ibus-libpinyin 中，中文模式下会显示英文候选词。
