### ISSUE TITLE
typing 著

### ISSUE THREAD

**Issue by Meresmata** [libpinyin/ibus-libpinyin#322]
I tried my best to write the character zhe - 著 as traditional character. I tried hard but didn't find it even after going through the how list of suggestions. 
I even tried the most common similar suggestions in different fonts. What might me going wrong_ Is it really missing or is it a difference in Taiwanese and Hong Kongese characters? (shouldn't be both versions given?) Is there a way to switch between HK and TW?

**Comment by epico** [comment]
For Traditional Chinese, please try ibus-libzhuyin, thanks!

**Comment by Meresmata** [comment]
Thanks for the tip. The only problem is, that I never learned to use Bopomofo. Therefore, This doesn't seam to to be a got option for me.

**Comment by epico** [comment]
ibus-libzhuyin supports Hanyu Pinyin.

**Comment by Meresmata** [comment]
Thanks. Found it!. It works. Though it's usage feels a bit less intuitive than intelligent pinyin to me. Thanks.

**Comment by wlinna** [comment]
I'm having the same problem, but Hanyu Pinyin isn't really an option for me. I tried it, but it seems to be based on QWERTY, while Intelligent Pinyin works fine with Colemak keyboard layout (the one I use in my daily life). Besides, I really like Intelligent Pinyin.

Is there another way? Maybe there's something I could do with user.lua ? Like adding a specific letter sequence or even just blindly replacing 着 with 著? I haven't scripted Intelligent Pinyin before, so tips would be greatly appreciated.

**Comment by epico** [comment]
Please read /usr/share/ibus-libpinyin/base.lua .

**Comment by wlinna** [comment]
Thanks for the quick answer. The first thing I'm going to try is creating my own command. So I started out by looking at base.lua.

However, I have trouble figuring out how I can use anything from that script. For example, when I write `sj` and the candidate box opens, I have no idea how to activate any of those commands. I tried pressing Space, Enter, Ctrl+Space, Ctrl+Enter, Shift+Enter etc. 

Do I need to first copy the base.lua to user.lua? Based on the quick look on source code, I got the impression that base.lua should be loaded automatically, so I imagine it's not about that.

How can I activate a command?

Thanks

**Comment by epico** [comment]
I think you need to press 'i' key.

**Comment by wlinna** [comment]
Thanks, I tried that and with different modifier keys too, but the letter 'i' was merely added to the search string. So `xz` became `xzi` and  the candidates were updated (e.g. 現在 -> 小子)

I tried the other keys as well, with different modifiers, but no commands were (apparently) invoked.

**Comment by epico** [comment]
Please try `ixz`.

**Comment by wlinna** [comment]
Thanks a lot! It's working, as are the commands. But what about triggers? What are they and how to trigger `get_today`?

**Comment by epico** [comment]
Please try `shijian` and `riqi`.

**Comment by wlinna** [comment]
Ah, I see that they offer the current time and date respectively. Very good. 

Thanks a lot for the pointers. I think I can develop my solution in the upcoming days.

**Comment by wlinna** [comment]
Hi, thanks a lot for your help! I was able to solve my problem

To those who have the same or a similar problem, here's how I was able to get 著:
1. I opened Intelligent Pinyin settings
2. From settings you can find an option to modify `user.lua`
3. Add the following script there.
```
function get_zhe()
  return { "著" }
end

ime.register_trigger("get_zhe", "著", {}, {'着'})
```

Now if you write zhe, both 着 and 著 should appear as candidates.

It works mostly as I'd expect. The only small problem is that if I write e.g. xiang zhe, Intelligent Pinyin will offer  想着 but not 想著. 

While this is good enough for me, and definitely better than Hanyu Pinyin (in my opinion), what I'd really like to do is to replace all occurrences of  着 with 著 in all candidates. Is there a way to do that? I couldn't figure that out by reading `base.lua`.

**Comment by epico** [comment]
Maybe you can try `ime.register_converter`.
