### ISSUE TITLE
如何删除自建词库的字/词？

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#325]
请问如何删除自建词库里的字/词？

**Comment by ping-wu** [comment]
Right now, it looks like the only way to remove an unwanted user vocabulary is to:

1.  export the user dictionary
2.  clear the cache
3.  edit the exported user dictionary
4.  re-import the edited user dictionary
5.  log out and re-log in

Any suggestions? ? ?

**Comment by epico** [comment]
I think it is the correct steps, maybe not need to re-login...

**Comment by ping-wu** [comment]
What's the difference between "clear (cache" and "clear all data"?  Which one should I select?

**Comment by epico** [comment]
Please try "Clear" first. If not work, please try "Clear All Data".

**Comment by epico** [comment]
"Clear" will clear the user and professional dictionary, "Clear All Data" will clear all user data.
