### ISSUE TITLE
切换成俄语后无法切回

### ISSUE THREAD

**Issue by Alfred-bio** [libpinyin/ibus-libpinyin#327]
当输入法切换到俄语后，在将输入法切换到本输入法时无效。即依然只能打出俄语字母，需要首先将输入源切换成 “汉语“ ，之后从” 
 “汉语”  在切换到本输入法方可实现输入中文

**Comment by epico** [comment]
请自行修改 `/usr/share/ibus/component/libpinyin.xml` 文件，`<layout>default</layout>` => `<layout>us</layout>` .
