### ISSUE TITLE
云输入没有记录词频

### ISSUE THREAD

**Issue by miaoerwu** [libpinyin/ibus-libpinyin#328]
![2021-08-01_11-20](https://user-images.githubusercontent.com/14366467/127758074-89d65b9b-e6ba-4a6c-bb82-34b8ac2ef661.png)
![2021-08-01_11-20_1](https://user-images.githubusercontent.com/14366467/127758075-85d8fe27-0984-41bc-bc5c-e524e341905b.png)
勾选将每个输入记录为新的词汇，并且修改候选词排列方式为词频后，开启云输入。当选用云输入显示的候选词时，并没有记录词频使得候选词中的顺序发生变化。比如输入某个词，候选词中有云输入的候选项，使用数字键选中候选词作为输入后，下次以及之后的每次输入，其都会出现在相同的候选词序号的位置。同时因为云输入需要联网，导致候选词会在输入停止后的几秒钟后发生变化。比如输入某个词后，第一页候选词中没有云输入的候选项，等待1到2秒后候选词中的第4个或者第4个（至少我本地是会出现在这两个位置上）会变成候选词，原本的候选词后顺序排列到云输入候选词后面。我认为可以把云输入的内容也记录词频这样整体的输入体验会更好。

**Comment by epico** [comment]
要不你试试 git repo 的代码？

**Comment by miaoerwu** [comment]
是要检出源码，编译，安装么？

**Comment by ping-wu** [comment]
如果有在 Debian 11 环境下编译成功的例子，请告知。谢谢！

**Comment by epico** [comment]
https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

**Comment by ping-wu** [comment]
> 如果有在 Debian 11 环境下编译成功的例子，请告知。谢谢！

https://forum.ubuntu.com.cn/viewtopic.php?f=8&t=492359

**Comment by epico** [comment]
Please try libpinyin 2.6.1 and ibus-libpinyin 1.12.1, thanks!
