### ISSUE TITLE
在正體中文模式，輸入li只會出現「里」，而不會出現「裡」這個繁體字

### ISSUE THREAD

**Issue by curewikipedia** [libpinyin/ibus-libpinyin#329]
里的確也算正體字的一種，但是用於比如公里，或者英里等距離單位

當你輸入xinli或者limian時，出來的結果會是心裡和裡面，這兩個是正確的

可是單獨打字li，卻怎麼找都找不到「裡」字

還有比如在拼音里打字jianao卻打不出來煎熬

**Comment by ping-wu** [comment]
在我的系統裡沒有問題（ibus-libpinyin 1.12 in Debian 11）。

另外，打開雲詞庫後，“煎熬” 就會出現爲候選詞之一。

**Comment by epico** [comment]
"裡" 這個字的位置比較靠後。

也許可以考慮從設置對話框中導入，格式在對話框下方有說明。可能需要要自己編輯這個詞庫。

**Comment by epico** [comment]
其實，ibus-libzhuyin 是支持漢語拼音的。

**Comment by epico** [comment]
I converted the libzhuyin dictionary to ibus-libpinyin format, which can be imported
in the ibus-libpinyin setup dialog.

URL: https://pwu.fedorapeople.org/ibus/libzhuyin/tsi.txt

**Comment by ping-wu** [comment]
> I converted the libzhuyin dictionary to ibus-libpinyin format, which can be imported in the ibus-libpinyin setup dialog.
> 
> URL: https://pwu.fedorapeople.org/ibus/libzhuyin/tsi.txt

拼音後面有數字，可以在 ibus-libpinyin 裏使用嗎？

**Comment by epico** [comment]
抱歉，有可能 ibus-libpinyin 不支持该格式，重新上传了 tsi.txt 文件。

**Comment by ping-wu** [comment]
tsi.txt 文件是繁体中文。有没有简体中文的版本？

**Comment by epico** [comment]
tsi.txt 来自于 libchewing, 没有简体中文版本...
