### ISSUE TITLE
中/英文切换问题

### ISSUE THREAD

**Issue by Mashimiao** [libpinyin/ibus-libpinyin#33]
hello
以前使用输入法的时候可以方便地使用shift键进行中英文切换输入。
升级到1.6.99.20150203之后之后就不能使用shift健进行中英文切换了。

**Comment by epico** [comment]
请描述使用的桌面环境。
试过重新登陆没有？

另外，现在快捷键都可以定制了。
请看看默认设置是否是 Shift 键，
不是的话，请说明，我看看是不是个 bug，谢谢。

**Comment by Mashimiao** [comment]
使用的是 gnome 3.14.2
重新登陆不起作用
默认设置是shift键

**Comment by epico** [comment]
使用的Linux发行版是？

**Comment by Mashimiao** [comment]
Fedora21

**Comment by epico** [comment]
在 updates-testing repo 中，有 ibus-libpinyin 1.7.0 和 libpinyin 1.1.0，也有问题吗？
请提供下面这条命令的输出:
$dconf read /desktop/ibus/engine/pinyin/MainSwitch

**Comment by Mashimiao** [comment]
$ dconf read /desktop/ibus/engine/pinyin/MainSwitch
'<Shift>'

**Comment by epico** [comment]
已确认是 bug, 修复中...

**Comment by epico** [comment]
Draft patch landed on https://github.com/epico/ibus-libpinyin/commit/e64b6ec09ec934e506d566174ac6524c61336228 .

**Comment by epico** [comment]
Please try https://admin.fedoraproject.org/updates/FEDORA-2015-3217/ibus-libpinyin-1.7.0-2.fc21,libpinyin-1.1.0-1.fc21

**Comment by Mashimiao** [comment]
已经重新装了ibus-libpinyin-1.7.0-2.fc21.x86_64，但是还是没有解决问题

**Comment by epico** [comment]
输出应该是 '\<Shift\>' .
在对话框里修改一下试试。

**Comment by Mashimiao** [comment]
是你说的那种Shift，不过那样在github这个网页内显示不出来。不知道你是怎么输入的

**Comment by epico** [comment]
请用下面的命令， work around 一下:
$ dconf reset -f /desktop/ibus/engine/pinyin/

**Comment by Mashimiao** [comment]
还是没有作用

**Comment by epico** [comment]
重新启动，或重新登陆也不行吗？

**Comment by Mashimiao** [comment]
恩  不起作用

**Comment by epico** [comment]
创建个新的用户也不行吗？

**Comment by Mashimiao** [comment]
不行  新创建了个用户尝试了下  一样不能切换

**Comment by Mashimiao** [comment]
Hi epico,
昨晚我尝试了下我另一个Feodra21系统，发现能够用Shift切换输入法了。
这一台不知道什么情况，还是不能切换。应该是其他问题影响着。
多谢你这几天的帮助！

**Comment by epico** [comment]
不客气
