### ISSUE TITLE
双拼输入候选框提示不够合理

### ISSUE THREAD

**Issue by wsxy162** [libpinyin/ibus-libpinyin#331]
使用双拼模式时，各种双拼方案还是避免不了输入的重码。比如在具体使用“小鹤双拼”时，键入“L+O”时，可以代表输入的是拼音 luo（罗）或 lo（咯）。而这种情况下，libpinyin 在候选框上显示是 luo。这明显忽略了 lo 这个拼音，虽然实际的候选词是正确地包含了两个拼音的。
如果要改进这个缺陷，可以像其它双拼输入法一样，候选框中的输入词不要做转换，直接显示原来的按键输入。或者可以补全候选框中的拼音，同时显示所有的可选拼音。比如上面的例子中，显示为“luo/lo”。

**Comment by epico** [comment]
在设置对话框中，"显示双拼原始输入" 选项已添加。

**Comment by epico** [comment]
ibus-libpinyin 1.12.91 is released, close issue.
