### ISSUE TITLE
【BUG】分词逻辑有漏洞，存在部分无法打出的汉字

### ISSUE THREAD

**Issue by NevilleZong** [libpinyin/ibus-libpinyin#332]
例如：虐，输入nue后，输入法分词会变为nu‘e，第一候选词为怒额，且使用`'`强行分词也无法解决该问题。
又如：嗯嗯，输入enen后，分词为e'nen，第一候选词为鄂嫩。这个情况下使用`'`可解决问题。

linux小白一个，刚刚开始接触ibus-pinyin，希望这款软件越来越好！

**Comment by epico** [comment]
我测试了一下，"nue" 和 "enen" 工作正常。

可能您使用的是 ibus-pinyin, 而不是 ibus-libpinyin。
