### ISSUE TITLE
elementary6 os的自带ibus中，使用ibus-libpinyin首个字出现黑块。

### ISSUE THREAD

**Issue by TTTJH** [libpinyin/ibus-libpinyin#333]
就像这样 [👇👇👇

**Comment by TTTJH** [comment]
![lALPDgtYyX4WW1DMvs0COw_571_190](https://user-images.githubusercontent.com/35984491/134790276-5f9bd532-3699-4d8e-8413-106dbba8af52.png)

**Comment by epico** [comment]
可能是主题的颜色问题，请报告此问题到 elementary OS.
