### ISSUE TITLE
中文拼音输入法下会卡住延迟

### ISSUE THREAD

**Issue by XL1031** [libpinyin/ibus-libpinyin#337]
点击键盘后过好几秒才输入到界面之上，有时直接卡死，不知什么原因。

**Comment by epico** [comment]
有可能是用户数据损坏了，可以尝试清除用户数据。

删除 ~/.cache/ibus/libpinyin/user.conf 文件，重新登录，可以清除用户数据。

**Comment by XL1031** [comment]
谢谢！

**Comment by ping-wu** [comment]
我的 user.conf 的档案是这样的：

ryzen@L32:~$ cat .cache/ibus/libpinyin/user.conf 
binary format version:6
model data version:14
database format:BerkeleyDB

重新登设会有效吗？

**Comment by epico** [comment]
当不存在 user.conf 文件或者 user.conf 文件和系统文件不匹配的话，libpinyin 启动后，会自动清理用户数据。

**Comment by ping-wu** [comment]
Thanks!
