### ISSUE TITLE
某些候选词汇无法选中输入

### ISSUE THREAD

**Issue by sosiaozomaker** [libpinyin/ibus-libpinyin#338]
这个候选词贝克利是无法选中上词，即使我选 3 但是最后上词的还是第一个。其他一些词汇也有这个现象。
![2021-11-15 17-37-30屏幕截图](https://user-images.githubusercontent.com/55429943/141758200-79b0c053-85b9-44b9-b522-205517ff3b27.png)

![2021-11-15 17-38-06屏幕截图](https://user-images.githubusercontent.com/55429943/141758205-1d1d3b1a-4e91-4d2a-9539-a213818d1deb.png)
不知道是哪里出问题。

**Comment by epico** [comment]
请问您使用的 Linux 发行版是?

libpinyin 和 ibus-libpinyin 的版本号是?

**Comment by sosiaozomaker** [comment]
> 请问您使用的 Linux 发行版是?
> 
> libpinyin 和 ibus-libpinyin 的版本号是?

感谢回复！
我使用的发行版是 fedoraworkstation 35.
linux kernel: 5.14.16-301.fc35.x86_64
ibus-libpinyin: 1.12.1
IBus: 1.5.25

**Comment by epico** [comment]
刚刚在 Fedora 35 中测试了一下，无法复现该问题。

能否试试 Fedora Workstation Live, 或者新建一个用户，看看是否也有问题。

**Comment by sosiaozomaker** [comment]
感谢回复！我在 live 系统中试了下发现没问题。经过排查发现是我导入的某一个词库有问题，清除用户数据后问题不再出现。

**Comment by epico** [comment]
不客气！
