### ISSUE TITLE
Suddenly Stopped Working on Fedora 35 (Gnome 41.2) 

### ISSUE THREAD

**Issue by HymanZHAN** [libpinyin/ibus-libpinyin#339]
Starting this morning, intelligent pinyin stopped working. The pop-up menu would sometimes appear for a second when I first switched to Chinese input and then abruptly disappear. Video recording:
 
https://user-images.githubusercontent.com/26806995/145429842-3ff5dbb9-a581-4599-aa31-5a4ebf5cadcb.mp4

Is there any way to diagnose the issue? Log files or the like?

**Comment by epico** [comment]
Maybe the user data is corrupted, using the following command will clear the user data.

`$ rm ~/.cache/ibus/libpinyin/user.conf`

**Comment by HymanZHAN** [comment]
I removed everything inside libpinyin's cache folder by `rm ~/.cache/ibus/libpinyin/*` and that did the trick. Thanks!
