### ISSUE TITLE
著『ㄓㄠˊ』用繁體拼音模式，zhe沒有這個字

### ISSUE THREAD

**Issue by hizukiayaka** [libpinyin/ibus-libpinyin#34]
著（正體） = 着(简体）
ㄓㄠˊ              zhe2
我用zhe是沒有這個字的，但是要輸入zhu (ㄓㄨˋ)才行。我沒嘗試過注音輸入法，不知道有沒有這個問題。
教育部的字典
http://dict.variants.moe.edu.tw/yitia/fra/fra03506.htm

**Comment by epico** [comment]
Please try ibus-libzhuyin, thanks.

**Comment by hizukiayaka** [comment]
Well, although it could solve this problem, but it means that libpinyin has a bug.

**Comment by epico** [comment]
Sorry, this is correct in Simplified Chinese.
See: http://hanyu.iciba.com/hanzi/8175.shtml

Please use libzhuyin, which is designed for Traditional Chinese.

**Comment by hizukiayaka** [comment]
The dictionary I used is the dictionary hosted by Ministry Education, ROC.
In that dictionary, it even doesn't have the character 着.
You could find some sample used 著 here, it comes from the the dictionary hosted by Ministry Education, ROC.
 http://goo.gl/vPCZm1

**Comment by epico** [comment]
Please use libzhuyin, which is designed for Traditional Chinese.
