### ISSUE TITLE
中文后打空格不起作用

### ISSUE THREAD

**Issue by ljhui** [libpinyin/ibus-libpinyin#340]
最近从fedora 34升级到fedora 35, 遇到一个问题。当我在gnome桌面的官方应用中先输入几个汉字，再输入空格，根本不起作用，这个主要出现在各种gnome应用中，如gedit, nautilus, geary，gnome todo 中，我录制了一个视频在[这里](https://youtu.be/u5-OocVceDQ)，当我输入“开始”后，试着打个空格，没有显示，继续打空格依然没显示，但gedit的列号一直在增加，按backspace删除，列号减小但光标不动，说明空格打出来来了就是不显示，然后切换到英文，空格正常显示。

一时找不到原因所在，我在VirtualBox全新安装了fedora 35，测试了一下，发现这个bug只出现在系统默认语言设置为英文时，中文后打空格不起作用，有时空格显示出来了，你继续敲汉字，汉字一敲进去，空格就消失了，这个bug经常出现，大部分的gnome官方应用都有这个，比如在nautilus的搜索框中输入中文再继续输空格光标根本不动，geary邮箱写邮件的To和Subject两项也会出这个问题，gnome todo创建task也会出现空格不显示的问题，一般就是gnome的官方应用的各种输入框会有这个问题，系统的searchbox也会这样，其他如vscode,liberoffice,firefox等都正常。但当我把系统默认语言设置为中文时，问题消失一切正常。

我一直系统默认语言设为英文使用，在fedora34下中文输入没遇到过这个问题，这个bug应该跟输入法无关的，我也用ibus-rime，一样有这个问题。主要不知道什么造成的，不过毕竟是输入方面问题，先在这里问问，看有谁能帮下，给出问题原因和解决方法，谢谢！

**Comment by epico** [comment]
这个问题好像是字体的问题，将文件存盘后，在中文环境下打开是正常的。

**Comment by ljhui** [comment]
是的，这个问题只出现在英文环境下打中文，空格其实输入进去了但就是不显示，切换到中文会正常显示。你说是字体问题，能详细解释下嘛，我试着改了下多种字体，没见恢复正常。

**Comment by epico** [comment]
这个字体可能是 DroidSansJapanese.ttf, 查看了一下，好像没有 space 这个字符。

删除 DroidSansJapanese.ttf 后，gedit 显示正常了。

**Comment by ljhui** [comment]
试了下删除 DroidSansJapanese.ttf，可以打空格了，问题应该解决了。刚开始我看字体DroidSansJapanese.ttf在/usr/share/fonts/google-droid-sans-fonts 下，想sudo dnf remove google-droid-sans-fonts，一下子要删除一大堆包，还是老老实实只删除 DroidSansJapanese.ttf文件。不过我实在不明白这个文件怎么会造成上述问题，毕竟我在gnome tweak里配置的字体没选这个，gedit使用的也不是这个字体，有空可以详细解释下吗，或有这方面相关参考链接吗？

**Comment by epico** [comment]
在 Fedora 35 中，默认的英文字体列表中不包括中文字体，pango 根据 “你好” 选择了 DroidSansJapanese.ttf; 而 space 字符会使用邻近的字符所使用的字体，即 DroidSansJapanese.ttf 字体，而 DroidSansJapanese.ttf 中并不包括 space 字符。

可以看看 fontconfig 和 pango 的文档。

**Comment by epico** [comment]
可以考虑给 google-droid-sans-fonts 汇报一个 bug.

URL: https://bugzilla.redhat.com

**Comment by epico** [comment]
有可能 pango 1.50.3 修复了这个问题，可以升级一下 Fedora 35，看看这个问题是否还存在。

**Comment by ljhui** [comment]
不错，问题已经修复了
