### ISSUE TITLE
Ubuntu下频繁无法输入/卡死 + 排序合理化建议

### ISSUE THREAD

**Issue by saindo** [libpinyin/ibus-libpinyin#341]
Ubuntu20.04.3LTS + IBus with Intelligent Pinyin 1.11.1 
1.BUG：最近开始特别频繁出现卡死现象，打开输入中文模式，按键后没有反应，没有中文提示选框界面出来，也没有任何字符出来，等5秒左右以后，在此期间所有按键都会以英文字符出来。没有发现此后能自行恢复的情况。重启Ibus恢复正常。每天能出现几次。
2.建议：建议增加一个选项“词组和单字一起排序“，这样自定义的词组里的单字也能提升排序。
建议增加”禁用颜文字“选项。

**Comment by epico** [comment]
可能是用户数据损坏了，删除 ~/.cache/ibus/libpinyin/user.conf 即可，libpinyin 会自动清理其他文件。

关闭表情符号的选项在 dconf 中，请自己用 dconf-editor 关闭。

Ubuntu 20.04 的 ibus-libpinyin 版本比较低，有些选项没有，而且不太稳定。推荐使用更高版本的 Ubuntu, libpinyin 是稳定版本，而且选项也多。
