### ISSUE TITLE
Ubuntu下联想输入模式下，按标点符号应该可以取消目前联想提示

### ISSUE THREAD

**Issue by saindo** [libpinyin/ibus-libpinyin#342]
Ubuntu下联想输入模式下，按标点符号应该可以取消目前联想提示。现在联想模式下，只有输入字符才会取消，有点不合理。

**Comment by secretxu** [comment]
首选项-拼音模式-输入个性化，取消勾选[,][.]翻页

**建议可以把这个选项默认不勾选，不然在自动联想后无法输入逗号和句号。**

**Comment by epico** [comment]
谢谢这个建议，选项[,][.]翻页默认不勾选。

Fixed in https://github.com/libpinyin/ibus-libpinyin .

**Comment by epico** [comment]
ibus-libpinyin 1.12.91 is released, close issue.
