### ISSUE TITLE
Wayland 环境下不定时输入法无响应

### ISSUE THREAD

**Issue by lumingzh** [libpinyin/ibus-libpinyin#347]
运行环境：Fedora Silverblue 35 Gnome 41
需要输入文字的应用为 flatpak 应用，比如 flatpak 版本的火狐浏览器

输入时有可能不定时突然出现输入无响应：
- 按shift切换英文输入无效
- 按super+空格键切换英文键盘可以输入
- 再次按super+空格键切换回中文输入依然无响应或只能输入英文
- 按键盘持续输入期间有可能会突然插入之前无响应时的输入内容（只有英文）
- 过几分钟后自己恢复正常

**Comment by lumingzh** [comment]
没有测试 Xorg 环境下的情况。

**Comment by epico** [comment]
有可能是用户数据损坏，请删除 ~/.cache/ibus/libpinyin/user.conf 文件，重新登录试试。

**Comment by b310v3** [comment]
我也是遇到同樣的問題，測試過刪除libpinyin的文件夾後馬上修復，但是不定時還是會發生同樣的問題。

**Comment by epico** [comment]
请运行如下命令，方便的话，把结果粘贴到这里，谢谢。

```
$ cd ~/.cache/ibus/libpinyin/
$ ls -lh
```

**Comment by b310v3** [comment]
`total 196K
-rw-r--r--. 1 b310v3 b310v3   27 Feb  8 09:21 addon.bin
-rw-r--r--. 1 b310v3 b310v3  20K Feb  7 15:22 english-user.db
-rw-r--r--. 1 b310v3 b310v3  12K Feb  8 09:21 gb_char.dbin
-rw-r--r--. 1 b310v3 b310v3  170 Feb  8 09:21 gbk_char.dbin
-rw-r--r--. 1 b310v3 b310v3   26 Feb  8 09:21 merged.dbin
-rw-r--r--. 1 b310v3 b310v3   27 Feb  8 09:21 network.bin
-rw-r--r--. 1 b310v3 b310v3 2.1K Feb  8 09:21 opengram.dbin
-rw-------. 1 b310v3 b310v3  16K Feb  8 09:21 user_bigram.db
-rw-r--r--. 1 b310v3 b310v3  26K Feb  8 09:21 user.bin
-rw-r--r--. 1 b310v3 b310v3   73 Feb  8 09:21 user.conf
-rw-------. 1 b310v3 b310v3  40K Feb  8 09:21 user_phrase_index.bin
-rw-------. 1 b310v3 b310v3  56K Feb  8 09:21 user_pinyin_index.bin`

**Comment by epico** [comment]
@b310v3 请问您使用的 Linux 发行版是？libpinyin 和 ibus-libpinyin 的版本号是？

**Comment by b310v3** [comment]
Fedora 35 with Kernal 5.15.13-200
libpinyin version: 2.6.1
ibus-libpinyin: 1.12.1

下次問題再次出現我會再留意看Log的。

**Comment by epico** [comment]
好的，其实只删除 ~/.cache/ibus/libpinyin/user.conf 文件即可，剩下的文件 libpinyin 会自己清除的。

**Comment by lumingzh** [comment]
之前为了更新 BIOS 固件安装了 windows，重新安装 fedora 后没再出现过这个问题。关闭 issue 了，如果再出现问题会重新开。

**Comment by lumingzh** [comment]
问题再次出现，而且比我想象的要严重，真正的问题不是输入无响应，而是 libpinyin 这个输入法整个失去响应，输入法设置都无法打开：
![截图 2022-05-28 11-29-00](https://user-images.githubusercontent.com/89230850/170808157-e1635eee-1400-4d57-a3b1-29b0c81de09a.png)
系统：Fedora Silverblue 36
桌面：Gnome Shell 42
ibus：1.5.26
ibus-libpinyin：1.12.91

**Comment by uniartisan** [comment]
我是Ubuntu 22.04 wayland 有同样的问题。
```
总用量 144K
-rw-r--r-- 1 lizhiyuan lizhiyuan  107  6月  1 23:51 addon.bin
-rw------- 1 lizhiyuan lizhiyuan 8.0K  5月 23 19:20 __db.user_phrase_index.bin.tmp
-rw-r--r-- 1 lizhiyuan lizhiyuan  20K  6月  1 22:36 english-user.db
-rw-r--r-- 1 lizhiyuan lizhiyuan  28K  6月  1 23:51 gb_char.dbin
-rw-r--r-- 1 lizhiyuan lizhiyuan   26  6月  1 23:51 gbk_char.dbin
-rw-r--r-- 1 lizhiyuan lizhiyuan   26  6月  1 23:51 merged.dbin
-rw-r--r-- 1 lizhiyuan lizhiyuan 3.7K  6月  1 23:51 network.bin
-rw-r--r-- 1 lizhiyuan lizhiyuan 7.7K  6月  1 23:51 opengram.dbin
-rw------- 1 lizhiyuan lizhiyuan  20K  6月  1 23:52 user_bigram.db
-rw-r--r-- 1 lizhiyuan lizhiyuan   27  6月  1 23:51 user.bin
-rw-rw-r-- 1 lizhiyuan lizhiyuan   73  6月  1 23:52 user.conf
-rw------- 1 lizhiyuan lizhiyuan  16K  5月 23 18:49 user_phrase_index.bin
-rw------- 1 lizhiyuan lizhiyuan  20K  6月  1 23:51 user_pinyin_index.bin
```


ibus-libpinyin/jammy,now 1.12.1-2ubuntu2 amd64 [已安装]
libpinyin-data/jammy,now 2.6.1-1build1 amd64 [已安装]
libpinyin13/jammy,now 2.6.1-1build1 amd64 [已安装]

**Comment by zhangyuebj** [comment]
和lumingzh遇到相同的问题。
我是fedora 36（Workstation Edition）版本，同样使用Wayland，gnome版本是42.2。IBus 智能拼音 1.12.91。

IBus输入法设置无法打开。输入文字时无响应，过一段时间会自动恢复。但感觉该现象出现的频率较高，比较影响体验。看能否定位到具体原因并修复，谢谢。

**Comment by wa1kmoon** [comment]
ubuntu18.04, 问题和@zhangyuebj描述的一样
ibus-libpinyin 1.11.0
libpinyin 2.2.2-1
![Screenshot from 2022-07-13 16-12-49](https://user-images.githubusercontent.com/46768971/178685025-d98fb38a-b669-473d-9ff9-99c6b8bdb2cd.png)

**Comment by suhw1999** [comment]
我的ubuntu22.04 在X11下也存在这个问题，在[#362 ](url)中跟此问题相似

这个现象最早在一年前就出现过，后来转用rime，现在重新使用后依然存在此问题，不知道是什么导致的，应该怎么解决？

**Comment by epico** [comment]
@suhw1999 请尝试删除 `~/.cache/ibus/libpinyin/user.conf` 文件试试。

**Comment by lovenemesis** [comment]
> 我的ubuntu22.04 在X11下也存在这个问题，在#362 中跟此问题相似

类似问题，主要出现在 Qt (如 WPS for Linux)和通过 Flatpak 安装的 Electron App (如 VS Code) 中，在 Mozilla 的 Firefox Beta 中也容易遇到。

应用了这个方法后一周有余，目前尚未复现：

https://github.com/libpinyin/ibus-libpinyin/issues/347#issuecomment-1244828541

**Comment by lumingzh** [comment]
> 问题再次出现，而且比我想象的要严重，真正的问题不是输入无响应，而是 libpinyin 这个输入法整个失去响应，输入法设置都无法打开： ![截图 2022-05-28 11-29-00](https://user-images.githubusercontent.com/89230850/170808157-e1635eee-1400-4d57-a3b1-29b0c81de09a.png) 系统：Fedora Silverblue 36 桌面：Gnome Shell 42 ibus：1.5.26 ibus-libpinyin：1.12.91

新发现，通过终端打开 ibus-setup，在 ibus-setup 里面可以正常打开输入法的首选项，通过 gnome shell 集成的状态栏菜单无法打开输入法首选项。
另外，是否能正常输入和应用无关，非 flatpak 应用同样存在这个问题。

**Comment by lumingzh** [comment]
> ibus-libpinyin 1.12.91 好像是不稳定版本，请更新一下系统试试。

Fedora silverblue 37
ibus-libpinyin 1.13.1
问题仍然存在，暂时换成ibus-rime使用以排除输入法问题。

**Comment by lumingzh** [comment]
Fedora Silverblue 38
ibus-libpinyin 1.15.3
问题仍然存在。
有头绪吗？ @epico

**Comment by epico** [comment]
目前，我这边并不容易复现这个问题。

**Comment by lumingzh** [comment]
前两天又出现一次，发现 gnome shell 顶栏菜单中不只是输入法首选项无法打开，下面的显示键盘布局也打不开，只有输入法切换和键盘设置（自动打开gnome设置的键盘设置页面）正常。

**Comment by lovenemesis** [comment]
`ibus-1.5.28-6.fc38.x86_64
ibus-libpinyin-1.15.3-2.fc38.x86_64`

这个问题依然存在，出现的时候，GNOME Shell 顶栏的"中/En"指示器会变成 “拼”，同时键盘布局无法打开。

**Comment by TieWay59** [comment]
系统：Ubuntu 22.04.3 LTS
GNOME：42.9
Wayland

安装软件版本：
ibus-libpinyin/jammy,now 1.12.1-2ubuntu2 amd64 [installed]
libpinyin13/jammy,now 2.6.1-1build1 amd64 [installed,automatic]

我也遇到了类似的问题，表现为：

每天此输入法软件会多次冻结，可以切换其他输入法。
待数分钟后，我会被强行注入冻结时的延迟输入，即便我不在这个输入法，所以我很困扰。

@epico 我目前也看不出是是什么因素导致的，因为我主要在 terminal 与 chrome （含VSCode）的软件中打字，并且因为几乎每天都会发生，所以在我记忆中任何地方都可能有触发过。

我的临时解决方案是：

```shell
> ibus restart
> ibus-daemon -d
```

可能和删除用户文件差不多，但是都治标不治本。

**Comment by Anthony6075** [comment]
> `ibus-1.5.28-6.fc38.x86_64 ibus-libpinyin-1.15.3-2.fc38.x86_64`
> 
> 这个问题依然存在，出现的时候，GNOME Shell 顶栏的"中/En"指示器会变成 “拼”，同时键盘布局无法打开。

有时遇到同样的现象，但是我这里是：有时候输入法卡顿的时候指示器不会变成“拼”，但也是没响应
我这里的环境是：
1. ubuntu 22.04，gnome 42.9, X11
2. 暗影精灵5, GTX 1660Ti

**Comment by epico** [comment]
ibus-libpinyin 1.15.5 已经发布，关闭了在 Logout 的时候，保存数据的功能。

ibus-libpinyin 会在停止输入5分钟后，保存用户数据。

如果之前有问题的话，请先升级到新版本，再清除用户数据，看看是否还有问题。

**Comment by lumingzh** [comment]
> 随着更新到 Fedora 39 和 ibus-libpinyin 1.15.5，这个现象没有再出现过了

需要时间测试，暂时关闭该issue了，如果还有问题再重新打开。

**Comment by y010204025** [comment]
> ibus-libpinyin 1.15.5 已经发布，关闭了在 Logout 的时候，保存数据的功能。
> 
> ibus-libpinyin 会在停止输入5分钟后，保存用户数据。
> 
> 如果之前有问题的话，请先升级到新版本，再清除用户数据，看看是否还有问题。
@epico @lumingzh @Anthony6075 @TieWay59 
对于这个问题,已确认gnome 桌面在Wayland 模式下兼容性导致,出现部分输入有用,部分输入无效的情况,需要安装https://extensions.gnome.org/extension/261/kimpanel/ 解决.
kde 桌面没有问题,xorg 模式下也没有问题,非 ibus-libpinyin的问题.

**Comment by lumingzh** [comment]
目前为止尚未出现该bug，工作良好。
