### ISSUE TITLE
设置为每个窗口独立输入法后，切换窗口时中英、简繁、全半角信息会丢失

### ISSUE THREAD

**Issue by HymanZHAN** [libpinyin/ibus-libpinyin#349]
如题，之前看到有个几年前的issue但是只提到了中英信息丢失，但其实所有的状态都会回滚到初始默认值。
可能是和ibus的输入源配置选项的实现有关，因为其实切换不同输入法之后该信息也会丢失，例如：
- 英文输入法 -> 中文拼音
- 中文拼音（中）-> 中文拼音（英）
- 中文拼音（英） -> 英文输入法 -> 中文输入法 （会重置为“中”）

录屏大概就是这个样子：

https://user-images.githubusercontent.com/26806995/152699185-21da16ac-bacc-451c-b2f5-ab22f101352e.mp4

如果这是ibus上游的问题请告知，我可以去那边看看写个新的issue，谢谢！

**Comment by epico** [comment]
我试了试其它输入法，好像也有这个问题。可以去 ibus upstream 用英文问问，我现在不确定是哪里的问题。

麻烦报告问题后，把问题链接粘贴到这里，谢谢！

**Comment by HymanZHAN** [comment]
ibus说这是gnome shell的问题，已经在gnome-shell创建了问题：https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5033
