### ISSUE TITLE
双拼自然码中的零声母方案有误

### ISSUE THREAD

**Issue by zhong-zi-wen** [libpinyin/ibus-libpinyin#35]
零声母方案详见https://zh.wikipedia.org/zh-hans/%E5%8F%8C%E6%8B%BC#.E4.B8.BB.E8.A6.81.E5.8E.9F.E7.90.86
目前输入法自然码采用的是第一种零声母方案，而自然码应采用第三种方案。
如“安”，应为'an'，而非'oj'；
“啊”，应为‘aa’，而非'oa'。

**Comment by epico** [comment]
Draft code landed on libpinyin and ibus-libpinyin master branch.

**Comment by epico** [comment]
As libpinyin 1.2.91 is released, close issue.
