### ISSUE TITLE
Unexpected characters when typing in Traditional Chinese with Intelligent Pinyin input [Ubuntu 21.10]

### ISSUE THREAD

**Issue by berglh** [libpinyin/ibus-libpinyin#350]
My girlfriend is Taiwanese and when I speak to her online, I try to speak with her in Mandarin as much as possible.  However, with this version of ibus-libpinyin (1.12.0), I notice that some of the traditional characters do not match those of Taiwan Mandarin as I would expect.

![爲什麼](https://user-images.githubusercontent.com/12455338/153696019-e36516bd-9e26-41b1-9654-2dc13242e492.png)

When I type `wèishéme` in pinyin, I expect to see the characters: 為什麼, however, I am seeing the characters 爲什麼.  It is stated that:
> This term, 爲什麼, is a variant traditional form of 為什麼.

Similarly, if I type 臺灣, I would expect to see 台灣.  My guess is that I'm doing something wrong or using something incorrectly.

I am not sure how to get the expected traditional character set to work for libpinyin.  I've tried some of the other libraries, such as Chewing, and I've noticed the same thing.  I am wondering if this a problem with the Chinese Traditional language support in Ubuntu or with the ibus input library as I can see 為什麼 rendered correctly.

I've been able to use Chinese (Pinyin) input (`ibus-pinying`) before and had the traditional characters I expected, however, it appears that this is now deprecated and is not compatible with the new GTK versions.

I have in addition tried `ibus-m17n`, `ibus-chewing` and selected the Hanyu input (which should be pinyin), and I seem to get the same result regardless of the input method.  This input library `ibus-libpinyin` looks like the best `ibus` input library, so I would hope to continue using this one if possible.  I'd appreciate any advice that you can offer.

**Comment by epico** [comment]
Maybe you can ask libchewing upstream, I think they know Traditional Chinese better than me.

Also there is ibus-libzhuyin project, maybe you can try it if you want.

**Comment by berglh** [comment]
@epico I did find some projects like this but they seemed a bit abandoned and didn't work with the newer versions of ibus/GTK/gnome. I will take your advice and try.  I really like the polish of Intelligent Pinyin input, it's a great library, I just wish it worked with traditional as I expected, forgive my naivety. 

@ping-wu I have not learned the bopomofo phonetic system yet, I do have a bopomofo keyboard though, but being a native English speaker, I find pinyin easier to write mandarin.  I would prefer to have confidence in the input method to know traditional Chinese better than myself, I am still learning the correct characters, and sometimes I need to rely on the contextual phonetics to get the correct Chinese character.  I had no problems in the past with the input method until Ubuntu 21.10.  Thank-you for your suggestions, there are some options here for me to try.

**Comment by epico** [comment]
> The problem with ibus-libzhuyin is that it only allows the bopomofo keyboard. Most of us who do not live in Taiwan don't know how to use it. (Unless there are some tricks that I am not aware of?)
> 
> Take my words back. I can actually choose hanyu pinyin keyboard. However, I was not able to list candidates, making this method very awkward to use.
> 
> I am correcting myself. I can use the down cursor to show candidates in ibus-libzhuyin. To input “台灣” instead of 臺灣“ in traditional Chinese, simply create a dictionary file then import it into ibus-libzhuyin. However, this method does not work in ibus-libpinyin.

The ibus-libzhuyin project also supports Hanyu Pinyin keyboard layout.

The ibus-libzhuyin code is written by me, and also uses libpinyin.

**Comment by berglh** [comment]
@epico I tried ibus-libzhuyin, and the pinyin mode does work, however, in Ubuntu 21.10 (Gnome 40), there is no candidate list and the input is only working in the Activities search menu. If I tried to type in any application, the keyboard is not working. Only seems to provide input in this search menu, and there are no hints to show similar words. Do you have any ideas about this problem?  ibus-libzhuyin didn't have a new release for over a year, so I'm wondering if this is a compatibility issue?
![pinyin](https://user-images.githubusercontent.com/12455338/156856251-c521fda6-0144-43b6-b004-5d83ce8b735d.png)

**Comment by epico** [comment]
Please press the down arrow key.

**Comment by berglh** [comment]
@epico Thanks, that is working. I also might add, I needed to change the input method per window for it to actually work at all. For the time being I will be happy with this. Thanks again, I will close this one. ibus-libzhuying was the solution for me.
