### ISSUE TITLE
QT应用无法使候选字输入

### ISSUE THREAD

**Issue by LawrenceZhang** [libpinyin/ibus-libpinyin#355]
系统版本：Centos 7.3.1611
ibus：1.5.17
ibus:-gtk2:1.5.17
ibus-gtk3:1.5.17
ibus-libpinyin 1.6.91
ibus-qt 1.3.2
ibus是系统自带的，ibus-qt是通过yum安装的。

在QT应用中切换中文输入法，敲击键盘时，可以出现候选框，但是按数字键选中，空格选中，回车选中都没有用，候选框会直接消失，选中的候选字也没有输入。在中文输入法状态，按键盘上的数字键，也无法输入。

PS：我有设置以下环境变量：
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
GTK_IM_MODULE=ibus

**Comment by epico** [comment]
请问您使用的 QT 版本号是？

**Comment by LawrenceZhang** [comment]
QT的版本号是4.8.7

**Comment by epico** [comment]
建议用英文问问 ibus upstream.

URL: https://github.com/ibus/ibus/issues
