### ISSUE TITLE
How to input "路jing"

### ISSUE THREAD

**Issue by NoSugarCoffee** [libpinyin/ibus-libpinyin#357]
## basic infos
ibus version 1.5.22
system: Ubuntu 20.04.4 LTS

## question
I want to input "路jing" like below, but only can input "路径". How can i troubleshooting with this. I have no idea. could you give me some advices? thanks a lot.
![image](https://user-images.githubusercontent.com/25247325/164959401-17572040-451b-42f2-bce9-7958788086df.png)

It's not problem with libpinyin, also have same problem in sunpinyin

**Comment by epico** [comment]
请用中文模式输入 “路”，切换到英文模式输入 "jing" .

**Comment by NoSugarCoffee** [comment]
> 请用中文模式输入 “路”，切换到英文模式输入 "jing" .

是不是理解错了？我要输入的是正常的`路径` 两个在中文字， 但是 jing 打不出来

**Comment by NoSugarCoffee** [comment]
我知道为什么理解不了，我截图下

![image](https://user-images.githubusercontent.com/25247325/164966655-91b0b34f-238f-4bd2-be17-591a0bce69bd.png)

**Comment by epico** [comment]
刚刚在 Ubuntu 21.10 上测试了一下，能够复现此问题。

可能是 Ubuntu 打包的问题，建议汇报到 Ubuntu Launchpad, 可以抄送我。

**Comment by NoSugarCoffee** [comment]
可以根据[ubuntu修复中文字体渲染问题](https://blog.airme.net/1015/ubuntu%E4%BF%AE%E5%A4%8D%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%E9%97%AE%E9%A2%98/) 解决
