### ISSUE TITLE
ibus-libpinyin doesn't work for many apps on Ubuntu 22.04

### ISSUE THREAD

**Issue by larryw3i** [libpinyin/ibus-libpinyin#358]
ibus-libpinyin doesn't work for many apps on Ubuntu 22.04, hope that you @epico could test it in your spare time, this is a common problem maybe, and not just on my computer. "Thank You for Your Service".

**Comment by epico** [comment]
Could you provide more information?

Chinese issue report is also okay here.

**Comment by epico** [comment]
I tried with Ubuntu 22.04 desktop iso, it seems work.

**Comment by larryw3i** [comment]
@epico   

https://user-images.githubusercontent.com/24457116/165762678-8f199c34-0553-4767-92d1-3f7f112d159a.mp4

Then I really don't know why, could it be because my system language is English?

**Comment by solrafa** [comment]
Same thing here:
I installed chinese language and can switch pressing Super + Space
In the shell, I can entry chinese characters
However, any other application accept the chinese characters 

![Captura de tela de 2022-04-28 23-27-51](https://user-images.githubusercontent.com/5498606/165877043-69775b0e-11d0-48eb-9ac6-a37568f38faf.png)

![Captura de tela de 2022-04-28 23-28-16](https://user-images.githubusercontent.com/5498606/165877053-f52c734a-64bc-4479-aee2-56987119f3a1.png)

**Comment by epico** [comment]
Maybe in English locale, the ibus is not enabled, but not sure about this.

**Comment by larryw3i** [comment]
> Maybe in English locale, the ibus is not enabled, but not sure about this.

I'm sure that's it.

**Comment by epico** [comment]
Please report this issue to Ubuntu launchpad, thanks!

**Comment by solrafa** [comment]
Thanks!

Finally I've solved with this command:

`gsettings set org.gnome.desktop.interface gtk-im-module 'ibus'`

https://askubuntu.com/questions/1405101/japanese-input-candidate-window-appears-at-the-bottom-after-upgrading-ubuntu-fro

**Comment by larryw3i** [comment]
@solrafa Ok, it works for me now, I appreciate your help.

**Comment by epico** [comment]
Great to hear that you solved this problem, thanks!
