### ISSUE TITLE
"[,] [.] flip page" option conflicts with period in built-in calculator

### ISSUE THREAD

**Issue by dongsibo** [libpinyin/ibus-libpinyin#363]
When _Pinyin mode > Input Custom > [,] [.] flip page_ is enabled in _ibus-libpinyin_'s preferences, the period cannot be used in _ibus-libpinyin_'s built-in calculator (obtained from pressing _i_, then _js_ for "计算模式") to enter numbers with decimal points (e.g., 2.5). In other words, pressing the period key does nothing in the calculator unless _[,] [.] flip page_ is disabled.

Would it be possible to allow periods to be entered into the built-in calculator even when _[,] [.] flip page_ is enabled?

**ibus-libpinyin version:** 1.12.1

**Comment by epico** [comment]
Fixed in https://github.com/libpinyin/ibus-libpinyin .
