### ISSUE TITLE
Chinese input doesn't work when switched from French

### ISSUE THREAD

**Issue by captnfab** [libpinyin/ibus-libpinyin#366]
Version: 1.12.0

Entering characters works, but selecting a candidate doesn't since on French layout, numbers are accessed through [shift]+[&], [shift]+[é], etc..
Workaround is to switch to US keyboard first (however, some letters are at different locations).

**Comment by captnfab** [comment]
#128 would help (though, not totally fix the problem)

**Comment by epico** [comment]
I think this is to support keyboard layout like Dvorak, etc.

**Comment by captnfab** [comment]
Well, French AZERTY keyboard has keys 1, 2, etc. on shift. So, using a US/UK QWERTY keyboard helps since the layouts are similars (with some differences of course) but at least, it's possible to choose among candidates.

Though, as you said, US Dvorak, or French Bépo, and probably a lot of layouts will have the same problem of accessing candidates with numbers which aren't always at the same position, and I see no "easy" generic solution for all of those.

**Comment by epico** [comment]
Sorry for late reply, there is a work around in issue #408 .
