### ISSUE TITLE
输入法没有出候选框

### ISSUE THREAD

**Issue by yayiji** [libpinyin/ibus-libpinyin#368]
我算是完全的Linux入门者，第一次在台式机上安装Ubuntu(22.04)，但是切换到中文输入法后，输入时没有候选框出现，还是和英文的状态下的模式一样，不知该如何解决

![Screenshot from 2022-06-28 13-01-15](https://user-images.githubusercontent.com/12449762/176096940-9920371d-9ae3-48c8-8f1f-180da8d59f55.png)

**Comment by epico** [comment]
切换到中文环境试试？

**Comment by yayiji** [comment]
氣死，重啓解決了
