### ISSUE TITLE
准备安装UBT22.04前，想导出“用户词典”，但是保存后，在保存路径下却找不到？

### ISSUE THREAD

**Issue by stevenGu** [libpinyin/ibus-libpinyin#369]
准备安装UBT22.04前，想导出“用户词典”（ibus智能拼音1.11.1版），但是保存后（显示路径 usr/share/ibus-libpinyin/setup），在保存路径下却找不到刚刚保存的文件？用了UBT2020.04版本2年多，已经打开“将每个输入记录为新词汇”。

**Comment by epico** [comment]
更换一个文件名，保存到用户目录试试。
