### ISSUE TITLE
用户词库的具体格式?

### ISSUE THREAD

**Issue by ivill** [libpinyin/ibus-libpinyin#37]
User data -> User Dictionary 可以支持导入词库，有几个问题没弄明白:
1. 词库导入后存放在什么位置?
2. 自带的词库存放在哪里了？ 
3. /usr/share/ibus-libpinyin/db/strokes.db 这个是什么?
4. 类似/usr/share/ibus-libpinyin/db/strokes.db 这样的文件(sqlite db)如何转换成可以导入的词库，比如 
https://code.google.com/p/hslinuxextra/downloads/list 这里下载的ibus词库内容是这样的:

    ``` 
    $ sqlite3 sougou-phrases-full/ibus/android.db
    SQLite version 3.8.10.2 2015-05-20 18:17:19
    Enter ".help" for usage hints.
    sqlite> .tables

        py_phrase_0   py_phrase_12  py_phrase_2   py_phrase_6
        py_phrase_1   py_phrase_13  py_phrase_3   py_phrase_7
        py_phrase_10  py_phrase_14  py_phrase_4   py_phrase_8
        py_phrase_11  py_phrase_15  py_phrase_5   py_phrase_9

    sqlite> select * from py_phrase_0 limit 10;

        的|7680|4|29
        了|7679|10|29
        我|7678|19|44
        是|7677|17|34
        在|7676|22|25
        你|7675|12|34
        和|7674|7|29
        有|7673|21|46
        不|7672|1|47
        就|7671|8|43
    ``` 
这样的内容如何转换成ibus-libpinyin要求的 "phrase pinyin [frequency]" (不明白sqlite db table中的那些数字究竟是什么...) ?

**Comment by epico** [comment]
词库导入后存放在 ~/.cache/ibus/libpinyin/ 。
自带的词库存放在 /usr/lib64/libpinyin/data/ 。

/usr/share/ibus-libpinyin/db/strokes.db 是按 "u" 用笔画输入汉字用的，和词库无关。

其实，你可以问问 hslinuxextra 的作者能否提供格式为 "phrase pinyin" ("你好 ni'hao") 的数据。
深蓝词库转换好像是支持 libpinyin 的倒入格式的。
猜测 ibus-pinyin 的格式是 汉字 id 声母id 韵母id。
