### ISSUE TITLE
繁體模式：沒有「吃」反而是用「喫飯」

### ISSUE THREAD

**Issue by imfulee** [libpinyin/ibus-libpinyin#370]
我有看到之前有個 issue #26 #329 也有類似的問題，例如「裏」「羣」這些字都和原本臺灣、香港通常會看到的字體不一樣，我只是想問說有沒有辦法修復這個問題？雖然我嘗試使用 libchewing 但我偶爾還是要用到簡體字所以簡體繁體切換對我來說蠻重要的（況且我自己還是比較習慣 libpinyin 的輸入方法）。我也願意嘗試幫忙修正這個問題，只是因爲我本身沒什麼開發 C++ 的經驗，希望可以指導我到相關的 file 和測試的方法～

**Comment by epico** [comment]
Maybe you can try ibus-libzhuyin project.

**Comment by imfulee** [comment]
Yea I did, it was good, and am currently using it but when I used it websites say HackMD, it wouldn't work properly (i.e. when I'm choosing the words and all, the cursor would not work properly) so I prefer the way libpinyin handles it. That's why I wonder if there's a way I could help contribute to the project or something that would help this?

**Comment by epico** [comment]
Please compile ibus-libpinyin with opencc support.

There is one opencc config in ibus-libpinyin, maybe you can change that option in dconf.

**Comment by ping-wu** [comment]
目前使用 ibus-libpinyin 繁體中文輸入最大的問題在於無法擴充使用者字庫。如果 Epico 能把一些常用的繁體字如 “吃”，“台” 等加入系統的繁體中文字庫，問題就解決了。

**Comment by epico** [comment]
ibus-libpinyin 使用的方法是簡體/繁體轉換，可以在設置對話框中導入一些繁體字庫試試。

**Comment by ping-wu** [comment]
Do you mean that we can use different user data for simplified Chinese and traditional Chinese, respectively?

**Comment by epico** [comment]
For the ibus-libpinyin project, there is only one data for Simplified Chinese. And for Traditional Chinese, the data is converted from Simplified Chinese.

**Comment by imfulee** [comment]
Thank you @epico  @ping-wu for what you have suggested, it now works flawlessly for me. For people that come across this in the future and wants more clarification the reply that @epico talked about 

> Please compile ibus-libpinyin with opencc support.
> 
> There is one opencc config in ibus-libpinyin, maybe you can change that option in dconf.

Using Pop OS 22.04, one way you could do it is install `dconf-editor` and find `libpinyin` with the search bar (Mine was under the directory of `/com/github/libpinyin/ibus-pinyin/libpinyin/opencc-config`) and change the default value from `s2t.json` to `s2tw.json` (or you could change it based on the [arch wiki  about `fcitx5`](https://wiki.archlinux.org/title/Fcitx5#Customizing_Traditional_and_Simplified_Chinese_conversion) ) 

![Screenshot from 2022-12-06 10-23-26](https://user-images.githubusercontent.com/40764288/205793747-8b351122-f81e-48a1-94e1-3863ecc1f0c5.png)

If that doesn't work for you, you could try re-compiling `ibus-libpinyin` (and/or `libpinyin`) yourself too. Here's a ![guide](https://forum.ubuntu.org.cn/viewtopic.php?f=8&t=491327) that @ping-wu provided years ago, but I never made it past the `checkinstall` step, so your mileage may vary. 

需要華語翻譯再找我吧，我懶惰寫了哈哈
