### ISSUE TITLE
最新版输入法在IntelliJ IDEA 2022.1.3 (Ultimate Edition)中打字有bug

### ISSUE THREAD

**Issue by xiaoduanayu** [libpinyin/ibus-libpinyin#371]
OS版本：Ubuntu 22.04 LTS
输入法版本：1.12.1
IntelliJ IDEA版本：2022.1.3
bug现象：在IDEA中输入中文时，打着打着就没有中文了，会自动插英文，然后就再也打不了中文了
[录屏 2022年07月13日 18时10分04秒.webm](https://user-images.githubusercontent.com/16379980/178709692-9b184487-6136-4490-8bcc-ba366a1d01ad.webm)

**Comment by epico** [comment]
在设置对话框里，将显示风格设置为兼容模式试试。

**Comment by xiaoduanayu** [comment]
> 在设置对话框里，将显示风格设置为兼容模式试试。

试过了，BUG更多了。重启过电脑试了下也是不行。 @epico

**Comment by miaoerwu** [comment]
这个bug我记得是jbr的问题，在[bug](https://youtrack.jetbrains.com/issue/JBR-4394/Intellij-Idea-dont-work-with-ibus-pinyin-since-202013)显示这个bug已经被修复了，预计在2022.2版本会发布

**Comment by xiaoduanayu** [comment]
> 这个bug我记得是jbr的问题，在[youtrack](https://youtrack.jetbrains.com/issue/JBR-4394/Intellij-Idea-dont-work-with-ibus-pinyin-since-202013)显示这个bug已经被修复了，预计在2022.2版本会发布。这里有临时解决方案[issues](https://github.com/libpinyin/ibus-libpinyin/issues/289)

临时方案有效，问题解决了，谢谢！
