### ISSUE TITLE
Inputting Chinese Characters with On-Screen Keyboard?

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#372]
OS: Debian 12 (Bookworm), DE: Gnome 4.2, ibus-libpinyin version: 1.12.1

I can turn on ibus-libpinyin when in on-screen keyboard mode, but it has no effect.  Has anyone been able to input Chinese characters when using on-screen keyboard?

This problem is most likely related to ibus, but just wonder if anyone has any success.

**Comment by epico** [comment]
Are you using wayland display server?

**Comment by ping-wu** [comment]
yes, I'm using Wayland

**Comment by epico** [comment]
This issue is related with mutter project.

**Comment by epico** [comment]
Maybe you can report this issue to Debian 12.
