### ISSUE TITLE
按shift上屏已输入字符的顺序问题

### ISSUE THREAD

**Issue by xuke-hat** [libpinyin/ibus-libpinyin#375]
我用的版本是1.12.91的小鹤双拼模式，发现中文模式下上屏的逻辑是这样的：如果不是小写英文就会直接输入，剩下的小写英文会留在输入法的缓冲区里。
但这样的话有时候中文模式下输入英文会出现顺序问题，比如想打c++但是没有切换成英文模式，++会直接上屏，c会留在缓冲区里，这时候再按shift会变成++c。感觉改成别的输入法一样如果缓冲区非空就把符号和数字也留在缓冲区，按shift的时候一起上屏会更好？

**Comment by epico** [comment]
请问别的拼音输入法指的是哪个输入法？

**Comment by xuke-hat** [comment]
> 请问别的拼音输入法指的是哪个输入法？

windows的微软拼音和ios的默认输入法都是这样的

**Comment by epico** [comment]
已在英文输入模式中改进该功能。
