### ISSUE TITLE
Fedora36 Gnome日历中无法输入中文记事，输入法图标消失

### ISSUE THREAD

**Issue by TonyTeng22** [libpinyin/ibus-libpinyin#377]
![输入法在日历bug](https://user-images.githubusercontent.com/104058725/187025825-97d6a610-22f3-49d8-af61-9963adae2e64.jpg)

**Comment by epico** [comment]
建议用英文到 ibus upstream 汇报一下问题。

URL: https://github.com/ibus/ibus/issues
