### ISSUE TITLE
如何关闭按键u、v的特殊功能

### ISSUE THREAD

**Issue by huweiATgithub** [libpinyin/ibus-libpinyin#379]
v可以切换到英文单词输入，不过不是很习惯
（习惯于在中文模式下，直接输入英文单词然后回车，因为v触发了特殊功能，所以经常输完发现少了一个v。）
如何关闭这个功能呢？

**Comment by epico** [comment]
在 ibus-libpinyin 1.13.0 中，在首选项对话框的用户数据页面关闭英文模式即可。

**Comment by ping-wu** [comment]
Probably can use a different pair of keys (or key combos) to replace u and v, respectively.

**Comment by huweiATgithub** [comment]
Unfortunately, Ubuntu 20.04 does not have the latest version.

**Comment by FranklinYu** [comment]
> 在 ibus-libpinyin 1.13.0 中，在首选项对话框的用户数据页面关闭英文模式即可。

非常感謝！我想改的包括「英文模式」和「英文候選詞」。小鶴雙拼要用到 `v` 🤣

**Comment by epico** [comment]
在最新版本中，可以关闭 "英文模式" 和 "英文候選詞" ...
