### ISSUE TITLE
如何修改字体大小,字体太小了。看着眼睛疼

### ISSUE THREAD

**Issue by wangyifan349** [libpinyin/ibus-libpinyin#383]
如何修改字体大小,字体太小了。看着眼睛疼。

**Comment by epico** [comment]
请问您使用的桌面环境是？

**Comment by wangyifan349** [comment]
> 请问您使用的桌面环境是？
系统是Ubuntu 22.04.1 LTS (Jammy Jellyfish)系统，桌面是GNOME 42 。

**Comment by epico** [comment]
这个功能需要安装 GNOME extensions, 才可以。

URL: https://extensions.gnome.org/extension/1121/ibus-font-setting/

**Comment by wangyifan349** [comment]
> 

似乎这个插件失效了。

**Comment by epico** [comment]
上周五，我刚刚更新了这个插件。

要不您也可以试试其他的插件。

**Comment by wangyifan349** [comment]
> 上周五，我刚刚更新了这个插件。
> 
> 要不您也可以试试其他的插件。

能否有空,帮我远程一下。修改输入法字体大小对于我这种小白来说挺费劲。。。。而且笔记本屏幕本来就小,实在是小的离谱了

**Comment by epico** [comment]
请用 `gnome-extensions install ibus-font-settingibus.github.com.v12.shell-extension.zip`, 安装这个扩展。

然后用 `gnome-extensions-app` 来启用这个扩展。

**Comment by isaaxite** [comment]
> 上周五，我刚刚更新了这个插件。
> 
> 要不您也可以试试其他的插件。

同样存在这个问题，gnome47。此 extension 仅支持到 gnome 44。请问还有其他解决方案吗？

**Comment by isaaxite** [comment]
> > 上周五，我刚刚更新了这个插件。
> > 要不您也可以试试其他的插件。
> 
> 同样存在这个问题，gnome47。此 extension 仅支持到 gnome 44。请问还有其他解决方案吗？

从 @epico 提到的 extension 得到提示，我使用 [customize-ibus](https://extensions.gnome.org/extension/4112/customize-ibus/) 解决了候选词无法调整大小的问题

**Comment by epico** [comment]
刚刚更新了这个插件，可以试一试。

URL: https://extensions.gnome.org/extension/1121/ibus-font-setting/
