### ISSUE TITLE
Uncommon characters

### ISSUE THREAD

**Issue by dheera** [libpinyin/ibus-libpinyin#387]
![197012511-6a5f8aa0-71a8-41f7-9aa2-0ac687406519](https://user-images.githubusercontent.com/1786477/197015371-a3136789-6fa2-49eb-8b65-6409c1b80c56.png)

連「吃飯」都打不了，只有「喫飯」的選擇，感覺只要某個字有異體字，ibus只能打那異體字

還有下面這些：
zongzi 糉子（-> 應該是“粽”）
qunzu 羣組（-> ”群“）
weishenme 爲什麼 （-> ”為“）

**Comment by epico** [comment]
Please try ibus-libzhuyin, thanks!

**Comment by dheera** [comment]
@epico Thanks. I installed ibus-libzhuyin but how do I tell the Pinyin input to use it?

**Comment by epico** [comment]
I think you can add a new Chinese input method called "New Zhuyin".
