### ISSUE TITLE
中英文状态(shift)切换时，systray里面的ibus-ui-gtk3图标永远是ibus-pinyin.svg

### ISSUE THREAD

**Issue by xmlscript** [libpinyin/ibus-libpinyin#39]
系统环境：https://spins.fedoraproject.org/zh_CN/xfce/

不知道icons目录下的10个svg图标是不是只是为浮动跟随工具栏准备的，反正在我环境中，libpinyin输入法内部无论如何切换，systray的图标永远是ibus-pinyin.svg。
（我暂时从别处找了一个好看的icon将其替换了）

另外一个问题，libpinyin（shift）临时切换到英文状态后，系统原生输入窗口还则罢了，如若遇到网页模拟输入区域，则按字母键不上词，需要再按空格才上词，而且空格也一起敲进去了。
可以在https://ide.coding.net 下面的终端面板里面重现这个问题。

最后请问，ibus能否设置仅用shift切换输入法（默认是super+space)，谢谢。

**Comment by epico** [comment]
是的，那些 SVG 图标是为了工具栏准备的。

对于网页的问题，需要提供能够重现 bug 的很小的 HTML 测试用例，才可能修复的。

在 ibus-setup 和 ibus-libpinyin 中，可以定制快捷键，请自行修改。

**Comment by wsdjeg** [comment]
在VIM中切换为中文, 使用 alt-tab 切换到浏览器,再立刻切换回来,输入法变为英文 但是状态实际上是中文,需要连续 ctrl+space 两次才能切换回中文

**Comment by epico** [comment]
@wsdjeg 请分开报 issue.
