### ISSUE TITLE
如何快速删除用户词组里错误的词

### ISSUE THREAD

**Issue by grassvalley** [libpinyin/ibus-libpinyin#392]
输入词组时，有时会不小心录入错误的词组。但是，这个错误的词组也会被保存下来。怎么快速删掉这个错误的词组呢？我试了 del, ctrl+del, shift+del 都不管用。

**Comment by epico** [comment]
如果这个词出现在前三个位置，重新输入可能会消失；如果这个词出现在后边的位置，可以移动光标到该词，按 Ctrl+Shift+d 键。
