### ISSUE TITLE
Intelligent Pinyin Upgraded to 1.14.91

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#393]
Just noticed (Debian Sid) that Intelligent Pinyin has been upgraded to 1.14.91, and libpinyin-data to 2.7.92-2 （libpinyin15, from libpinyin13).

Was wondering what are the main differences in this version upgrade?

**Comment by ping-wu** [comment]
Looks like the main differences are: Improve English candidates; Support longer candidates; Improve Suggestion candidates; etc:

https://salsa.debian.org/debian/ibus-libpinyin/-/blob/master/ChangeLog

For my own benefit (learning), info about libpinyin15:

https://salsa.debian.org/debian/libpinyin/-/commit/8cf9ad3455efd521b1393ed5e3965ec087cbc7b7

**Comment by epico** [comment]
The phrase suggestion candidate feature will provide some candidates which will following the previous input.

The longer pinyin candidate feature will provide one phrase candidate which is longer than the pinyin input.

**Comment by ping-wu** [comment]
I typed "zh h r" then the following candidate list shows up:

![Screenshot from 2022-11-28 07-54-15](https://user-images.githubusercontent.com/21325422/204348108-ed15ad56-edb2-4fb0-b906-375caaa3b7e5.png)

Looks great!  Thanks!
