### ISSUE TITLE
双拼模式下不支持自定义短语

### ISSUE THREAD

**Issue by burg1ar** [libpinyin/ibus-libpinyin#394]
操作系统：Ubuntu 22.04
双拼模式下，参考 https://www.liangzl.com/get-article-detail-174014.html 设置自定义短语，但不生效
双拼模式下，输入“i”并不能触发“智能模式”
测试了全拼模式下，上述方法是可以成功的
请问，双拼模式下，有无可能实现“自定义短语”的功能，感谢！

**Comment by epico** [comment]
双拼模式下，请输入 "I" 键。

**Comment by burg1ar** [comment]
感谢回复，经过测试，【双拼模式下，请输入 "I" 键】是可行的
当前好像相关文档几乎没有，建议完善一下说明文档

**Comment by epico** [comment]
@burg1ar 谢谢您的建议，刚刚更新了下 wiki page.

https://github.com/libpinyin/ibus-libpinyin/wiki
