### ISSUE TITLE
ubuntu 22.04 双拼下无法导入用户词库

### ISSUE THREAD

**Issue by burg1ar** [libpinyin/ibus-libpinyin#395]
环境：ubuntu 22.04，双拼
尝试导入用户词库，选择词库后没有任何改变（反应）

**Comment by epico** [comment]
导入成功后，确实没有提示。

**Comment by burg1ar** [comment]
![image](https://user-images.githubusercontent.com/3461895/204952582-780888e0-fe90-4c29-ae1b-eb8cc5a22eaa.png)
建议列出已导入的词库，更加友好一些

**Comment by wangyifan349** [comment]
> 环境：ubuntu 22.04，双拼 尝试导入用户词库，选择词库后没有任何改变（反应）

你是怎么倒入的，搜狗转换的吗，我一直在找能用的python3脚本来转换你可以分享下吗

**Comment by wangyifan349** [comment]
> 那有没有什么方法确认词库已成功导入呢？
> 
> ![image](https://user-images.githubusercontent.com/3461895/204952582-780888e0-fe90-4c29-ae1b-eb8cc5a22eaa.png) 建议列出已导入的词库，更加友好一些

我觉得你可以导出来看看有没有

**Comment by epico** [comment]
好像他导入的是第三方的 libpinyin-dict 词库...

URL: https://github.com/broly8/libpinyin-dict

好像是 MPL 2.0 的协议...

**Comment by wangyifan349** [comment]
> 好像他导入的是第三方的 libpinyin-dict 词库...
> 
> URL: https://github.com/broly8/libpinyin-dict
> 
> 好像是 MPL 2.0 的协议...

非常感谢你

**Comment by epico** [comment]
不客气
