### ISSUE TITLE
中文状态下怎么去掉 v 这个命令 

### ISSUE THREAD

**Issue by giwhy** [libpinyin/ibus-libpinyin#397]
每次在中文状态下输入英文单词时回车都少一个v字母，太不习惯了。
有没有对应设置取消掉，实在找不到这个设置。

**Comment by epico** [comment]
在 ibus-libpinyin 1.13.1 或者更高版本，可以在设置对话框的用户数据页面关闭英文模式。

**Comment by giwhy** [comment]
安装了 1.13.1版本后 解决了我的问题 感谢
