### ISSUE TITLE
GNOME 3.16 下ibus-libpinyin的菜单没有显示

### ISSUE THREAD

**Issue by tonghuix** [libpinyin/ibus-libpinyin#40]
系统环境 Debian Testing Stretch + GNOME 3.16

这也是六月份突然就不显示了，另一台电脑部署的是完全一样的环境，并没有出现这个问题。

与此同时，还会出现中英文切换失效，需要先切换到 ibus-pinyin，激活一下，然后再切换回 libpinyin 就可以了。

这是 ibus-libpinyin 和 ibus-pinyin 的对比：
![ibus-libpinyin](https://cloud.githubusercontent.com/assets/423703/10174345/f311c7ba-671b-11e5-84ea-8f322eeef745.png)

**Comment by epico** [comment]
试试清理下 ~/.cache/ibus/libpinyin.

方便的话，请用 tar ball 发邮件给我 ~/.cache/ibus/libpinyin 中的内容。

**Comment by tonghuix** [comment]
删除 `~/.cache/ibus/libpinyin.`下所有文件以后，问题解决。

tar ball 已经邮件发你咯
