### ISSUE TITLE
['] cannot be used to separate pinyin when English is enabled

### ISSUE THREAD

**Issue by dongsibo** [libpinyin/ibus-libpinyin#418]
In previous versions of *ibus-libpinyin*, the apostrophe `'` could be used to separate pinyin, for example, to type `zeng'e` instead of `zen'ge`. However, when *User data > Input Modes > English Mode* is enabled in the preferences, this no longer happens since typing an apostrophe after some pinyin (e.g., `zeng'`) causes an unwanted transition into English mode.

**ibus-libpinyin version:** 1.15.2

**Comment by epico** [comment]
Fixed in https://github.com/libpinyin/ibus-libpinyin .
