### ISSUE TITLE
xfce4 panel tray icon flashing during window focusing

### ISSUE THREAD

**Issue by WXZhao7** [libpinyin/ibus-libpinyin#419]
I use `Intelligent Pinyin 1.12.1` in XFCE4+Ubuntu22. The tray icon flashed during the window focusing. I set the global input method in ibus as here:
![image](https://user-images.githubusercontent.com/56864878/233523506-7b9b1101-2c77-4e48-aad2-dc998cd928b0.png)

Please notice the tray icon `拼` top right corner. It flashed between `拼` and `中`/`英`.

https://user-images.githubusercontent.com/56864878/233524065-6a3f296a-16d2-4824-8266-0e3d329f8273.mp4

**Comment by epico** [comment]
请用英文在 ibus upstream 开个 issue, 谢谢!

URL: https://github.com/ibus/ibus/issues

**Comment by WXZhao7** [comment]
closed according to https://github.com/ibus/ibus/issues/2505
