### ISSUE TITLE
Hotkeys "Shift+Space" and "Shift+." not working

### ISSUE THREAD

**Issue by camiloaa** [libpinyin/ibus-libpinyin#42]
Documentation states that "Shift+Space" toggles full/half latin Mode, and "Shift+." toggles full/half punctuation. Neither works.

## How to reproduce:
1. Select input mode "ibus-pinyin".
2. Configure it for "half mode."
3. Press space bar and 'a'.
4. Press "shift+space."
5. Press space bar and 'a'.

## Whats the result?
Both step 3 and 5 produce "half mode" characters (' a').
After step 4, the "full/half mode" indicator doesn't change.

## What's the expected result?
Step 3 should produce a normal space followed by 'a' (aka ' a', aka 0x20 0x61).
Step 4 should cause "full/half mode" indicator to toggle.
Step 5 should produce a full size space followed 'ａ' ('　ａ').

**Comment by epico** [comment]
For ibus-libpinyin, you can customize the shortcut keys in the setup dialog.

**Comment by camiloaa** [comment]
PBKAC. I was using "ibus-pinyin" instead of "ibus-libpinyin".
