### ISSUE TITLE
【功能请求】禁用英文模式后，字母 v 不直接上屏而是放进候选框里

### ISSUE THREAD

**Issue by gdh1995** [libpinyin/ibus-libpinyin#420]
禁用英文模式、启用“英文候选词”后，能不能把 `v` 放到候选框里，而不是直接上屏？

这样 view、vue 这种单词就可以整个回车了，也能利用上英文单词的补全机制，而不是看半个 `iew` 莫名其妙地单独在候选框里。

如果不确定哪个好，能不能再加个配置项 😂

算是对 https://github.com/libpinyin/ibus-libpinyin/issues/318 的补充。

**补充1：** 发现 i、u 这种不能组成拼音的，都会直接上屏，但我觉得放到候选框会更好，比如我想输入 `input` 的时候，i 直接上屏了就有点怪。

另外，有个小问题：`u` 的笔画输入模式似乎也没有开关？我在首选项里没找到

**Comment by epico** [comment]
笔画输入模式现在叫码表模式。

**Comment by lzw-jm** [comment]
这个是已经解决了吗?我现在的v还是不能直接上屏幕

**Comment by epico** [comment]
这个功能请求是 `v` 不直接上屏啊。

**Comment by wangzz-lzw** [comment]
现在是这样子的,中文模式我输入vue这三个字母的时候,得连着按两下v,只按一下的话然后回车就成了ue这两个字母了..

**Comment by epico** [comment]
@wangzz-lzw 试试关掉用户数据页面的英文模式...

**Comment by OnceAce** [comment]
希望能分别提供不启用 i、u、v模式的选项。如果我三个选项都不启用，我期待我输入input在候选框，然后shift切换英文模式就直接上屏

**Comment by epico** [comment]
@OnceAce 在设置对话框的用户数据页面中，关闭 Lua 脚本模式，码表模式和英文模式选项即可。
