### ISSUE TITLE
【问题反馈】候选框显示时，大写字母立即上屏导致单词被删、字母乱序

### ISSUE THREAD

**Issue by gdh1995** [libpinyin/ibus-libpinyin#421]
最新版 1.15.2，手动编译开启了云词库、在 Chrome 112 + Ubuntu 22.04 上遇到此问题：

## 问题复现
1. 想输入 `HostBuffer`
2. 按下 `H` 后立即上屏
3. 按下 `ost` 后，输入法显示候选框，内容是针对 `ost` 猜测的组词，浏览器网页上显示带下划线的 `ost`
- 1. 虽然猜的词不可能对，但不影响我使用
- 2. 和 https://github.com/libpinyin/ibus-libpinyin/issues/420 属于同一类问题，有的键（这次是`H`）被立即上屏了，但如果放候选框里，感觉会更好
- 3. 如果不确定哪个好，能不能再加个配置项 😂
4. 按 `B`，原来上屏的“带下划线的 `ost`”被替换为大写字母 `B`，而候选框内容不变，仍然是 `ost`
5. 按 `uffer`，候选框内容变成了 `ostuffer`，按回车后可以上屏到 `B` 右边

我觉得目前这种流程很不好，影响我临时打长串单词，如果把“大写字母立即上屏”改成添加到候选框里，就显得自然了。

## 修复建议
添加一个配置项，在启用时输入法应该：

1. 最好是在中文模式下，对所有不组词的字母，比如大写字母、`v`和`u`，都显示到候选框里，回车再上屏
2. 如果方案 1 不够有说服力，至少应当在候选框里有内容时，对追加输入的大写字母等不立即上屏

**Comment by ping-wu** [comment]
？？？
要输入英文时，当然就要按 shift 键转为英文输入模组。我实在不知道问题在那里？？？

**Comment by gdh1995** [comment]
输英文不需要shift啊，要汉字我按回车、1234，要英文我就回车，微软拼音和搜狗拼音就这样。

**Comment by ping-wu** [comment]
你所建议的“新”功能在 1.15.1 里已有了。在 ibus-libpinyin 的 preerence 里，把 English mode 打开，就可以输入 “HostBuffer”：

![Screenshot from 2023-05-09 06-43-44](https://github.com/libpinyin/ibus-libpinyin/assets/21325422/b138faaa-e8d9-47a9-b42d-4890d543b155)

这个功能印象中好像有一点问题，一般我们都是关掉的（也许在 1.15.1 里已经解决了？？？）。输入英文时，使用 shift 键已习惯了。

**Comment by gdh1995** [comment]
我不喜欢 `v` 模式，它会造成 `view` 回车变成 `iew`。所以我自己下载编译了最新版 ibus-libpinyin 来让我的 ubuntu 22 能关掉 `v` 模式。这个是背景了，感谢你们能添加这个开关。

我习惯上不用 shift 切换，因为我自己也开发程序，写文档的时候经常要中英文混输，shift 切换太影响我的输入效率了。

不过如果你们觉得 shift 切换的方式更明确，那我也接受。我这个 issue 的核心想法是，如果已经输入了一些字母显示到候选框里，这时候按 Shift+字母 会立即上屏，而不是追加到候选框，这个造成输入顺序和实际打出来的字完全不同，在临时输入 驼峰命名的变量名 时很难受。能不能至少把这个情况特殊处理一下？

**Comment by epico** [comment]
可能您想输入 Vue 或者 View。如果你想在 ibus-libpinyin 全拼模式下，输入 view, instance，则你需要关闭 英文模式，Lua扩展模式和码表模式。

英文模式只是需要输入 v 来激活而已，或者大写字母也可以切换到英文模式。

ibus-libpinyin 的设计并不支持 i/u/v 输入到 preedit。也需要我可以改改看，但是如果引入其他 bug 的话，我只好 revert 这些修改。

**Comment by gdh1995** [comment]
我已经关了这些。目前最影响我使用的还是标题里说的，“大写字母无视候选框文字立即上屏”造成文字顺序和输入顺序不同，不知道好不好改。我昨天看了会这个项目英文模式的处理代码没看懂……

**Comment by ping-wu** [comment]
启动 v 模式可以使用自建的英文词库，不知道搜狗或 rime 有没有这个功能？

我曾使用过 rime，因为它的词库很强大，刚开始很好用，曾建议 Ubuntu 的预设中文输入改为 rime。但后来发现问题很多，configuration 越来越乱，而且中文繁简体字常常搞混，就又转回 ibus-libpinyin 了。

**Comment by gdh1995** [comment]
然后，微软拼音的 `v` 长这样
 ![image](https://github.com/libpinyin/ibus-libpinyin/assets/5547703/24a02966-0541-4427-9ed5-d7c6623eac93)

但继续输入 `iew` 的话就变成
![image](https://github.com/libpinyin/ibus-libpinyin/assets/5547703/4bd81682-f2f8-45eb-b9f7-2f510d3ba77e)
![image](https://github.com/libpinyin/ibus-libpinyin/assets/5547703/efb79316-7a14-49e1-b658-5477f2180237)

搜狗类似。

=============

如果你觉得 shift 更好，也不想加新的配置项来让用户手动启用新的模式，随你吧。首字母直接上屏我也能接受，毕竟顺序没乱只是没有词典补全了。

**Comment by gdh1995** [comment]
顺带请问你是 libpinyin 项目的开发者吗？还是主要负责社区答疑的协助人员，又或者是个普通路人？

**Comment by ping-wu** [comment]
@dgh1995 > 呃先别讨论习惯不习惯了，我想确认一句：全拼、禁用英文模式下输入 `hostBuffer` 回车，结果上屏的变成 `hBostuffer`，这个事情算不算 bug？

我试了一下 v 模式，问题很多，根本不稳定。我使用的是 ibus-libpinyin v. 1.15.1 (Debian Sid)，可能因为最近 “增加” 功能的关系，引进了 bugs，跟我以前使用的经验完全不同。如果有更好的中文输入方法可以在 Linux 里使用，请告知。

**Comment by epico** [comment]
这个问题回来我看一下。

**Comment by ping-wu** [comment]
如果第一个字母不是大写则必须启动 v 模式，如下：

![test resized](https://github.com/libpinyin/ibus-libpinyin/assets/21325422/8b16a8e6-9705-4c8c-b753-35bcec8145f7)

hostBuffer 这个字已被 cached 到 v 模式的英文字库，因此出现在候选词里。我们公司的(桌面）作业系统是  Debian Sid，员工必须根据公司的SOP来操作，使用 ibus-libpinyin 完全没有问题。一般 Linux 桌面使用者总是希望开发者能配合自己以前的习惯修码，这当然没有问题，但希望在修改程式时注意到长期，公司使用者的过去所投入时间。尤其不要引入新的 bugs。

**Comment by epico** [comment]
Fix in https://github.com/libpinyin/ibus-libpinyin .

其实，我也不知道这个功能会不会引起其他问题；如果有的话，可能会 revert 这个 patch.

**Comment by gdh1995** [comment]
我今天晚上拉代码测了一下，确实能显示候选框了，输入`HostBuffer` 也不会乱序，谢谢。

**Comment by epico** [comment]
不客气

**Comment by gdh1995** [comment]
补充一个小问题，可改可不改的那种：

最新 commit 版本输入 `vie` 时没有候选词，只有输入了 `view` 才会给出 `view` 和 `views` 两个候选，不知道方不方便改成在 `vie` 或者 `vi` 的时候就给出若干英文单词作为候选词。

编译选项里开启了云输入 `--enable-cloud-input-mode`

**Comment by epico** [comment]
可以自行修改 src/PYPEnglishCandidates.cc 中的 MINIMAL_ENGLISH_CHARACTERS 常量。

个人不推荐修改这个常量。
