### ISSUE TITLE
如何编写 lua 脚本？

### ISSUE THREAD

**Issue by caijiMK** [libpinyin/ibus-libpinyin#422]
我无法找到任何关于编写用户 lua 脚本的文档，有人能教教我吗？
我尝试阅读 base.lua，但我仍然无法搞懂一些内置的模块的用法（比如 `ime`）。
请问是否已经有文档，只是我没有看到？如果有，能给我一个链接吗？
十分感谢！

**Comment by schemacs** [comment]
FYI:
- [Google拼音输入法 API 开发指南_知识库_博客园](https://kb.cnblogs.com/page/116147/)
- [谷歌拼音输入法扩展API开发指南-51CTO.COM](https://www.51cto.com/article/293595.html)
- [Google 黑板报: 用扩展来优化谷歌拼音输入法——U模式部件输入](https://china.googleblog.com/2009/12/u_2830.html)
-  [Google 黑板报: 用扩展来优化谷歌拼音输入法----I模式扩展输入](https://china.googleblog.com/2010/04/i.html)
- [008 谷歌拼音输入法扩展——数字序号](https://dramatea.github.io/008 谷歌拼音输入法扩展——数字序号.html)

**Comment by caijiMK** [comment]
感谢！
