### ISSUE TITLE
cloud input feature needs to be ported to libsoup3

### ISSUE THREAD

**Issue by jbicha** [libpinyin/ibus-libpinyin#423]
ibus-libpinyin's cloud input feature uses libsoup 2.4 . The latest version of libsoup is libsoup3. Linux distributions would like to remove the old library from their archives. Therefore, please switch to libsoup3.

References
----------------
- https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html
- https://gitlab.gnome.org/GNOME/libsoup/-/issues/218

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .

**Comment by epico** [comment]
Thanks for the report!

The ibus-libpinyin 1.15.4 package is released, close issue.
