### ISSUE TITLE
中文模式下，启动大写锁定，输入大写字母，关闭大写锁定后再尝试输入中文会出现字母v

### ISSUE THREAD

**Issue by EnderTheCoder** [libpinyin/ibus-libpinyin#426]
[录屏 2023-08-15 16-31-04.webm](https://github.com/libpinyin/ibus-libpinyin/assets/47713889/7b3d859d-fe74-4152-b71c-d7afdce57075)
如题，在关闭大写锁定后会出现一个莫名其妙的字母v。请问有没有能够解决的办法？

附加信息：
输入法版本 1.5.1
系统版本 ubuntu 23.04

**Comment by epico** [comment]
Fixed in https://github.com/libpinyin/ibus-libpinyin .

**Comment by EnderTheCoder** [comment]
非常感谢，这个问题困扰了我许久！

**Comment by epico** [comment]
不客气。
