### ISSUE TITLE
云输入在哪设置？版本IBus 智能拼音 1.15.1

### ISSUE THREAD

**Issue by Randy-xuefm** [libpinyin/ibus-libpinyin#427]
如题？更新版本后，云输入的设置项看不到了

**Comment by epico** [comment]
云输入的选项需要在编译时打开的。

**Comment by Randy-xuefm** [comment]
我用以下
./configure --prefix=/usr --enable-cloud-input-mode LIBSOUP_LIBS="/lib/x86_64-linux-gnu/libsoup2.4.1" LIBSOUP_CFLAGS="1" JSONGLIB_CFLAGS="1" JSONGLIB_LIBS='/lib/x86_64-linux-gnu/libjson-glib-1.0-0'     

但是在make的时候报错

请问这两个库该如何设置


已经安装这两个库，只是版本有一点点差别

![image](https://github.com/libpinyin/ibus-libpinyin/assets/12120720/457b3217-b18d-47af-a310-bba34fd2ad27)

![image](https://github.com/libpinyin/ibus-libpinyin/assets/12120720/333b0383-38b0-47a9-aeee-11809da8724e)

**Comment by Randy-xuefm** [comment]
> 云输入的选项需要在编译时打开的。

帮忙看下 谢谢！

**Comment by Randy-xuefm** [comment]
应该是这样，要下载dev包

./configure --prefix=/usr --enable-cloud-input-mode  LIBSOUP_CFLAGS="-I/usr/include/libsoup-2.4/libsoup" JSONGLIB_CFLAGS="-I/usr/include/json-glib-1.0/json-glib" 

对C++不是很熟悉，打扰了。

建议将云输入默认打开。这个对于词库有很好的补充作用。

**Comment by Randy-xuefm** [comment]
sudo apt install libjson-glib-dev
sudo apt install libsoup2.4-dev

**Comment by epico** [comment]
出于安全原因，云输入默认关闭。

**Comment by epico** [comment]
ibus-libpinyin 1.15.4 将会使用 libsoup3 .
