### ISSUE TITLE
Firefox和Thunderbird下，想选择文字反而会删掉

### ISSUE THREAD

**Issue by nijiawen** [libpinyin/ibus-libpinyin#43]
用IBus的拼音输入法，用滑鼠或键盘选择文字反而会把字完全删除掉，文字也没有输入到buffer里面，已经害我很多次把撰著已久的小文章和信函完全删掉，现在只好用pluma 先写完再复制过来。简体繁体都会出现同样的问题，别的ibus输入法不会(已经试过英语、hanyu pinyin (m17n)和Anthy，三个都有照常的功能)，别的软体不会出现这个问题，只有Firefox和Thunderbird才会。我用的是Linux Mint 17.1下的Ibus 1.5.5。

**Comment by epico** [comment]
这个问题请先报到 Linux Mint 的 ibus 组件。

**Comment by suokunlong** [comment]
不只是 Linux Mint，我在Fedora 32 下也出现这种情况，与之前报告的键入一个字母后会连续接受输入好多次的情况有点类似。

**Comment by suokunlong** [comment]
需要说明的是，我用 ibus-rime 很久都没出现过这种情况，今天切换到 ibus-libpinyin 就出现了。

**Comment by epico** [comment]
请运行 `ibus engine` 命令，并提供命令的输出。

方便的话，请提供更详细的复现步骤。
