### ISSUE TITLE
找不到详细的安装文档:(

### ISSUE THREAD

**Issue by yx91490** [libpinyin/ibus-libpinyin#44]
我用的debian testing,因为想体验下最新版便下了源码开始编译,没有找到详细的安装文档,只好一步一步摸索,安装了好几个依赖后终于装上了,但是ibus却找不到,最终发现有个component目录是配置ibus的engine的,把xml文件拷贝过去后才成功.
希望有一个详细点的文档能帮助像我这样的初学者,提供一些有关依赖关系,配置方面的内容,谢谢!

**Comment by epico** [comment]
Wrote https://github.com/libpinyin/ibus-libpinyin/wiki/Installation .
