### ISSUE TITLE
[BUG] 拼写 "不可" 并选中, 会导致输入法无响应

### ISSUE THREAD

**Issue by signdo** [libpinyin/ibus-libpinyin#448]
## 环境和配置
- System: Fedora39
- DE: GNOME 45.3 (Wayland)
- WM: Mutter
- ibus Version: 1.5.29-rc2
- ibus-libpinyin Version: 1.15.6
- 在 gnome-terminal 中测试
- 标点和字母都是半角

## 问题复现

1. 打开 gnome-terminal, 按 `shift` 切换输入法到中文模式, 在键盘敲击 `buke`.
2. 第一个候选词是 `不可`, 按空格选中.
3. 输入法停顿大约 `0.3` 秒, 候选词窗口消失, gnome-terminal 没有被输入任何内容.
4. 此时 (托盘显示是中文模式) 再次敲击 `buke`, gnome-terminal 中被输入了 `buke`, 没有显示候选词窗口.
5. 按 `shift` 切换, 托盘仍然显示是中文模式, 敲击的内容会被直接输入在 gnome-terminal 中.
6. 点击输入法托盘, 点击 "首选项", 没有弹出首选项界面.
7. 按 super-space 切换到英文输入法, 再切换回 ibus-libpinyin.
8. 输入法恢复使用, 可以切换模式和输入中英文字符, 点击 "首选项" 也会弹出界面.

- 如果在输入法的中文模式下敲击 `bu`/ `bukeyi`并选中第一个候选词 `不`/ `不可以`, 则会正常显示在 gnome-terminal.
- 目前只发现 `不可` 会触发这种问题, 而且全拼和双拼模式都是同样的效果.
- 百分百复现, 重启 fedora 也没有解决.

**Comment by epico** [comment]
可以考虑在 Console 下删除 ~/.cache/ibus/libpinyin/user.conf 文件试试。

注意这个操作会清除用户输入法历史数据...

**Comment by signdo** [comment]
删除文件后问题解决了
