### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xuefliang** [libpinyin/ibus-libpinyin#45]
I make iubs-libpinyin on linux mint ,I encountered a problem
make[3]: Entering directory `/home/xuefliang/ibus-libpinyin/data'
  GEN      english.db
/bin/bash: line 2: english.db: command not found
make[3]: *** [english.db] Error 1
make[3]: Leaving directory `/home/xuefliang/ibus-libpinyin/data'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/xuefliang/ibus-libpinyin/data'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/xuefliang/ibus-libpinyin'
make: *** [all] Error 2
How do I solve this problem？

**Comment by yx91490** [comment]
google get it: [issue 5](https://github.com/libpinyin/ibus-libpinyin/issues/5)

**Comment by xuefliang** [comment]
I run make -n in  ibus-libpinyin/data , I got 
fail=; \
	if (target_option=k; case ${target_option-} in ?) ;; *) echo "am__make_running_with_option: internal error: invalid" "target option '${target_option-}' specified" >&2; exit 1;; esac; has_opt=no; sane_makeflags=$MAKEFLAGS; if test -n ' Makefile' && test -n '0'; then sane_makeflags=$MFLAGS; else case $MAKEFLAGS in *\\[\ \	]*) bs=\\; sane_makeflags=`printf '%s\n' "$MAKEFLAGS" | sed "s/$bs$bs[$bs $bs	]*//g"`;; esac; fi; skip_next=no; strip_trailopt () { flg=`printf '%s\n' "$flg" | sed "s/$1.*$//"`; }; for flg in $sane_makeflags; do test $skip_next = yes && { skip_next=no; continue; }; case $flg in *=*|--*) continue;; -*I) strip_trailopt 'I'; skip_next=yes;; -*I?*) strip_trailopt 'I';; -*O) strip_trailopt 'O'; skip_next=yes;; -*O?*) strip_trailopt 'O';; -*l) strip_trailopt 'l'; skip_next=yes;; -*l?*) strip_trailopt 'l';; -[dEDm]) skip_next=yes;; -[JT]) skip_next=yes;; esac; case $flg in *$target_option*) has_opt=yes; break;; esac; done; test $has_opt = yes); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo all-recursive | sed s/-recursive//`; \
	case "all-recursive" in \
	  distclean-* | maintainer-clean-*) list='icons ' ;; \
	  *) list='icons ' ;; \
	esac; \
	for subdir in $list; do \
	  echo "Making $target in $subdir"; \
	  if test "$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$target-am"; \
	  else \
	    local_target="$target"; \
	  fi; \
	  (CDPATH="${ZSH_VERSION+.}:" && cd $subdir && make  $local_target) \
	  || eval $failcom; \
	done; \
	if test "$dot_seen" = "no"; then \
	  make  "$target-am" || exit 1; \
	fi; test -z "$fail"
Making all in icons
make[1]: Entering directory `/home/xuefliang/ibus-libpinyin/data/icons'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/xuefliang/ibus-libpinyin/data/icons'
make[1]: Entering directory `/home/xuefliang/ibus-libpinyin/data'
echo "  GEN     " english.db; \
	rm -f english.db; \
	gawk -f ./english.awk ./wordlist |  english.db || \
		( rm -f english.db ; exit 1 )
echo "  GEN     " strokes.db; \
	rm -f strokes.db; \
	gawk -f ./strokes.awk ./strokes |  strokes.db || \
		( rm -f strokes.db ; exit 1 )
echo "  GEN     " ibus-setup-libbopomofo.desktop.in; sed \
		-e "s|\@libexecdir\@|/usr/local/libexec|" \
		-e "s|\@pkgdatadir\@|/usr/local/share/ibus-libpinyin|" \
		ibus-setup-libbopomofo.desktop.in.in > ibus-setup-libbopomofo.desktop.in.tmp && mv ibus-setup-libbopomofo.desktop.in.tmp ibus-setup-libbopomofo.desktop.in
echo "  ITMRG " ibus-setup-libbopomofo.desktop;LC_ALL=C /usr/bin/intltool-merge -q -d -u -c ../po/.intltool-merge-cache ../po ibus-setup-libbopomofo.desktop.in ibus-setup-libbopomofo.desktop
echo "  GEN     " ibus-setup-libpinyin.desktop.in; sed \
		-e "s|\@libexecdir\@|/usr/local/libexec|" \
		-e "s|\@pkgdatadir\@|/usr/local/share/ibus-libpinyin|" \
		ibus-setup-libpinyin.desktop.in.in > ibus-setup-libpinyin.desktop.in.tmp && mv ibus-setup-libpinyin.desktop.in.tmp ibus-setup-libpinyin.desktop.in
echo "  ITMRG " ibus-setup-libpinyin.desktop;LC_ALL=C /usr/bin/intltool-merge -q -d -u -c ../po/.intltool-merge-cache ../po ibus-setup-libpinyin.desktop.in ibus-setup-libpinyin.desktop
make[1]: Leaving directory `/home/xuefliang/ibus-libpinyin/data'

**Comment by epico** [comment]
Please try to install /usr/bin/sqlite3.

**Comment by xuefliang** [comment]
thank you!

**Comment by epico** [comment]
Automatically detect sqlite3 tool now.

Fixed in https://github.com/epico/ibus-libpinyin/commit/7a712b44bfe2e25741311ef82cd9fb4b53c35757 .
