### ISSUE TITLE
Firefox浏览器部分网页无法输入中文

### ISSUE THREAD

**Issue by Mr-Spade** [libpinyin/ibus-libpinyin#455]
如题，使用的是Ubuntu系统，自带的最新版snap Firefox浏览器。在某些特定的网页上，输入中文时会出现键入字母后马上被“删除”的情况，视觉上表现为输入框快速闪烁一下然后消失。

目前发现的出现问题的网页为：

- [通义千问](https://tongyi.aliyun.com/qianwen)。在和AI聊天的输入框尝试输入就会发生此情况。
- Nextcloud的Office功能。在Nextcloud中在线编辑Office文档的时候，也会发生此情况。

更换为fcitx5后不会出现该问题。同时，如果更改为其他浏览器，例如Edge，即使用ibus也不会出现该问题。

如果能够解决该问题，将不胜感激。谢谢！

**Comment by epico** [comment]
可以试试将显示风格选项更改为兼容，看看问题是否有所改善。

**Comment by Mr-Spade** [comment]
> 可以试试将显示风格选项更改为兼容，看看问题是否有所改善。

确实可以解决这个问题，感谢！

P.S. 不知道后续是否会有在默认风格也解决这个问题的计划呢？

**Comment by epico** [comment]
问一下 flatpak 的 Firefox 也有这个问题吗？

URL: https://flathub.org/setup/Ubuntu

**Comment by Mr-Spade** [comment]
> 问一下 flatpak 的 Firefox 也有这个问题吗？
> 
> URL: https://flathub.org/setup/Ubuntu

是的，我尝试安装使用了flatpak版本的Firefox，在通义千问上也存在这个问题。同样，如果改为兼容风格，也可以解决这个问题。
