### ISSUE TITLE
After invoking ibus_panel_service_candidate_clicked UI is not updated properly

### ISSUE THREAD

**Issue by lanoxx** [libpinyin/ibus-libpinyin#46]
@epico I am opening this bug here based on the suggestion of @fujiwarat's suggestion.

Question, you posted on the original issue that its fixed in https://github.com/epico/ibus-libpinyin/commit/5c0158fed5d62a1c995c36486328c577d1b1d194, but @fujiwarat recommended to open the bug here which seems to be a fork of your repository, so which one is actual upstream repository.

**Comment by epico** [comment]
https://github.com/libpinyin/ibus-libpinyin are actual upstream repository.

https://github.com/epico/ibus-libpinyin is personal repository, will sync to https://github.com/libpinyin/ibus-libpinyin later.

**Comment by lanoxx** [comment]
Just one question. Will this bug fix make it into the Ubuntu 16.04 release?

**Comment by epico** [comment]
Maybe you can file a bug in launchpad for this issue.

**Comment by lanoxx** [comment]
Original bug report in ibus: https://github.com/ibus/ibus/issues/1841

Reference bug for Ubuntu in launchpad: https://bugs.launchpad.net/ubuntu/+source/ibus-libpinyin/+bug/1539585

**Comment by epico** [comment]
Wait for Ubuntu package update.

Already fixed, close issue.
