### ISSUE TITLE
unwanted traditional characters like "喫" instead of "吃"

### ISSUE THREAD

**Issue by mariohaya** [libpinyin/ibus-libpinyin#467]
Traditional pinyin prints out weird characters like "喫" instead of "吃", 裏 instead of 裡，etc. 
Is there a way to solve this? Even though these _are_ traditional characters, they are not used anymore.

**Comment by epico** [comment]
Which Linux distribution are you using?

**Comment by mariohaya** [comment]
> Which Linux distribution are you using?

Debian. FYI, my temporary solution has been to use the "New Zhuyin" input method in which you can configure "Chinese Pinyin" as your keyboard layout. So you can use pinyin or zhuyin and it will print out traditional characters and their correct versions.

**Comment by epico** [comment]
Maybe this is similar to https://github.com/libpinyin/ibus-libpinyin/issues/453 .

**Comment by dheera** [comment]
Same problem here. Extremely frustrating, this has been this way for almost 10 years and still not fixed.
fcitx5 with opencc profile set to "s2tw" works well but I really wish ibus could fix this.

**Comment by epico** [comment]
I think in ibus-libpinyin there are `/com/github/libpinyin/ibus-libpinyin/libpinyin/opencc-config` in dconf. You can set the dconf value to `s2tw.json`.

**Comment by dheera** [comment]
Thanks, that fixed it. I'd recommend that be the default setting, I don't know any part of the world that writes it as 喫, even if it exists, it is definitely not the majority.

**Comment by epico** [comment]
The ibus-libpinyin 1.15.8 will use `s2tw.json` by default.
