### ISSUE TITLE
3 * resource leaks ?

### ISSUE THREAD

**Issue by dcb314** [libpinyin/ibus-libpinyin#47]
[PYLibPinyin.cc:217]: (error) Resource leak: dictfile

Source code is

    if (NULL == iter)
        return FALSE;

[PYLibPinyin.cc:265]: (error) Resource leak: dictfile
[ZYLibZhuyin.cc:164]: (error) Resource leak: dictfile

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/4c2d59718debad6f753b6265e4fc93f37c24a29d and https://github.com/epico/ibus-libzhuyin/commit/de3efada16bf585bb85ca24d3364aee160067fd7 .

Please review it, thanks!

**Comment by dcb314** [comment]
>Please review it, thanks!

Your patch looks at best doubtful to fix the problem to me.

I expected to see something like

    if( NULL == iter)
    {
        fclose(dictfile);
        return FALSE;
    }

**Comment by epico** [comment]
Sorry, my mistake.

Fixed again in https://github.com/epico/ibus-libpinyin/commit/429cc899b778a472f52f8b59ee1f439729246b65 and https://github.com/epico/ibus-libzhuyin/commit/f9433cf1b2ed101d67bab38aad24bdca86247b5b .

Please review it again, thanks!

**Comment by epico** [comment]
Fixed, close issue.
