### ISSUE TITLE
How does register_converter Lua API work?

### ISSUE THREAD

**Issue by johnbeard** [libpinyin/ibus-libpinyin#472]
I was experimenting with Lua plugins, having just discovered that they exist. They seem like they could be very useful, but I have no idea how to use them.

<details><summary>Details</summary>
<p>
The built-in Lua commands don't seem to all work. But I am not sure how they are all _supposed_ to work:~~
```
ime.register_command("sj", "get_time", "输入时间", "alpha", "输入可选时间，例如12:34")
ime.register_command("rq", "get_date", "输入日期", "alpha", "输入可选日期，例如2013-01-01")
ime.register_command("js", "compute", "计算模式", "none", "输入表达式，例如log(2)")
ime.register_command("xz", "query_zodiac", "查询星座", "none", "输入您的生日，例如12-3")
ime.register_trigger("get_current_time", "显示时间", {}, {'时间'})
ime.register_trigger("get_today", "显示日期", {}, {'日期'})
```

The following two do work:

* Type `rq` or `日期`, get date options
  * ![image](https://github.com/user-attachments/assets/f111f632-4885-472b-ad10-84900b68165c)
* Type `时间`, and get time options. `sj` doesn't seem to work.

I can't see how to trigger the others, since I can't enter numbers.
</p>
</details> 

(Edit: Found the Wiki page: the `i` prefix does work)

I can't find any other documentation about the functions, but from the lua plugin code, I think the API is:

* `register_trigger`:
  * Lua function name, as a string
  * Help string (not sure where this is shown)
  * List of input triggers
  * List of candidate triggers
* `register_command`
  * Command name, as a string, which must be two chars. Which is the trigger?
  * The Lua function to call
  * "Leading", not sure what this is
  * Help string
* `register_converter` - I could register this from user.lua, but not actually trigger it
  * Converter name
  * Lua function name

All functions seem to take a string and return a string or table of strings.

My converter looks like 
```
function converter(a)
    print("conv_func")
    print(a)
    return {"ddd", "eee"}
end

print(ime.get_version())
ime.register_converter("converter", "cv desc")
```
It prints `conv_func`, the input and returns `0.ddd >	1.eee` from `lua-ext-console`  with `c converter foobar`. But it doesn't trigger when it runs normally, but I do see the `get_version()` output.

Questions:

* Have I understood the above correctly?
* How do I use the other functions in `base.lua`
* How do I use `register_converter`

Thank you!

**Comment by epico** [comment]
I think the converter name should be set on `/com/github/libpinyin/ibus-libpinyin/libpinyin/lua-converter` in dconf...

**Comment by johnbeard** [comment]
Oh I see, thanks! I hope it's not a silly question but is there documentation about this stuff? Setting it to `converter` (the name of the Lua function): now the converter is called very many times with individual characters.

I changed it to 
```
function converter(a)
    print("conv_func")
    print(a)
    return a .. "ddd"
end
```
which allows `ibus_engine_plugin_call` to return `1`  (unlike returning a table). And now I see a `ddd` suffix on every candidate. In practice, what are converters expected to be used for?
 
For example the cloud plugins prepend a cloud symbol, but it looks like they commit the original string.

Whereas the converter function copies the entire converted string, which means it's not possible to add things that isn't ending up in the committed text. Which might be intentional, but I'm not quite sure what it is _supposed_ to be used for.

For example, I found, though I don't fully understand the implications of the action condition, that this diff allows the pre-converted string to be what is committed:

```
diff --git a/src/PYPLuaConverterCandidates.cc b/src/PYPLuaConverterCandidates.cc
index fff151e..36e4eb5 100644
--- a/src/PYPLuaConverterCandidates.cc
+++ b/src/PYPLuaConverterCandidates.cc
@@ -92,12 +92,12 @@ LuaConverterCandidates::selectCandidate (EnhancedCandidate & enhanced)
 
     int action = m_editor->selectCandidateInternal (m_candidates[id]);
 
-    if (action & SELECT_CANDIDATE_MODIFY_IN_PLACE) {
+    if (action & SELECT_CANDIDATE_MODIFY_IN_PLACE|SELECT_CANDIDATE_COMMIT) {
         int num = ibus_engine_plugin_call (m_lua_plugin, converter,
                                            enhanced.m_display_string.c_str ());
         if (1 == num) {
             gchar * string = ibus_engine_plugin_get_nth_result (m_lua_plugin, 0);
-            enhanced.m_display_string = string;
+            enhanced.m_display_string = m_candidates[id].m_display_string;
             g_free (string);
         }
         ibus_engine_plugin_clear_results (m_lua_plugin);
```

**Comment by epico** [comment]
I think the lua converter will commit the converted string.

Because the user may want to modify the candidate and commit the converted string.

If the lua converter commit the original string, it maybe not so useful.

Some user may want to input `沵恏` by input `你好`.

If you want, you can use the patch yourself.

**Comment by johnbeard** [comment]
OK, thanks for the answer! I just wasn't clear what the API was supposed to be used for as I couldn't find any example or documentation! I've decided to move to using a C++ engine anyway as it's faster and easier to debug.

Thanks for the help!

**Comment by epico** [comment]
Welcome!
