### ISSUE TITLE
ubuntu 24.04 not work for most application

### ISSUE THREAD

**Issue by yxlyes** [libpinyin/ibus-libpinyin#474]
Chinese pinyin not work  recently, it work well 2 days ago.

It work well only in floder and setting, not work in other application, such as chrome and shell

**Comment by epico** [comment]
If you create a new account in Ubuntu, does it works?

or you can delete the user history data, by removing the `~/.cache/ibus/libpinyin/user.conf` file.

**Comment by yxlyes** [comment]
> If you create a new account in Ubuntu, does it works?
> 
> or you can delete the user history data, by removing the `~/.cache/ibus/libpinyin/user.conf` file.

Thanks for your reply.
It works if i create a new account.
But, in the previous account, the question is still by the operation: removing the ~/.cache/ibus/libpinyin/user.conf file and restart the computer

**Comment by epico** [comment]
Could you provide the screenshot of the 语言支持 dialog?

**Comment by yxlyes** [comment]
> Could you provide the screenshot of the 语言支持 dialog?

Thanks for your reminder. I found that what I set in the language support was not ibus. After changing it to ibus, the problem was solved.
