### ISSUE TITLE
openSUSE 15.6 下设置窗口崩溃无法打开

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/ibus-libpinyin#476]
hillwood@localhost:~/桌面> cd /usr/share/ibus-libpinyin/setup/
hillwood@localhost:/usr/share/ibus-libpinyin/setup> python3.11 main2.py 

(ibus-setup-libpinyin:16375): Gtk-CRITICAL **: 21:02:29.014: _gtk_css_lookup_resolve: assertion '(((__extension__ ({ GTypeInstance *__inst = (GTypeInstance*) ((provider)); GType __t = ((_gtk_style_provider_private_get_type ())); gboolean __r; if (!__inst) __r = (0); else if (__inst->g_class && __inst->g_class->g_type == __t) __r = (!(0)); else __r = g_type_check_instance_is_a (__inst, __t); __r; }))))' failed
/usr/share/ibus-libpinyin/setup/main2.py:78: Warning: g_object_set_data_full: assertion 'G_IS_OBJECT (object)' failed
  self.__builder.add_from_file("ibus-libpinyin-preferences.ui")

(ibus-setup-libpinyin:16375): Gtk-ERROR **: 21:02:29.017: Can't create a GtkStyleContext without a display connection
追踪与中断点陷阱 (核心已转储)

**Comment by epico** [comment]
Please try `python3 main2.py`.

CC @qiangzhao

**Comment by hillwoodroc** [comment]
确实是赵强的变更造成的，直接用 python3 就没问题。
