### ISSUE TITLE
在系统自带的文本编辑器中打字的时候出现重复汉字，且中英文切换功能失效

### ISSUE THREAD

**Issue by xiaoduanayu** [libpinyin/ibus-libpinyin#478]
操作系统：Ubuntu 24.04 LTS
软件版本：IBus 智能拼音 1.15.7
问题描述：在系统自带的文本编辑器中打字的时候出现重复汉字，且中英文切换功能失效，包括但不限于原生GNOME软件，比如文本编辑器、Endeavour等。
[录屏 2024-08-29 13-47-30.webm](https://github.com/user-attachments/assets/ae351ed4-37f7-4ef1-b163-907ee6342ce9)

**Comment by kands-code** [comment]
我也遇到了，但是重复汉字没有遇到，只是无法切换输入模式（指从 英文 输入变成 中文 输入）
系统：ArchLinux
IBus 版本：1.5.30
ibus-libpinyin 版本：1.15.4-2
libpinyin 版本：2.8.1-2

<details>

<summary>具体表现</summary>

[录屏 2024-09-05 23-50-10.webm](https://github.com/user-attachments/assets/d31f7971-0a33-4f78-8790-7f8666c0e37e)

</details>

> 补充：目前测试中，因为系统中软件比较少，只有 gnome-text-editor 以及 flatpak 中的一些 GTK4 软件

**Comment by wxrighttoleft** [comment]
我的也有出现，但目前我只在gnome-text-editor应用中有发现这个情况，其他编辑器不会出现这个现象

**Comment by heshi2019** [comment]
在系统自带的文本编辑器中，输入会有汉字重复问题

**Comment by xiaoduanayu** [comment]
升级到Ubuntu 24.10，问题自动解决！
