### ISSUE TITLE
Fedora下文字候选框错位

### ISSUE THREAD

**Issue by chenzhekl** [libpinyin/ibus-libpinyin#49]
如图：
http://ww2.sinaimg.cn/large/0060lm7Tgw1f3732iu2drj31b60m4whd.jpg

使用的是Fedora 23，安装在Macbook Pro late 2013上。猜这个问题和HiDPI支持有关系。

**Comment by epico** [comment]
这个问题可能和 ibus 相关。
建议到 https://github.com/ibus/ibus/issues/ , 再开一个 issue, 谢谢。

**Comment by epico** [comment]
请问所用的浏览器是？

**Comment by chenzhekl** [comment]
浏览器版本：Google Chrome Version 50.0.2661.86 (64-bit)

这个问题不限于浏览器，在其他程序里也有类似的问题。我待会儿去ibus那边开个issue询问一下。

**Comment by epico** [comment]
请问在最新的 ibus 版本能否重现该问题?

可能和 https://github.com/ibus/ibus/issues/1806 有关。

**Comment by chenzhekl** [comment]
抱歉，现在没有在 MBP 下使用 Fedora 了。或许其他人可以帮忙测试一下。

**Comment by epico** [comment]
此问题应该和 ibus 项目有关，关闭 issue.
