### ISSUE TITLE
Adding entries to the dictionary

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [libpinyin/ibus-libpinyin#50]
How do you do this? I can't find any information. Can it be added to the wiki?

**Comment by epico** [comment]
The easiest way to add phrases is to use the setup dialog to import it.

**Comment by epico** [comment]
Or you could try to modify merged.table.
The file format is:
pinyin phrase id frequency

**Comment by epico** [comment]
No response, just close it for now.

**Comment by LewisAndrewCampbell** [comment]
Sorry for the late reply.

I should describe the issue more clearly. I have the "Chinese - Intelligent Pinyin" and "Chinese - Bopomofo" input methods installed. On the pinyin one, there is a user data tab, and I can import my own dictionary from there. But not on the Bopomofo.

I am not trying to do anything very clever, I was just always taught to say 和 like han4 ㄏㄢˋ. Maybe he2 ㄏㄜˊ is more common, but I always forget.

**Comment by epico** [comment]
No problem.

Maybe you could try ibus-libzhuyin (New Zhuyin) for Traditional Chinese.
In long term, ibus-libzhuyin is recommended. :)

**Comment by epico** [comment]
Please try ibus-libzhuyin, thanks.
