### ISSUE TITLE
How to remove a remembered phrase after I turn on remember feature.

### ISSUE THREAD

**Issue by kunyan** [libpinyin/ibus-libpinyin#51]
Because of the bad dictionary, I usually turn on "Remember every input as a phrase".  
but when I made a mistake to input a incorrect word, I can't remove it

I suggest add a remove feature or the word candidates should order by use frequency

**Comment by epico** [comment]
Thanks for the report, I will check it later.

Maybe add a new function, like pinyin_remove_token(context, token).

**Comment by epico** [comment]
To remove a wrong word candidate, move to the word candidate, then press Ctrl+Shift+d.

**Comment by epico** [comment]
As lipinyin 1.5.91 and ibus-libpinyin 1.7.91 are released, close issue.
