### ISSUE TITLE
无法在youku，乐视等地方的视频弹幕中输入中文

### ISSUE THREAD

**Issue by ganloo** [libpinyin/ibus-libpinyin#52]
但是ibus-googlepinyin可以正常输入，换成libpinyin，无论是在中文模式或是英文模式都只能输入英文。我的系统是Arch Linux，gnome 3.20.2, ibus-libpinyin 1.7.3-2，谢谢。

**Comment by epico** [comment]
请问你的浏览器是？
libpinyin 的版本是?

**Comment by epico** [comment]
如果新创建一个用户账户，也有问题吗？

**Comment by ganloo** [comment]
我的浏览器是firefox 47.0-2（Arch official package），IBus 智能拼音 1.7.3。我试了下epiphany(3.20.3-1)，甚至在弹幕输入框时无法转换成中文输入。我不认为是用户账户的问题，我说过，使用googlepinyin(ibus-googlepinyin 0.1.2-6)是可以输入中文的，谢谢。

**Comment by epico** [comment]
请你试试新用户帐号，数据问题也可以造成这种现象。
或者在 text terminal 下，清除 ~/.cache/ibus/libpinyin/ 的数据，重新登录试试。

**Comment by ganloo** [comment]
按你的方法清除libpinyin的用户数据后，可以输入了，谢谢。

**Comment by epico** [comment]
不客气。

**Comment by ganloo** [comment]
我重新登陆几次后，又出现了无法输入的情况，不知道是否在您们的电脑中可以重现这种现象，如果也是如此，那么还是需要调查一下了，毕竟不能为了输入弹幕而每次重置配置文件呀，谢谢。

**Comment by epico** [comment]
无法重现，请尝试创建新用户，看看能不能解决问题。
或者试试 Google Chrome 浏览器，Chrome 的 Flash Player 版本比较高，可能会好点。

**Comment by ganloo** [comment]
Ok，非常感谢。
