### ISSUE TITLE
请问双拼下支持 i 模式吗？

### ISSUE THREAD

**Issue by bluesnowlake** [libpinyin/ibus-libpinyin#53]
如果不支持的话可不可以考虑像 google 输入法那样，双拼下输入大写 I 进入 i 模式，谢谢。

**Comment by epico** [comment]
Draft implemented in
https://github.com/epico/ibus-libpinyin/commit/deb96075e0fe9021f8fab16de612f3c4a8dc2d5e .

**Comment by epico** [comment]
As lipinyin 1.5.91 and ibus-libpinyin 1.7.91 are released, close issue.
