### ISSUE TITLE
Intelligent Pinyin 1.7.92 crashed

### ISSUE THREAD

**Issue by sean722** [libpinyin/ibus-libpinyin#54]
When I type 'fangan'(方案)，finally got n and libpinyin is crashed. It seems some bug. But you type 'fang'an', everything is fine.

**Comment by sean722** [comment]
[abrt] ibus-libpinyin: PY::PinyinEditor::updatePreeditText(): ibus-engine-libpinyin killed by SIGABRT 
Description of problem:
1.When I type 'fangan'(方案)，finally got a 'n' character and libpinyin is crashed. But when you type 'fang'an', everything is fine. 
2.When you type 'fangan', it's  crashed every time.
3.not yet

Version-Release number of selected component:
ibus-libpinyin-1.7.92-1.fc24

Additional info:
reporter:       libreport-2.7.2
backtrace_rating: 4
cmdline:        /usr/libexec/ibus-engine-libpinyin --ibus
crash_function: PY::PinyinEditor::updatePreeditText
executable:     /usr/libexec/ibus-engine-libpinyin
global_pid:     1884
kernel:         4.6.4-301.fc24.x86_64
pkg_fingerprint: 73BD E983 81B4 6521
pkg_vendor:     Fedora Project
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (9 frames)
 #4 PY::PinyinEditor::updatePreeditText at PYPPinyinEditor.cc:269
 #5 PY::FullPinyinEditor::update at PYPFullPinyinEditor.cc:116
 #6 PY::FullPinyinEditor::insert at PYPFullPinyinEditor.cc:57
 #7 PY::PinyinEngine::processKeyEvent at PYPPinyinEngine.cc:223
 #8 _ibus_marshal_BOOLEAN__UINT_UINT_UINT at ibusmarshalers.c:290
 #13 ibus_engine_service_method_call at ibusengine.c:883
 #14 call_in_idle_cb at gdbusconnection.c:4832
 #19 ibus_main at ibusshare.c:299
 #20 start_component at PYMain.cc:141

**Comment by epico** [comment]
Fixed in https://bodhi.fedoraproject.org/updates/FEDORA-2016-2cd5442e7a .

**Comment by epico** [comment]
As libpinyin 1.6.0 and ibus-libpinyin 1.8.0 are released, close issue.
