### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by Jibec** [libpinyin/ibus-libpinyin#55]
Hi,

there is an issue with this file with title "UI" :
https://github.com/libpinyin/ibus-libpinyin/blob/master/setup/ibus-libpinyin-preferences.ui#L498

please have a look to screenshot :
![capture d ecran de 2016-08-20 09-45-01](https://cloud.githubusercontent.com/assets/474883/17829822/ce9c93f2-66ba-11e6-89aa-4fd726f70837.png)

and probably with :

- window name "main2.py" that sound scary
- icons in help and left menu that is missing (you may re-use the one from the input method ?)

![capture d ecran de 2016-08-20 09-46-05](https://cloud.githubusercontent.com/assets/474883/17829843/9160117a-66bb-11e6-8714-6bca791ebf94.png)

**Comment by epico** [comment]
Sorry, where is the "help and left menu"?

**Comment by Jibec** [comment]
the help is the bottom right application, when you type "alt-tab", instead of a logo you get that "black-screen-icon"
the left menu is the left side dock, you can see nine "black-screen-icon"

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/3918b17d54f807b4643737f08c202751c8358131 .

**Comment by epico** [comment]
As libpinyin 1.6.0 and ibus-libpinyin 1.8.0 are released, close issue.
