### ISSUE TITLE
使用双拼模式时，特定键会导致输入法失效

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/ibus-libpinyin#56]
我使用的自然码双拼，首键如果按下的是键盘的“a”和“o”时，输入法会完全失效，无法输入中文，只有重新切换回来才可以恢复。

**Comment by epico** [comment]
请问你使用的 libpinyin 和 ibus-libpinyin 的版本是？

**Comment by hillwoodroc** [comment]
均为最新版本。

**Comment by ruoshan** [comment]
我也有这个问题, 按到特定键就coredump了, https://github.com/libpinyin/ibus-libpinyin/issues/60

**Comment by epico** [comment]
As libpinyin 1.6.0 and ibus-libpinyin 1.8.0 fix the bug, close issue.
