### ISSUE TITLE
Shift Key Doesn't work in Texmaker

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#58]
Running texmaker in UbuntuMate 16.04, shift-key (_L or _R）doesn't shift the input mode.  It works everywhere else.  I can still use Ctrl-space (or Super-space) to toggle between English and Chinese keyboards.

**Comment by epico** [comment]
Please also file two issues, one for texmaker, the other for ibus, thanks.

**Comment by ping-wu** [comment]
Thanks.  Done!

**Comment by epico** [comment]
Maybe Texmaker handled the Shift key, not sent to input method.
