### ISSUE TITLE
1.7.92 coredump on archlinux

### ISSUE THREAD

**Issue by ruoshan** [libpinyin/ibus-libpinyin#60]
PID: 4351 (ibus-engine-lib)
           UID: 1000 (ruoshan)
           GID: 1000 (ruoshan)
        Signal: 6 (ABRT)
     Timestamp: Sun 2016-09-04 13:04:28 CST (20min ago)
  Command Line: /usr/lib/ibus-libpinyin/ibus-engine-libpinyin --ibus
    Executable: /usr/lib/ibus-libpinyin/ibus-engine-libpinyin
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (ruoshan)
       Boot ID: d9739ef2885945279f49a1b2064fccab
    Machine ID: 9efbf61a6d9f4e56ba819c59ec866bb4
      Hostname: r3
      Coredump: /var/lib/systemd/coredump/core.ibus-engine-lib.1000.d9739ef2885945279f49a1b2064fccab.4351.1472965468000000000000.lz4
       Message: Process 4351 (ibus-engine-lib) of user 1000 dumped core.
                
                Stack trace of thread 4351:
                #0  0x00007fcdf4ed704f raise (libc.so.6)
                #1  0x00007fcdf4ed847a abort (libc.so.6)
                #2  0x00007fcdf5850515 g_assertion_message (libglib-2.0.so.0)
                #3  0x00007fcdf58505aa g_assertion_message_expr (libglib-2.0.so.0)
                #4  0x00000000004123cc n/a (ibus-engine-libpinyin)
                #5  0x0000000000411cbc n/a (ibus-engine-libpinyin)
                #6  0x00000000004130d2 n/a (ibus-engine-libpinyin)
                #7  0x0000000000414aaa n/a (ibus-engine-libpinyin)
                #8  0x00007fcdf6339122 n/a (libibus-1.0.so.5)
                #9  0x00007fcdf60e5f85 g_closure_invoke (libgobject-2.0.so.0)
                #10 0x00007fcdf60f838d n/a (libgobject-2.0.so.0)
                #11 0x00007fcdf610069f g_signal_emit_valist (libgobject-2.0.so.0)
                #12 0x00007fcdf6100fdf g_signal_emit (libgobject-2.0.so.0)
                #13 0x00007fcdf633f844 n/a (libibus-1.0.so.5)
                #14 0x00007fcdf4bf316c n/a (libgio-2.0.so.0)
                #15 0x00007fcdf582ad1a g_main_context_dispatch (libglib-2.0.so.0)
                #16 0x00007fcdf582b0d0 n/a (libglib-2.0.so.0)
                #17 0x00007fcdf582b3f2 g_main_loop_run (libglib-2.0.so.0)
                #18 0x00007fcdf633ba6c ibus_main (libibus-1.0.so.5)
                #19 0x00000000004055a8 n/a (ibus-engine-libpinyin)
                #20 0x00007fcdf4ec4291 __libc_start_main (libc.so.6)
                #21 0x00000000004057ea n/a (ibus-engine-libpinyin)
                
                Stack trace of thread 4353:
                #0  0x00007fcdf4f8348d poll (libc.so.6)
                #1  0x00007fcdf582b066 n/a (libglib-2.0.so.0)
                #2  0x00007fcdf582b3f2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fcdf4c027c6 n/a (libgio-2.0.so.0)
                #4  0x00007fcdf5851345 n/a (libglib-2.0.so.0)
                #5  0x00007fcdf4695454 start_thread (libpthread.so.0)
                #6  0x00007fcdf4f8c7df __clone (libc.so.6)
                
                Stack trace of thread 4352:
                #0  0x00007fcdf4f8348d poll (libc.so.6)
                #1  0x00007fcdf582b066 n/a (libglib-2.0.so.0)
                #2  0x00007fcdf582b17c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fcdf582b1c1 n/a (libglib-2.0.so.0)
                #4  0x00007fcdf5851345 n/a (libglib-2.0.so.0)
                #5  0x00007fcdf4695454 start_thread (libpthread.so.0)
                #6  0x1.7.92-100007fcdf4f8c7df __clone (libc.so.6)

**Comment by epico** [comment]
As libpinyin 1.6.0 and ibus-libpinyin 1.8.0 fix the bug, close issue.

**Comment by wuxinyumrx** [comment]
新增20M的用户词典后，切换到中文输入，再按i按键同样会crash，栈信息和一楼一样，必显。

**Comment by epico** [comment]
请使用 libpinyin 1.6.0 和 ibus-libpinyin 1.8.0 .

**Comment by wuxinyumrx** [comment]
@epico 恩，问一下archlinux下ibus-libpinyin 1.8.0什么时候有更新

**Comment by epico** [comment]
这个问题请问 ArchLinux, 可以报 bug 给 ArchLinux.

**Comment by wuxinyumrx** [comment]
ibus-libpinyin 1.8.91-1
libpinyin 1.9.92-1
切换到中文输入，再按i按键，问题依然存在

**Comment by epico** [comment]
Please try ibus-libpinyin 1.8.92.
