### ISSUE TITLE
有没有办法导入些源

### ISSUE THREAD

**Issue by kongdeyuan** [libpinyin/ibus-libpinyin#61]
识别率不太好用

**Comment by epico** [comment]
能否详细说明？

**Comment by kongdeyuan** [comment]
描述错了，应该是词库
有没有办法引用，qq输入法的词库或者搜狗输入法的词库
http://dict.qq.pinyin.cn/
http://pinyin.sogou.com/dict/
指条路也行^0^

**Comment by epico** [comment]
请在 "首选项" 对话框中，"用户数据" 页面按照说明自行导入。
