### ISSUE TITLE
drop zhuyin support

### ISSUE THREAD

**Issue by baimafeima** [libpinyin/ibus-libpinyin#65]
I have noticed that you also offer a zhuyin (BoPoMoFo) option as part of libpinyin. I would suggest to drop support and focus exclusively on improving the pinyin experience. There is ibus-chewing for zhuyin users. 

Testing system: Solus (https://www.solus-project.com/)
https://dev.solus-project.com/T1528

**Comment by epico** [comment]
For now, some users are still using it...

**Comment by ikeydoherty** [comment]
I should point out that this isn't something requested by or on behalf of the Solus project, but the views of an individual user.

 - Actual Solus Dude.

**Comment by epico** [comment]
@ikeydoherty Thanks!

Just close this issue for now.
