### ISSUE TITLE
settings do not save (no vertical orientation and number of characters cannot be altered)

### ISSUE THREAD

**Issue by baimafeima** [libpinyin/ibus-libpinyin#66]
Left-click on 拼 in the indicator area and select Preferences. Changing the settings under General > UI > Orientation and number of candidates does not take any effect, even after manually restarting IBus through right-click > Restart. More settings may be affected by this.

Testing system: Solus (https://www.solus-project.com/)
https://dev.solus-project.com/T1528

**Comment by epico** [comment]
Could you check with other engines like ibus-table with this issue?

**Comment by epico** [comment]
Actually this setting problems remained me one issue.

In the past, ibus-libpinyin uses capital key name in gconf.
But later ibus used dconf, dconf use low case key name.

For compatibility, ibus developer makes a patch for some input methods
to keep the capital key name.

Could you check whether ibus-libpinyin store capital key name in dconf?
in /desktop/ibus/engine/pinyin.

**Comment by epico** [comment]
I changed the dconf key name to lower case.
in https://github.com/epico/ibus-libpinyin .

Could you try or test it?

**Comment by epico** [comment]
As ibus-libpinyin 1.8.1 is released, close issue.

**Comment by baimafeima** [comment]
@epico Apologies for getting back so late. I have just tested with the latest ibus-libpinyin 1.8.91 and the issue is still there, that is, vertical orientation of characters is not possible as the settings do not get saved. Could you please look into this again and re-open this issue?

Steps: Left-click on 拼 in the indicator area and select Preferences. Changing the settings under General > UI > Orientation and number of candidates does not take any effect, even after manually restarting IBus through right-click > Restart.

**Comment by epico** [comment]
Sorry, it is a new Regression bug. I will fix it soon.

**Comment by baimafeima** [comment]
Thanks for looking into this again. Is this already fixed in 1.8.92?

**Comment by epico** [comment]
Fixed, I think.
