### ISSUE TITLE
replace default icon with a better one

### ISSUE THREAD

**Issue by baimafeima** [libpinyin/ibus-libpinyin#67]
Activate pinyin. It shows the character 拼 (pin) in a relatively ugly default rendering. We should replace this by a more beautiful Chinese font and a color which blends in better with other language engines available. Any chance you can add a setting for a user to decide whether to display an icon or simply CN for Chinese?

Testing system: Solus (https://www.solus-project.com/)
https://dev.solus-project.com/T1528

**Comment by epico** [comment]
Could you ask this issue with ibus upstream?

If you want to let engines display CN or TW, I think this is a feature in ibus code.

**Comment by epico** [comment]
For Solus project, maybe you could replace this icon when build ibus-libpinyin.

The icon is in /usr/share/ibus-libpinyin/icons/ibus-pinyin.svg .

**Comment by epico** [comment]
As commented above, just close this issue for now.
