### ISSUE TITLE
ibus-libpinyin在高分辨率屏幕下候选框偏移

### ISSUE THREAD

**Issue by AlynxZhou** [libpinyin/ibus-libpinyin#68]
4k高分屏，gnome的高分屏适配开启，然后ibus-libpinyin的候选框大部分情况下不能正确指向输入框内光标，而是指向偏左上方一段。并且解锁后第一次输入会丢失第一个按键，第一个字直接以英文输入，然后剩下的输入才被其捕捉。

**Comment by epico** [comment]
请问你的 Linux 发行版，GNOME 版本是？

**Comment by decdl** [comment]
Arch Linux, ibus 1.5.14, ibus-libpinyin 1.8.1, 3840x2160, Wayland Gnome 3.22.2
候选框会出现在输入光标的左上角，离光标的距离不固定

**Comment by AlynxZhou** [comment]
无论是arch还是gentoo，gnome版本从3.16到3.22都有这个问题，而且似乎不是libpinyin的问题，而是ibus框架的问题，ibus-rime也偏移。

**Comment by epico** [comment]
是的，我也觉得是 ibus 框架的问题。
