### ISSUE TITLE
英语模式下改变图标

### ISSUE THREAD

**Issue by mozbugbox** [libpinyin/ibus-libpinyin#69]
当处于英语模式下 (shift_L)，图标上的`拼`字应该转变为`英`或者`A`，以便用户识别当前模式，否则盲打很不方便。

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/58353eb49f56ce43d7cdbb73c01aafa37a44b715 .

**Comment by epico** [comment]
As libpinyin 1.9.92 and ibus-libpinyin 1.8.92 are released, close issue.
