### ISSUE TITLE
--localedir configure option does not work

### ISSUE THREAD

**Issue by KazuhikoMaekawa** [libpinyin/ibus-libpinyin#70]
--localedir option for autogen.sh/configure is not taken care.

At least the followings are required to enable --localedir option
  - For the ibus-setup-libpinyin, locale.bindtextdomain() is required with IBUS_LOCALEDIR environment variable in main2.py
  - src/Makefile.am is needed -DLOCALEDIR=\"(localedir)\" additionally.
  - src/PYMAIN.cc is needed bindtextdomain()

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/27aa99000d3a49ff690694dbb4c3f5cc2eff0767 .

Please review the patch, thanks!

**Comment by KazuhikoMaekawa** [comment]
For the main2.py, I tried and it looks gettext.bindtextdomain() functions does not affect to gtk binding behavior. I think locale.bindtextdomain() is needed( https://docs.python.org/2.7/library/locale.html#access-to-message-catalogs )

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/0871fa0eb228af0abee03421f91256a779de4316 .

Please review it again, thanks!

**Comment by epico** [comment]
As libpinyin 1.9.92 and ibus-libpinyin 1.8.92 are released, close issue.
