### ISSUE TITLE
在中文模式下，第一个字母输入v，导致系统图形界面崩溃

### ISSUE THREAD

**Issue by ZhangHoucheng** [libpinyin/ibus-libpinyin#71]
不知是否只发生在我的系统上，当使用中文模式输入，以字母v开头，则会导致图形界面崩溃，系统黑屏，几秒后自动进入系统登录页面，登录后之前打开的所有窗口都被关闭了。
系统是fedora 25，系统语言为英文。bug可复现。

**Comment by epico** [comment]
建议你换台机器试试，印象中 ibus 很少会引起这么严重的问题。

**Comment by epico** [comment]
问一下，是否可以在其他机器或者 Fedora 26 上复现？

**Comment by epico** [comment]
No response, just close issue.
