### ISSUE TITLE
potential buffer-overrun in units[i] - src/PYExtEditor.cc

### ISSUE THREAD

**Issue by KazuhikoMaekawa** [libpinyin/ibus-libpinyin#72]
The following code fragments is better to be revised to 'for( i = 0; i < 6; ++i)'
since "units" data array is prepared with size 7, and value i should not be larger than 6.

src/PYExtEditor.cc: line 99:
----------------------------------------------------------
        while ( pos > 0 ) {
            for ( i = 0; i < 7; ++i) {
                pos = pos % units[i].digits;
                if ( pos == 0 )
                    break;
            }
        }

        if ( units[i].persist ) {
----------------------------------------------------------

Fortunately actual data units_simplified[] and units_traditional[] 
have value '1' for unit_t.digits parameter at 6th(i=5) position.
So actually this buffer-overrun does not happen.

Just filed this issue since it's confusable.

**Comment by epico** [comment]
Thanks for the report!

Fixed in https://github.com/epico/ibus-libpinyin/commit/3d713493579c1c916684a3e0af6deff75cf22c7d .

**Comment by epico** [comment]
As libpinyin 1.9.92 and ibus-libpinyin 1.8.92 are released, close issue.
