### ISSUE TITLE
已经安装了ibus-1.5.14，但是下载ibus-libpinyin-1.8.1源码安装包报错：Requested 'ibus-1.0 >= 1.5.11' but version of IBus is 1.5.3

### ISSUE THREAD

**Issue by lemonzone2010** [libpinyin/ibus-libpinyin#73]
已经安装了ibus-1.5.14，但是下载ibus-libpinyin-1.8.1源码
执行安装时报错
```bash
./autogen.sh 
```
报错信息如下：
```bash
configure: error: Package requirements (
    ibus-1.0 >= 1.5.11
) were not met:

Requested 'ibus-1.0 >= 1.5.11' but version of IBus is 1.5.3

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables IBUS_CFLAGS
and IBUS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by epico** [comment]
Please try https://github.com/libpinyin/ibus-libpinyin/wiki/Installation .

**Comment by lemonzone2010** [comment]
还是这个错误，ibus-1.0应该ibus-devel安装生成的,但是最新ibus-devel无法找到源码，在yum仓库中只能找到 ibus-devel-1.5.3-13.el7.x86_64，版本是1.5.3，麻烦问下知道 最新ibus-devel源码地址吗？

```
configure: error: Package requirements (
    ibus-1.0 >= 1.5.11
) were not met:

Requested 'ibus-1.0 >= 1.5.11' but version of IBus is 1.5.3

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

**Comment by epico** [comment]
ibus-devel is generated by ibus source rpm.

BTW, maybe try Fedora instead of RHEL/CentOS.

or try the work around below:

I update ibus-libpinyin to use ibus 1.5.11 to use ibus_keyval_name function,
in order to drop gdk-3.0 depends.

URL: https://github.com/libpinyin/ibus-libpinyin/commit/ac63a9737c418d562f971c07d697ae0fb3e9b7a2

Maybe you could try to revert the above patch, then use ibus 1.5.0 to check whether it compiles.

**Comment by epico** [comment]
close issue.

**Comment by wming126** [comment]
> 已经安装了ibus-1.5.14，但是下载ibus-libpinyin-1.8.1源码 执行安装时报错
> 
> ```shell
> ./autogen.sh 
> ```
> 
> 报错信息如下：
> 
> ```shell
> configure: error: Package requirements (
>     ibus-1.0 >= 1.5.11
> ) were not met:
> 
> Requested 'ibus-1.0 >= 1.5.11' but version of IBus is 1.5.3
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables IBUS_CFLAGS
> and IBUS_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> ```

you should install the dev package:
sudo apt install libpinyin-dev
sudo apt install libsqlite3-dev
sudo apt install libibus-1.0-dev

**Comment by WhymustIhaveaname** [comment]
@lemonzone2010 Set 
```
export IBUS_CFLAGS=1
export IBUS_LIBS=1
```
can bypass the error in configure. However, it will alert "no <ibus.h>" during making. I am using Fedora so the packages for Debian do not work for me. I did some try and error and found that installing the following two packages solves the problem: `sqlite-devel ibus-devel`

**Comment by epico** [comment]
> @lemonzone2010 Set
> 
> ```
> export IBUS_CFLAGS=1
> export IBUS_LIBS=1
> ```
> 

I think the above environment variables are not correct, please do not use it.
