### ISSUE TITLE
fedora25下，配置首选项设置后，不会保存

### ISSUE THREAD

**Issue by caida0** [libpinyin/ibus-libpinyin#75]
fedora25更新到最新，配置首选项设置后，例如开始候选词数为5，设置候选词数为10，点退出后，候选词数仍为5，再进入首选项，发现设置没有变化，仍为默认值

**Comment by epico** [comment]
不好意思，这是个 bug，我尽快修正。

**Comment by epico** [comment]
Fixed in https://bodhi.fedoraproject.org/updates/FEDORA-2017-fcdfe9c57c .
