### ISSUE TITLE
[Regression?] Setup not working

### ISSUE THREAD

**Issue by Garnasha** [libpinyin/ibus-libpinyin#76]
Something very similar to issue https://github.com/libpinyin/ibus-libpinyin/issues/3 seems to have been (re-)introduced in version 1.8.91 . 

Changing shortcuts in libpinyin setup (entered via ibus-setup) does not get saved on closing the setup window, and even with the window still open, the new hotkey setting is never applied. The base ibus-setup interface does not have this issue. 

System: Arch Linux, last full system upgrade on 2017-03-02 (just now). ibus-libpinyin 1.8.91, Arch package https://www.archlinux.org/packages/community/x86_64/ibus-libpinyin/ (last updated 2017-02-24)

**Comment by epico** [comment]
Sorry, it is fixed in https://github.com/epico/libpinyin and https://github.com/epico/ibus-libpinyin .

To generate the patch, please try:
libpinyin: $ git diff 1.9.91
ibus-libpinyin: $ git diff 1.8.91

**Comment by xsinx** [comment]
I'm in same situation here on Arch Linux, with version 1.8.91.
Is there a workaround to fix this before next release?

**Comment by epico** [comment]
Please try the above patch, or waits for the next release.

I plan to release a new version soon.

**Comment by epico** [comment]
As libpinyin 1.9.92 and ibus-libpinyin 1.8.92 are released, close issue.

**Comment by losnake** [comment]
@epico  Thank you!!
