### ISSUE TITLE
Supporting typing tone unto words for faster searching

### ISSUE THREAD

**Issue by fluteguitar** [libpinyin/ibus-libpinyin#77]
Hello,
I found it is more convenient if it is possible to add tone to the word. As Chinese new learner, after typing the Pinyin words without having tone, there are still too many options for me to pick, which bring a bit confusion.

**Comment by epico** [comment]
Please try ibus-libzhuyin.

**Comment by mozbugbox** [comment]
maybe use `ctrl-1`, `ctrl-2`, `ctrl-3`, `ctrl-4`, `ctrl-5` for inserting tones at the cursor.

**Comment by epico** [comment]
The problem is that ibus-libpinyin doesn't contain tone information now.

Please try ibus-libzhuyin!
