### ISSUE TITLE
Delete behavior seems incorrect on Qt in Fedora 25

### ISSUE THREAD

**Issue by soiamsoNG** [libpinyin/ibus-libpinyin#78]
In program of Qt based. like Calibre ( I screen cast on) and Qt Creator

1. when we still left suggestion on suggestion window

2. I start to delete all characters use **Backspace** in the suggestion window, Qt widget will still have the most first character(with underline), even after delete them all from the pinyin suggestions window.

3. If input new character(English or Chinese) immediately the still left character will disappear.

**Comment by epico** [comment]
Please also report an issue on ibus project.

URL: https://github.com/ibus/ibus/issues/

**Comment by epico** [comment]
It seems like ibus or Qt bug, close issue.
