### ISSUE TITLE
How to change order of the syllables to most used ones in suggestion mechanism?

### ISSUE THREAD

**Issue by strixaluco** [libpinyin/ibus-libpinyin#79]
I apologize for possibly too simple question, but I've switched all the options in preferences and still couldn't find the one that is responsible for my case.
I want that when I type two initial latin letters, suggestion mechanism offers me the most used syllables instead of less common ones.
E.g. `n h` gives 你好 instead of 年和, which is given by default;
`x x` gives 谢谢 instead of 学习, which is given by default.

**Environment:**
Intelligent Pinyin 1.6.92

**Comment by epico** [comment]
Please try libpinyin 1.9.92 and ibus-libpinyin 1.8.92.

After input "你好" for 3-5 times, it will change the order of the candidates.

**Comment by strixaluco** [comment]
I'm on Debian stable, so will have to compile as even Debian Sid has ibus-libpinyin 1.7.3.
Thanks for reply anyway. Now it's clear that I haven't overlooked anything.
