### ISSUE TITLE
可以请教下那些词典是从哪里来吗？

### ISSUE THREAD

**Issue by 0lidaxiang** [libpinyin/ibus-libpinyin#80]
可以请教下那些词典是从哪里来吗？
这些词典是否能更新呢？
谢谢。

**Comment by epico** [comment]
其实那是通过自然语言处理算法生成的，效果比较一般。

**Comment by 0lidaxiang** [comment]
谢谢。这个词典是否可以更新呢？或者这些算法有没有进一步改进的计划？
因为在使用的时候感觉不是很流畅，个人猜测可能是词典内容还不够新和全面吧。
当然最近发现了用户数据可以自己更新，这也算另外一种办法。

**Comment by epico** [comment]
其实这些词典的效果比较一般，现在没有改进的计划，推荐用户自己导入词库。
