### ISSUE TITLE
我在opensuse下使用时出现一条黑色边框阻挡看字

### ISSUE THREAD

**Issue by LonelyFaith** [libpinyin/ibus-libpinyin#82]
打字时候出现一条黑色的匡妨碍看字怎么办！使用的kde桌面

**Comment by epico** [comment]
Please provides screenshot,
and could you open an issue also for ibus in English?

**Comment by LonelyFaith** [comment]
I changed my system back to fedora(gnome).the problem is gone now !

**Comment by LonelyFaith** [comment]
sorry I don't have screenshot and I changed  my system to fedora!

**Comment by epico** [comment]
Okay.

**Comment by epico** [comment]
close issue.
