### ISSUE TITLE
[Solved] Missing characters in Pinyin input

### ISSUE THREAD

**Issue by doihara** [libpinyin/ibus-libpinyin#83]
Dear members,

my Pinyin input seemed to suddenly get broken after a recent update. Now many characters can't be displayed in the input method. Please see the screenshot below.

![screenshot from 2017-07-02 00-02-01](https://user-images.githubusercontent.com/20506319/27765791-0b7ec0fc-5ebc-11e7-9a9d-943b88d41993.png)
![screenshot from 2017-07-02 00-19-50](https://user-images.githubusercontent.com/20506319/27765798-482c6676-5ebc-11e7-8627-085e8bcda8d0.png)

My initial suspect was a system font related issue. Now I have changed all the fonts in Gnome-Tweak Tool to CJK compatible fonts, but the problem remains unsolved.

I am running Arch Linux with Gnome 3.24, ibus-libpinyin version is 1.9.0-1. I hope someone could give me a hint of how the solve this issue. Thank you!

Best wishes,
Doihara

**Comment by doihara** [comment]
I would like to add that Chinese character display, no matter TC or SC, is totally alright in my current system. It seems to be really a problem only related to the input method. But what surprised me most was that even I switched to fcitx, the same problem is still there. I am afraid that it is a deeper, system-related problem, which has actually nothing to do with ibus or ibus-libpinyin? Anyway, I would really appreciate some hints about how to solve this issue.

Many thanks in advance.
Doihara

**Comment by epico** [comment]
I think you could open a bug for Arch Linux Chinese font maintainer,
if this issue also exists in gedit without input method.

BTW, which Chinese fonts you choose to use?

**Comment by doihara** [comment]
By "without input method" did you mean text display in gedit? If I just open an existing document or copy some text to it, everything seems to be just fine. I tend to believe that it is an input method specific issue, although I am not sure at which level it lies. 

The Chinese font I am using is the Noto CJK family from Google.

BTW, I remember at the time I just started using Ubuntu, I also had a similar issue with its ibus-based Chinese input. The output of the input method was totally strange. Without knowing much about Linux, I just switched to the Fcitx. Although it involved a more complicated installation and was not integrated to the distro by default, at least it worked. And that was also my first (maybe unjustified) impression of the compatibility between ibus and Chinese typing. I am afraid I just failed to understanding something fundamental about the system, but have no idea what it is.

In Arch I have been struggling with Fcitx because of some issues about German input, so I wanted to give ibus another try...

**Comment by epico** [comment]
Maybe try to remove noto-fonts-cjk, then install adobe-source-han-sans-cn-fonts
and adobe-source-han-sans-tw-fonts.

**Comment by doihara** [comment]
Tried it, didn't work. But still thank you for your efforts, sir! It seems I have to go and dip deeper into the web...
I will report if I somehow get it working again.

**Comment by doihara** [comment]
I would like to add a brief comment that in my system, using the adobe-source-han-sans-cn-fonts will lead to abnormal display of Chinese characters. Totally strange ... 
One problem of Linux, specifically for users without enough knowledge and experience, is that once you mess up your configuration and settings, in most cases without knowing what you actually have done, there will be no way back ...

**Comment by doihara** [comment]
The issue has been solved. It seems to have absolutely nothing to do with ibus-libpinyin itself. My first suspect is a certain cjk font maintenance issue in arch. In order to get everything right, I have to install exactly noto-cjk-font, but not the more popular adobe-han or any other niche cjk fonts.  

![screenshot from 2017-07-03 16-29-09](https://user-images.githubusercontent.com/20506319/27797311-79477db6-600d-11e7-9cd9-19595c4d9007.png)

**Comment by epico** [comment]
Glad to hear that you solved it. :)
