### ISSUE TITLE
双拼模式下日常性崩溃

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/ibus-libpinyin#88]
切换至双屏自然码模式，输入“bijwbg”，然后键入2选择第二个候选词，输入法立即崩溃，然后无法输入任何汉字。

ibus-libpinyin:1.9.0 libpinyin 2.0.92

**Comment by epico** [comment]
我回来看一下。

**Comment by epico** [comment]
请问您使用的发行版是？

**Comment by hillwoodroc** [comment]
openSUSE 42.3

2017年8月28日 17:24，"Peng Wu" <notifications@github.com>写道：

请问您使用的发行版是？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libpinyin/ibus-libpinyin/issues/88#issuecomment-325305546>,
or mute the thread

**Comment by epico** [comment]
该问题有可能已经修复...

能否自行编译 Fedora 的 source rpm, 看看是否能重现。

libpinyin:
https://koji.fedoraproject.org/koji/buildinfo?buildID=960846

ibus-libpinyin:
https://koji.fedoraproject.org/koji/buildinfo?buildID=962356

**Comment by hillwoodroc** [comment]
依然如此。

**Comment by hillwoodroc** [comment]
总的来说就是三个字的词组在选择第三个候选字的时候就会崩溃。

**Comment by epico** [comment]
我无法在 Fedora 26 上复现。

方便测试下 Fedora 27 吗？
或者在 Fedora 26 上编译最新的 libpinyin 和 ibus-libpinyin.

我可能得过一阵儿才有时间装 openSUSE.

**Comment by epico** [comment]
试试新建一个用户，看看是不是用户数据出问题了？

**Comment by hillwoodroc** [comment]
有调试错误的办法吗？gdb 可以么？

**Comment by epico** [comment]
如果能够提供 backtrace 的话，也许可以帮助定位问题。

首先找到 ibus-engine-libpinyin 的进程 PID, 然后用 gdb -p $PID 来 attach 进程，
等 crash 后，把 backtrace 发上来。

**Comment by hillwoodroc** [comment]
重启了系统似乎就没问题了，我再观察看看。
