### ISSUE TITLE
After updating every time, the inputting habit would lose.

### ISSUE THREAD

**Issue by bolan** [libpinyin/ibus-libpinyin#9]
Hi,

I know that the libpinyin can learn the inputting habit from users. However, after updating every time, the inputting habit would lose, and everything would come back to default. Is it possible to avoid this problem, and let the libpinyin record the habit forever?

By the way, I have this problem in Fedora right now, and I have not tested it in other distro yet. Thus, if you have any idea to avoid this problem in Fedora, please let me know.

**Comment by epico** [comment]
After enable "Remember every input as a phrase" option, ibus-libpinyin can export user phrases.
