### ISSUE TITLE
Ctrl+Shift+F快捷键冲突

### ISSUE THREAD

**Issue by zyddn** [libpinyin/ibus-libpinyin#90]
Ctrl+Shift+F与Eclipse 代码格式化 快捷键冲突，请问如何更改该快捷键？

**Comment by epico** [comment]
在首选项对话框中的快捷键页面可以修改。

**Comment by zyddn** [comment]
Centos7 ibus 1.6.91版没有找到在哪设置

**Comment by epico** [comment]
可能 ibus-libpinyin 1.6.91 没有这个功能。

**Comment by zyddn** [comment]
好的，谢谢您的解答！

**Comment by xieyangyue1990** [comment]
请问下这个问题有没有什么好的解决方法？在不换输入法和更该eclipse快捷键的前提下？

**Comment by zyddn** [comment]
排除你所说的我这边没其他办法

**Comment by epico** [comment]
ibus-libpinyin 的最新版本支持定制快捷键和其他改进。

**Comment by zj970** [comment]
ibus-libpinyin?
 
所以ibus-pinyin不支持更改快捷键吗？
