### ISSUE TITLE
Add changelog to GitHub releases

### ISSUE THREAD

**Issue by baimafeima** [libpinyin/ibus-libpinyin#91]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by epico** [comment]
Actually ibus-libpinyin are released in tar balls on sourceforge.
URL: https://sourceforge.net/projects/libpinyin/files/ibus-libpinyin/

And it has a short ChangeLog in
https://raw.githubusercontent.com/libpinyin/ibus-libpinyin/master/ChangeLog .

Hope the above ChangeLog helps, maybe I will write more in the ChangeLog.

**Comment by baimafeima** [comment]
@epico Would be great to have everything bundled here on GitHub than spread over so many places. I don't really like the Sourceforge interface.

**Comment by epico** [comment]
The tar ball is in github.com now.

URL: https://raw.githubusercontent.com/libpinyin/ibus-libpinyin/master/NEWS
