### ISSUE TITLE
关于无法看见单引号的问题 and 输入标识移动的问题。

### ISSUE THREAD

**Issue by lunarjoll** [libpinyin/ibus-libpinyin#92]
第一个问题是 我输入 『词汇』，但是 c'h 中的单引号无法看见。
第二个是拼写单词时，如『范冰冰』，但是我错误输入了fan'bin'bin。在第一个范字输入后，输入符在第一个字后面。这让我修改拼写并不方便。希望一个字输入后自动跳跃到下一个拼音结尾。

**Comment by epico** [comment]
"c'h" 的话，中间会显示一个空格。

这个行为设计是为了方便选择候选词。
