### ISSUE TITLE
新的图形界面启动后无法正常使用拼音输入法

### ISSUE THREAD

**Issue by Dapeng-W** [libpinyin/ibus-libpinyin#94]
我用的是红帽7系统。
通过ctrl + alt + F3，进入字符终端界面，（使用root用户登陆）之后执行startx，图形界面起来后，系统成全英文状态，切换到原有的拼音输入法但不能使用，按下按键打出的都是英文。
但是通过设置语言和输入法，移除拼音输入法再重新添加拼音输入法之后又可以进行拼音拼写。
这之后，注销当前用户，会关闭图形界面且回到字符终端下，但再次执行startx之后，拼音输入法再次无法使用。

**Comment by Dapeng-W** [comment]
补充：
安装的libpinyin版本0.9.93-4
ibus-libpinyin版本1.6.91-4

**Comment by epico** [comment]
推荐使用图形界面登陆，比如 GDM .

**Comment by Dapeng-W** [comment]
我在fedora22系统下切换字符终端再起图形界面，输入法是正常可用的。看了一下ibus-libpinyin等包的版本都比红帽系统上相关包版本高许多，但是红帽上版本好像没升上来，也没法验证。我想把fedora的ibus-libpinyin版本降到1.6.91-4，但是发现fedora的koji上该版本包被删除了，也没法检验。。。

当然如您所说，在红帽上正常使用图形界面登陆，输入法是没有问题的。我想请问我遇到的这种情况是不是bug呢？或者说我遇到的这种情况怎么解释呢？

**Comment by epico** [comment]
这个问题应该是 ibus 或者 GNOME 修正的，具体原因我也不太清楚。

**Comment by Dapeng-W** [comment]
看来目前只能先移除拼音输入法再重新添加拼音输入法了。感谢您的回复。

**Comment by ada-wang** [comment]
> 这个问题应该是 ibus 或者 GNOME 修正的，具体原因我也不太清楚。

我使用centos7 两年了，自从去年年末 centos7 更新变成 3代后，就一直没修复输入法调用失败的问题。
现在centos7 使用的gnome Version 3.22.2

具体表现与这个去年的问题一致： gnome 的 setting里 添加libpinyin，然后输入法可以正常启动使用； 但是重新启动后，gnome就调不起libpinyin了，得删掉重新添加，就可以再次用了。 我都不知道这个bug该去gnome 什么地方反映。。 QAQ

**Comment by epico** [comment]
可能 GDM 启动的时候，设置了一些环境变量。

参考 /etc/X11/xinit/xinput.d/ibus.conf .
