### ISSUE TITLE
Ibus-setup has no effect

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#96]
System: Fedora 26
Machine: AMD FX 8350 + RX 480
Input System: ibus-libpinyin for simplified Chinese and Kana Kanji for Japanese
Issue: Tried to use ibus-setup to change candidate font size or orientation, but has no effect.  There is no option to change font size.

**Comment by epico** [comment]
For candidate font size, please install the gnome-shell extension.
URL: https://extensions.gnome.org/extension/1121/ibus-font-setting/

For orientation, please change it in ibus-libpinyin dialog.
The ibus-libpinyin setting will override ibus-setup.

**Comment by ping-wu** [comment]
Thanks.  Must be done on-line.  There is no way to change fonts off-line?

**Comment by epico** [comment]
Please just download the zip from the web site,
then install it by gnome-tweak-tool off-line.

After installed, it works off-line.

**Comment by ping-wu** [comment]
Thanks again.  Forgot to restart gnome session.  Everything is good.

**Comment by epico** [comment]
Great! :)
