### ISSUE TITLE
在qt应用程序中无法使用shift键切换中英文

### ISSUE THREAD

**Issue by im-red** [libpinyin/ibus-libpinyin#97]
在qt程序的输入框中，无法通过shift快捷键切换中英文。在其他输入框（如terminal中）可以使用shift切换中英文
发行版：ubuntu 16.04
ibus-libpinyin版本：1.7.3-2
qt版本：5.5.1

**Comment by epico** [comment]
Could you try higher version of qt5, like 5.7.1?

Maybe already fixed in qt5 upstream.

It works with qt5 5.7.1 and ibus-libpinyin 1.9.0 on Fedora 25.

**Comment by epico** [comment]
No response, just close issue.
