### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/ibus-libpinyin#98]
The version of ibus-libpinyin in Ubuntu has stopped at 1.7.3-2 for almost two years.
How do I upgrade to 1.9.x, the version that I am using in Fedora 26?

**Comment by epico** [comment]
Please upgrade libpinyin to 2.1.0 first, then upgrade ibus-libpinyin to 1.9.2 .

BTW, ibus-libpinyin requires ibus 1.5.11 at least.

I updated ibus ppa for Ubuntu, but need some one to merge it.
URL: https://launchpad.net/~pkg-ime/+archive/ubuntu/ibus-stable
Maybe you can use the ibus package from the above ppa.

**Comment by ping-wu** [comment]
The version of ibus-libpinyin in your ppa is still @ 1.7.4, not the most recent?

**Comment by epico** [comment]
Right, if some one can merge it into Ubuntu, I can start to update the PPA soon.

**Comment by ping-wu** [comment]
I will give it a try, but it will take time, if ever.
Do you know the version of libpinyin in Ubuntu's version of fcitx-libpinyin?

**Comment by ping-wu** [comment]
Oops, just found out that the version of ibus has been upgraded to 1.5.14 since zesty.
Does this change your comment re upgrading ibus-libpinyin to 1.9?
If yes, how do I upgrade libpinyin in Ubuntu to 2.1.0?

**Comment by epico** [comment]
If I find some time, I will update libpinyin, ibus-libpinyin and ibus-libzhuyin in the PPA.

**Comment by ping-wu** [comment]
If possible, please also document how you do it.  We also would enjoy a learning process.
