### ISSUE TITLE
Non-stop Repeating of Last Letter When Typing

### ISSUE THREAD

**Issue by suokunlong** [libpinyin/ibus-libpinyin#99]
At certain circumstances, the last letter you have typed in will repeat n times, make it impossible to input.
Steps to Reproduce:
1. Make your CPU nearly full-load (e.g. I am building libreoffice from source so that the CPU is quite busy).
2. In LibreOffice Writer (or Firefox), type Chinese chars very fast using ibus intelligent pinyin. To reproduce, you have to type in the next letter before the char suggestion box appear.

Current behaviour: The last letter is repeated n times which makes intelligent pinyin trying to suggest n chinese chars which will freeze the window. If you hit Backspace key early you may stop the loop.

A screenshot  is attached.

ibus-libpinyin-1.9.0-1.fc26.x86_64
libpinyin-2.0.0-1.fc26.x86_64

![2017-11-12 21-36-03](https://user-images.githubusercontent.com/5754862/32699490-a4659bb2-c7f1-11e7-92b3-a66f5f6ce9bc.png)
(I am typing in jingwai trying to get the word "境外" but I get the above if I hit backspace early enough. If I hit backspace late, I will get "经哇啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊".

**Comment by epico** [comment]
What will happens if you hit 'Enter' key after the bug occurs?

**Comment by epico** [comment]
Does this issue also happens in other applications, like gedit?

**Comment by suokunlong** [comment]
> What will happens if you hit 'Enter' key after the bug occurs?
It produces sth like “经gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg” which is no different than my original description.

> Does this issue also happens in other applications, like gedit?
It happens in LibreOffice, Firefox. But it seems not reproducible in gedit.

**Comment by epico** [comment]
Please file an bug for Firefox, thanks!

**Comment by suokunlong** [comment]
Should I file one bug to firefox and one bug for libreoffice, or just for firefox is enough?

**Comment by epico** [comment]
Please file bugs for both, thanks! :)

And refer the reported bugs in this issue.

**Comment by jeffshee** [comment]
Although it is very rare, I experienced it sometimes too. And this bug seem to be similar with these reported in gnome-shell, so they might be related. (I'm not sure, might be completely wrong ;P)
https://bugzilla.gnome.org/show_bug.cgi?id=757942
https://bugzilla.gnome.org/show_bug.cgi?id=777693

**Comment by suokunlong** [comment]
Thanks for the information. I have left a comment in Gnome bugzilla.

**Comment by epico** [comment]
Please file bug for Firefox and LibreOffice, thanks!

I think maybe they need different patches, BICBW.

**Comment by suokunlong** [comment]
Bug report in libreoffice bugzilla:
https://bugs.documentfoundation.org/show_bug.cgi?id=114255

**Comment by epico** [comment]
Thanks! :)

**Comment by suokunlong** [comment]
This only happens in Gnome Shell desktops. When I switch to Gnome Classic mode, it works.

**Comment by suokunlong** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=777693
